### ISSUE TITLE
terraform helm provider

### ISSUE THREAD

**Issue by prathjan** [hashicorp/terraform-provider-helm#1000]
If you prefer, you can also ask your question in the Kubernetes community Slack channel [#terraform-providers](https://kubernetes.slack.com/messages/CJY6ATQH4). ([Sign up here](http://slack.k8s.io/))

## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version:
Helm Provider version:
Kubernetes version:
```
## Terraform configuration
```hcl
Enter your configuration here.
```

## Question
```
I am trying to pull images from ECR. And would like to account for a dependency on Helm >= 3.8.0. How do I specify this here? I do not see a version 3.x in the terraform registry.

https://registry.terraform.io/providers/hashicorp/helm/2.7.1 

```

**Comment by bentastic27** [comment]
@prathjan That looks to be noted in the changelog. It's [imported into the plugin code](https://github.com/hashicorp/terraform-provider-helm/tree/main/vendor/helm.sh/helm/v3) so you can't specify helm versions it looks like.

https://github.com/hashicorp/terraform-provider-helm/blob/main/CHANGELOG.md#270-september-28-2022

2.7.0 is helm 3.9.4
