### ISSUE TITLE
Upgrade Helm pkg dependency that provides $HELM_BURST_LIMIT

### ISSUE THREAD

**Issue by dkulchinsky** [hashicorp/terraform-provider-helm#1011]
### Description

Clusters that have many Custom Resource Definitions (CRDs) tend to cause the client to self-throttle, as a result operations such as helm install or upgrade can take a very long time, in some of our clusters can take over 30 minutes.

The issue was described in detail here: https://github.com/helm/helm/issues/10560

The option to set the burst limit (via CLI & Env var) was added here: https://github.com/helm/helm/pull/10842 and is available since Helm 3.10.0

so, upgrading the Helm pkg dependency used by the provider should do the trick here.

### Potential Terraform Configuration

To align with current practices, I think it would good to support both setting the `HELM_BURST_LIMIT` env variable as well as adding a provider attribute:

```hcl
provider "helm" {
  burst_limit = "1000"
  kubernetes { ... }
}
```

### References

Helm related issue: https://github.com/helm/helm/issues/10560
Helm related PR: https://github.com/helm/helm/pull/10842

dependabot PR to bump to Helm 3.10.2: https://github.com/hashicorp/terraform-provider-helm/pull/990

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dkulchinsky** [comment]
On the other hand, I did find this in the existing code: https://github.com/hashicorp/terraform-provider-helm/blob/74b48cb0d81501a80bcbbc9d0caf5aaf2d881199/helm/structure_kubeconfig.go#L47

so it looks like the burst limit is hard coded to 100 at the moment, which is indeed quite low for target clusters that have a lot of CRDs

perhaps we can just make it configurable?

**Comment by loafoe** [comment]
> perhaps we can just make it configurable?

@dkulchinsky yes, this is exactly what we need! We experimented locally with a fork tweaking this value and applies that took 20+ minutes with a high chance of failure now consistently succeed in just 1.5 to 2 minutes! We'll happily work on a PR for this if no one else volunteers

**Comment by loafoe** [comment]
Hi @dkulchinsky, created PR #1012 for this

**Comment by loafoe** [comment]
FYI @dkulchinsky  while we patiently wait for the upstream merge we have published a [temporary fork](https://registry.terraform.io/providers/loafoe/helm/2.9.0) which we are using in our Terraform pipeline for the time being. It's a drop in replacement but supports the `burst_limit` argument so if you are blocked on the above you can give it a try.

**Comment by dkulchinsky** [comment]
thanks for this @loafoe!! 

we have also built a private version a while back and just bumped the limit in the code, but would be great to try your fork where this can actually be tuned.

thanks for building it and letting us know!

**Comment by BBBmau** [comment]
#1012 Closes this issue
