### ISSUE TITLE
Non-existent attribute in 'helm_template' example usage documentation

### ISSUE THREAD

**Issue by nfielder** [hashicorp/terraform-provider-helm#1019]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.3.6
Provider version: 2.8.0
Kubernetes version: N/A
Helm: N/A
```

### Affected Data Source
- helm_template

### Steps to Reproduce

1. Create a valid `helm_template` data source.
1. Create an output variable that references the `manifest_bundle` attribute as the [docs suggest](https://github.com/hashicorp/terraform-provider-helm/blob/169ff943220abd8a14c21cfbd7497166f187b4a4/website/docs/d/template.html.markdown).
    <details><summary>Expand</summary>
    <p>

    ## Example Usage

    ### Render all chart templates

    The following example renders all templates of the `mariadb` chart of the official Helm stable repository. Concatenated manifests are exposed as output variable `mariadb_instance_manifest_bundle`.

    ```hcl
    data "helm_template" "mariadb_instance" {
      name       = "mariadb-instance"
      namespace  = "default"
      repository = "https://charts.helm.sh/stable"
      chart   = "mariadb"
      version = "7.1.0"
      set {
        name  = "service.port"
        value = "13306"
      }
      set_sensitive {
        name = "rootUser.password"
        value = "s3cr3t!"
      }
    }
    resource "local_file" "mariadb_manifests" {
      for_each = data.helm_template.mariadb_instance.manifests
      filename = "./${each.key}"
      content  = each.value
    }
    output "mariadb_instance_manifest_bundle" {
      value = data.helm_template.mariadb_instance.manifest_bundle # NON-EXISTENT ATTRIBUTE!
    }
    output "mariadb_instance_manifests" {
       value = data.helm_template.mariadb_instance.manifests
    }
   output "mariadb_instance_notes" {
     value = data.helm_template.mariadb_instance.notes
    }
    ```
    </p>
    </details>
1. `terraform apply`

### Expected Behavior
The output variable should have been populated succesfully with a concatenated manifests of all templates.

### Actual Behavior
There is an error that the attribute `manifest_bundle` does not exist. I believe the fix is to update all usages of `manifest_bundle` to `manifest` in the example section of the [documentation](https://github.com/hashicorp/terraform-provider-helm/blob/169ff943220abd8a14c21cfbd7497166f187b4a4/website/docs/d/template.html.markdown).

I am happy to open a PR to fix!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @nfielder,

Thank you for opening this issue. That would be great if you can open a PR to fix the documentation. Please feel free to ping me to review it.

Appreciate your help!

Thanks.
