### ISSUE TITLE
Helm_Release resource in terraform provide error when Apply plan

### ISSUE THREAD

**Issue by AlexanderBurdenko** [hashicorp/terraform-provider-helm#1021]
Hello!

When i Generate plan it's okay, when i apply plan it's showing me error

Error: error validating "": error validating data: unknown object type "nil" in " Secret.data.<name of variable>

helm_provider has latest version

**Comment by AlexanderBurdenko** [comment]
Additional information:
In terraform variable blank
previously everything was okay when trying to create secret with blank variable but last time it game me an error

**Comment by arybolovlev** [comment]
Hi @AlexanderBurdenko,

It is not quite clear what is the issue and how to reproduce it. Please use the issue template when you open a new issue(do not remove any fields from it) and provide more information regarding the problem you are encountering.

Thank you.
