### ISSUE TITLE
 Support KUBECONFIG environment variable

### ISSUE THREAD

**Issue by reegnz** [hashicorp/terraform-provider-helm#1039]
### Description

It is a common expectation that tools that talk to the kubernetes API can be configured with the KUBECONFIG environment variable. When a tool uses the kubernetes client libraries, it gets that functionality out of the box. The terraform helm provider however does not seem to be supporting the KUBECONFIG environment variable, instead it's using the KUBE_CONFIG_PATH and KUBE_CONFIG_PATHS environment variables to retrieve the config file location. It does however support the kubeconfig format.

The helm provider should also start supporting the KUBECONFIG variable, to meet the common expectation that setting this environment variable will allow all kubernetes client tools to work with the given selected cluster (unless the provider is explicitly configured to use a different configuration).

### References

https://github.com/hashicorp/terraform-provider-kubernetes/issues/1973

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by andyspiers** [comment]
Support for obtaining credentials automatically via `KUBECONFIG` was explicitly removed in v2.0.0 - the reasoning is [explained in the upgrade guide](https://github.com/hashicorp/terraform-provider-helm/blob/main/website/docs/guides/v2-upgrade-guide.markdown#changes-to-kubernetes-credentials-supplied-in-the-provider-block)
