### ISSUE TITLE
The resource is getting deleted when any changes are made in helm_release

### ISSUE THREAD

**Issue by devyanial07** [hashicorp/terraform-provider-helm#1041]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: Terraform v1.2.0
Provider version: helm v2.8.0
Kubernetes version: kubernetes v2.17.0
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "prod_deployment" {
   name             = "prod-instance"
   create_namespace = "true"
   namespace        = "SQ"
   chart            = #the configs on helm for sonarqube https://github.com/SonarSource/helm-chart-sonarqube
   timeout          = "600"
   set {
     name = "image.repository"
     value =  #my image 
  }
   set  {
      name  = "image.tag"
      value = #my tag
 }
  set {
    name  =  "image.pullPolicy"
    value =  "Always"
  }
  set  {
      name  = "jdbcOverwrite.jdbcUsername"
      value = #my details
  }
   set_sensitive {
      name  = "jdbcOverwrite.jdbcUrl"
      value =#my details
  }
   set_sensitive {
      name  = "jdbcOverwrite.jdbcPassword"
      value = #my details
  }

}
```

### Debug Output

When I update my prod_deployment, my sonarqube instance gets deleted and it recreates new instance loosing all my projects in sonarqube.
NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

If I make any changes in my resource it should make changes without deleting entire k8s deployment.
### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
@devyanial07 Is your plan producing a force replacement? Can you share the output of your plan/apply run?

**Comment by devyanial07** [comment]
Hello, no in plan there is no force replacement - it shows as 
But after apply I will have new deployement created instead of modifying my current one
![image](https://user-images.githubusercontent.com/34202154/216615723-b1d95ace-6429-44ad-abcf-ea3c095098ce.png)
