### ISSUE TITLE
Can I use a helm package with dependencies using the terraform provider?

### ISSUE THREAD

**Issue by buckleyGI** [hashicorp/terraform-provider-helm#1043]
Hi,

I am using Terraform to install the chart temporal which has dependent helm packages

resource "helm_release" "temporal" {
   chart            = "https://github.com/temporalio/helm-charts/archive/refs/tags/v1.19.1.tar.gz"
   name             = "temporal-release"
   namespace        = "temporal"
   create_namespace = true
}

I think I am almost there. The above gives

Error: found in Chart.yaml, but missing in charts/ directory: cassandra, prometheus, elasticsearch, grafana

So I add
   
   dependency_update = true

But now I am stuck with this error

Error: only unpacked charts can be updated

Does the Terraform helm provider support unpacking the tar.gz so it can install its dependencies?
Or do I have to write Terraform that downloads, unpacks the tar.gz and then do the helm commands?

**Comment by jrhouston** [comment]
Yeah this is a helm thing, you can see you'll get the same errors if you try it via `helm install` too:

```
helm install temp https://github.com/temporalio/helm-charts/archive/refs/tags/v1.19.1.tar.gz --dependency-update
Error: INSTALLATION FAILED: only unpacked charts can be updated
```

You will need to make your chart available via a repository if you want to use dependencies. The provider doesn't have any logic for dealing with tar.gz files it defers to the behaviour of the helm install action.

**Comment by buckleyGI** [comment]
Thanks @jrhouston  for the quick response. It helps to know that I'm on the right track.
Is this by design or do you consider it a bug? Would be nice if the provider could handle dependent packages no?

I tried a few permutations by linking directly to the Github repo thinking this should work as well (and pinning to a specific commit to be future proof)

resource "helm_release" "temporaltest" {
   repository       = "http://temporalio.github.io/helm-charts"
   chart            = "temporal"
   name             = "temporaltest" # releaseName
   namespace        = "temporaltest"
   dependency_update = true
   create_namespace = true
}

I get this error now. Is linking to a Github repo directly supported or is this out of scope?

Error: could not download chart: looks like "http://temporalio.github.io/helm-charts" is not a valid chart repository or cannot be reached: failed to fetch http://temporalio.github.io/helm-charts/index.yaml : 404 Not Found


As a workaround I suppose we could use a provider (Github comes to mind) to clone the repo and then to the use the helm provider to do its thing on the unpacked helm chart.
I am not executing this workaround at this point as we have other priorities. Will report back if we ever did this.

**Comment by buckleyGI** [comment]
@jrhouston Would you be so kind to provide a last time feedback? Thank you.

**Comment by buckleyGI** [comment]
Hi @jrhouston If this is by design I think we can close this issue right?

**Comment by buckleyGI** [comment]
Hi @jrhouston For the moment we should script it out with terraform right? If this is by design you can close this issue.

A fellow developer asked for this at https://github.com/temporalio/helm-charts/issues/355#issuecomment-1487662772

**Comment by jrhouston** [comment]
Yeah this is the design of helm itself, you get the same behaviour if you use `helm install` so we can close this issue. Thanks @buckleyGI
