### ISSUE TITLE
[Question] Is this repo still active?

### ISSUE THREAD

**Issue by migueleliasweb** [hashicorp/terraform-provider-helm#106]
Hey guys,

I'm seeing quite a few PRs and Issues opened without any response from the author. Does anybody know if this repo is still active?

Cheers!

**Comment by djha-skin** [comment]
@migueleliasweb Shameless plug for one that is (and I run it): https://github.com/djhaskin987/terraform-provider-helmcmd

**Comment by djha-skin** [comment]
That said, it looks like a PR was accepted on this repository just a month ago, it does appear to be very active and popular. Probably the author had a busy summer. I certainly know I have.

**Comment by migueleliasweb** [comment]
That's good to know! 

Hopefully he's just very busy atm and will come back shortly. I still hope the stale PRs get merged or at least answered.

This repo can become a very important one if we manage to get enough traction.

**Comment by mcuadros** [comment]
Yep, this repository is active, not as much it should, be soon this repository will be maintained properly, since is actively used by @src-d
