### ISSUE TITLE
terraform helm release unable to set complex value

### ISSUE THREAD

**Issue by sreenivas-ps** [hashicorp/terraform-provider-helm#1070]
### Terraform, Provider, Kubernetes and Helm Versions

I'm trying to deploy a airflow helm release with terraform but I need to set a complex value and getting this error.
```
Terraform version: 1.2.5
Provider version: google provider 4.52.0
Kubernetes version: 2.17.0
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "airflow-testing" {
  for_each   = { for k, v in var.environments : k => v if k == "testing" }
  name       = "${var.deployment}-airflow-${each.value.name}"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "airflow"
  version    = var.airflow["helm_chart_version"]
  namespace  = local.core[each.value.name].namespace

  timeout       = 900
  wait_for_jobs = true

  values = [
    file("${path.module}/files/values_testing.yaml"),
    yamlencode({ extraEnvVars = local.airflow_env_vars[each.value.name] }),
  ]

  set {
    name  = "service.annotations.cloud\\.google\\.com/neg"
    value = "{\"exposed_ports\": {\"8080\":{\"name\":\"${var.deployment}-${each.value.name}-neg\"}}}"
  }

  set {
    name  = "service.annotations.controller\\.autoneg\\.dev/neg"
    value = "{\"backend_services\":{\"8080\":[{\"name\":\"${var.deployment}-${each.value.name}-bs\",\"max_rate_per_endpoint\":100}]}}"
  }

  set {
    name  = "serviceAccount.name"
    value = each.value.name
  }
  ...
```

### Debug Output

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
It should be able to set the service annotations to the kubernetes service. The annotation looks like this:
```

metadata:
  annotations:
      "cloud.google.com/neg" : "{\"exposed_ports\": {\"8080\":{\"name\":\"http-testing-neg\"}}}"
      "controller.autoneg.dev/neg" : "{\"backend_services\":{\"8080\":[{\"name\":\"san2-testing-bs\",\"max_rate_per_endpoint\":100}]}}"
```

### Actual Behavior
```
 Error: failed parsing key "service.annotations.controller\\.autoneg\\.dev/neg" with value {"backend_services":{"8080":[{"name":"san2-testing-bs","max_rate_per_endpoint":100}]}}, key "]}}" has no value
│
│   with module.dataplatform_transformation.helm_release.airflow-testing["testing"],
│   on ../../modules/data-platform-transformation/deployment_testing.tf line 10, in resource "helm_release" "airflow-testing":
│   10: resource "helm_release" "airflow-testing" {
```

### References

- [gke autoneg controller](https://github.com/GoogleCloudPlatform/gke-autoneg-controller#example-annotations)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sreenivas-ps** [comment]
Just tried this and worked:

```
  values = [
    file("${path.module}/files/values_testing.yaml"),
    yamlencode({ extraEnvVars = local.airflow_env_vars[each.value.name] }),
    <<EOT
service:
  annotations:
    cloud.google.com/neg: "{\"exposed_ports\": {\"8080\":{\"name\":\"${var.deployment}-${each.value.name}-neg\"}}}"
    controller.autoneg.dev/neg: "{\"backend_services\":{\"8080\":[{\"name\":\"${var.deployment}-${each.value.name}-bs\",\"max_rate_per_endpoint\":100}]}}"
EOT
  ]
```

would be good to add something in the terraform documentation on setting some complex values.

**Comment by jrhouston** [comment]
It's not super obvious, but you have to escape the `{}`, `[]`, and `,` characters when using `--set` (which is what the `set` block does here) to supply JSON. So you need to escape the JSON string like this:

```hcl
value = "\\{\"backend_services\":\\{\"8080\":\\[\\{\"name\":\"test-bs\"\\,\"max_rate_per_endpoint\":100\\}\\]\\}\\}"
```

I was able to get your supplied config to work by doing this. 

We will update the documentation for `set` to try and explain this gotcha as it's not super clear what's going on here.

**Comment by NathanBaulch** [comment]
FWIW, I got around this peculiar issue by combining `jsonencode` with `replace`. So the example above becomes:

```hcl
set {
  name  = "service.annotations.cloud\\.google\\.com/neg"
  value = replace(jsonencode({
    backend_services = {
      "8080" = [
        {
          name = "${var.deployment}-${each.value.name}-bs",
          max_rate_per_endpoint = 100
        }
      ]
    }
  }), "/[{}[\\],]/", "\\$0")
}
```
