### ISSUE TITLE
Helm values diff on plan shows the whole file, not just the diff

### ISSUE THREAD

**Issue by gammore** [hashicorp/terraform-provider-helm#1080]
If you prefer, you can also ask your question in the Kubernetes community Slack channel [#terraform-providers](https://kubernetes.slack.com/messages/CJY6ATQH4). ([Sign up here](http://slack.k8s.io/))

## Terraform version, Kubernetes provider version and Kubernetes version

```
Terraform version: v1.3.7
Helm Provider version: v2.8.0
Kubernetes version: v1.23.14
```
## Terraform configuration

```hcl
provider "helm" {
  kubernetes {
    config_path    = "~/.kube/config"
    config_context = "cluster-context"
  }
  experiments {
    manifest = true
  }
}

resource "helm_release" "release" {
  name      = "release"
  chart     = "../../helm/helmchart"
  namespace = "release"
  wait     = true
  values = [
    file("helm/values-release.yaml")
  ]
}
```

### Background
Hello! I'm creating this as a question since i don't really know if i'ts a provider issue or a terraform one.

We have a configuration similar of the one I add above. This is a local helm chart, with the typical basic resources (a deployment, ingress and a service). We would like to manage the chart via terraform and I started importing the resource reusing our current values file.

 We can't manage the values using "set" directives in the `helm_release` resource block so, for the moment we keep using the values file (if you need more info please let me know but this doesn't seem related).

### Issue
The issue comes when doing a plan/apply when a change has been made to the values file, terraform outputs the whole file diff instead of just the modifications. With a big file this makes plans difficult to read.

An example, in this case i'm changing the values file replicaCount from 1 to 2:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # helm_release.release will be updated in-place
  ~ resource "helm_release" "release" {
        id                         = "release"
      ~ manifest                   = jsonencode(
          ~ {
              ~ "deployment.apps/apps/v1/release" = {
                  ~ spec       = {
                      ~ replicas = 1 -> 2
                        # (2 unchanged elements hidden)
                    }
                    # (3 unchanged elements hidden)
                }
                # (2 unchanged elements hidden)
            }
        )
        name                       = "release"
      ~ values                     = [
          - <<-EOT
                replicaCount: 1
                imagePullSecrets: []
                nameOverride: ""
                fullnameOverride: ""
                (...)  # we see in here the full values file
            EOT,
          + <<-EOT
                replicaCount: 2
                imagePullSecrets: []
                nameOverride: ""
                fullnameOverride: ""
                (...)  # we see in here the full values file
            EOT,
        ]
        # (27 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

I've tried to ignore the values but doing this makes terraform not detect changes on the file:
```hcl
resource "helm_release" "release" {
  name      = "release"
  chart     = "../../helm/helmchart"
  namespace = "release"
  wait     = true
  values = [
    file("helm/values-release.yaml")
  ]
  lifecycle = {
    ignore_changes = [values]
  }
}
```

### Question
Is there a way to prevent this? Even removing the whole values section from the plan output would be ok, since changes on the values file would reflect on the manifest anyway.

If you need more information or any test please let me know.

Thank you!

**Comment by arybolovlev** [comment]
Hi @gammore,

Thank you for raising this question and detailed explanation. This is expected Terraform behavior and the provider developers cannot do much about it. The `values` attribute has a [type string](https://github.com/hashicorp/terraform-provider-helm/blob/main/helm/resource_release.go#L139). When you do a change in the values file Terraform compares two strings and if a single symbol changes there you will see the entire file content in diff.

I hope this helps.

**Comment by kfkawalec** [comment]
It would be nice to have something like helm diff with the --context option.
This way we would only see the interesting part of the difference.
https://github.com/databus23/helm-diff

**Comment by gammore** [comment]
Yeah! Or maybe the hability to convert the yaml file to a terraform object and input that. Having a terraform object would diff correctly.

**Comment by marchenko1985** [comment]
Guys and how about importing existing release into terraform

aka I have run: `terraform import helm_release.front-internal internal/front-internal`

have following tf:

```tf
resource "helm_release" "front-internal" {
  name       = "front-internal"
  namespace  = "internal"
  chart      = "ingress-nginx"
  repository = "https://kubernetes.github.io/ingress-nginx"
  version    = "4.2.5"
  # values    = [file("ingress.internal.yml")]
  values     = split("\n", file("ingress.internal.yml"))
}
```

and it does not matter what I have tried, `terraform plan` always says that it is going to perform a change on top of existing release because it does think that values changed 🤔 which makes me little bit scare, I want to import existing release and have the manifest with which terraform will say "ok, seems like nothing changed, you are done"

looking at `terraform show state helm_release.front-internal` I see

```
# helm_release.front-internal:
resource "helm_release" "front-internal" {
    atomic                     = false
    chart                      = "ingress-nginx"
    cleanup_on_fail            = false
    create_namespace           = false
    dependency_update          = false
    description                = "Upgrade complete"
    disable_crd_hooks          = false
    disable_openapi_validation = false
    disable_webhooks           = false
    force_update               = false
    id                         = "front-internal"
    lint                       = false
    max_history                = 0
    metadata                   = [
        {
            app_version = "1.3.1"
            chart       = "ingress-nginx"
            name        = "front-internal"
            namespace   = "internal"
            revision    = 19
            values      = jsonencode(
                {
                    controller = {
                        config               = {
                            large-client-header-buffers = "4 16k"
                            proxy-buffer-size           = "16k"
                        }
                        ingressClass         = "internal"
                        ingressClassResource = {
                            controllerValue = "k8s.io/internal"
                            default         = false
                            enabled         = true
                            name            = "internal"
                        }
                        kind                 = "DaemonSet"
                        publishService       = {
                            enabled = true
                        }
                        replicaCount         = 1
                        service              = {
                            annotations           = {
                                "service.beta.kubernetes.io/load-balancer-internal" = "true"
                            }
                            externalTrafficPolicy = "Local"
                        }
                    }
                }
            )
            version     = "4.2.5"
        },
    ]
    name                       = "front-internal"
    namespace                  = "internal"
    recreate_pods              = false
    render_subchart_notes      = true
    replace                    = false
    reset_values               = false
    reuse_values               = false
    skip_crds                  = false
    status                     = "deployed"
    timeout                    = 300
    verify                     = false
    version                    = "4.2.5"
    wait                       = true
}
```

Note how values in metadata are wrapped with `jsonencode` even so the provider expects array of strings, so if I try to do something similar in manifest terraform complains that: Inappropriate value for attribute "values": list of string required.

So the question is: how then may we import existing resources without the need to reapply them? Or it is safe to use existing values and just apply changes so provider will recognize it for next time?

**Comment by gammore** [comment]
What changes does it show? I've seen sometimes that terraform (and helm) want to create a new revision but without real changes to kubernetes infrastructure. In the cases I've seen this happens when the yaml helm keeps for that release is different than what you are trying to apply.

I've seen this sometimes when an image tag was changed manually and then updated on helm. It wanted to create a new revision but the pods were not affected since the tag was already updated on kubenetes.

**Comment by marchenko1985** [comment]
So far, if I understand this correctly, the issue is that import step does not import values 


e.g.: my expectation is: I will prepare terraform file, import the resource and it will say - ok, seems like we are ready to go and nothing really changed

but reality is: we did not imported the values and it does not matter what we will do there will be an one more release even so we are just trying to import existing stuff

from a follow up comment it seems that at moment it is an by design approach which is probably fine, but shouldn’t we describe this in docs? So noobs like me won’t loose themselves
