### ISSUE TITLE
Changing the tiller image version has no effect

### ISSUE THREAD

**Issue by subesokun** [hashicorp/terraform-provider-helm#109]
Changing the tiller image version via the `tiller_image` parameter has no effect, or at least doesn't cause any TF updates after the tiller has been once initialised.

### Terraform Version
Terraform v0.11.8
Terraform Provider Helm v0.5.1

### Affected Resource(s)
- provider

### Debug Output
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Expected Behavior
When changing the `tiller_image` parameter there should be some change in the TF plan.

### Actual Behavior
No change in the TF plan gets detected hence the tiller won't be upgraded.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  Change the `tiller_image` parameter of the Helm provider
2. `terraform apply`

**Comment by andor44** [comment]
The automatic tiller installation is not currently a resource, so it's not surprising that it does not show up as a resource change. It is just something the provider initialization code does. And currently it just calls the [install](https://github.com/mcuadros/terraform-provider-helm/blob/76df45106b36e5e15c0dd331565574d813265ab9/helm/provider.go#L417) method of the tiller library, [upgrade](https://github.com/helm/helm/blob/7b821dd52fffa135cfe78611299b0491f7f03d39/cmd/helm/installer/install.go#L62) is never called. It could just call that every time with the version specified in the provider.

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
