### ISSUE TITLE
Stale metadata output from previous release

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform-provider-helm#1099]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.4.2
Provider version: 2.9.0
Kubernetes version: 1.25
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "example" {
  name       = "my-redis-release"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "redis"
  version    = "6.0.1"

  values = [
    "${file("values.yaml")}"
  ]

  set {
    name  = "cluster.enabled"
    value = "true"
  }

  set {
    name  = "metrics.enabled"
    value = "true"
  }

  set {
    name  = "service.annotations.prometheus\\.io/port"
    value = "9127"
    type  = "string"
  }
}

output "metadata" {
  value = helm_release.example.metadata
}
```

### Debug Output

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. create new helm release
1. `terraform apply`
1. change values or release version
1. `terraform apply`

Notice the metadata output is from the prior apply. If we run `apply` again, it will show the newer metadata.

### References

- https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#metadata
- similar to #1093 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi!
What specifically in the metadata does not get updated as you would expect?

**Comment by alexsomesan** [comment]
Might be actually improved by this change: https://github.com/hashicorp/terraform-provider-helm/pull/1097
