### ISSUE TITLE
Is there a way to get the helm output as run from terraform

### ISSUE THREAD

**Issue by RandellP** [hashicorp/terraform-provider-helm#1106]
I am using the helm chart for kube-prometheus-stack in my terraform with a helm_release to install prometheus and friends on an aws k8s cluster.
I often tweak the values that I am feeding it, and sometimes those values have typos or what not. When I run the terraform, it come back and says everything is fine.  But if I go look in k8s, there is a missing pod.
Is there a way to get at the output of the helm run that I assume is happening under the hood?  I am hoping there is some error information in there that somehow isn't getting propagated up to the terraform level (which is a different problem).  Being able to see it would speed up my work.

More details...
I tried outputting the values from terraform and plugging them into a download of the helm chart and running `helm install --dry-run ...` with it.  It comes back with this error:

`Error: INSTALLATION FAILED: template: kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/networkpolicy-patchWebhook.yaml:1:14: executing "kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/networkpolicy-patchWebhook.yaml" at <.Values.prometheusOperator.networkPolicy.enabled>: nil pointer evaluating interface {}.enabled`

So I tried undoing my changes, and ran terraform to prove the values were valid.  It all worked, I got my missing pod back and all that. So then I tried to run helm with that outputted values, but I still get the error from helm.  Even helm lint says the values are no good.  But somehow the terraform provider was able to make it work. So I am a bit stuck in a spot where I can't reproduce the working helm run that the terraform provider does with manual helm commands, and thus can't get the errors for a non-working values set that the terraform provider thinks is fine, but isn't.

**Comment by alexsomesan** [comment]
I think the `helm_template` data-source is what you may be after.
You can a look at it here: https://registry.terraform.io/providers/hashicorp/helm/latest/docs/data-sources/template

**Comment by RandellP** [comment]
That's perfect.  Thank you.
