### ISSUE TITLE
Linking k8s provider issue with azure aks limited permissions here. Most likely the helm provider is affected also.

### ISSUE THREAD

**Issue by slzmruepp** [hashicorp/terraform-provider-helm#1114]
### Affected Resource(s)
Here is the full description about the issue. Most likely the helm provider is affected the same way:
https://github.com/hashicorp/terraform-provider-kubernetes/issues/2072

**Comment by sheneska** [comment]
Hi @slzmruepp this seems like a configuration issue that is specific to your use case, however how do you suggest this can be addressed on the provider side?

**Comment by iBrandyJackson** [comment]
Without further feedback to proceed, we're closing this ticket to maintain clarity in our issue tracker. This closure is purely procedural; we're still interested in addressing your concerns.

Should this issue persist or if you have additional information to share, please feel free to open a new ticket. Your contributions are valuable to us, and we're keen to assist wherever possible.
