### ISSUE TITLE
Mapping Provider version to Helm version

### ISSUE THREAD

**Issue by tcgbrett** [hashicorp/terraform-provider-helm#1116]
## Question
Hello there,

I am having difficulties determining which version of Helm is actually being used when using the TF Provider. Is there any documentation which states which version of Helm each provider offers? For example, I know I need Helm 3.0.0+ for a specific chart, but the TF Provider is version 2.9.0. I have reason to believe this provider is using a version of Helm greater than v3, but how can I prove that? 
Is this documented?

Thank you!

**Comment by arybolovlev** [comment]
Hi @tcgbrett,

The provider development and release cycles are not matching with the Helm project. We have our own versioning. You can refer to the [`go.mod`](https://github.com/hashicorp/terraform-provider-helm/blob/main/go.mod#L13) file to check the version of Helm we use. We don't have any plans to align versions.

I hope that helps.

Thanks.
