### ISSUE TITLE
Support For Helm Secrets Plugin

### ISSUE THREAD

**Issue by nkazarian-spokeo** [hashicorp/terraform-provider-helm#1124]
### Description

Would like to be able to run `helm secrets` for some of our charts that have encrypted files. This way it would run `helm secrets install` so that the decryption and installation happens. Right now we need to do a wonky workaround with `local-exec` and a bunch of explicit dependencies (`depends_on`)

### Potential Terraform Configuration

```hcl
resource "helm_release" "newrelic" {
  name               = "newrelic"
  namespace           = "newrelic"
  chart                = "${var.path_to_repo}/newrelic"
  values_secret = "path/to/encrypted/secret.yaml"
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by StefanoMantero** [comment]
Agree with that! Currently the way to go is to execute the external command and get the result in base64. Would be nice to have it  already built in.
