### ISSUE TITLE
Helm release with set and ignore_changes

### ISSUE THREAD

**Issue by gammore** [hashicorp/terraform-provider-helm#1141]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.4.2
Helm Provider version: v2.9.0
Kubernetes version: 1.23.17
```
## Terraform configuration
```hcl
# This is a basic example config
data "kubernetes_resource" "data-deployment" {
  api_version = "apps/v1"
  kind        = "Deployment"

  metadata {
    name      = "example"
    namespace = "example"
  }
}

resource "helm_release" "helm-release" {
  name      = "helm-pro"
  chart     = "../../helm/example"
  namespace = "example"
  wait      = true
  set {
    name  = "image.tag"
    value = split(":", data.kubernetes_resource.data-deployment.object.spec.template.spec.containers[0].image)[1]
  }
  values = [
    file("helm/values.yaml")
  ]
  lifecycle {
    ignore_changes = [
      set
    ]
  }
}

```

### Context
Hi!

I hope you can help me. I'm facing something that might be related to how the provider applies helm releases but i don't know how to work around.

We have a weird setup (i know), simplifying we have 2 repos that can't communicate with each other (firewalls):
 - The repo that contains the terraform infra + helm chart
 - The repo that contains the app + deployment pipeline

What we do to deploy? In the app repo's pipeline we run:
kubectl set image deployment xxx <image>

This triggers the rolling update, but doesn't update helm's manifest. If the old image is "oldimage" and new image is "newimage", the cluster is running newimage but the helm chart has oldimage.

### Problem
The main problem with this approach is on the infra repo, that contains the helm chart. When we need to make a change (let's say, the deployment resource.limits) the provider will apply the helm chart, containing oldimage.

The solution we arrived at you can see it on the terraform configuration in this issue. We query kubernetes for the image before deploying the chart and include the image tag in a set parameter, so the manifest is updated. 

The problem came when we included the ingore_changes parameter, since we don't care what the tag is I thought to hide it in the terraform plan, but this actually applies helm without the --set parameter! I just wanted to ingore the changes to the image tag, to prevent them from showing in the terraform plan, but I do want to update the image.

Is there a way to work around this? 

Thank you!

**Comment by alexsomesan** [comment]
I think you might be misunderstanding the effect of `ignore_chages`. It will do exactly what you are observing - it will not just hide things from the plan, but completely disregard any new values set to those attributes. 

Currently, there is no mechanism available to just remove changes from the plan, but still perform them. The main purpose of the plan IS to preview EVERY change that will be performed during the following apply.

**Comment by gammore** [comment]
I understand, thank you for your help!
