### ISSUE TITLE
401 unauthorized with private Gitlab Helm repository

### ISSUE THREAD

**Issue by ontramatt** [hashicorp/terraform-provider-helm#1152]
## Terraform version, Kubernetes provider version and Kubernetes version

```
Terraform version: 1.3.7
Helm Provider version: 2.10.0
Kubernetes version: 1.2.3
```
## Terraform configuration

```hcl
File Edit Options Buffers Tools Terraform Help                                                                                                                                                                    
resource "helm_release" "my_release" {
  count               = var.enabled ? 1 : 0
  name                = "my_release_name"
  chart               = "my_chart_name"
  repository          = "https://gitlab.com/api/v4/projects/<MY_PROJECT_ID>/packages/helm/stable"
  version             = var.chart_version
  namespace           = var.namespace
  repository_password = var.password
  repository_username = var.username
  create_namespace    = true
  pass_credentials    = true

  values = [
    var.values
  ]
}
```

## Question

I have tried many combinations of chart, repository, etc.  but I keep getting this error on `apply`:
```
│ Error: could not download chart: looks like "https://gitlab.com/api/v4/projects/<MY_PROJECT_ID>/packages/helm/stable" is not a valid chart repository or cannot be reached: failed to fetch https://gitlab.com/api/v4/projects/<MY_PROJECT_ID/packages/helm/stable/index.yaml : 404 Not Found
│ 
│   with helm_release.my_release[0],
│   on main.tf line 1, in resource "helm_release" "my_release":
│    1: resource "helm_release" "my_release" {
```

Not sure what i'm doing wrong here. . .

**Comment by jrhouston** [comment]
Does this work if you add your repository URL using the helm CLI with `helm repo add`? 

AFAIK you can't use a GitHub repo like this. You should however be able to specify the URL to specific charts in a GitHub repo using the full path to the package for the chart, see here: 

https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#example-usage---chart-url

**Comment by ontramatt** [comment]
@jrhouston this was user error on my part, bad credentials. basically. Thank you for the response.

**Comment by kimllee** [comment]
Hello,
I'm facing the exact same issue.
It's working fine through the CLI with the same credentials entered in the helm_release block.

Terraform 1.7.4
Helm provider v2.12.1
k8s 1.26.13

**Comment by madhavdas** [comment]
It is 2024/09 and helm_release is at 2.15.x.  It is amazing from opensource community perspective that this bug persists to this day.  Token expiry(someone wrote 12 hours) is not being taken into consideration and not sure where the token hides.  It is a no go with helm_release for this reason.  I am removing helm from all our automation.  It is template/variables heavy anyways.  'envsubst' linux command does an old school cool job of substituting environment specific variables  in manifests.  Simple and best.

**Comment by drootsad** [comment]
> [@jrhouston](https://github.com/jrhouston) this was user error on my part, bad credentials. basically. Thank you for the response.

@ontramatt Did you actually get a private github/gitlab repo working with this/your configuration? 

AFAICT the only method seeming to work is specifying the repository as a link including credential like: `https://<username>:<pat>@raw.githubcontent.com/<org>/<helm-repo>/refs/headds/gh-pages` which means sensitive u/p info will be stored into tf state, which is not acceptable.

**Comment by ontramatt** [comment]
@drootsad I did get it working but it 1 1/2 years ago so I don't remember what I did exactly.
