### ISSUE TITLE
depends_on keyword for module dependency 

### ISSUE THREAD

**Issue by jeannot-ranaivosoa** [hashicorp/terraform-provider-helm#1154]
### Description

Hi all, 

I am currently trying to deploy an application with helm with terraform.
In my case, i want to deploy k8s cluster first then when it's ready, install my charts in my newly created cluster.
I have one terraform module for my k8s cluster and one helm module for my applications.

Terraform v1.4.6
provider registry.terraform.io/hashicorp/helm v2.9.0

### Potential Terraform Configuration

What i want to do : 
```hcl
module "k8s" {
  source       = "./modules/k8s"
}

module "helm" {
  source = "./modules/helm"
  depends_on = [module.k8s]

}
```

The error i am getting :
```
   on main.tf , in module "helm":
     depends_on = [module.k8s]
 
 The module at module.helm is a legacy module which contains its own local provider configurations, and so calls to it may not use the count, for_each, or
depends_on arguments.

If you also control the module "./modules/helm", consider updating this module to instead expect provider configurations to be passed by its caller.
```

I tried to do it with implicit dependency using output variables in my k8s that i used as input in my helm modules but i still get an error,  my helm tries to login to my k8s, which leads to run a terraform apply command again for the charts to be installed.

is the depends_on keyword available yet with helm provider ? 
Or perhaps a way to add some dependency to install the charts when the k8s cluster is deployed and ready ? 

Best regards

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Thanks for opening this @jeannot-ranaivosoa. We recommend not trying to create a k8s cluster and install charts into it in the same apply operation. See [this section of the Kubernetes provider documentation](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources) for more information:
