### ISSUE TITLE
Version conflicts between terraform and chart

### ISSUE THREAD

**Issue by scoof** [hashicorp/terraform-provider-helm#1157]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.3.9
Provider version: 2.10.1
Kubernetes version: 1.24
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "release" {
  count      = var.enable ? 1 : 0
  name       = "release"
  chart      = "release"
  version    = "1.0.0"
  repository = "${path.module}/charts/"
  namespace  = local.namespace
  wait       = true
}

```

### Expected Behavior
Should only be applied once

### Actual Behavior
If the version stated in terraform is different from the one in Chart.yaml, the Helm provider will now plan an update on every apply. This is new behaviour since 2.10.0. If you remove the version in Terraform and rely solely on the Chart.yaml, everything is fine. In pre-2.10, the version in Chart.yaml seemed to take precedence for both planning and deployment.

### References

- GH-1097
- GH-1150

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jgournet** [comment]
Hi,
Is there any progress on this ?
This breaks the whole terraform workflow where terraform only apply when there are changes.

**Comment by juljaeg** [comment]
Also this causes some secret parameters to be leaked as the metadata do not seem to honor the sensitive flag... This is quite critical imo.
