### ISSUE TITLE
Helm authentication broken

### ISSUE THREAD

**Issue by lud0v1c** [hashicorp/terraform-provider-helm#1163]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.5.0 (also happens with 1.4.6)
Provider version: 2.10.1 (also happens with >= 2.8)
Kubernetes version: 1.27 (also happens with 1.26)
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
provider "aws" {
  region = var.region

  default_tags {
    tags = {
      Project = "${var.cluster_name}"
    }
  }
}

provider "helm" {
  kubernetes {
    host                   = aws_eks_cluster.main.endpoint
    cluster_ca_certificate = base64decode(aws_eks_cluster.main.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.main.token
  }
}

terraform {
  backend "remote" {
    organization = "foo"
    workspaces {
      name = "bar"
    }
  }

  required_version = "~> 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.1.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.10.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0.0"
    }
  }
}

data "tls_certificate" "main" {
  url = aws_eks_cluster.main.identity.0.oidc.0.issuer
}

data "aws_eks_cluster_auth" "main" {
  name = aws_eks_cluster.main.name
}

resource "aws_eks_cluster" "main" {
  name     = var.cluster_name
  version  = var.kubernetes_version
  role_arn = aws_iam_role.cluster.arn

  vpc_config {
    security_group_ids = [module.eks_cluster_sg.security_group_id]
    subnet_ids         = module.vpc.private_subnets
  }

  enabled_cluster_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]

  depends_on = [
    aws_iam_role_policy_attachment.AmazonEKSClusterPolicy,
    aws_iam_role_policy_attachment.AmazonEKSServicePolicy,
  ]
}

resource "helm_release" "metrics_server" {
  name       = "metrics-server"
  repository = "https://kubernetes-sigs.github.io/metrics-server"
  chart      = "metrics-server"
  version    = "3.10.0"

  set {
    name  = "nodeSelector.eks\\.amazonaws\\.com/nodegroup"
    value = "default"
  }
  set {
    name  = "resources.limits.memory"
    value = "32Mi"
  }
  set {
    name  = "resources.requests.cpu"
    value = "10m"
  }
  set {
    name  = "resources.requests.memory"
    value = "32Mi"
  }

  depends_on = [
    aws_eks_node_group.default
  ]
}
```

### Debug Output

https://gist.github.com/lud0v1c/e7a9669df37f2781d26425022052edaf

### Steps to Reproduce

1. `terraform apply` or `terraform plan`

### Expected Behavior
The provider should authenticate against EKS and perform the desired command.

### Actual Behavior
Terraform is not able to refresh the state of any helm_release (there were more, I kept it short).

### Important Factoids

Three weeks ago, everything was working fine. I was using terraform with the exec-plugin (calling `aws eks get-token...`) login method. Suddenly, with no updates either to providers or my aws cli tool, this started happening. Tried non terraform ways of interacting with my EKS cluster and was able to, just as normal (kubectl, helm, aws eks...). As per the documentation, I authenticated with the AWS_* family of environment variables. After spending almost a day going up and down with terraform, provider and even EKS versions - with a very non helpful generic error message - I gave up and switched authentication to fetching a `aws_eks_cluster_auth` token and using that. Suddenly, everything started working again.

Until I wrote a .gitlab-ci.yml script for a simple plan/apply/destroy pipeline. The output posted above is from the Gitlab job, which matches the previous error. However, the auth method is the one that supposedly got it working again. I'm still using AWS_ACCESS_KEY variables and I can confirm the aws provider is working as I'm able to use it in other terraform CI jobs not using the helm provider.

My `aws-auth` ConfigMap is the same as before. I know Helm does not officially support Kubernetes 1.27 but this broke initially on 1.26 too.

### References
Not a GH issue but just saw someone [very recently struggling with this with a similar setup](https://stackoverflow.com/questions/75752465/github-actions-are-unable-to-connect-to-eks-cluster).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @lud0v1c,

Could you please run your code with `exec` and share the [debug](https://developer.hashicorp.com/terraform/internals/debugging) output? With the `exec` you can also [specify environment variables ](https://registry.terraform.io/providers/hashicorp/helm/latest/docs#exec).

Thank you.

**Comment by lud0v1c** [comment]
Will do, just have to make some CI modifications to include `aws cli`. Will update once it's done.

**Comment by lud0v1c** [comment]
> Hi @lud0v1c,
> 
> Could you please run your code with `exec` and share the [debug](https://developer.hashicorp.com/terraform/internals/debugging) output? With the `exec` you can also [specify environment variables ](https://registry.terraform.io/providers/hashicorp/helm/latest/docs#exec).
> 
> Thank you.

Thank you for the wait. I have signed & encrypted with Hashicorp's key the full debug output in [here](https://file.io/zXmByKNCAJ8N).

As for environment variables, I'm using `AWS_CONFIG_FILE` and `AWS_SHARED_CREDENTIALS_FILE` pointing to `~/.aws/config` and `~/.aws/credentials`. Running fine on the other modules.

Also note that after I did the switch to the exec plugin my local setup failed as described, and just switching to `token = data.aws_eks_cluster_auth.main.token` instead of exec makes it work again (no other changes). In Gitlab CI, neither seem to work.

**Comment by lud0v1c** [comment]
Just noticed that locally, adding the region to the command makes it being able to refresh the state as normal:

```hcl
    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      args        = ["eks", "--region", var.region, "get-token", "--cluster-name", var.cluster_name]
      command     = "aws"
    }
```

As strange as it seems, just removing it breaks it again (in Gitlab CI it also didn't work). I have aws cli `2.12.0` for reference.

**Comment by lud0v1c** [comment]
@arybolovlev any suggestions? This is blocking the CI pipeline at the moment.

**Comment by bryantbiggs** [comment]
What version of Kubernetes are you using?

**Comment by lud0v1c** [comment]
> What version of Kubernetes are you using?

1.27 on EKS.

**Comment by lud0v1c** [comment]
Turns out it was an authentication issue cluster-side. The dedicated AWS user running in Gitlab CI needed to have admin-like permissions to run `helm` it seems. Solved it by adding this to `aws-auth`:

```
- groups:
  - system:masters
  rolearn: arn:aws:iam::123456789:user/gitlab-ci
  username: gitlab-ci
```
