### ISSUE TITLE
Error after create resource. Terraform tries to update resource that has not changed.

### ISSUE THREAD

**Issue by magic7s** [hashicorp/terraform-provider-helm#117]
terraform-provider-helm_v0.5.1_darwin_amd64.tar.gz
Helm chart that sets a number of values sourced from a external data source is failing with below error.
https://pastebin.com/mV6bBtDR

Error: Error applying plan:

1 error(s) occurred:

* module.istio-eks.helm_release.istio-remote: helm_release.istio-remote: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.8
    Resource ID: helm_release.istio-remote
    Mismatch reason: attribute mismatch: set.746131047.name
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"set.858870270.value":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.172860242.value":*terraform.ResourceAttrDiff{Old:"172.17.130.6", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.4101431154.value":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.858870270.name":*terraform.ResourceAttrDiff{Old:"global.proxy.envoyStatsd.enabled", New:"global.proxy.envoyStatsd.enabled", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.1775896600.name":*terraform.ResourceAttrDiff{Old:"global.remotePolicyAddress", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.172860242.name":*terraform.ResourceAttrDiff{Old:"global.remotePilotAddress", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.~2741614750.value":*terraform.ResourceAttrDiff{Old:"", New:"${ var.control_cluster_ip_address_map[\"STATSD_POD_IP\"] }", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.~2741614750.name":*terraform.ResourceAttrDiff{Old:"", New:"global.proxy.envoyStatsd.host", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.~1617837330.value":*terraform.ResourceAttrDiff{Old:"", New:"${ var.control_cluster_ip_address_map[\"PILOT_POD_IP\"] }", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.~3986887714.name":*terraform.ResourceAttrDiff{Old:"", New:"global.remotePolicyAddress", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.~990504032.value":*terraform.ResourceAttrDiff{Old:"", New:"${ var.control_cluster_ip_address_map[\"ZIPKIN_POD_IP\"] }", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.746131047.name":*terraform.ResourceAttrDiff{Old:"grafana.enabled", New:"grafana.enabled", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.1936498494.name":*terraform.ResourceAttrDiff{Old:"global.remoteTelemetryAddress", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.1936498494.value":*terraform.ResourceAttrDiff{Old:"172.17.133.5", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.4037934527.value":*terraform.ResourceAttrDiff{Old:"172.17.129.6", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.~3986887714.value":*terraform.ResourceAttrDiff{Old:"", New:"${ var.control_cluster_ip_address_map[\"POLICY_POD_IP\"] }", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.~1617837330.name":*terraform.ResourceAttrDiff{Old:"", New:"global.remotePilotAddress", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.~742612944.value":*terraform.ResourceAttrDiff{Old:"", New:"${ var.control_cluster_ip_address_map[\"TELEMETRY_POD_IP\"] }", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.746131047.value":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.1775896600.value":*terraform.ResourceAttrDiff{Old:"172.17.133.6", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.4037934527.name":*terraform.ResourceAttrDiff{Old:"global.proxy.envoyStatsd.host", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.~742612944.name":*terraform.ResourceAttrDiff{Old:"", New:"global.remoteTelemetryAddress", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.~990504032.name":*terraform.ResourceAttrDiff{Old:"", New:"global.remoteZipkinAddress", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "set.4101431154.name":*terraform.ResourceAttrDiff{Old:"global.remoteZipkinAddress", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

```hcl
resource "helm_release" "istio-remote" {
  // run only if remote_cluster = true
  count = "${ var.remote_cluster == "true" ? 1 : 0}"
  repository = "${ var.chart_repo_name_remote }"
  name = "istio-remote"
  chart = "istio-remote"
  namespace = "istio-system"
  set {
    name = "grafana.enabled"
    value = "true"
  }
  set {
    name = "global.remotePilotAddress"
    value = "${ var.control_cluster_ip_address_map["PILOT_POD_IP"] }"
  }
  set {
    name = "global.remotePolicyAddress"
    value = "${ var.control_cluster_ip_address_map["POLICY_POD_IP"] }"
  }
  set {
    name = "global.remoteTelemetryAddress"
	value = "${ var.control_cluster_ip_address_map["TELEMETRY_POD_IP"] }"
  }
  set {
    name = "global.proxy.envoyStatsd.enabled"
    value = "true"
  }
  set {
    name = "global.proxy.envoyStatsd.host"
    value = "${ var.control_cluster_ip_address_map["STATSD_POD_IP"] }"
  }
  set {
    name = "global.remoteZipkinAddress"
    value = "${ var.control_cluster_ip_address_map["ZIPKIN_POD_IP"] }"
  }
  depends_on = ["null_resource.istio-svc-act", "null_resource.istio-crd", "helm_repository.istio-remote"]
}
```

**Comment by JacobHeidelbachDFDS** [comment]
Any news on this?

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
