### ISSUE TITLE
Please share an example how to create dynamic structure with helm_release resource

### ISSUE THREAD

**Issue by marounik** [hashicorp/terraform-provider-helm#1220]
If you prefer, you can also ask your question in the Kubernetes community Slack channel [#terraform-providers](https://kubernetes.slack.com/messages/CJY6ATQH4). ([Sign up here](http://slack.k8s.io/))

## Terraform version, Kubernetes provider version and Kubernetes version

```
Terraform version: 1.4.4
Helm Provider version: 2.10.1
Kubernetes version: 1.27
```
## Terraform configuration

```hcl
variable "helm_charts" {
  description = "Map of helm charts to be installed on cluster"
  type = map(object({
    options = object({
      chart      = string
      name       = string
      namespace  = string
      repository = string
    })
    value_sets = optional(list(
      object({
        name  = string
        value = string
        type  = optional(string, "string")
      })
    ))
    list_sets = optional(list(
      object({
        name  = string
        value = list(string)
        type  = optional(string, "string")
      })
    ))
    sensitive_sets = optional(list(
      object({
        name  = string
        value = string
        type  = optional(string, "string")
      })
    ))
  }))
  default = {}
}

resource "helm_release" "this" {
  for_each = var.eks_helm_charts

  chart      = each.value.options.chart
  name       = each.value.options.name
  namespace  = each.value.options.namespace
  repository = each.value.options.repository
}

eks_helm_charts = {
  ingress-nginx = {
    options = {
      chart      = "ingress-nginx"
      name       = "ingress-nginx"
      namespace  = "kube-system"
      repository = "https://kubernetes.github.io/ingress-nginx"
      cleanup_on_fail = true
    }
    value_sets = [
      {
        name  = "ingressClass",
        value = "nginx"
      },
      {
        name  = "something",
        value = "some-value"
      }
    ]
    sensitive_sets = [
      {
        name  = "password",
        value = "qwerty!@#$%^"
      }
    ]
  }
}

```

## Question

How to add dynamically optional multiple name/value pairs for **set**, **set_list**, and **set_sensitive** block support

**Comment by arybolovlev** [comment]
Hi @marounik,

Here is a simple example of how to use dynamic blocks for `set` attribute, other attributed can be configured in the same way.

Without Dynamic Blocks:

```hcl
resource "helm_release" "nginx" {
  name = "nginx-ingress-controller"

  repository = "https://charts.bitnami.com/bitnami"
  chart      = "nginx-ingress-controller"

    set {
      name = "service.type"
      value = "ClusterIP"
    }

    set {
      name = "service.port"
      value = "443"
    }
}
```

With Dynamic Blocks:

```hcl
variable "chart_nginx_service" {
  type = list(object({
    name  = string
    value = string
  }))
  default = [
    {
      name  = "service.type"
      value = "ClusterIP"
    },
    {
      name  = "service.port"
      value = "80"
    },
  ]
}

resource "helm_release" "nginx" {
  name = "nginx-ingress-controller"

  repository = "https://charts.bitnami.com/bitnami"
  chart      = "nginx-ingress-controller"

  dynamic "set" {
    for_each = var.chart_nginx_service

    content {
      name  = set.value["name"]
      value = set.value["value"]
    }
  }
}
```

Please read [Best Practices for dynamic Blocks](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks#best-practices-for-dynamic-blocks) to better understand the use case of the Dynamic Blocks.

Since this is not a provider issue and a more how-to-use Terraform question, I will go ahead and close this issue. If you have more questions on this topic, please reach out to Terraform discussion forum: https://discuss.hashicorp.com/c/terraform-core/27

Thanks!

**Comment by marounik** [comment]
Hi, @arybolovlev  The answer you provided is for single chart, which is **not interesting case for us**. We need a dynamic block for **multiple charts** each of them has optional array of set/setlist/set sensitive data. If we use provided approach, the result might be a nested foreach statements, one per chart, second one per setValue. That is not supported and required some flattening technique. 

This is actually the nature of my question: dynamic statement of multiple charts with nested/optional lists.
