### ISSUE TITLE
Authentication at provider level breaks resource level dependence to a Kubernetes Cluster resource

### ISSUE THREAD

**Issue by sspreitzer** [hashicorp/terraform-provider-helm#1237]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v1.5.6
Provider version: v2.11.0
Kubernetes version: v1.27.3
```

### Affected Resource(s)
- helm_release

### Behavior & Problem
Terraform Helm provider conceptionally requires authentication at provider level and not at resource level. This leads to a problem where the provider’s helm_release resource cannot be used in combination with another’s provider for creating a Kubernetes cluster. The authentication and Kubernetes cluster must already exist when the provider is being initialised. It cannot be referenced as a computed dependence.

helm_release resources cannot be put into dependency on Kubernetes clusters from other providers. I consider this a design flaw or bug.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sheneska** [comment]
Hi @sspreitzer, Could you please provide a sample config of what you are trying to do?

**Comment by sspreitzer** [comment]
> Hi @sspreitzer, Could you please provide a sample config of what you are trying to do?

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
}

resource "helm_release" "helm" {
  depends_on = [ azurerm_kubernetes_cluster.aks ]
}
```

`helm_release` expects an existing kubeconfig. The `aks` kubeconfig however will be created after.

What I would expect is a resource level authentication like:
```hcl
resource "azurerm_kubernetes_cluster" "aks" {
}

resource "helm_release" "helm" {
  kubeconfig = azurerm_kubernetes_cluster.aks.kube_admin_config_raw
}

```

**Comment by sheneska** [comment]
Hi @sspreitzer, thanks for sharing. Creating the cluster together with other Kubernetes resources in the same apply is not supported by Terraform. Instead, you would need to do two separate applies to first create cluster and another to create the Kubernetes resources.

**Comment by sspreitzer** [comment]
Hi @sheneska, Terraform **does** support creating dependent resources. I use the mechanism daily and it is a critical feature to me. I am able to achieve the functionality with a `null_resource` and `local-exec` provisioner. However would prefer the helm provider would support resource level authentication.

Terraform does support what I point out a bug or «design flaw» in `helm_release`. 

`helm_release` would need to be changed to interpolate the state at apply time and mark it as dynamic at plan time.

Example:
```hcl
resource "azurerm_kubernetes_cluster" "aks" {}

resource "null_resource" "release" {

  provisioner "local-exec" {
    when        = create
    interpreter = [ "/bin/bash", "-c" ]
    command     = <<-EOT
    #!/bin/bash

    set -e
    set -x

    tempfile=$(mktemp /tmp/helm.XXXXX)
    cat > $${tempfile} <<EOF
    ${azurerm_kubernetes_cluster.aks.kube_admin_config_raw}
    EOF

    varfile=$(mktemp /tmp/helmvars.XXXXX)
    cat > $${varfile} <<EOF
    ${var.release_variables}
    EOF

    helm upgrade '${var.release_name}' '${var.chart_repository_name}/${var.chart_name}' --kubeconfig "$${tempfile}" --install --create-namespace --namespace '${var.release_namespace}' --values "$${varfile}" --wait

    rm -f $${tempfile}
    rm -f $${varfile}
    EOT
  }

}
```
