### ISSUE TITLE
Terraform plan does not capture diff between the tf state & actual real infrastructure state

### ISSUE THREAD

**Issue by Nits26** [hashicorp/terraform-provider-helm#1239]
If you prefer, you can also ask your question in the Kubernetes community Slack channel [#terraform-providers](https://kubernetes.slack.com/messages/CJY6ATQH4). ([Sign up here](http://slack.k8s.io/))

## Terraform version, Kubernetes provider version and Kubernetes version

```
Terraform version: 1.3.7
Helm Provider version: 2.8.0
Kubernetes version: 1.26.5
```
## Terraform configuration

```hcl
resource "helm_release" "local-charts" {
  name       = var.name
  namespace  = var.namespace
  chart      = var.chart

  values = [
    "${file(var.values)}"
  ]

}
```
**values.yaml**
```hcl
resources:
  limits:
    cpu: 400m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 250Mi
```

## Question

Deploying helm chart with the values.yaml file stored in local machine to the GKE cluster. 

**Use Case:** Helm chart is successfully deployed on the GKE cluster with helm_release. When user make any changes on the Kubernetes object directly in the GKE cluster & run Terraform plan, no changes/differences were captured.
But since there are actual infrastructure state change compared to the terraform state, I was expecting Terraform to show the diff.

For Example:- While deploying the helm chart the CPU requests & limits were 200m & 400m. These values are changed by user manually on the GKE cluster say to 300m & 600m respectively. Now after running Terraform plan it does not show any changes/difference at all.

```hcl
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

Happy Terraforming
```

**Comment by sheneska** [comment]
Hi @Nits26, the way Helm works is that it generates a manifest template using the values specified in `values.yaml`. If you change resources manually using `kubectl` helm doesn't know which values in the `values.yaml` have changed. You might find it helpful to enable the [manifest feature](https://registry.terraform.io/providers/hashicorp/helm/latest/docs#manifest) as this will show you a diff of what will be changed for each resource.
