### ISSUE TITLE
GCPCKMS auto-unseal not working

### ISSUE THREAD

**Issue by kenk667** [hashicorp/terraform-provider-helm#1245]
### Terraform, Provider, Kubernetes and Helm Versions

```
terraform -v
Terraform v1.5.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.79.0
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "vault" {
  name       = "vault"
  namespace  = "vault"
  repository = "https://helm.releases.hashicorp.com"
  chart      = "vault"
  version    = "0.20.1"

  set {
    name  = "server.ha.enabled"
    value = "true"
  }
  set {
    name  = "server.ha.raft.enabled"
    value = "true"
  }
  set {
    name  = "server.ha.raft.setNodeId"
    value = "true"
  }
  set {
    name  = "server.ha.raft.config"
    value = <<EOT
ui = false

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

storage "raft" {
  path    = "/vault/data"
}

service_registration "kubernetes" {}

  seal "gcpckms" {
    #credentials = "Service-account-key.json"
    project     = "${var.project_id}"
    region      = "${var.keyring_location}"
    key_ring    = "${var.keyring_name}"
    crypto_key  = "${var.key_name}"
  }
EOT
  }
}
```

### Debug Output
Terraform itself doesn't error, the error is within GCPCKMS auto-unseal when applied via helm_resources. Below are kubectl info and container level logs;

kubectl get pods --namespace=vault
NAME                                    READY   STATUS             RESTARTS      AGE
vault-0                                 0/1     CrashLoopBackOff   2 (26s ago)   53s
vault-1                                 0/1     CrashLoopBackOff   2 (26s ago)   53s
vault-2                                 0/1     CrashLoopBackOff   2 (26s ago)   53s

kubectl logs --namespace=vault vault-0

Error parsing Seal configuration: failed to encrypt with GCP CKMS - ensure the key exists and the service account has at least roles/cloudkms.cryptoKeyEncrypterDecrypter permission: rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes.

### Steps to Reproduce
*Helm provider's token is set from: data.google_client_config.current.access_token

1. You will need a GKE cluster, a service account with sufficient privs (cloudkms.viewer and EncryptorDecryptor), and a KMS key and keyring.
2. Either write the variables or replace the variables with strings
3. Terrafrom apply then look for the running pods via kubectl get pods --namespace=vault
4. If in crashloop, get logs with: kubectl logs --namespace=vault vault-0

### Expected Behavior
stable running containers without CrashLoopBackOf and auto-unseal working

### Actual Behavior
Containers run as CrashLoopBackOf and error message in container shows auto-unseal failed

### Important Factoids
Tried debugging by deploying from helm without terraform with the same settings in values.yaml and it deploys with expected bahavior, stable and running containers in a good state and successful auto-unseal. 

I've tried deploying via terraform helm_resources without credentials line and expected behavior for vault is to use the default compute engine service account in vault, added necessary permissions and it still failes (https://github.com/hashicorp/vault/issues/22578#issuecomment-1703976723)

I've tried different terraform versions, and different helm chart versiosn. Nothing has worked when deploying via helm_resources (https://github.com/hashicorp/terraform/issues/33766#issuecomment-1706824727)

### References

https://github.com/hashicorp/terraform/issues/33766
https://github.com/hashicorp/vault/issues/22578

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@kenk667 I'm tempted to suspect that there is a formatting issue with the inlining those key and keyring variables into the structure of `server.ha.raft.config`

Could you share how are you setting the value of `server.ha.raft.config` when deploying with Helm standalone?

**Comment by kenk667** [comment]
@alexsomesan here you go, just realized that the default from an older version is consul and not raft, I do have a version with raft that I'm struggling to find atm

config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }

      service_registration "kubernetes" {}

      # Example configuration for using auto-unseal, using Google Cloud KMS. The
      # GKMS keys must already exist, and the cluster must have a service account
      # that is authorized to access GCP KMS.
      seal "gcpckms" {
         project     = "your_project_name"
         region      = "global"
         key_ring    = "your_keyring"
         crypto_key  = "your_seal"
      }

**Comment by kenk667** [comment]
I took the example from hashicorp and assumed that inline to server.ha.raft.config is the appropriate place for it, and looking at the values yaml it looks right, well at least the newer version where raft is the default instead of the consul

**Comment by kenk667** [comment]
@alexsomesan 

Do you have an example of what that should look like? The example I copied came from Hashicorp documentation 

> @kenk667 I'm tempted to suspect that there is a formatting issue with the inlining those key and keyring variables into the structure of `server.ha.raft.config`
> 
> Could you share how are you setting the value of `server.ha.raft.config` when deploying with Helm standalone?

**Comment by kenk667** [comment]
@alexsomesan 

to understand what you are saying, below is the values.yaml default from helm. Are you saying that the GCPCKMS stanza should be moved up to the Raft stanza and remove the consul settings?

raft:

      # Enables Raft integrated storage
      enabled: true
      # Set the Node Raft ID to the name of the pod
      setNodeId: true

      # Note: Configuration files are stored in ConfigMaps so sensitive data
      # such as passwords should be either mounted through extraSecretEnvironmentVars
      # or through a Kube secret.  For more information see:
      # https://www.vaultproject.io/docs/platform/k8s/helm/run#protecting-sensitive-vault-configurations
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}

    # config is a raw string of default configuration when using a Stateful
    # deployment. Default is to use a Consul for its HA storage backend.
    # This should be HCL.

    # Note: Configuration files are stored in ConfigMaps so sensitive data
    # such as passwords should be either mounted through extraSecretEnvironmentVars
    # or through a Kube secret.  For more information see:
    # https://www.vaultproject.io/docs/platform/k8s/helm/run#protecting-sensitive-vault-configurations
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }

      service_registration "kubernetes" {}

      # Example configuration for using auto-unseal, using Google Cloud KMS. The
      # GKMS keys must already exist, and the cluster must have a service account
      # that is authorized to access GCP KMS.
      #seal "gcpckms" {
      #   project     = "vault-helm-dev-246514"
      #   region      = "global"
      #   key_ring    = "vault-helm-unseal-kr"
      #   crypto_key  = "vault-helm-unseal-key"
      #}

**Comment by kenk667** [comment]
@alexsomesan I was able to replicate the bad deployment through helm by changing the HA settings to this;

```
  raft:

      # Enables Raft integrated storage
      enabled: true
      # Set the Node Raft ID to the name of the pod
      setNodeId: true

      # Note: Configuration files are stored in ConfigMaps so sensitive data
      # such as passwords should be either mounted through extraSecretEnvironmentVars
      # or through a Kube secret.  For more information see:
      # https://www.vaultproject.io/docs/platform/k8s/helm/run#protecting-sensitive-vault-configurations
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}

        seal "gcpckms" {
         project     = "project_name"
         region      = "global"
         key_ring    = "keyring_name"
         crypto_key  = "key_name"
        }

```

**Comment by kenk667** [comment]
I figured it out, you need to set raft configuration and gcpckms seperately. Thank you @alexsomesan for inspiring me when you pointed out that inlining in ```server.ha.raft.config``` structure didn't look right. after replicating the error in helm and then changing the inlining in the structure I was able to deploy with the expected result. I did try just the gcpckms stanza in the ```server.ha.config``` structure but it failed until I placed listener and storage stanzas in it

```
set {
    name  = "server.ha.raft.config"
    value = <<EOT
ui = false

listener "tcp" {
  tls_disable = 1
  address = "[::]:8200"
  cluster_address = "[::]:8201"
}

storage "raft" {
  path    = "/vault/data"
}

service_registration "kubernetes" {}
EOT
  }
  set {
    name  = "server.ha.config"
    value = <<EOT
  ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }

      service_registration "kubernetes" {}
      
  seal "gcpckms" {
  project     = "project_name"
  region      = "global"
  key_ring    = "key_name"
  crypto_key  = "keyring_name"
}
    EOT
  }
}
```

**Comment by kenk667** [comment]
Found solution, thanks again @alexsomesan

**Comment by maxb** [comment]
@kenk667  The above configuration is incorrect. You should not set both `server.ha.config` and `server.ha.raft.config` at the same time. The Helm chart will **entirely ignore** one or the other, based on the setting of `server.ha.raft.enabled`.

I think this is bad confusing design in the Vault Helm chart, but it is what it is.
