### ISSUE TITLE
kubeVersion: >= 1.19.0 which is incompatible with Kubernetes v1.27.4-eks-2d98532

### ISSUE THREAD

**Issue by johncf** [hashicorp/terraform-provider-helm#1253]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.5.7-1
Provider version: 2.10.1
Kubernetes version: 1.27.4-eks-2d98532
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files

These are the relevant parts:

```hcl
terraform {
  backend "s3" {
    bucket = "my-cool-terraform-bucket"
    key    = "terraform.state"
    region = "us-east-1"
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    cloudinit = {
      source  = "hashicorp/cloudinit"
      version = "~> 2.3"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.21"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.10"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.14"
    }
  }
}

provider "helm" {
  kubernetes {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args = ["eks", "get-token", "--cluster-name", module.eks.cluster_name]
    }
  }
}

resource "helm_release" "mlflow_rel" {
  namespace = "mlflow"
  name      = "mlflow"
  chart     = "${path.module}/../charts/mlflow"

  values = [
    templatefile("${path.module}/files/mlflow-values.yaml", {
      image_tag          = "2.6.0-0ce9295"
    })
  ]
}
```

The corresponding `Chart.yaml` (from `${path.module}/../charts/mlflow`):

```yaml
apiVersion: v2
name: mlflow
description: A Helm chart for MLflow
type: application
version: 0.1.0
appVersion: 2.6.0
kubeVersion: ">= 1.19.0"
```

If you need additional config files, please let me know and I should be able to provide it.

### Debug Output

Here's the relevant part:

```
helm_release.mlflow_rel: Creating...
╷
│ Error: chart requires kubeVersion: >= 1.19.0 which is incompatible with Kubernetes v1.27.4-eks-2d98532
│ 
│   with helm_release.mlflow_rel,
│   on [mlflow.tf](http://mlflow.tf/) line 10, in resource "helm_release" "mlflow_rel":
│   10: resource "helm_release" "mlflow_rel" {
│ 
╵
```

If you need additional outputs, please let me know.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

The helm release should be installed since `1.27.4` is indeed greater than or equal to `1.19.0`

### Actual Behavior

The helm release fails.

### Important Factoids

- Running on Amazon EKS

### References

None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sheneska** [comment]
Hi @johncf, it looks like there may be a problem with how the charts were installed. Could you please try to install the charts with helm?
