### ISSUE TITLE
Now an official provider?

### ISSUE THREAD

**Issue by sebastien-prudhomme** [hashicorp/terraform-provider-helm#126]
Just seen that: https://github.com/terraform-providers/terraform-provider-helm

@mcuadros are you aware and involved?

**Comment by snebel29** [comment]
Looks like a clone of the same code base in fact

**Comment by rporres** [comment]
Yes, this has been made official: https://twitter.com/mitchellh/status/1051942623177392134

**Comment by rporres** [comment]
And now the old repository has been transferred. Closing this.
