### ISSUE TITLE
Helm provider kubeconfig

### ISSUE THREAD

**Issue by okgolove** [hashicorp/terraform-provider-helm#127]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.8

### Affected Resource(s)
- helm provider

### Terraform Configuration Files
```hcl
provider "helm" {
  debug = true
  install_tiller = false

  kubernetes {
    config_path = "${var.kubeconfig}"
  }
}

resource "helm_release" "autoscaler" {
  name      = "${var.release_name}"
  chart     = "stable/cluster-autoscaler"
  namespace = "${var.autoscaler_namespace}"
}
```

### Expected Behavior
Helm release has been created

### Actual Behavior
Got en error:

```
Error: Error applying plan:

1 error(s) occurred:

* module.autoscaler.helm_release.autoscaler: 1 error(s) occurred:

* helm_release.autoscaler: error creating tunnel: "Get http://localhost/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp [::1]:80: connect: connection refused"
```
But if I run `terraform apply` again it will be deployed without any errors

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply` again

### Important Factoids
Running in Amazon EKS

**Comment by okgolove** [comment]
Understood what's happened.
I created EKS and then helm resources created.
But in the start I don't have specified kubeconfig. That's why I have this error.
In this case I have a question: can helm provider load kubeconfig dynamically, not on the start? Sounds like it is bad idea for Terraform.

**Comment by rporres** [comment]
If you're creating EKS via terraform you may have connection details (host, client_certificate, cluster_ca_certificate, client_key) in order to pass it to the provider. `config_path` is not meant to be dynamic, it's just there if the cluster has been created outside terraform and you need the credentials to access and url to access.

**Comment by okgolove** [comment]
Got it, thank you!

**Comment by etheleon** [comment]
hi @okgolove , did you manage to resolve this? I'm running in to similar issue with GCP

**Comment by okgolove** [comment]
@etheleon hi! I haven't resolved it completely. In my case it was EKS, Terraform can't check helm resources because there is not a cluster url until EKS cluster has created.
