### ISSUE TITLE
Where is the store folder of helm charts when run "Terraform Apply"

### ISSUE THREAD

**Issue by barryzhoutrojai** [hashicorp/terraform-provider-helm#1276]
I have a terraform project that sits in a github repository, it will deploy a helm chart via running "terraform apply". So we define a helm_release as following.

Basically our helm chart that sits in another separate repository. When we release a helm chart version, we package helm charts into a tgz file and push it to google cloud artifactory registry.

As following helm_release, we provide repository url and chart version, then terraform can pull down our helm charts.

resource "helm_release" "somexxxx" {
  count = var.install_somexxxx_helm_release ? 1 : 0

  # Chart information.
  repository = var.somexxxx_repository
  version    = var.somexxxx_version
  chart      = "somexxxx"

  name              = "somexxxx"
  
  ......
}

Because we encrypt some credential stuff in the helm charts repo, such as, we use "helm-secrets" to encrypt a file into secrets.yaml, secrets.yaml sits in the helm charts repo and stays with Chart.yaml, so secrets.yaml also is packaged and push google registry.

Now in the terraform, we use the following code to decrypt secrets.yaml, I refer it from https://github.com/jkroepke/helm-secrets.

data "external" "helm-secrets" {
  program = ["helm", "secrets", "decrypt", "--terraform", "secrets.yaml"]
}

When I run "terraform apply", I got error during running helm-secrets, it complains about "File secrets.yaml not exists"

Obviously, terraform doesn't find secrets.yaml, I think we provide an incorrect path of file secrets.yaml.

My question is, what is the folder of my helm chart somexxxx when terraform pull down my charts from google registry? If I know the folder of my helm chart somexxxx, then I know the location of secrets.yaml.

I am getting stuck, any ideas for that? I appreciate your help.

**Comment by arybolovlev** [comment]
Hi @barryzhoutrojai,

This provider does not unpack the chart and uses the Helm [Load](https://github.com/hashicorp/terraform-provider-helm/blob/main/helm/resource_release.go#L1175) method to work with the chart object. By default, the provider keeps downloaded charts in the cache directory which depends on the operating system you use. [Here](https://helm.sh/docs/helm/helm/) you can find more details about the Helm cache. You can [change](https://registry.terraform.io/providers/hashicorp/helm/latest/docs#repository_cache) the path in the provider block.

Thanks.

**Comment by barryzhoutrojai** [comment]
Great answer.
