### ISSUE TITLE
helm_release is not rendering the set of stringMap 

### ISSUE THREAD

**Issue by goutham-sabapathy** [hashicorp/terraform-provider-helm#1280]
We are using aws-load-balancer-controller and while deploying any service which uses this as ingress, we need to annotate it to enable accessing logging. But that annotation takes stringMap as input which has multiple values separated by comma. And there is no way to set that using helm_release module. 

Using `set{}` only renders the value upto the first comma and the omits values after it. I have also tried `set_list{}` but it accepts only `stringMap`. 

Annotation syntax:
```yaml
alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=my-access-log-bucket,access_logs.s3.prefix=my-app
```

### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: Terraform v1.6.2 on darwin_arm64
Provider version: hashicorp/helm v2.11.0
Kubernetes version: 1.27
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
  set {
    name  = "server.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/load-balancer-attributes"
    value = "access_logs.s3.enabled=true,access_logs.s3.bucket=dlx-charter-${var.env}-lb-access-${var.region}"
    type  = "string"
  }
```

Also tried this,

```hcl
  set {
    name  = "server.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/load-balancer-attributes\\.access_logs\\.s3\\.enabled"
    value = "true"
    type  = "string"
  }

  set {
    name  = "server.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/load-balancer-attributes\\.access_logs\\.s3\\.bucket"
    value = "dlx-charter-${var.env}-lb-access-${var.region}"
  }
```

Both did not work.

### Debug Output

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

  ingress:
    annotations:
      alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=dlx-charter-dev-lb-access-us-east-1

### Actual Behavior

  ingress:
    annotations:
      alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true

### References

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/ingress/annotations/#load-balancer-attributes

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Hello, this was recently added to our documentation and will be included in the latest release. It can be found [here](https://github.com/hashicorp/terraform-provider-helm/pull/1252/files#diff-f5347690e1eb7c48c2162f0c2b5d2be33ce55dd4773312214598be3152f65c32R222).

You'll want to escape each comma twice in the `value` field in order for it to be parsed correctly. It would look like this:
```
    value = "access_logs\\.s3\\.enabled=true\\,access_logs\\.s3\\.bucket=dlx-charter-${var.env}-lb-access-${var.region}"

```
