### ISSUE TITLE
Add option to delete namespace after `helm_release` destroy.

### ISSUE THREAD

**Issue by ScionOfDesign** [hashicorp/terraform-provider-helm#1281]
### Description

I try to keep all of my helm charts in separate namespaces if possible, and although this chart has the `create_namespace` option, this namespace is not subsequently deleted if the resource is destroyed. Instead, the namespace persists and causes clutter unless it is removed manually.

### Potential Terraform Configuration

Just a variable like the following would work fine:
```tf
remove_namespace = true
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Hello! Thank you for opening this issue, from reviewing the helm docs their is no mention of being able to delete namespaces. The solution would be to use the kubernetes provider to create a namespace which would then allow you to destroy once finished. I've linked the docs to the appropriate resource [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/namespace_v1)
