### ISSUE TITLE
Fix minor spelling issue in Terraform Provider Helm README.md

### ISSUE THREAD

**Issue by hnarasaki** [hashicorp/terraform-provider-helm#129]
https://github.com/mcuadros/terraform-provider-helm/blob/master/README.md

"This is a small example of how to install the mariadb chart on your default kubernetes cluster, since the provider was initialized, all the configuration is retrieve from the environment."

Change retrieve to retrieved.

**Comment by hnarasaki** [comment]
Claimed

**Comment by hnarasaki** [comment]
Submitted PR: https://github.com/mcuadros/terraform-provider-helm/pull/130

**Comment by meyskens** [comment]
Fixed in #130
