### ISSUE TITLE
Release > v2.9.0 fails to install with "error validating data: the server has asked for the client to provide credentials" for RKE clusters

### ISSUE THREAD

**Issue by spirilis** [hashicorp/terraform-provider-helm#1294]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v1.4.4
Provider version: v2.10.0
Kubernetes version: v1.24.17
```

We are accessing a Rancher RKE1 cluster through a Rancher v2.6.13 UI system, using the rancher/rancher2 provider to broker access to the API URL and a token.  This fault appears to be consistent across multiple releases of the rancher/rancher2 provider and we believe the rancher2 provider is not at fault here.

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.23"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "2.10"
    }
    rancher2 = {
      source  = "rancher/rancher2"
      version = "~> 3.2"
    }
  }
}

provider "rancher2" {
  api_url   = "<redacted>"
  token_key = "<redacted>"
}

data "rancher2_cluster" "selected" {
  name = "intrak8s-dev"
}


provider "helm" {
  kubernetes {
    host  = yamldecode(data.rancher2_cluster.selected.kube_config).clusters[0].cluster.server
    token = yamldecode(data.rancher2_cluster.selected.kube_config).users[0].user.token
  }
}

provider "kubernetes" {
  host  = yamldecode(data.rancher2_cluster.selected.kube_config).clusters[0].cluster.server
  token = yamldecode(data.rancher2_cluster.selected.kube_config).users[0].user.token
}

resource "helm_release" "test" {
  name = "erictest1"
  namespace = "default"
  repository = "<redacted internal repo>"
  chart = "multi-web"

  values = [
    templatefile("test-values.yaml",
      {
      }
    ),
    yamlencode({
      "tags": {
        "GitCommit": "asdf"
        "GitUrl": "asdf"
        "Project": "asdf"
        "Env": "asdf"
        "Owner": "asdf"
      }
    })
  ]

}
```

### Debug Output

https://gist.github.com/spirilis/091285cf78c7dd126078754167e9a82c

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

Helm chart should have installed

### Actual Behavior

Terraform failed with:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: the server has asked for the client to provide credentials

  with helm_release.test,
  on test.tf line 52, in resource "helm_release" "test":
  52: resource "helm_release" "test" {
```

### Important Factoids

Further troubleshooting confirms this problem exists for Helm provider v2.10.0 and v2.11.0 but NOT for v2.9.0.

Further research into differences between v2.9.0 and v2.10.0 reveals the HELM software was upgraded to v3.12.0 for terraform-helm v2.10.0

We have confirmed the helm CLI tool v3.12.0 also exhibits this fault:

```
$ ~/tmp2/v3.12.0/helm version
version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}

$ ~/tmp2/v3.12.0/helm -n default upgrade -i erictest1 prh-helm-templates/multi-web -f test-values.yaml --set tags.Project=asdf --set tags.Env=asdf --set tags.Owner=asdf --set tags.GitUrl=asdf
Release "erictest1" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: the server has asked for the client to provide credentials
```

However, using Helm CLI release v3.12.1 fixes it:

```
$ ~/tmp2/v3.12.1/helm version
version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.4"}

$ ~/tmp2/v3.12.1/helm -n default upgrade -i erictest1 prh-helm-templates/multi-web -f test-values.yaml --set tags.Project=asdf --set tags.Env=asdf --set tags.Owner=asdf --set tags.GitUrl=asdf
Release "erictest1" does not exist. Installing it now.
NAME: erictest1
LAST DEPLOYED: Thu Nov 16 18:29:59 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=multi-web,app.kubernetes.io/instance=erictest1" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
```

### References

https://github.com/hashicorp/terraform-provider-helm/commit/6277f8e9e5c936e9c189c1e903a8f09ea2f429cb

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by towolf** [comment]
I'm also facing this issue and I think this only happens when we use the Rancher management cluster as a control plane proxy. When we connect via `local_auth_endpoint` which is proxied by other means, it works.

**Comment by spirilis** [comment]
I have not tested this without the rancher system as a controlplane proxy, but I suspect the fix is easy: bump up the helm library version to 3.12.1 or later (have successfully tested the helm CLI all the way from 3.12.1 to the latest of 3.13.2)

It's odd this bug only showed up when we upgraded our RKE1 clusters to 1.24.  And it works fine on EKS 1.24 too.  I did some trace/debugging to try and figure it out but didn't quite find the root cause.

**Comment by BBBmau** [comment]
> However, using Helm CLI release v3.12.1 fixes it:

@spirilis Thank you for opening this issue! It looks like the latest release may have fixed this problem by bumping to the latest helm release. Could you confirm if this issue is still occurring for you with the latest release? Thank you!

**Comment by spirilis** [comment]
Confirmed working with 2.12.1

Thank you!!
