### ISSUE TITLE
Helm provider 2.12.0 broken

### ISSUE THREAD

**Issue by shezaan** [hashicorp/terraform-provider-helm#1299]
There is an issue with the helm provider 2.12.0. The error it throws when using ECR is

`Error: unexpected status from HEAD request to https://public.ecr.aws/v2/karpenter/karpenter/manifests/v0.32.1: 400 Bad Request`

and is likely caused due to this helm issue https://github.com/helm/helm/issues/12491#issuecomment-1765552182 for which a fix seems to have been released already in their 3.13.2 milestone.

Using version 2.11.0 (downgrade) of the helm provider fixes the problem.

providers.tf

```
provider "helm" {
  kubernetes {
    host                   = data.terraform_remote_state.staging_eks1.outputs.cluster_endpoint
    cluster_ca_certificate = base64decode(data.terraform_remote_state.staging_eks1.outputs.cluster_certificate_authority_data)
    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args = ["eks", "get-token", "--cluster-name", data.terraform_remote_state.staging_eks1.outputs.cluster_name, "--region", "us-east-1"]
    }
  }
}
```

**Comment by arybolovlev** [comment]
Hi @shezaan,

Thank you for raising this issue. I have bumped dependencies and we will cut a new patch release this week.

TY!
