### ISSUE TITLE
Semver and schema

### ISSUE THREAD

**Issue by flah00** [hashicorp/terraform-provider-helm#1320]
### Description

Do others find it desirable to include tf state schema version bumps as a reason to bump major version of the provider? 

### Why

I was running down an error. It was a very unhelpful helm error. I thought I'd try upgrading from helm provider 2.8 to 2.12. I assumed that if it didn't help I'd easily return to 2.8. My thinking was that all versions of 2.x must be compatible and that only incremental and reversible changes would be introduced. I did not read the changelog. The upgrade didn't help.

After I sorted the issue (PEBKAC) I thought, there's no need to stay on helm provider 2.12.1. I'll try to downgrade to 2.8, so lock files aren't needlessly updated in a feature branch. But no sooner did I do than than I bumped up against the schema incompatibility error.

And through my own laziness and erroneous assumptions, I was forced to upgrade various lock files.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Hi @flah00 – I wasn't able to reproduce this. Between 2.8.0 and 2.12.1 we didn't bump the schema version of the the `helm_release` resource. I was able to create a `helm_release` with v2.8.0, upgrade to v2.12.1, run a plan successfully, then downgrade back to v2.8.0 and run a plan successfully without any errors. I didn't see the `schema_version` of the resource change in the stateful at any point during this. 

In any case I am going to close this as we don't recommend downgrading provider versions once upgraded unless there is a problem with that specific version. The providers state upgrader mechanism is one-way (i.e it only upgrades states from previous version to newer versions, not the other way around.
