### ISSUE TITLE
Regression bug "Error: non-absolute URLs should"

### ISSUE THREAD

**Issue by Gianluca755** [hashicorp/terraform-provider-helm#1351]
### Terraform, Provider, Kubernetes and Helm Versions
```
Terraform version: 1.4.7
Provider version: 2.13.0
Kubernetes version: 1.24
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "argocd" {
  chart = "argo-cd"
  name = "argocd"
  version = "5.28.0"
  namespace  = "argocd"
  repository  = "https://gitlab.com/api/v4/projects/xxxxxxxxxxx/packages/helm/stable"
  atomic   = true

  repository_username = "gitlab-ci-token"
  repository_password = xxxxxx
}
```

### Expected Behavior
Correct installation from the Helm chart in the Gitlab package registry. It works with the provider v2.12.x.

### Actual Behavior
Error during terraform plan:
`Error: non-absolute URLs should be in form of repo_name/path_to_chart, got: argo-cd`

**Comment by jrhouston** [comment]
Thanks for opening this @Gianluca755 , I suspect this is the same issue as: https://github.com/hashicorp/terraform-provider-helm/issues/1348

**Comment by Gianluca755** [comment]
Given the small diff in the versions it is. Closing as duplicate.
