### ISSUE TITLE
Charts.yaml is missing when installing metallb in terraform submodule 

### ISSUE THREAD

**Issue by imyashkale** [hashicorp/terraform-provider-helm#1359]
https://github.com/hashicorp/terraform-provider-helm/issues/831
This issue was already raised but not fixed. I can fix this issue if required. I faced this today and then changed the module name it worked.
I can fix this just let me know

### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v1.8.2
Provider version: v2.13.1
Kubernetes version: v2.29.0
```

### Affected Resource(s)

- helm_release  crossplane
- helm_repository https://charts.crossplane.io/stable

### Terraform Configuration Files
```hcl
resource "kubernetes_namespace_v1" "crossplane" {
  metadata {
    name = "crossplane-system"
  }
}

resource "helm_release" "crossplane" {
    name        = "crossplane"
    chart       = "crossplane"
    repository  = "https://charts.crossplane.io/stable/"
    version     = "1.8.1"
    namespace   = kubernetes_namespace_v1.crossplane.metadata[0].name
    description = "Crossplane Helm chart"
}

```

### Debug Output

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Panic Output
Chart.yaml not found

### Steps to Reproduce

1. rmake sure epo and module name same. (installing crossplane with module named crossplane)
2. `terraform apply`

### Expected Behavior
Install the chart

### Actual Behavior
Its trows error saying Chart.yaml doesnt exists

### References
https://github.com/hashicorp/terraform-provider-helm/issues/831

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@imyashkale What's your proposed solution to this issue?

Also, for the sake of preserving context, it would be helpful to not duplicate existing issues, especially when they already include conversations that carry information relevant to solving the issue. Duplicates will obscure these conversations and information will get lost.

**Comment by alexsomesan** [comment]
Update: this stems from an [upstream issue in Helm](https://github.com/helm/helm/pull/13008).
Closing this, let's continue the conversation in the earlier [issue](https://github.com/hashicorp/terraform-provider-helm/issues/831).
