### ISSUE TITLE
terraform init downloads outdated helm-provider version

### ISSUE THREAD

**Issue by tpolekhin** [hashicorp/terraform-provider-helm#136]
Hello)

On the latest terraform version 0.11.9 (did not test on others) `terraform init` downloads terraform-provider-helm version 0.1.0
https://releases.hashicorp.com/terraform-provider-helm/ only have 0.1.0 version available
Setting `version = 0.6.0` in `provider "helm" {}` results in error - specified version not found

**Comment by meyskens** [comment]
0.1.0 in terraform init is actually 0.6. We are awaiting Hashicorp to set up releases properly on this repo, 0.1 was a test release that happened during the 2 days that the official provider was a fork from the repo.

**Comment by rporres** [comment]
cc @alexsomesan

**Comment by alexsomesan** [comment]
Thanks for letting me know about this.
I'm looking into this.

**Comment by alexsomesan** [comment]
It's done.
I have released v0.6.1 which should now be available through `terraform init`. Unfortunately I could not reuse v0.6.0 since it would mean rewriting the v0.6.0 tag in GitHub, which I think is best avoided.
