### ISSUE TITLE
GKE authentication is underdocumented

### ISSUE THREAD

**Issue by x-yuri** [hashicorp/terraform-provider-helm#1371]
It's a documentation issue, so I believe the usual template doesn't apply here.

The methods [described][a] in the documentation:

* the implicit way: I bet it's very unusual to run `terraform` inside a cluster
* 2 ways where you need to reference `~/.kube`: I don't want to run any commands before running `terraform`, moreover I need to involve myself with contexts in case I have more than 1 cluster
* the exec plugin way: no example for GKE, and I thought it's not possible until I stumbled into [this][b]

I believe the way described by the last link is what should be recommended. But it's like not at all obvious where it's documented. At least it deserves a link form the `hashicorp/helm` documentation.

[a]: https://registry.terraform.io/providers/hashicorp/helm/latest/docs#authentication
[b]: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/using_gke_with_terraform#using-the-kubernetes-and-helm-providers

**Comment by sheneska** [comment]
Hi @x-yuri, thanks for the suggestion. We've added it!
