### ISSUE TITLE
Suppressing warnings returned from provider

### ISSUE THREAD

**Issue by oponomarov-tu** [hashicorp/terraform-provider-helm#1398]
## Terraform version, Helm provider version and Kubernetes version

```
Terraform version: v1.8.4
Helm Provider version: v2.13.2
Kubernetes version: v1.30 (EKS)
```
## Terraform configuration

N/A

## Question

https://github.com/hashicorp/terraform-provider-helm/pull/671 introduced a warning that is displayed to the user when `helm_release` resource is destroyed & an information message has been returned by Helm. In my case it is:

```hcl
│ Warning: Helm uninstall returned an information message
│
│ These resources were kept due to the resource policy:
│ [CustomResourceDefinition] applications.argoproj.io
│ [CustomResourceDefinition] applicationsets.argoproj.io
│ [CustomResourceDefinition] appprojects.argoproj.io
```

Is it possible today to suppress the warning messages returned explicitly by the Helm provider?

**Comment by appilon** [comment]
~You should be able to control [log levels](https://developer.hashicorp.com/terraform/internals/debugging). Hopefully this works.~ Apologies I just realized this was diag.Warning. This is a type of message by TF Core, and unfortunately cannot be suppressed. You can however compact the warnings with the following [option](https://developer.hashicorp.com/terraform/cli/commands/plan#other-options)
