### ISSUE TITLE
There's no way to set some values as strings

### ISSUE THREAD

**Issue by calind** [hashicorp/terraform-provider-helm#14]
Currently there's no way to set a value to string `"true"` or `"false"` or numbers `"12345"`. Some resources really need these values quoated (eg. some pod annotations).

The snippet bellow
```hcl
value {
  name = "foo.bar"
  content = "true"
}
```
yields
```yaml
foo:
  bar: true
```

while 
```hcl
value {
  name = "foo.bar"
  content = "\"true\""
}
```
yields
```yaml
foo:
  bar: '"true"'
```

**Comment by calind** [comment]
I guess you can close this issue since this is a issues with helm cli tool as well. I have opened a bug report on https://github.com/kubernetes/helm/issues/2848.

The only workaround with the cli currently is to specify a yaml file with `-f` option. As for the terraform module this is tackled in #9.

**Comment by andrexus** [comment]
since [this](https://github.com/helm/helm/pull/4142) pull request is merged it would be really nice to have _setString_ option here also
