### ISSUE TITLE
Why helm release metadata is a list type

### ISSUE THREAD

**Issue by prashantkalkar** [hashicorp/terraform-provider-helm#1423]
## Terraform version, Kubernetes provider version and Kubernetes version

```
Terraform version: 1.9.1
Helm Provider version:  2.14.0
Kubernetes version: v1.25.5
```
## Terraform configuration

```hcl
output "output_variable" {
  value = yamldecode(helm_release.release_name.metadata[0].values.key)
}
```

## Question

The above code fails unless metadata[0] is used.  But why is metadata treated as a list. Also what should be the valid index here. If it is always should be 0 then why it is required?

It will be useful if the reasoning being using a list type here can be made clear to reduce the confusion of using the provider resource.

**Comment by BBBmau** [comment]
@prashantkalkar metadata being a list is due to the use of Terraform SDKv2, the plugin framework migration for the helm provider would allow single nested attributes removing the need of `metadata[0]`

https://developer.hashicorp.com/terraform/plugin/framework/handling-data/blocks/single-nested
