### ISSUE TITLE
Question about when helm values need escaping

### ISSUE THREAD

**Issue by asheynkmantyler** [hashicorp/terraform-provider-helm#1446]
If you prefer, you can also ask your question in the Kubernetes community Slack channel [#terraform-providers](https://kubernetes.slack.com/messages/CJY6ATQH4). ([Sign up here](http://slack.k8s.io/))

## Terraform version, Kubernetes provider version and Kubernetes version

```
Terraform version: 1.8.3
Helm Provider version: 2.14.0
Kubernetes version: 1.29
```
## Question

This is related to https://github.com/hashicorp/terraform-provider-helm/issues/1280. The question is which characters need to be escaped? The example https://github.com/hashicorp/terraform-provider-helm/blob/main/docs/resources/release.md#example-usage---chart-repository-configured-outside-of-terraform mentions `[ ] { } . ,` but even your example there,

```
set {
  name  = "grafana.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/group\\.name"
  value = "shared-ingress"
}
```

does not appear to be escaping all periods. Also, we have tf with `[ ] { } and .` and it appears to be translating correctly. 

thank you

**Comment by korjek** [comment]
@asheynkmantyler did you find the answer?
