### ISSUE TITLE
Release v2.15.0

### ISSUE THREAD

**Issue by ri-roee** [hashicorp/terraform-provider-helm#1449]
Quick question - what is the release cadence of this provider? There's a [fix](https://github.com/helm/helm/pull/13120) in upstream helm, which was cut in version `3.15.3`, the version currently on [master](https://github.com/hashicorp/terraform-provider-helm/pull/1422). Thanks!

**Comment by arybolovlev** [comment]
Hi @ri-roee,

Thank you for raising this issue. I will cut a new release this week and since it only has some dependency changes, it will get the `2.14.1` tag.

Thanks!
