### ISSUE TITLE
CI: use `$GITHUB_OUTPUT` instead of `set-output` in `get-version-matrix.sh`

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-helm#1456]
### Description

We are currently using the deprecated method for setting output values for github actions in `get-version-matrix.sh`:
![image](https://github.com/user-attachments/assets/2a1cdcdc-ed56-42ac-96d9-9db97f090e91)

We'll want to address this to get rid of the warning. Related Documentation: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/defining-outputs-for-jobs

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ri-roee** [comment]
Hey @BBBmau, not sure if this is the right place to call this out but it looks that CI is hanging looking for a runner
https://github.com/hashicorp/terraform-provider-helm/actions/runs/10288152714/job/28472908758

**Comment by BBBmau** [comment]
> Hey @BBBmau, not sure if this is the right place to call this out but it looks that CI is hanging looking for a runner https://github.com/hashicorp/terraform-provider-helm/actions/runs/10288152714/job/28472908758

@ri-roee  Thanks for pointing this out! This was due to a recent change to custom labels in our runners. This was brought up earlier today. https://github.com/hashicorp/terraform-provider-helm/pull/1455

This fixed the issue and now `v2.14.1` is released. Thank you again!!
