### ISSUE TITLE
Terraform + Helm + Kibana, unable to set variable env

### ISSUE THREAD

**Issue by jonatasfreitasv** [hashicorp/terraform-provider-helm#147]
Hi!

Iam using this chart (https://github.com/helm/charts/tree/master/stable/kibana)

I need to set elasticsearch.url config, but, not work.

How I use env or files parameter?

Any idea?

**Comment by hairmare** [comment]
Is `set` not working for you?
```hcl
resource "helm_release" "kibana" {
  name  = "kibana"
  chart = "stable/kibana"

  set {
    name  = "elasticsearch.url"
    value = "http://example.com/url-to-elastic"
  }
}
```

**Comment by jonatasfreitasv** [comment]
Man, thx very very a lot!! I try a lot of options!!
