### ISSUE TITLE
  "wait_for_jobs = true" does not work as expected in helm_release terraform resource

### ISSUE THREAD

**Issue by UtopiaWorld** [hashicorp/terraform-provider-helm#1483]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v1.4.0
- Installing hashicorp/helm v2.15.0...
- Installed hashicorp/helm v2.15.0 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)
- Installing hashicorp/aws v5.66.0...
- Installed hashicorp/aws v5.66.0 (signed by HashiCorp)
- Installing hashicorp/kubernetes v2.32.0...
- Installed hashicorp/kubernetes v2.32.0 (signed by HashiCorp)
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "aqa_test" {
  name      = "aqa-test"
  chart     = "s3://${s3_tests_key}"

  wait_for_jobs    = true
}
```
### Expected Behavior
Terraform should wait for job complete status and return failed or success status

### Actual Behavior
Terraform does not wait for jobs complete status and just report success status while job is still running

### References
It was added in 2.1.2 but it does not work in 2.15.0
2.1.2 (April 27, 2021)
Add support for the --wait-for-jobs option (#720)
Here you can check it was reproduced in 2.6.0 - https://github.com/hashicorp/terraform-provider-helm/issues/672

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sheneska** [comment]
I will close this issue as it is already being investigated in #672 .

**Comment by UtopiaWorld** [comment]
it was investigated, but it starts reproducing in newer vesrion of provider.
