### ISSUE TITLE
postrender ignores args since v2.15.0

### ISSUE THREAD

**Issue by dawid-remitly** [hashicorp/terraform-provider-helm#1533]
Provider since v2.15.0 ignores `args` parameters and does not pass them to renderer.

### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v1.6.5
Provider version: v2.15.0
Kubernetes version: v1.29
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
> cat main.tf
provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

terraform {
  required_version = ">= 1.0"

  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "= 2.15.0"
    }
  }
}

resource "helm_release" "example" {
  name       = "test-chart"
  chart      = "./test"

  postrender {
    binary_path = "${path.module}/patch.sh"
    args        = ["a", "b"]
  }
}

> cat patch.sh
#!/usr/bin/env bash
set -euo pipefail

if [ $# -ne 2 ]
then
  echo "Usage: $0 <arg1> <arg2>" >&2
  exit 1
fi
```

### Expected Behavior
No error

### Actual Behavior
```

> terraform apply
(...)
│ Error: error while running post render on files: error while running command /tmp/helm_version/patch.sh. error output:
│ Usage: /tmp/patch.sh <arg1> <arg2>
│ : exit status 1
│
│   with helm_release.example,
│   on main.tf line 18, in resource "helm_release" "example":
│   18: resource "helm_release" "example" {
```

**Comment by arybolovlev** [comment]
Hi @dawid-remitly,

Thank you for reporting this issue. It looks like postrender binary path arguments parsing was accidentally removed in this [PR](https://github.com/hashicorp/terraform-provider-helm/pull/1247).

I think this should be a relatively easy fix. I will go ahead, create a PR and ask my colleagues to review it.

Thanks!

**Comment by PT-GD** [comment]
This doesn't appear to be in 2.16.0 or 2.16.1. How do we track when this is released?
