### ISSUE TITLE
helm_template create_namespace option does not create namespace manifest

### ISSUE THREAD

**Issue by chrxmvtik** [hashicorp/terraform-provider-helm#1538]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.9.8
Provider version: 2.16.1
Kubernetes version: 1.31.1
```

### Affected Resource(s)

- helm_template

### Terraform Configuration Files
```hcl
data "helm_template" "ceph_csi_cephfs" {
  name       = "ceph-csi-cephfs"
  namespace  = "ceph-csi-cephfs"
  repository = "https://ceph.github.io/csi-charts/"

  chart   = "ceph-csi-cephfs"
  version = "3.12.2"

  create_namespace = true
}
```

### Debug Output

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

helm_template should include namespace manifest in manifests list

### Actual Behavior

There is no namespace manifest, so can't apply manifest.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sheneska** [comment]
Hi @chrxmvtik, I have tried your example and it seems to work on my end - `output "test" { value = data.helm_template.ceph_csi_cephfs.namespace }`. Also the `helm_template` is a data source & will not create anything but instead just [render charts](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/data-sources/template#create_namespace-2:~:text=Data%20Source%3A%20helm_template).

**Comment by chrxmvtik** [comment]
> Hi @chrxmvtik, I have tried your example and it seems to work on my end - `output "test" { value = data.helm_template.ceph_csi_cephfs.namespace }`. Also the `helm_template` is a data source & will not create anything but instead just [render charts](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/data-sources/template#create_namespace-2:~:text=Data%20Source%3A%20helm_template).

Hi, thanks for response, however..

Provided output simply returns a namespace field which you set using ```namespace  = "ceph-csi-cephfs"```.

My question is what does ``create_namespace`` parameter do when using helm_template data source?

Should it render additional namespace manifest and add it to manifests list, shouldn't it? Or it is just useless parameter?

**Comment by sheneska** [comment]
Helm renders only resources that are defined in the templates. This specific field does nothing in the context of this resource, it is present there because it is also in the corresponding `helm template` subcommand.
