### ISSUE TITLE
Can not upgrade Helm charts anymore

### ISSUE THREAD

**Issue by vfouqueron** [hashicorp/terraform-provider-helm#1546]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.10.1
Provider version: 2.16.1
Kubernetes version: 1.30.6
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "mariadb_galera" {
  name = "mariadb-galera-${var.name}"

  repository = "https://charts.bitnami.com/bitnami"
  chart      = "mariadb-galera"
  version    = "14.1.0"

  namespace = module.k8s_namespace.namespace
}
```

### Debug Output
https://gist.github.com/vfouqueron/f7f9915bd74cdfd476a20182197b4ff6

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
The helm chart is upgraded to the desired versions

### Actual Behavior
A invalid_reference: invalid tag error appears

### Important Factoids
Was working fine until recently, but it is now broken for all helm_release resource I use

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kfkawalec** [comment]
I had the same problem related to: https://blog.bitnami.com/2024/10/bitnami-helm-charts-moving-to-oci.html
Solunion is to change:
  repository  = "https://charts.bitnami.com/bitnami"
to 
  repository  = "oci://registry-1.docker.io/bitnamicharts"

**Comment by jrhouston** [comment]
As @kfkawalec has pointed out, this is because bitnami has switched to OCI for their charts. See here:

https://github.com/bitnami/charts/issues/30110
