### ISSUE TITLE
0.6.2 binary release please

### ISSUE THREAD

**Issue by zzzuzik** [hashicorp/terraform-provider-helm#157]
### Affected Resource(s)

- helm_resource
- helm_repository

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Steps to Reproduce

1. `terraform apply`

### References

- GH-1234

**Comment by rporres** [comment]
It was uploaded a while ago... https://releases.hashicorp.com/terraform-provider-helm/0.6.2/
