### ISSUE TITLE
Cannot use alias with static config

### ISSUE THREAD

**Issue by nhamlh** [hashicorp/terraform-provider-helm#158]
### Terraform Version

0.11.10
### Affected Resource(s)

- helm provider

### Terraform Configuration Files
```hcl
provider "helm" {
  install_tiller = true
  alias          = "test"

  kubernetes {
    host                        = "dedacted"
    password                = "dedacted"
    username               = "dedacted"
    client_certificate     = "dedacted"
    client_key               = "dedacted"
    cluster_ca_certificate = "dedacted"
  }
}

```

### Debug Output

https://pastebin.com/47DSEJKn
### Panic Output

* provider.helm: failed to configure kubernetes config: tls: failed to find any PEM data in certificate input

### Expected Behavior

Terraform should configure the provider properly
### Actual Behavior

It's not
### Steps to Reproduce

1. `terraform apply`

### References

- GH-1234

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
