### ISSUE TITLE
Helm provider ignores FAILED state of release

### ISSUE THREAD

**Issue by stepanstipl** [hashicorp/terraform-provider-helm#159]
Terraform will ignore that release is in a `FAILED` state and will not try to bring it to desired state.

### Terraform Version
```
Terraform v0.11.7
+ provider.helm v0.6.2
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
Please clone https://github.com/stepanstipl/issue-terraform-provider-helm-ignores-failed

### Expected Behavior
Terraform should try to update releases in a `FAILED` state.

### Actual Behavior
Terraform does not try to update resource in a `FAILED` state once the initial creation succeeds.

### Steps to Reproduce
Prereqs:
- Working Kubernetes cluster (verify by running `kubectl get pods` for example)
- Working Helm (verify by running `helm list` for example)

Steps:
- Clone https://github.com/stepanstipl/issue-terraform-provider-helm-ignores-failed
  ```
  git clone https://github.com/stepanstipl/issue-terraform-provider-helm-ignores-failed
  ```
- Initialize Terraform
  ```
  cd issue-terraform-provider-helm-ignores-failed
  terraform init
  ```
- Apply Terrafrom for the 1st time
  ```
  terraform apply
  ```
  Terrafrom correctly creates release `test`. You can verify this by running `helm list` and you should see release with name `test` and status `DEPLOYED`.

- Apply terraform with invalid Kubernetes spec
  *In kubernetes, `image` field of `Job` object is immutable and can't be modified once resource is created, therefore updating this field will fail.*
  ```
  terraform apply -var image=alpine:v2
  ```
  Terraform will correctly fail, with message that `helm_release.test: 1 error(s) occurred:`. This is expected so far. Running `helm list` st this stage should show `test` release with `FAILED` status.

- Apply terraform with same config again
  ```
   terraform apply -var image=alpine:v2
  ```
  Terraform will **NOT apply any changes** even though release is in `FAILED` state (`Apply complete! Resources: 0 added, 0 changed, 0 destroyed.`).

### Important Factoids
As `helm_release` does not explicitly track state, the provider will "ignore" releases with `FAILED` status once the release has been succeesfully created at least once.

This is not specific to the `Job` K8s resource used in the example code, but rather applies to any situation when helm provider tries to upgrade existing release and fails.

**Comment by stepanstipl** [comment]
This was fixed by #161

**Comment by bluemalkin** [comment]
Is there an ETA for a release with the fix please?

**Comment by rporres** [comment]
@bluemalkin Should be done today #211

**Comment by alexsomesan** [comment]
release is out: https://releases.hashicorp.com/terraform-provider-helm/0.8.0/
