### ISSUE TITLE
can't create cluster and helm install in same configuration

### ISSUE THREAD

**Issue by cjstone** [hashicorp/terraform-provider-helm#16]
It seems I can't write a single configuration which creates a GKE cluster and then performs a helm install to the new cluster. When I try, `terraform plan` fails trying to connect to a non-existent cluster referenced in .kube/config or localhost:

```
Error running plan: 1 error(s) occurred:

* provider.helm: error creating tunnel: "Get https://104.197.58.127/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 104.197.58.127:443: i/o timeout"
```

Is it possible to prevent this checking when applying the configuration, or is that a limitation of how terraform compiles the configuration?

**Comment by mcuadros** [comment]
The helm provider doesn't install the tiller right now, so is failing because is trying to connect to something that doesn't exists. Run `helm init` in order to install the tiller in the cluster.

In a future is planned to install tiller if is not present in the cluster.

**Comment by cjstone** [comment]
Thanks! Actually I already install tiller as part of the configuration, and do get confirmation that it exists:

```
// Configure the Google Cloud provider
provider "google" {
  credentials = "${file("account.json")}"
  project     = "chris-test"
  region      = "us-central1"
}

resource "google_container_cluster" "primary" {
  name               = "chris-tf-test"
  zone               = "us-central1-b"
  initial_node_count = 1

  master_auth {
    username = "chris"
    password = "blah"
  }

  timeouts {
    create = "30m"
    delete = "30m"
  }

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    machine_type = "n1-standard-4"
  }

  provisioner "local-exec" {
    command = "/bin/sleep 60 ; /Users/chris/Downloads/google-cloud-sdk/bin/gcloud container clusters get-credentials chris-test --zone us-central1-b --project chris-test"
  }

  provisioner "local-exec" {
    command = "/bin/sleep 60 ; /usr/local/bin/helm init"
  }

}


resource "helm_chart" "jupyterhub" {
    depends_on = ["google_container_cluster.primary"],
    name = "jupyterhub",
    chart = "helm-chart",
    disable_webhooks = "true",
//    raw_values = "config.yaml"
}
```
But I do like that a tiller install will be part of the provider.  In any case, you're saying that what I'm trying to do should work?

**Comment by mcuadros** [comment]
Should work, if the helm init was success, and the kubectl namespace is the default one

**Comment by cjstone** [comment]
Thanks, that's encouraging. At this point though, I can't get past `terraform plan`, as I show above. It seems to try to test for the existence of the cluster first?  I'll keep trying though...

**Comment by mcuadros** [comment]
Tiller installed implemented at https://github.com/mcuadros/terraform-provider-helm/commit/b1a5f907f9e2e24ce0e36114d19a4c458a6f51c3

**Comment by cjstone** [comment]
None of the recently released versions remedied this issue. I still can't get these things to happen in a single terraform apply:

1. Create cluster
2. Perform helm install

When I attempt, the apply succeeds for 1 but fails on 2 with:

`* helm_chart.zz-jupyterhub: error installing: Post https://104.154.241.204/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp 104.154.241.204:443: i/o timeout`

Running terraform apply again does succeed, resulting in a complete helm install.

I tried to remedy by inserting sleep statements, but regardless of how long I waited, the helm install would still fail, apparently attempting to connect to a not-yet-ready cluster.

```
variable "cluster_name"  { default = "tf-test11"}

provider "google" {
  credentials = "${file("account.json")}"
  project     = "chris-jupyterhub"
  region      = "us-central1"
}

resource "google_container_cluster" "primary" {
  name               = "${var.cluster_name}"
  zone               = "us-central1-b"
  initial_node_count = 1

  master_auth {
    username = "blah"
    password = "blahblah"
  }

  timeouts {
    create = "60m"
    delete = "60m"
  }

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    machine_type = "n1-standard-4"
  }

    provisioner "local-exec" {
    command = "/bin/sleep 60 ;/bin/gcloud container clusters get-credentials ${var.cluster_name} --zone us-central1-b --project chris-jupyterhub ; /bin/sleep 30"
    }

}
provider "helm" {
 debug = true
}

resource "helm_chart" "zz-jupyterhub" {
    depends_on = ["google_container_cluster.primary"]
    name = "jupyterhub"
    chart = "helm-chart"
}
```

**Comment by dmeenhuis** [comment]
@cjstone Did you ever manage to resolve your issue with regards to creating both the Kubernetes cluster and installing the Helm charts? I'm trying to do the same with the latest versions, but can't seem to get it to work in the same run. Running `terraform apply` a second time works just fine.
