### ISSUE TITLE
Proxy configuration ignored

### ISSUE THREAD

**Issue by NickLarsenNZ** [hashicorp/terraform-provider-helm#160]
### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.34.0
+ provider.external v1.0.0
+ provider.helm v0.6.2
+ provider.kubernetes v1.2.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Affected Resource(s)

- helm_repository

### Terraform Configuration Files
```hcl
resource "helm_repository" "stable" {
  name = "stable"
  url  = "https://kubernetes-charts.storage.googleapis.com"
}

resource "helm_release" "external-dns" {
  name       = "external-dns"
  repository = "${helm_repository.stable.metadata.0.name}"
  chart      = "external-dns"
}
```

### Debug Output

I'm unable to provide trace level debugging as there is so much output to remove sensitive information from. Here is a Gist of the usual; TF output however, and I have TCPdump showing my machine trying to connect directly to the Helm repository rather than using the proxy.
https://gist.github.com/NickLarsenNZ/9a50e659022b5d3d43df7111d215da3a

### Panic Output

None

### Expected Behavior
The Provider should be using the system proxies:
```sh
export HTTP_PROXY=http://proxy.example.com:8080
export HTTPS_PROXY=http://proxy.example.com:8080
export http_proxy=http://proxy.example.com:8080
export https_proxy=http://proxy.example.com:8080
export NO_PROXY=localhost,127.0.0.1
export no_proxy=localhost,127.0.0.1
```

### Actual Behavior
The provider times out while trying to pull from the Helm registry. Also TCP dump shows the local machine attempting to connect directly to the resolved IP of the registry.

### Steps to Reproduce

1. `terraform apply`
2. `tcpdump -i ens192 dst host $(host kubernetes-charts.storage.googleapis.com | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')`

### Important Factoids

None

### References

No

**Comment by NickLarsenNZ** [comment]
On further inspection, it appears to be something in `k8s.io/helm/pkg/repo`.

I see `index.yaml` file being loaded here: https://github.com/helm/helm/blob/99bfe7c5ec44f90eda059a8d0fe65a2178b8e462/pkg/repo/chartrepo.go#L124

The client is set here: https://github.com/helm/helm/blob/99bfe7c5ec44f90eda059a8d0fe65a2178b8e462/pkg/repo/chartrepo.go#L65

Then through whatever means, it looks like the HTTP Client is obtained with ProxyFromEnvironment here: https://github.com/helm/helm/blob/2e9855b98ba0a04a4aa1576f3ed769b0dbd15c42/pkg/getter/httpgetter.go#L86

I guess I'll go and submit an issue over there. Would you like this kept open until it's fixed?

**Comment by NickLarsenNZ** [comment]
The error string can be found here:
- https://github.com/helm/helm/blob/8be42bae885a04b4acc242cf420911145b32ee1c/cmd/helm/init.go#L415
- https://github.com/helm/helm/blob/99bfe7c5ec44f90eda059a8d0fe65a2178b8e462/pkg/repo/chartrepo.go#L228
- https://github.com/helm/helm/blob/d3b69c1fc1ac62f1cc40f93fcd0cba275c0596de/cmd/helm/repo_add.go#L131

**Comment by NickLarsenNZ** [comment]
From this issue: https://github.com/helm/helm/issues/4326, it looks like it was fixed in https://github.com/helm/helm/releases/tag/v2.11.0

This repo currently uses v2.10.0 https://github.com/terraform-providers/terraform-provider-helm/blob/master/Gopkg.lock#L1485

**Comment by NickLarsenNZ** [comment]
Would be fixed in #143, but that PR is quite substantial

**Comment by NickLarsenNZ** [comment]
Ping @mcuadros @alexsomesan .
Is there a simple way to upgrade the helm dependency?

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
