### ISSUE TITLE
Allow Provider TLS information to provided directly

### ISSUE THREAD

**Issue by lanej** [hashicorp/terraform-provider-helm#175]
### Terraform Version

```
$ terraform -v
Terraform v0.11.11
+ provider.helm v0.7.0
```

### Affected Resource(s)

- helm_resource

### Terraform Configuration Files

```hcl
resource "tls_private_key" "helm" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P384"
}

resource "tls_self_signed_cert" "helm" {
  key_algorithm   = "ECDSA"
  private_key_pem = "${tls_private_key.helm.private_key_pem}"

  subject {
    common_name  = "www.example.com"
    organization = "foo, inc."
  }

  validity_period_hours = 86400

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
    "client_auth",
  ]
}

resource "kubernetes_service_account" "helm" {
  metadata {
    name      = "helm"
    namespace = "${var.namespace}"
  }

  automount_service_account_token = true
}

resource "kubernetes_namespace" "helm" {
  metadata {
    name = "${var.namespace}"
  }
}

resource "kubernetes_cluster_role_binding" "helm" {
  metadata {
    name = "helm"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "cluster-admin"
  }

  subject {
    api_group = ""
    kind      = "ServiceAccount"
    name      = "helm"
    namespace = "${var.namespace}"
  }

  depends_on = [
    "kubernetes_namespace.helm",
  ]
}

resource "local_file" "helm_certificate" {
  content  = "${tls_self_signed_cert.helm.cert_pem}"
  filename = "${path.cwd}/helm.pem"
}

resource "local_file" "helm_key" {
  content  = "${tls_private_key.helm.private_key_pem}"
  filename = "${path.cwd}/helm.key"
}

provider "helm" {
  version = "~> 0.7"

  insecure = true

  client_certificate = "${local_file.helm_certificate.filename}"
  client_key         = "${local_file.helm_key.filename}"
  enable_tls         = true

  install_tiller = true
  tiller_image   = "gcr.io/kubernetes-helm/tiller:v2.11.0"

  namespace       = "${var.namespace}"
  service_account = "helm"

  kubernetes {
    host = "https://${var.kubernetes}"
  }
}
```

### Expected Behavior

If TLS material could be specified directly, instead of as a file reference, the example would converge appropriately in a single run.

### Actual Behavior

Requiring TLS to specified as an external file disables making the provider to be dependent on the TLS certificate and key generation.  The provided example requires 3 terraform runs.  Two with the specific local file targets and another to setup the provider.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* Helm is being installed in a specific namespace.
* Having the TLS material stored in the remote state is desired in this case.
* The `kubernetes` sub-provider uses key data and is inconsistent with how the remainder of the `helm` provider is specified.

### References

- #53

**Comment by lanej** [comment]
Following the implementation you can see that while helm `installer.Options` requires the specification of a file, the file content is ultimately just read into memory https://github.com/terraform-providers/terraform-provider-helm/blob/4e9c862ca49d6d7ba5ba126dbdfa52e74f5d61cf/vendor/k8s.io/helm/cmd/helm/installer/install.go#L379-L405.

**Comment by shaneramey** [comment]
I worked around this issue by creating a secret using terraform-provider-kubernetes in the same namespace as Tiller.

**Comment by ewoutp** [comment]
@shaneramey Can you elaborate on what exactly you did?

**Comment by shaneramey** [comment]
@ewoutp  something like this:
```
resource "kubernetes_secret" "tiller_tls" {
  metadata {
    name      = "tiller-secret"
    namespace = "kube-system"
  }

  data = {
    "tls.key" = "${tls_private_key.tiller_server.private_key_pem}"
    "tls.crt" = "${tls_locally_signed_cert.tiller_server.cert_pem}"
    "ca.crt"  = "${tls_self_signed_cert.ca.cert_pem}"
  }

  type = "Opaque"
}
```

**Comment by Aaron-ML** [comment]
> @ewoutp something like this:
> 
> ```
> resource "kubernetes_secret" "tiller_tls" {
>   metadata {
>     name      = "tiller-secret"
>     namespace = "kube-system"
>   }
> 
>   data = {
>     "tls.key" = "${tls_private_key.tiller_server.private_key_pem}"
>     "tls.crt" = "${tls_locally_signed_cert.tiller_server.cert_pem}"
>     "ca.crt"  = "${tls_self_signed_cert.ca.cert_pem}"
>   }
> 
>   type = "Opaque"
> }
> ```

@shaneramey How do you then reference that in the helm provider configuration?

**Comment by ewoutp** [comment]
@shaneramey Understood. Thx
