### ISSUE TITLE
Outputs..

### ISSUE THREAD

**Issue by dasher** [hashicorp/terraform-provider-helm#18]
Hiya,

Just wondering how we can get outputs from charts for use with other terraform modules?

Say we deploy the influxdb helm chart - what would be the right syntax to use to get an output variable - like the IP address?

**Comment by mcuadros** [comment]
The current outputs of the `resource_chart` are the information about the release itself, not about the different stuff deployed at k8s

**Comment by iorlas** [comment]
So... We cannot automate anything? Like, we run multiple charts, then we need to manually take generated data and put it into terraform variables. Then.. Damn, so what is the purpose of this provider, if it cannot work in conjunction with other modules?

**Comment by mathplusyou** [comment]
Are there plans to implement this anytime soon?

**Comment by teu** [comment]
@iorlas You could use the kubernetes service data source https://www.terraform.io/docs/providers/kubernetes/d/service.html

**Comment by mo-elsherif** [comment]
We are having a problem that when the helm release resource is not even created then the kubernetes service is still successfully getting the helm releases' name (because its an input) and hence runs and errors with "service not found". However if this name was an output after helm release creation this would solve our problem

**Comment by JWDobken** [comment]
@mo-elsherif I think I solved your issue simply with a dependency statement, e.g.:

```hcl
resource "helm_release" "postgres" {
  name             = "postgres"
  repository       = "https://charts.bitnami.com/bitnami"
  chart            = "postgresql"
  version          = "9.8.1"
}

data "kubernetes_service" "postgres" {
  depends_on = [helm_release.postgres]
  metadata {
    name = "postgres-postgresql"
  }
}
```

**Comment by neemiasjnr** [comment]
I had the same issue deploying a chart based on a Kubernetes operator, the cluster takes time to bootstrap and I couldn't use terraform data source to get the IPs. To solve it I disabled LoadBalancer on the chart and changed to a normal ClusterIP, deployed a Load Balancer with terraform + deployed Nginx helm chart, then I could have predictable IPs/DNS I could export on outputs.tf

**Comment by ndealmeida** [comment]
Instead of getting the IP from the chart, you can pass the IP to the chart. This worked for me (GCP):
1. Created a [static global IP](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_global_address)
2. Passed the IP to the chart
```hcl
set {
  name = "loadBalancerIP"
  value = google_compute_address.my_application_ip.address
}
```
3. Configured `loadBalancerIP` on the chart
```yaml
type: LoadBalancer
loadBalancerIP: {{ .Values.loadBalancerIP }}
```
4. Added the IP as output
```hcl
output "cluster_ip" {
  value = google_compute_address.my_application_ip.address
}
```

**Comment by alias-rahil** [comment]
```terraform
provider "helm" {
  experiments {
    manifest = true
  }

  kubernetes {
    host                   = google_container_cluster.default.endpoint
    token                  = data.google_client_config.current.access_token
    cluster_ca_certificate = base64decode(google_container_cluster.default.master_auth.0.cluster_ca_certificate)
  }
}

provider "kubernetes" {
  host                   = google_container_cluster.default.endpoint
  token                  = data.google_client_config.current.access_token
  cluster_ca_certificate = base64decode(google_container_cluster.default.master_auth.0.cluster_ca_certificate)
}
```

This doesn't look very elegant because I am having to write the same code twice for authentication. Any workaround or a better way to authenticate both providers?
