### ISSUE TITLE
helm_release does not work with a custom namespace

### ISSUE THREAD

**Issue by lanej** [hashicorp/terraform-provider-helm#180]
### Terraform Version

```
$ terraform -v
Terraform v0.11.11
+ provider.helm v0.7.0
```

### Affected Resource(s)

- helm_resource

### Terraform Configuration Files

```hcl
resource "helm_release" "linkerd" {
  name      = "linkerd"
  chart     = "linkerd"
  namespace = "platform"
}
```

### Debug Output

https://gist.github.com/lanej/5b7ca3c2178a87a4f6c45644e246c597

### Expected Behavior

I would expect linkerd to be installed into the `platform` namespace.

### Actual Behavior

```
* helm_release.linkerd: rpc error: code = Unknown desc = configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "kube-system"
```

### Steps to Reproduce
```hcl
provider "helm" {
  version = "~> 0.7"

  insecure = true # self-signed TLS for now

  client_certificate = "${local_file.helm_certificate.filename}"
  client_key         = "${local_file.helm_key.filename}"
  enable_tls         = true

  install_tiller = true
  tiller_image   = "gcr.io/kubernetes-helm/tiller:v2.11.0"

  namespace       = "${var.namespace}"
  service_account = "helm"

  kubernetes {
    host = "https://${var.kubernetes}"
  }
}

resource "helm_release" "linkerd" {
  name      = "linkerd"
  chart     = "linkerd"
  namespace = "${var.namespace}"
}
```
2. `terraform apply`

### Important Factoids

The `platform` namespace is being set in the provider and the release.  I have no idea why `kube-system` is being referenced or why `configmaps` are being listed.

!!! This works as the following command

`helm upgrade --install linkerd --tiller-namespace=platform --tls --tls-cert helm.pem --tls-key helm.key`

**Comment by shaneramey** [comment]
That error indicates to me that you haven't set up the ServiceAccount and ClusterRoleBinding necessary for RBAC: https://github.com/helm/helm/blob/master/docs/rbac.md#example-service-account-with-cluster-admin-role

**Comment by lanej** [comment]
@shaneramey Sorry, should have mentioned this works as a shell command *outside* of terraform.  Updated the issue to reflect this fact.

**Comment by shaneramey** [comment]
Thanks for the update; interesting that it works from the shell. I don't know why that would be, but I can give you some info that might help to troubleshoot:

Tiller needs permission to read+write to ConfigMaps (for release metadata) in the namespace where tiller is deployed, which is why you're seeing "configmaps is forbidden". One thing to consider is the last field in the string "system:serviceaccount:kube-system:default" is the ServiceAccount name, which shows "default" and not "helm" like you specified. You might try checking the tiller pod logs. I've seen that error a lot and it's always been RBAC.

**Comment by lanej** [comment]
@shaneramey That would imply that https://github.com/terraform-providers/terraform-provider-helm/blob/edad39b04b06245707f39ddea732452169e201a4/helm/provider.go#L481-L491 should set the service account right?

**Comment by shaneramey** [comment]
The SA is specified in the link below, but must already exist when Tiller is installed. There's no logic in this repo, or the helm repo, to create the SA (nor any ClusterRoleBinding)

https://github.com/terraform-providers/terraform-provider-helm/blob/a30c4b4d8fd8e1284eeb5187d981dbab817c9a28/helm/provider.go#L406

I've used terraform-provider-kubernetes to create the ServiceAccount and ClusterRoleBinding successfully.

**Comment by lanej** [comment]
@shaneramey ok got it.  Really curious why `terraform-provider-helm` is using `serviceaccount:kube-system` if tiller knows to use `platform`.

I also used `terrafrom-provider-kubernetes` to create the `ServiceAccount`, `Namespace`, `ClusterRoleBinding`, etc.

**Comment by Pencerval** [comment]
Could we have some code snippet or documentation about how to achieve that with terraform-provider-kubernetes ? 
We are facing this issue also.
Thanks!

**Comment by legal90** [comment]
@Pencerval This is how I do and it works:
```hcl
provider "kubernetes" {
  config_context = "${var.kubernetes_context}"
}

provider "helm" {
  install_tiller  = true
  service_account = "tiller"
  namespace       = "kube-system"

  kubernetes {
    config_context = "${var.kubernetes_context}"
  }
}

resource "kubernetes_service_account" "tiller" {
  metadata {
    name      = "tiller"
    namespace = "kube-system"
  }
}

resource "kubernetes_cluster_role_binding" "tiller" {
  metadata {
    name = "tiller"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "cluster-admin"
  }

  # api_group has to be empty because of a bug:
  # https://github.com/terraform-providers/terraform-provider-kubernetes/issues/204
  subject {
    api_group = ""
    kind      = "ServiceAccount"
    name      = "tiller"
    namespace = "kube-system"
  }
}

# resource "helm_release" "your_release" <...>
```

After that `helm_release` resource works fine. Beware: Here I use not really secure setup, as `tiller` ServiceAccount is granted with `cluster-admin` ClusterRole. If you want to use more restricted setup you should follow helm instructions: https://docs.helm.sh/using_helm/#role-based-access-control
Objects `Role`, `RoleBinding` as well as `ClusterRole` and `ClusterRoleBinding` could be created by appropriate resources of `kubernetes` provider.

**Comment by rporres** [comment]
Closing this as it is related to RBAC instead of namespace issues.

@legal90 Thanks for that long write-up

At the bottom of this problem is the fact that we should have more control over tiller. Making it a resource should ease the way to handle the whole lifecycle. See #134

**Comment by prein** [comment]
I'm observing the same issue.
@legal90 in your example you are using default namespace ("kube-system") while the issue is about using a custom namespace. Try changing to a custom namespace and it will likely fail.
