### ISSUE TITLE
helm plugin is not able to connect to EKS cluster rising context deadline exceeded 

### ISSUE THREAD

**Issue by MichalPloski** [hashicorp/terraform-provider-helm#183]
I have installed tiller without TLS on EKS. Command line helm works perfectly fine, but I'm not unable to use via terraform plugin as I got "context deadline exceeded" every time I apply terraform file.
No logs are present in Tiller pod logs

Version:

Terraform v0.11.11
+ provider.external v1.0.0
+ provider.helm v0.6.2
+ provider.kubernetes v1.5.0
+ provider.null v1.0.0

Helm version:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

Affected Resource(s)

All resources for provider "helm" {}

Terraform Configuration Files:

```
provider "helm" {
  install_tiller  = true
  service_account = "tiller"
  kubernetes {
    config_context = "<REMOVED>"
  }
```
Tiller configuration:
```kubectl describe deployment tiller-deploy -n kube-system                                                                                                                                              
Name:                   tiller-deploy
Namespace:              kube-system
CreationTimestamp:      Thu, 03 Jan 2019 14:30:16 +0100
Labels:                 app=helm
                        name=tiller
Annotations:            deployment.kubernetes.io/revision: 3
Selector:               app=helm,name=tiller
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           app=helm
                    name=tiller
  Service Account:  tiller
  Containers:
   tiller:
    Image:       gcr.io/kubernetes-helm/tiller:v2.12.1
    Ports:       44134/TCP, 44135/TCP
    Host Ports:  0/TCP, 0/TCP
    Liveness:    http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:   http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:                <none>
  Volumes:                 <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   tiller-deploy-98f68568f (1/1 replicas created)
Events:          <none>
```

Expected Behavior

A chart is successfully installed just like when using Helm CLI.

Actual Behavior
 ```Error: Error refreshing state: 8 error(s) occurred:

* helm_release.nginx_ingress_l7: helm_release.nginx_ingress_l7: context deadline exceeded
* helm_release.cluster-autoscaler: 1 error(s) occurred:

* helm_release.cluster-autoscaler: helm_release.cluster-autoscaler: context deadline exceeded
```

Helm Client:
```
helm ls                                                                                                                                                                                             
NAME              	REVISION	UPDATED                 	STATUS  	CHART                        	APP VERSION           	NAMESPACE
xxx          	1       	Mon Jan 14 15:53:57 2019	DEPLOYED	xxx-0.1.3               	0.4.13                	xxx
```

**Comment by aaronmell** [comment]
Does kubectl connect with the same config?

This is what my config looks like

```
provider "kubernetes" {
 
  config_path = "~/.kube/config-environment"
  load_config_file       = true
}
```

**Comment by tecnobrat** [comment]
I am having the exact same issue.  Were you ever able to find out a solution @MichalPloski?

I can use the kubernetes provider with the exact same configuration, with the same token etc.  However helm_release still breaks.

Using the same config locally, with the exact same token, I can use `helm get` and `helm history` and get back the proper "not found".

I see no errors on tiller logs, just these:

```
[storage] 2019/02/07 15:15:28 getting last revision of "vault"
[storage] 2019/02/07 15:15:28 getting release history for "vault"
```

**Comment by tecnobrat** [comment]
I have more info, this appears to be an issue with the port forwarding in some capacity.

Mainly this section of code:

https://github.com/terraform-providers/terraform-provider-helm/blob/9f8bff689d63b8b9cbca073ee1830a3e2a04de24/helm/provider.go#L466-L480

If I create my own port-forward with `kubectl port-forward --address 192.168.2.2 -n kube-system pod/tiller-deploy-57f988f854-fwhts 44134 44135` and then set my `host` in my provider as such:

```
provider "helm" {
  ...
  host                            = "192.168.2.2:44134"
  ...
}
```

Then it works and I do not get this error.

**Comment by yorinasub17** [comment]
I just ran into this too and it looks like there is an issue with using `localhost` in `TillerHost`. Changing 

```
m.Settings.TillerHost = fmt.Sprintf("localhost:%d", m.Tunnel.Local)
```

to

```
m.Settings.TillerHost = fmt.Sprintf("127.0.0.1:%d", m.Tunnel.Local)
```

worked. Will be opening a PR soon...

**Comment by tecnobrat** [comment]
We had a suspicion that might have been the cause.  Thanks for confirming!

**Comment by rporres** [comment]
@yorinasub17  It looks like there's some issue in your local name resolution as the standard in Linux is for `localhost` to resolve to `127.0.0.1`. Can you run the command 
```
dscacheutil -q host -a name localhost
```
in your Mac OS X system to see if there's any issue?

**Comment by yorinasub17** [comment]
Thanks @rporres that appears to be the cause. On Macs it defaults to resolving both ipv4 and ipv6. This is my `/etc/hosts`:

```
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
```
