### ISSUE TITLE
Helm provider tries to connect to not yet existing k8s cluster on terraform plan

### ISSUE THREAD

**Issue by rporres** [hashicorp/terraform-provider-helm#19]
Given below config

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error running plan: 1 error(s) occurred:

* provider.helm: error installing: Post http://localhost/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:80: getsockopt: connection refused
```

### Terraform Version
Terraform v0.10.3

### Affected Resource(s)

helm provider

### Terraform Configuration Files
```hcl
provider "google" {
  credentials = ""
  project     = "${var.project}"
  region      = "{$var.zone}"
}

resource "google_container_cluster" "primary" {
  name               = "development"
  zone               = "${var.zone}"
  initial_node_count = "1"
  node_version = "1.7.4"
  cluster_ipv4_cidr = "10.12.0.0/14"

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]

    machine_type = "n1-standard-2"
    image_type = "COS"
    disk_size_gb = 100
  }
}

provider "helm" {
  kubernetes {
    host                   = "https://${google_container_cluster.primary.endpoint}"
    cluster_ca_certificate = "${base64decode(google_container_cluster.primary.master_auth.0.cluster_ca_certificate)}"
    client_certificate     = "${base64decode(google_container_cluster.primary.master_auth.0.client_certificate)}"
    client_key             = "${base64decode(google_container_cluster.primary.master_auth.0.client_key)}"
  }
}

resource "helm_repository" "stable" {
    name = "stable"
    url  = "https://kubernetes-charts.storage.googleapis.com"
}
```

### Debug Output
https://gist.github.com/rporres/5c038ec35e995b062daf92c8291e1eb6

### Expected Behavior

Terraform should have been able to create plan without trying to connect to the cluster

### Actual Behavior

Apparently it tries to connect to `localhost` since `google_container_cluster.primary.endpoint` it is not yet computed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan` with given config

**Comment by rporres** [comment]
I've confirmed that tiller is installed on `terraform plan`. This causes above example to fail because endpoint is unknown until cluster is created.

**Comment by mcuadros** [comment]
Can you check if the problem is solve with the latest version 0.3.2?
https://github.com/mcuadros/terraform-provider-helm/commit/c59546799ff8895223e6826a5c1609c7a63b65ad

**Comment by rporres** [comment]
It worked fine. The only glitch was the first time I tried to install the charts I got this message

```
Error applying plan:

1 error(s) occurred:

* module.kube-lego.helm_chart.kube-lego: 1 error(s) occurred:

* helm_chart.kube-lego: error creating tunnel: "could not find a ready tiller pod"

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
Most likely tiller wasn't yet ready the first time I tried to install a chart

Thx for the quick solution!

Closing this.

**Comment by mcuadros** [comment]
This is really weird because the provider waits for having the tiller ready. I tried several times and for me works... strange.

**Comment by rporres** [comment]
No worries, If I find it again I will try to reproduce and report it.

**Comment by Quentin-M** [comment]
Here is mine on apply, slightly different issue:

```
* module.kubernetes.helm_chart.kube-system: 1 error(s) occurred:

* helm_chart.kube-system: error installing: Post https://<redacted>/apis/extensions/v1beta1/namespaces/kube-system/deployments: EOF
```

Because the cluster is starting up, the load balancer is not yet exposing healthy API endpoints. The helm provider errors out immediately rather than retrying for a given period of time (which every Terraform provider should always do since every resources are assumed eventually consistent).

**Comment by Quentin-M** [comment]
Here is a workaround though for that specific issue:

```
resource "null_resource" "wait_for_kubernetes_api" {
  provisioner "local-exec" {
    command = <<EOF
until [ "$(curl -sk -o /dev/null -w "%{http_code}" https://<redacted> | grep 401)" ]; do
  echo The Kubernetes API is unavailable, retrying.
  sleep 10
done
EOF
  }
}

resource "helm_chart" "kube-system" {
  depends_on = ["null_resource.wait_for_kubernetes_api"]

  [...]
}
```

**Comment by Quentin-M** [comment]
And now seeing the actual reported earlier (with 0.3.2) ...

```
* helm_chart.core-components: error creating tunnel: "could not find tiller""
```

It does not look like it's waiting for anything.

**Comment by rporres** [comment]
Hi @Quentin-M I've never had that issue you're reporting. I manage to reproduce the tiller not being ready issue when deploying multiple charts. Reported in https://github.com/mcuadros/terraform-provider-helm/issues/20
