### ISSUE TITLE
Difficulty Using Provisioned TLS Information on First Apply

### ISSUE THREAD

**Issue by kevinflansburg** [hashicorp/terraform-provider-helm#191]
### Terraform Version

Terraform v0.11.10
+ provider.helm v0.7.0
+ provider.kubernetes v1.5.0
+ provider.local v1.1.0
+ provider.tls v1.2.0

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
provider "helm" {
    install_tiller  = "true"
    tiller_image              = "gcr.io/kubernetes-helm/tiller:v2.12.3"
    namespace = "${var.namespace}"
    service_account = "tiller"
    enable_tls = true
    automount_service_account_token = "true"
    client_key = "${tls_private_key.helm.private_key_pem}"
    client_certificate = "${tls_locally_signed_cert.helm.cert_pem}"
    ca_certificate = "${tls_self_signed_cert.ca.cert_pem}"

    kubernetes {
        host = "https://${var.kubernetes_host}"
        username = "admin"
        password = "${var.kubernetes_password}"
        client_certificate = "${base64decode(var.kubernetes_client_certificate)}"
        client_key = "${base64decode(var.kubernetes_client_key)}"
        cluster_ca_certificate = "${base64decode(var.kubernetes_ca_certificate)}"
    }
}

resource "helm_release" "postgres" {
  depends_on = ["kubernetes_namespace.helm", "kubernetes_secret.tiller", "kubernetes_service_account.tiller", "kubernetes_role_binding.tiller"]
  name = "postgres"
  namespace = "${var.namespace}"
  chart = "${path.root}/charts/postgres"
  values = [
    "namespace: ${var.namespace}\nhost: ${var.postgres_host}"
  ]
}

resource "helm_release" "redis" {
  depends_on = ["kubernetes_namespace.helm", "kubernetes_secret.tiller", "kubernetes_service_account.tiller", "kubernetes_role_binding.tiller"]
  name = "redis"
  namespace = "${var.namespace}"
  chart = "${path.root}/charts/redis"
  values = [
    "namespace: ${var.namespace}\nhost: ${var.redis_host}"
  ]
}
```

### Debug Output
```
2019/01/28 15:42:24 [TRACE] root.helm: eval: *terraform.EvalWriteState
2019/01/28 15:42:24 [TRACE] root.helm: eval: *terraform.EvalApplyProvisioners
2019/01/28 15:42:24 [TRACE] root.helm: eval: *terraform.EvalIf
2019/01/28 15:42:24 [TRACE] root.helm: eval: *terraform.EvalWriteState
2019/01/28 15:42:24 [TRACE] root.helm: eval: *terraform.EvalWriteDiff
2019/01/28 15:42:24 [TRACE] root.helm: eval: *terraform.EvalApplyPost
2019/01/28 15:42:24 [TRACE] root.helm: eval: *terraform.EvalUpdateStateHook
2019/01/28 15:42:26 [ERROR] root.helm: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:
* helm_release.redis: error installing: open -----BEGIN RSA PRIVATE KEY-----
<SNIP>
: file name too long
2019/01/28 15:42:26 [ERROR] root.helm: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
* helm_release.redis: error installing: open -----BEGIN RSA PRIVATE KEY-----
<SNIP>
```

### Panic Output
N/A

### Expected Behavior
Helm provider uses the PEM contents of the TLS keys to connect to Tiller. 

### Actual Behavior
Helm provider succeeds with the `postgres` release, but fails for `redis`:
* helm_release.redis: error installing: open -----BEGIN RSA PRIVATE KEY-----

A subsequent run of Terraform succeeds at applying the `redis` release. This issue only appears to happen when the TLS keys are first provisioned. 

It appears that there are certain circumstances where the provider does not identify that the supplied string is the key contents and not a file path, a feature which appears to work properly most of the time. 

### Steps to Reproduce
On a fresh install:
1. `terraform apply`

Subsequent runs succeed. 

### Important Factoids
* Kubernetes is provisioned with GKE using google provider. 
* TLS keys are provisioned with `tls` provider. 
* Kubernetes provider is used to configure Tiller secret, service account, etc. 
* `postgres` release works fine. 
* The Tiller install has been tested manually using `helm` CLI. 
* The charts are simple external name services. 

### References
My plan is configured following the suggestion in #175 to manually configure tiller-secret.

**Comment by magic7s** [comment]
I'm having the same issue (helm_release fails on first run), but I am using kubeconfig file. Helm provider is trying to connect to localhost as if kubeconfig is missing and using default localhost. Step prior uses kubeconfig successfully so the file exists. 

```hcl
provider "helm" {
  alias           = "eks"
  service_account = "tiller"
  tiller_image    = "gcr.io/kubernetes-helm/tiller:v2.11.0"

  kubernetes {
    config_path = "${ local.remote_cluster_kubeconfig }"
  }
}
```

```
2019/02/02 12:23:39 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* helm_release.istio-remote-eks: error installing: Post http://localhost/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:80: connect: connection refused
2019/02/02 12:23:39 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* helm_release.istio-remote-eks: error installing: Post http://localhost/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:80: connect: connection refused
```

https://github.com/magic7s/k8s-hybrid-cloud/issues/3

**Comment by kevinflansburg** [comment]
I have subsequently played around with the provider, and I don't believe that it is successfully configuring any releases. Terraform marks the resource as applied, but the cluster does not reflect that. It is unclear why one of the release reports success (when nothing has happened) and the other reports failure, and then success on a second run. I've switched to using the Kubernetes provider for configuring Kubernetes objects with Terraform. 

The only thing that I think is functioning is the initial Tiller installation (using my manually configured tiller-secret), but I don't think it ever successfully connects to Tiller after that point using the TLS certificates.

**Comment by magic7s** [comment]
I’m able to deploy my helm charts with this module. The fail on first run is annoying along with some other bugs. But I found the Kubernetes module very limiting. When the deployment gets complex, having helm is very useful.

**Comment by meyskens** [comment]
I was able to replicate this, the error `no such file or directory` seems to point to that somewhere in the code that gives this info to Helm a path is assumed and not the PEM itself. I have marked this as a bug. Full code to test this issue is at https://github.com/meyskens/tf-helm-playground/blob/master/tiller-tls/test.tf

**Comment by Aaron-ML** [comment]
> I was able to replicate this, the error `no such file or directory` seems to point to that somewhere in the code that gives this info to Helm a path is assumed and not the PEM itself. I have marked this as a bug. Full code to test this issue is at https://github.com/meyskens/tf-helm-playground/blob/master/tiller-tls/test.tf

@meyskens Any update on this issue? This is a big concern as we don't generally have keys floating in a file directory, versus referencing it in a vault. Makes this provider a no go.

**Comment by jonasdebeukelaer** [comment]
hi @meyskens, thanks for looking into this. Are there any updates on this bug?

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
