### ISSUE TITLE
Migrate codebase to use Go Modules

### ISSUE THREAD

**Issue by chenrui333** [hashicorp/terraform-provider-helm#196]
### Description
Go 1.11 has introduced Go modules, which looks like the official solution for dependency management going forward. 

### References 
- https://github.com/terraform-providers/terraform-provider-aws/issues/5773
- https://github.com/golang/go/wiki/Modules

**Comment by mbarrien** [comment]
Closed by #200?

**Comment by alexsomesan** [comment]
Almost. Some version tweeks are still needed on the modules. I'll close this once it's done.

**Comment by alexsomesan** [comment]
Done!
