### ISSUE TITLE
Call for more maintainers?

### ISSUE THREAD

**Issue by legal90** [hashicorp/terraform-provider-helm#197]
Hi guys,

I really like this provider and want to use it widely as well as to contribute here as much as I can. I also see that currently it has quite a lot of things to do in order to be ready for production usage. At least these things:

- [ ] Review open PRs & groom open issues as some of them might be already fixed or irrelevant
- [x] Actualize the documentation
- [x] Release a new version
- [x] Update Changelog, provide more details about releases. 
- [x] Update "Releases" page with a valid _Latest Release_ mark, short release description, etc.

From the other hand, I see that open issues and PRs don't have response from maintainers for weeks. Of course, that's absolutely OK for OSS, so I just want to offer:

- If current maintainers don't have enough time for this (which is totally fine) - let's add some more from collaborators? I can offer myself as a candidate, just in case.
- Add `OWNERS`/`MAINTAINERS` file or the section of `README.md` listing all current maintainers, so other collaborator will know whom to expect to review issues, PRs and manage releases.

/cc: @meyskens, @alexsomesan, @mcuadros

**Comment by rporres** [comment]
Hi @legal90. You're right in the need for the provider for more active development. Added to those points I would add

* Make tiller a separate resource
* Deprecate repository resource

I'm working in finding time with our current employer to develop those which are cause of a lot of current grief. In the maintime, @meyskens and myself will work in the current issues you've mentioned. At some point we will talk with @alexsomesan about appointing new maintainers.

**Comment by rporres** [comment]
> Update Changelog, provide more details about releases.

What do you mean by this @legal90? Is #211 what you were expecting?

**Comment by rporres** [comment]
> * Update "Releases" page with a valid _Latest Release_ mark, short release description, etc.

AFAIK, that's not the standard in terraform providers... All the information is in the `CHANGELOG` file

**Comment by Jeeppler** [comment]
@rporres @ctrox is already working on a separate Tiller resource: https://github.com/terraform-providers/terraform-provider-helm/pull/203

**Comment by legal90** [comment]
> What do you mean by this @legal90? Is #211 what you were expecting?

@rporres, yes, that's it! Thank you!

> AFAIK, that's not the standard in terraform providers... All the information is in the `CHANGELOG` file

Ah, OK then. I was just a bit confused by seeing _Latest Release_ as `v0.6.0`. Regarding the release notes - CHANGELOG is fine. 👍

**Comment by ianks** [comment]
Also, I think we should make a 1.0 milestone and gather all the issues that need to be tackled to get there

**Comment by cwiggs** [comment]
I don't have any Go experience but I do have a fair amount of Terraform experience, and am actively using this provider.  If I can help I'm more than willing, just let me know.

**Comment by rporres** [comment]
@Jeeppler Reviewed the great work from @ctrox in #203.

**Comment by aaronmell** [comment]
After the work done on helm v3, I wouldn't mind being added as a maintainer. Our company is committed to using helm and terraform, so I have a vested interest in the plugin. @meyskens, @rporres

**Comment by jrhouston** [comment]
Thanks for opening this issue @legal90. I recently joined HashiCorp and will be a maintainer on this provider. 

We are open to adding community maintainers to this provider, but we haven't yet established a process for doing so. I will update this issue when I know more.

**Comment by mcuadros** [comment]
Looks like now we have enough maintainers, since I am back after a year or so, plus now we have @jrhouston giving support to this from inside of Hashicorp. 

Plus @aaronmell has become an excellent contributor after the migration to Helm 3 (kudos).

I am grooming all the issue and closing the old related to v2, and I found two main areas to improve:
- Avoid leaking sensitive values on plans
- Research the about print a diff of the manifest on the plan.

I will try to work these days that we are lockdown but anyway it's free to give a hand too.

So I am happy to close this issue. Thanks @legal90
