### ISSUE TITLE
Option to not wait for a healthy helm release

### ISSUE THREAD

**Issue by mattysweeps** [hashicorp/terraform-provider-helm#205]
I have a circular dependency issue:

Imagine a helm release with two services, Service A and Service B.

Service A requires a DNS record to resolve before it can become healthy.
The DNS record in question needs to point at Service B.

1. Helm release launches Services A and B, but A never becomes healthy
2. The DNS record is never created because its Terraform resource relies on a Terraform data source for the Kubernetes service Service B

Thus the deployment cannot succeed.

I can think of two solutions:
1. Have better helm chart(s)
2. Include an option in a Terraform helm release to not wait for resources to become healthy.

Since I do not control the Helm charts (https://github.com/SUSE/scf) the only option left for me is the latter.

**Comment by legal90** [comment]
> 2\. Include an option in a Terraform helm release to not wait for resources to become healthy.

@mattysweeps Actually, there is the one called `wait` (it's not mentioned in the docs by some reason). Try setting it to `false` for your release resource:
```hcl
resource "helm_release" "my_database" {
    name       = "my-database"
    repository = "stable"
    chart      = "mariadb"

    wait = false
}
```

**Comment by rporres** [comment]
There were some attributes missing from the documentation, see #192 and #209. They will reach the main terraform doc when we cut a new release.

**Comment by prein** [comment]
When was "wait" introduced? I'm getting the following error:
`Error: helm_release.prometheus-operator: : invalid or unknown key: wait`
My TF version:
```
Terraform v0.11.11
+ provider.external v1.2.0
+ provider.helm (unversioned)
+ provider.kubernetes v1.7.0
+ provider.null v2.1.2

```
