### ISSUE TITLE
Helm option and bool in Terraform

### ISSUE THREAD

**Issue by okgolove** [hashicorp/terraform-provider-helm#208]
### Terraform Version

Terraform v0.11.11

### Affected Resource(s)

- helm_resource

### Terraform Configuration Files
```hcl
resource "helm_release" "certmanager" {
  name      = "${var.certmanager_release_name}"
  chart     = "stable/cert-manager"
  namespace = "${var.certmanager_namespace}"
  version   = "${var.certmanager_chart_version}"

  set {
    name  = "webhook.enabled"
    value = false
  }

  set {
    name  = "ingressShim.defaultIssuerName"
    value = "letsencrypt"
  }

  set {
    name  = "ingressShim.defaultIssuerKind"
    value = "ClusterIssuer"
  }
}
```

### Expected Behavior

`helm get values cert-manager`
```
webhook:
  enabled: false
```

### Actual Behavior

I'm not sure, but it seems not so obvious:

`helm get values cert-manager`
```
webhook:
  enabled: "0"
```

### Steps to Reproduce

1. `terraform apply`

In my case if I specify just `false`, webhook dependency will be installed.
If I specify `"false"`, everything works as expected, dependency won't be installed.

**Comment by rporres** [comment]
Terraform converts `true` and `false` to strings `1` and `0`, see https://www.terraform.io/docs/configuration/variables.html#booleans

The use of `"true"` as a string combined with `set` block will get the behaviour you want.

Feel free to reopen if you have further issues.
