### ISSUE TITLE
helm_chart repository_url does not update existing repository

### ISSUE THREAD

**Issue by rporres** [hashicorp/terraform-provider-helm#21]
If I configure my helm chart using `repository_url` to download the chart, new versions need the cache file to be updated manually (via `helm update`) or it will fail to provision the new version

### Terraform Version
Terraform v0.10.3
terraform-provider-helm v0.3.2

### Affected Resource(s)
`helm_chart`

### Terraform Configuration Files
```hcl
resource "helm_chart" "drone" {
  name           = "drone"
  repository_url = "https://src-d.github.io/charts/"
  chart          = "srcd/drone"
  version        = "0.1.2"
}
```

### Output
```
terraform apply
(...)
module.drone_server.helm_chart.drone: Creating...
  chart:                "" => "srcd/drone"
  keyring:              "" => "/Users/rporres/.gnupg/pubring.gpg"
  metadata.#:           "" => "<computed>"
  name:                 "" => "drone"
  namespace:            "" => "default"
  repository_url:       "" => "https://src-d.github.io/charts/"
  version:              "" => "0.1.2"
1 error(s) occurred:

* module.drone_server.helm_chart.drone: 1 error(s) occurred:

* helm_chart.drone: chart "drone" matching 0.1.2 not found in srcd index. (try 'helm repo update'). No chart version found for drone-0.1.2

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior
provider being able to update existing repository

### Actual Behavior
It prompted the user for manual update

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
with a chart version
2. `terraform apply`
with a new version

**Comment by mcuadros** [comment]
`repository_url` shouldn't be used. Use `repository` and remove the `repo/` from the name.
