### ISSUE TITLE
the server could not find the requested resource (post deployments.extensions)

### ISSUE THREAD

**Issue by hareku** [hashicorp/terraform-provider-helm#214]
### Terraform Version

`Terraform v0.11.11`

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "example" {
  name     = "test-release"
  chart     = "./helm/example"
}
```

### Debug Output

```
helm_release.example: Creating...
  chart:            "" => "./helm/example"
  disable_webhooks: "" => "false"
  force_update:     "" => "false"
  metadata.#:       "" => "<computed>"
  name:             "" => "test-release"
  namespace:        "" => "default"
  recreate_pods:    "" => "false"
  reuse:            "" => "false"
  reuse_values:     "" => "false"
  status:           "" => "DEPLOYED"
  timeout:          "" => "300"
  verify:           "" => "false"
  version:          "" => "0.1.0"
  wait:             "" => "true"
Releasing state lock. This may take a few moments...

Error: Error applying plan:

1 error(s) occurred:

* helm_release.example: 1 error(s) occurred:

* helm_release.example: error installing: the server could not find the requested resource (post deployments.extensions)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

terraform providers version.
```
* provider.aws: version = "~> 1.58"
* provider.helm: version = "~> 0.8"
* provider.local: version = "~> 1.1"
* provider.null: version = "~> 2.0"
* provider.template: version = "~> 2.0"
```

helm version.
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

kubectl version.
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:49:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Expected Behavior

`helm_release` install chart

### Actual Behavior

`helm_release` returns error, but `helm install --name test-release helm/example/` worked well.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

https://github.com/helm/helm/issues/4699
I set `wait = "false"`, but that returned same above error.

### References

- GH-1234

**Comment by hareku** [comment]
I got more information.
`chart     = "./charts/does-not-exist-dir"`

I set `helm_release.chart` to directory that does not exist, but I got same error.
I think this is due to this helm provider.

**Comment by hareku** [comment]
Hmmm...
I got a different error after restarting local client(macbook).

```
* helm_release.example: error creating tunnel: "Get http://localhost/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp [::1]:80: connect: connection refused"
```

Helm command is working.
Is helm provider different authN flow from `helm` command ?

terraform provider config is below.
```
provider "helm" {
  kubernetes {
    config_path = "${file("~/.kube/config")}"
  }
  debug = true
  install_tiller = false
}
```

**Comment by legal90** [comment]
This issue duplicates #189.

@hareku Try setting the absolute path this way:
```
resource "helm_release" "example" {
  name     = "test-release"
  chart     = "${path.module}/helm/example"
}
```

**Comment by hareku** [comment]
@legal90 Thank you
I fixed a chart path, but that is not working.

```
* helm_release.example: error installing: Post http://localhost/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:80: connect: connection refused
```

The command `helm install --debug --name test-release helm/example/`  is working well.

**Comment by hareku** [comment]
I comment outed `config_path` in provider config, helm_release worked out, but I don't know why that worked.
`~/.kube/config` exists in my computer.

```
provider "helm" {
  # kubernetes {
  #   config_path = "${file("~/.kube/config")}"
  # }
}
```

**Comment by legal90** [comment]
Oh, it seems that the usage example for `config_path` option in docs is wrong https://www.terraform.io/docs/providers/helm/index.html#file-config

`config_path` should be the file path, but not the content of the file. So try without `file()` function:
```
provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}
```
P.s. `"~/.kube/config"` is the default value for `config_path`. That's why you got it working when you just omit this option: https://github.com/terraform-providers/terraform-provider-helm/blob/da3bd8d7430e86b08b9b93eb8086724e95de2b43/helm/provider.go#L198-L208

**Comment by hareku** [comment]
@legal90 Thank you
I opened a PR to fix the doc.
https://github.com/terraform-providers/terraform-provider-helm/pull/215
