### ISSUE TITLE
Helm release doesn't work with gitlab-runner chart

### ISSUE THREAD

**Issue by lahsivjar** [hashicorp/terraform-provider-helm#223]
### Terraform Version

v0.11.11

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "null_resource" "helm_add_gitlab_repository" {
  triggers {
    run_everytime = "${timestamp()}"
  }
  provisioner "local-exec" {
    command = "helm repo add gitlab https://charts.gitlab.io"
  }
}

resource "helm_release" "gitlab-runner" {
  name = "gitlab-runner"
  repository = "gitlab"
  chart = "gitlab/gitlab-runner"
  namespace = "gitlab"

  values = [
    "${file("gitlab-runner-values.yaml")}"
  ]

  depends_on = [
    "null_resource.helm_add_gitlab_repository"
  ]
}
```

### Debug Output

```hcl
Error: Error applying plan:

1 error(s) occurred:

* helm_release.gitlab-runner: 1 error(s) occurred:

* helm_release.gitlab-runner: repo gitlab not found
```
Full trace log: https://gist.github.com/lahsivjar/1ceed78d2dadba56d62917df367b7b91

### Expected Behavior

Chart is applied

### Actual Behavior

Fails with an output that is so simple that it makes you want to pull out your hair

### Steps to Reproduce

Try to use the above tf resources

### Important Factoids

Running on gitlab ci

**Comment by meyskens** [comment]
Can you try using the repository resource? https://www.terraform.io/docs/providers/helm/repository.html

**Comment by lahsivjar** [comment]
Hi @meyskens,

I am avoiding using helm_repository because of this issue: https://github.com/terraform-providers/terraform-provider-helm/issues/146

**Comment by legal90** [comment]
> chart = "gitlab/gitlab-runner"

@lahsivjar I would recommend setting `chart = "gitlab-runner"` instead, because the repository name is already declared via `repository` argument. Does it work?

**Comment by lahsivjar** [comment]
@legal90 Sorry, have been away for a while. Will confirm this weekend

**Comment by lahsivjar** [comment]
Sorry, for the late response.

Still getting the same issue with:

```
resource "helm_release" "gitlab-runner" {
  name = "gitlab-runner"
  repository = "gitlab"
  chart = "gitlab-runner"
  namespace = "gitlab"

  values = [
    "${file("gitlab-runner-values.yaml")}"
  ]


  depends_on = [
    "null_resource.helm_repo_update"
  ]
}
```

**Comment by meyskens** [comment]
@lahsivjar have you tried with 0.9.0 and the new repo data source?

**Comment by lahsivjar** [comment]
@meyskens You mean try with terraform version 0.9.0?

Today I tried using elasticsearch chart the same way and it works so maybe some issue specifically with the gitlab chart

**Comment by lahsivjar** [comment]
Got it to work using this:

```
resource "helm_release" "gitlab-runner" {
  name = "gitlab-runner"
  repository = "https://charts.gitlab.io"
  chart = "gitlab-runner"
  namespace = "gitlab"
...
}
```

**Comment by rporres** [comment]
@lahsivjar @meyskens was referring to the provider version... But glad things work for you now.
