### ISSUE TITLE
`client_certificate` reused as the Tiller server's certificate

### ISSUE THREAD

**Issue by BarnabyShearer** [hashicorp/terraform-provider-helm#225]
### Terraform Version
Terraform v0.11.11
+ provider.helm v0.8.0

### Affected Resource(s)
- provider "helm"

### Terraform Configuration Files
```hcl
provider "helm" {
  enable_tls = true
  client_key = "key.pem"
  client_certificate = "cert.pem"
  ca_certificate = "ca.pem"
}
```

### Expected Behavior
`key.pem` and `cert.pem` are used by the client to authenticate with Tiller. The Tiller server should use a different certificate and key. 

### Actual Behavior

The provider also reuses `key.pem` and `cert.pem` as the Tiller server's certificate.

### Steps to Reproduce

1. `terraform apply`

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
