### ISSUE TITLE
terraform 0.12 Compatible release

### ISSUE THREAD

**Issue by TMaYaD** [hashicorp/terraform-provider-helm#229]
Now that terraform 0.12-beta1 is out, we should build and release a compatible binary.

**Comment by alexsomesan** [comment]
There is already a pending PR for this, so it should happen very soon.
We do have to make sure no urgent fixes needs to be release for 0.11 before we can merge that.

You can build off of the PR branch in the mean time if you want to try it out.
See here: https://github.com/terraform-providers/terraform-provider-helm/pull/219

**Comment by TMaYaD** [comment]
I've seen the branch but I failed to build the branch, probably due to an issue in my setup. This issue was for beta-binaries. It would be great if you or someone more familiar can build the branch and make binaries available as pre-release binaries.

**Comment by alexsomesan** [comment]
Version 0.9.1 has been released which supports the new Terraform 0.12 protocol.
