### ISSUE TITLE
Should helm_chart be renamed to helm_release?

### ISSUE THREAD

**Issue by mstrzele** [hashicorp/terraform-provider-helm#24]
According to [Helm documentation](https://docs.helm.sh/using_helm/#using-helm):

> A _Chart_ is a Helm package. It contains all of the resource definitions necessary to run an application, tool, or service inside of a Kubernetes cluster. Think of it like the Kubernetes equivalent of a Homebrew formula, an Apt dpkg, or a Yum RPM file.

> A _Release_ is an instance of a chart running in a Kubernetes cluster. One chart can often be installed many times into the same cluster. And each time it is installed, a new _release_ is created. Consider a MySQL chart. If you want two databases running in your cluster, you can install that chart twice. Each one will have its own release, which will in turn have its own _release name_.

**Comment by ilyasotkov** [comment]
This is an important issue.

The way Helm works, you can have one main chart and many subcharts installed at the same time, all in one release.

Chart: templates + generic default `values.yaml`

Release: a main chart + one or more subcharts + custom (release-specific) `values.yaml`
