### ISSUE TITLE
TFE runs error with helm_repository: Couldn't load repositories file

### ISSUE THREAD

**Issue by jcam** [hashicorp/terraform-provider-helm#246]
### Terraform Version
Terraform v0.11.13

### Affected Resource(s)
- helm_repository

### Terraform Configuration Files
```hcl
data "helm_repository" "bedrock_helm" {
  name = "bedrock"
  url  = "https://repo.br.hmheng.io/artifactory/kubernetes-charts"
}

resource "helm_release" "myapp" {
  name      = "myapp"
  chart     = "bedrock/myapp"
  namespace = "myapp"
}
```

### Expected Behavior
The data resource should have caused terraform to check for and create a helm repository

### Actual Behavior
Terraform plan errors unable to read file:
```
* data.helm_repository.bedrock_helm: data.helm_repository.bedrock_helm: Couldn't load repositories file (/root/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
```

### Steps to Reproduce

1. Add a helm_repository to a template that uses TFE's atlas backend (issue occurs with both data source and resource)
2. Plan and apply the template on a local machine
3. Trigger a plan in TFE

**Comment by rporres** [comment]
If you use the syntax
```hcl
  chart     = "bedrock/myapp"
```
helm will ignore whatever repository you have previously defined and will look locally for a repository called `bedrock`. Your example should be written as follows to let the provider take care
```hcl
data "helm_repository" "bedrock_helm" {
  name = "bedrock"
  url  = "https://repo.br.hmheng.io/artifactory/kubernetes-charts"
}

resource "helm_release" "myapp" {
  name      = "myapp"
  repository = data.helm_repository.bedrock_helm.metadata[0].name
  chart     = "myapp"
  namespace = "myapp"
}
```
