### ISSUE TITLE
helm-release, tiller resources not deleted in order, ends up in error

### ISSUE THREAD

**Issue by sheelachoudhari** [hashicorp/terraform-provider-helm#247]
Hi There,
I am able to create helm releases onto EKS cluster with Terraform Helm Release along with service-account and cluster-role-binding for Tiller. Terraform destroy is not successful and ends in errors.

### Terraform Version

Terraform v0.11.11

### Affected Resource(s)

- Terraform helm_release
- Terraform kubernetes_cluster_role_binding

### Terraform Configuration Files
```hcl
provider "helm" {
  service_account = "${module.tiller.service_account}"

  kubernetes {
    host                   = "--"
    cluster_ca_certificate = "--"
    token                  = "--"
  }
}

module "tiller" {
  source = "../terraformmodules/helm/tiller"
  --other configurations--
}

module "cluster-autoscaler" {
  source       = "../terraformmodules/helm-releases/cluster-autoscaler" 
  --other configurations--
}

module "metrics-server" {
  source       = "../terraformmodules/helm-releases/metrics-server"
  --other configurations--
}

#Resources created in tiller module:
resource "kubernetes_service_account" "tiller" {
  metadata {
    name      = "tiller"
    namespace = "kube-system"
  }
}

resource "kubernetes_cluster_role_binding" "tiller" {
  metadata {
    name = "tiller"
  }

  role_ref {
    kind      = "ClusterRole"
    name      = "cluster-admin"
    api_group = "rbac.authorization.k8s.io"
  }

  subject {
    kind      = "ServiceAccount"
    name      = "tiller"
    namespace = "kube-system"
    api_group = ""
  }
}

#Resources created in helm-releases module
resource "helm_release" "cluster-autoscaler" {
  name      = "cluster-autoscaler"
  chart     = "${path.module}/chart"
  namespace = "kube-system"
  --set other chart values --
}

resource "helm_release" "metrics-server" {
  name      = "metrics-server"
  chart     = "${path.module}/chart"
  namespace = "kube-system"
}
```

### Expected Behavior

Terraform destroy is successful deleting resources in following order,
1. helm-release
2. tiller/k8s-cluster-role-binding

### Actual Behavior

Error: Error applying plan:

3 error(s) occurred:

* module.metrics-server.helm_release.metrics-server (destroy): 1 error(s) occurred:

* helm_release.metrics-server: rpc error: code = Unknown desc = configmaps is forbidden: User "system:serviceaccount:kube-system:tiller" cannot list configmaps in the namespace "kube-system"
* module.cluster-autoscaler.helm_release.cluster-autoscaler (destroy): 1 error(s) occurred:

* helm_release.cluster-autoscaler: rpc error: code = Unknown desc = configmaps is forbidden: User "system:serviceaccount:kube-system:tiller" cannot list configmaps in the namespace "kube-system"

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

Other comments:
Cluster-role-binding seems to have been deleted before helm-releases, or these are tried to delete in parallel.

Terraform helm_release does not have supported argument that can be used to refer tiller cluster_role_binding. Something like,
```hcl
resource "helm_release" "my-release" {
  --other values--
  cluster_role_binding = "tiller"
}
```
Is this something tf helm provider can support? Is there a issue being tracked or addressed around cluster-role-binding and helm-release dependencies? What are the best workarounds if any. Appreciate any suggestions here. Thanks.

**Comment by jbuettnerbild** [comment]
As a workaround you can do something like that:

resource "helm_release" "my-release" {
....

provisioner "local-exec" {
    when = "destroy"
    command = "kubectl delete deploy tiller-deploy -n kube-system --context='your context' --kubeconfig='path to your kubeconfig'"
  }
}

**Comment by rporres** [comment]
Hi @sheelachoudhari. The order of the creation/update/deletion is out of the scope of the provider. I guess that the thing is biting you is the fact that tiller is not a resource yet and you cannot use the user definition there.

What you could try to do is adding a fake `depends_on` variable in your helm releases modules in which you add an output of the tiller module. That would create an implicit dependency.

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
