### ISSUE TITLE
helm_release resource succeeds before CRD propagation

### ISSUE THREAD

**Issue by jpreese** [hashicorp/terraform-provider-helm#248]
### Terraform Version
Terraform v0.11.13
+ provider.helm v0.9.0
+ provider.kubernetes v1.5.2
+ provider.local v1.2.0
+ provider.null v2.1.0
+ provider.tls v1.2.0

### Affected Resource(s)
- helm_resource

### Expected Behavior
When using helm_release on a chart that contains a CRD, helm_release should mark itself as deployed when the applied CRDs have been propogated to the kube api server

### Actual Behavior
The helm_release completes, and the next helm_resource that relies on the CRDs from the previous install fails because it cannot use the CRDs yet.

### Steps to Reproduce
In my case, I'm using Istio

```code
resource "helm_release" "istio_init" {
  name       = "istio-init"
  repository = "${data.helm_repository.istio.url}"
  chart      = "istio-init"
  version    = "${var.version}"
  namespace  = "${kubernetes_namespace.istio.metadata.0.name}"
}

/* even though depends_on is configured, this will fail because the above CRDs
* have yet to propagate to the api server. the only solution thus far is to introduce
* a delay within the terraform config. */
resource "helm_release" "istio" {
  name       = "istio"
  repository = "${data.helm_repository.istio.url}"
  chart      = "istio"
  version    = "${var.version}"
  namespace  = "${kubernetes_namespace.istio.metadata.0.name}"

  depends_on = [
    "helm_release.istio_init",
  ]
}
```

### Important Factoids
Running on Docker Desktop for Windows

**Comment by dineshba** [comment]
~Can we use `wait` [option](https://helm.sh/docs/helm/#options-21) of helm like below~
```
resource "helm_release" "istio_init" {
  ...
  wait = true
}
```
**Sorry** By default it is using wait as true

**Comment by jpreese** [comment]
Yes, it is true by default. I'm also not convinced it would be something Helm itself should concern itself with. 

In the Terraform world, I imagine adding a delay/sleep after a helm_release that has CRDs would be common place because proceeding releases would fail, unless you got lucky enough.

**Comment by librasean** [comment]
Encountered same problem - minor inconvenience  but added a delay in between istio-init and istio as @jpreese suggested:
`
resource "null_resource" "delay" {
  provisioner "local-exec" {
    command = "sleep 60"
  }
  depends_on = ["helm_release.istio-init"]
}
`

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
