### ISSUE TITLE
Sensitive Values leak when changed/removed

### ISSUE THREAD

**Issue by rmb938** [hashicorp/terraform-provider-helm#251]
### Terraform Version
```
Terraform v0.11.7
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "thanos" {
  name       = "thanos"
  repository = "${var.helm_repo}"
  chart      = "thanos"
  version    = "0.2.0"
  namespace  = "${module.prometheus.namespace}"

  set_sensitive {
    name  = "s3.awsAccessKey"
    value = "access key"
  }
  set_sensitive {
    name  = "s3.awsSecretKey"
    value = "secret key"
  }

}
```

### Expected Behavior

Diff not to show sensitive values

### Actual Behavior

Diff showed sensitive values

```
      set_sensitive.#:                "2" => "0"
      set_sensitive.3469752628.name:  "s3.awsSecretKey" => ""
      set_sensitive.3469752628.value: "some_secret_here" => ""
      set_sensitive.4209480927.name:  "s3.awsAccessKey" => ""
set_sensitive.4209480927.value: "other_secret_here" => ""
```

### Steps to Reproduce
1. `terraform apply`
1. Remove `set_sensitive` values
1. `terraform plan`

### Important Factoids

This seems like it would be a terraform bug instead of one in the provider but I figured I would start here first.

**Comment by dineshba** [comment]
As @rmb938 you mentioned it is `terraform` bug [refer](https://github.com/hashicorp/terraform/issues/20051).

**Comment by gordonbondon** [comment]
I don't know if I should create another issue. But with terraform > 0.12 helm provider leaks secrets when anything in release changes because all of the unchanged attributes are also shown. And they include `metadata = [ { values ="..." } ]` which displays all of the values in plaintext during plan/apply.

**Comment by bjaworski3** [comment]
Is this being worked on right now? With terraform > 0.12, we basically can't use the helm provider because any changes in the helm chart will print out all values in plaintext via the `metadata.values` field, including any `set_sensitive` values

**Comment by aareet** [comment]
Closing in favour of https://github.com/terraform-providers/terraform-provider-helm/pull/480
