### ISSUE TITLE
'unexpected EOF' if value is set to null, then overridden in another values file

### ISSUE THREAD

**Issue by mattparkes** [hashicorp/terraform-provider-helm#254]
I'm feeding in 2 values files to `helm_release`:
 1.  `common.yaml` sets `foo.bar: null` _(primarily to override a dangerous value in the chart's `values.yaml`)_
 2. `foo.yaml` which then sets `foo.bar: <whole bunch of sub keys>`

When I do a `terraform apply` with this configuration, I get `unexpected EOF`

### Terraform Version
`Terraform v0.11.13`

### Affected Resource(s)
`helm_resource`

### Terraform Configuration Files
```hcl
resource "helm_release" "prometheus-foo" {
  name = "prometheus-foo"
  chart = "stable/prometheus"
  timeout = 600
  version = "8.10.0"
  force_update = true

  values = [
    "${file("values/prometheus-common.yaml")}",
    "${file("values/prometheus-foo.yaml")}"
  ]

  set {
    name = "serverFiles.prometheus\\.yml.remote_write[0].url"
    value = "https://cortex.${var.environment-purpose}.foo.com/api/prom/push"
  }

  set {
    name = "serverFiles.prometheus\\.yml.scrape_configs[0].relabel_configs[1].replacement"
    value = "${var.environment-brand}"
  }
}
```

**prometheus-common.yaml**
```
serverFiles:
  prometheus.yml:
    scrape_configs: null
```

**prometheus-foo.yaml**
```
serverFiles:
  prometheus.yml:
    scrape_configs: 
      - job_name: 'kubernetes - cadvisor'
        scheme: https
        tls_config:
```

### Panic Output
```
panic:Error: Error applying plan:
 interface conversion: interface {} is nil, not []interface {}
```

### Expected Behavior
`helm_release` resources successfully deployed.

### Actual Behavior
```
Error: Error applying plan:

* helm_release.prometheus-foo: 1 error(s) occurred:

* helm_release.prometheus-foo: unexpected EOF

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
```
helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"```

**Comment by mattparkes** [comment]
_**Edit:** Have completely overhauled the initial report._

**Comment by rporres** [comment]
Why are you mixing `set` and `values` over the same yaml keys. It looks as some merging issues are happening. Can you just pass everything you want in the yaml and see if that helps?

**Comment by mattparkes** [comment]
It is a merging issue and it does help.

However it works fine doing the exact same thing natively with helm (and an example is even given in the documentation of how to do exactly this).

I cannot hardcore the values in YAML files as I have >50 environments, and the value of any properties I set with `set` are dynamically calculated from other terraform resources. (Though they aren’t in my slightly redacted/contrived example in this issue.)

My issue is two parts:
1.) that this issue exists at all
2.) that the EOF error doesn’t give any hints to diagnose the issue.

**Comment by felippe-mendonca** [comment]
Had this problem when try to add some annotations. 
```HCL
set {
    name  = "ingress.annotations.kubernetes\\.io/ingress\\.class"
    value = "internal"
}
```

After take a look at [documentation](https://www.terraform.io/docs/providers/helm/release.html), realized that I should use `set_string` instead. Although, still having same issue.

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
