### ISSUE TITLE
bcrypt() function not working when used inside set_string in terraform template.

### ISSUE THREAD

**Issue by as-ajitsingh** [hashicorp/terraform-provider-helm#259]
### Terraform Version
Terraform v0.11.13
provider.helm v0.9.0

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
provider "helm" {
}
variable "domain_name" {
    default = "my-sample-domain.com"
}
variable "password" {
    default = "somepassword123"
}

resource "helm_release" "mosipjfrog" {
    name      = "jfrog"
    chart     = "../charts/jfrog-7.13.11.tgz"
    

    set {
        name = "artifactory.image.repository"
        value = "docker.bintray.io/jfrog/artifactory-oss"
    }
	set {
        name = "postgresql.enabled"
        value = "false"
    }
    set {
        name = "artifactory.configMapName"
        value = "my-release-bootstrap-config"
    }
    set_string {
        name = "ingress.host"
        value = "${var.domain_name}"
    }

    set_string {
        name = "ingress.tls.hostname"
        value = "${var.domain_name}"
    }

    set_string {
        name = "admin.password"
        value = "${bcrypt(var.password)}"

    }
}
```

### Debug Output
https://gist.github.com/as-ajitsingh/c4dd753e490921a03ad86b6046b9f21a

### Expected Behavior
It should generate bcrypt hash of the given string

### Actual Behavior
It is failing to set bcrypt hash and giving  `Mismatch reason: attribute mismatch: set_string.2081887169.name`

### Steps to Reproduce
1. `terraform apply`

**Comment by Swatikp** [comment]
I am also facing the same issue. For me it is working for sha1, but when I use bcrypt function, I get the same error.

**Comment by rporres** [comment]
The problem is with [bcrypt](https://www.terraform.io/docs/configuration/functions/bcrypt.html) function:

> Since a bcrypt hash value includes a randomly selected salt, each call to this function will return a different value, even if the given string and cost are the same. Using this function directly with resource arguments will therefore cause spurious diffs. We recommend using this function only in provisioner blocks, or in data resources whose results are only used in provisioner blocks.

This is due to `bcrypt` not allowing to specify salt in golang. See golang/go#18737

That's why @Swatikp example works well, as `sha1` works fine, as `sha1` value remains constant

You may want to work with [random provider](https://www.terraform.io/docs/providers/random/index.html) and use k8s secrets to store passwords.
