### ISSUE TITLE
Terraform wants to recreate already existing releases

### ISSUE THREAD

**Issue by sagikazarmark** [hashicorp/terraform-provider-helm#26]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.10.4

### Affected Resource(s)
Please list the resources as a list, for example:
- helm_chart

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "kubernetes_namespace" "logging" {
    metadata {
        name = "logging"
    }
}

resource "helm_chart" "logcollector" {
    name       = "logcollector"
    namespace  = "${kubernetes_namespace.logging.metadata.0.name}"
    chart      = "fluent-bit"
    repository = "${helm_repository.web.name}"
    version    = "0.1.0"
    timeout    = 600

    set {
        name  = "image.fluent_bit.tag"
        value = "0.12.2"
    }

    set {
        name  = "filter.merge"
        value = "On"
    }

    set {
        name  = "backend.type"
        value = "es"
    }

    set {
        name  = "backend.es.host"
        value = "${helm_chart.es.name}-elasticsearch.${kubernetes_namespace.persistence.metadata.0.name}.svc"
    }

    set {
        name  = "resources.limits.memory"
        value = "300Mi"
    }

    set {
        name  = "rbac.create"
        value = true
    }

    # TODO: increase resources
}
```

Happens with several different configurations as well (note that this is only a partial configuration missing the elasticsearch setup)

### Panic Output
None

### Expected Behavior
Terraform should just work

### Actual Behavior
Terraform wants to recreate already existing releases:

```
  + module.dev-k8s.helm_chart.logcollector
      id:                   <computed>
      chart:                "fluent-bit"
      keyring:              "/Users/Y9CRPE/.gnupg/pubring.gpg"
      metadata.#:           <computed>
      name:                 "logcollector"
      namespace:            "logging"
      repository:           "web"
      set.#:                "6"
      set.121059550.name:   "rbac.create"
      set.121059550.value:  "1"
      set.2276311802.name:  "filter.merge"
      set.2276311802.value: "On"
      set.3063255997.name:  "image.fluent_bit.tag"
      set.3063255997.value: "0.12.2"
      set.3604222029.name:  "backend.es.host"
      set.3604222029.value: "es-elasticsearch.persistence.svc"
      set.4294762615.name:  "backend.type"
      set.4294762615.value: "es"
      set.983515542.name:   "resources.limits.memory"
      set.983515542.value:  "300Mi"
      timeout:              "600"
      version:              "0.1.0"
```

Looking at the the log above, it wants to recalculate the id and some metadata immediately after it was already successfully created.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` or `terraform plan`

### Important Factoids
Running Helm 2.6.1 with the same Tiller version.

**Comment by sagikazarmark** [comment]
Funny thing is that it's not consistent at all, a few charts just shows up in the plan upon subsequent `terraform plan` calls.

**Comment by sagikazarmark** [comment]
Looks like if the resource is not "up" (containers crashing), then terraform wants to recreate the release. Not sure if this is something that we want.

**Comment by sagikazarmark** [comment]
I can confirm this is the case after 5 times making a container crash and running `terraform plan` before and after.

**Comment by sagikazarmark** [comment]
No, it's not related. But there are only two helm charts which does this: the one above and another.

**Comment by andrewrynhard** [comment]
@mcuadros Any idea where to start with this. I am seeing this as well.

**Comment by Mistobaan** [comment]
@mcuadros running into this too consistently with the latest v0.4.0 release. It seems that the `id` of the release is being recomputed all the times.

**Comment by mcuadros** [comment]
Fixed by https://github.com/mcuadros/terraform-provider-helm/pull/39
