### ISSUE TITLE
Docs for helm_repository example is wrong.

### ISSUE THREAD

**Issue by marianord** [hashicorp/terraform-provider-helm#263]
### Terraform Version
`N/A`

### Affected Resource(s)
- Docs

### Expected Behavior
Copying the examples should work to start from there.

### Actual Behavior
It doesn't work and creates errors in the terraform code.

### Steps to Reproduce
Copy and paste 

### Current example
```hcl
...

resource "helm_release" "my_cache" {
    name       = "my_cache"
    repository = "${helm_repository.incubator.metadata.0.name}"
    chart      = "redis-cache"
}
```

### Proposed example
```hcl
...

resource "helm_release" "my_cache" {
    name       = "my_cache"
    repository = "${data.helm_repository.incubator.metadata.0.name}"
    chart      = "redis-cache"
}
```

**Comment by legal90** [comment]
It is supposed to be fixed by https://github.com/terraform-providers/terraform-provider-helm/pull/262

**Comment by rporres** [comment]
Thx for reporting this. #262 merged
