### ISSUE TITLE
Terraform state is updated even if apply fails

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-helm#266]
We recently had a developer try to update the Ingress host for Grafana, which we have deployed into kubernetes as a helm release. They updated the relevant YAML file, ran `terraform apply` and saw the change that they were expecting (updating the URL). However, they did not have helm installed on their machine!

The apply (obviously) failed, however terraform's state was left such that it no longer thought there were any changes to be made to our grafana helm release. Running `helm status grafana` confirmed that no change had been made to the actual release - it still had the old Ingress host. Given that no change was made, I would expect terraform's state to have been left unchanged also.

Once helm was installed on their machine, we had to make another change to the YAML in order to "trick" terraform into updating the release. 

### Terraform Version
```
Terraform v0.11.13
+ provider.helm v0.9.0
+ provider.kubernetes v1.6.2
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "grafana" {
  name      = "grafana"
  chart     = "stable/grafana"
  version   = "2.2.1"
  namespace = "grafana"

  values = [
    "${file("helm-values/grafana.yaml")}"
  ]

  wait          = false
  recreate_pods = true
}
```

### Expected Behavior
Ideally, `terraform apply` wouldn't even let you attempt to apply changes, and would instead give you an error telling you to install helm. Failing this:

`terraform apply` should fail, and terraform state should be left unchanged. Subsequent `terraform plan`/`terraform apply' commands should list the same changes as the original one, as nothing has actually been done.

### Actual Behavior
`terraform apply` fails, terraform state is updated as if it succeeded.

### Steps to Reproduce
1. Set up a kubernetes cluster and deploy a helm release to it through terraform.
2. On a second machine without helm installed, make some sort of change to the config that would update that release. 
3. `terraform apply` on the second machine.

**Comment by prokvk** [comment]
+1

I've had similar problem. I removed `helm_release` resource and ran `terraform apply`. TF ran successfully, but it failed to destroy the resource. It also showed no changes to be made on `terraform plan`. I see helm provider as unreliable at this point, exploring alternatives (helmfile, direct helm..)

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
