### ISSUE TITLE
data provider for helm_repository seems slow

### ISSUE THREAD

**Issue by jpreese** [hashicorp/terraform-provider-helm#267]
### Terraform Version
Terraform v0.11.13
+ provider.helm v0.9.1
+ provider.kubernetes v1.6.2
+ provider.local v1.2.1
+ provider.null v2.1.2
+ provider.tls v1.2.0

### Affected Resource(s)
- helm_repository

### Terraform Configuration Files
```hcl
data "helm_repository" "stable" {
  name = "stable"
  url  = "https://kubernetes-charts.storage.googleapis.com"
}

resource "helm_release" "metallb" {
  name       = "metallb"
  repository = "${data.helm_repository.stable.metadata.0.name}"
  chart      = "metallb"
}
```

### Debug Output
```
2019/05/01 10:39:58 [TRACE] dag/walk: vertex "root", waiting for: "provider.helm (close)"
2019/05/01 10:40:00 [TRACE] dag/walk: vertex "provider.helm (close)", waiting for: "module.metrics_server.data.helm_repository.stable"
2019/05/01 10:40:03 [TRACE] dag/walk: vertex "root", waiting for: "provider.helm (close)"
2019/05/01 10:40:05 [TRACE] dag/walk: vertex "provider.helm (close)", waiting for: "module.metrics_server.data.helm_repository.stable"
2019/05/01 10:40:08 [TRACE] dag/walk: vertex "root", waiting for: "provider.helm (close)"
2019/05/01 10:40:10 [TRACE] dag/walk: vertex "provider.helm (close)", waiting for: "module.metrics_server.data.helm_repository.stable"
2019/05/01 10:40:13 [TRACE] dag/walk: vertex "root", waiting for: "provider.helm (close)"
2019/05/01 10:40:15 [TRACE] dag/walk: vertex "provider.helm (close)", waiting for: "module.metrics_server.data.helm_repository.stable"
2019/05/01 10:40:18 [TRACE] dag/walk: vertex "root", waiting for: "provider.helm (close)"
2019/05/01 10:40:20 [TRACE] dag/walk: vertex "provider.helm (close)", waiting for: "module.metrics_server.data.helm_repository.stable"
2019/05/01 10:40:23 [TRACE] dag/walk: vertex "root", waiting for: "provider.helm (close)"
2019/05/01 10:40:25 [TRACE] dag/walk: vertex "provider.helm (close)", waiting for: "module.metrics_server.data.helm_repository.stable"
2019/05/01 10:40:28 [TRACE] dag/walk: vertex "root", waiting for: "provider.helm (close)"
2019/05/01 10:40:30 [TRACE] dag/walk: vertex "provider.helm (close)", waiting for: "module.metrics_server.data.helm_repository.stable"
2019/05/01 10:40:33 [TRACE] dag/walk: vertex "root", waiting for: "provider.helm (close)"
2019/05/01 10:40:35 [TRACE] dag/walk: vertex "provider.helm (close)", waiting for: "module.metrics_server.data.helm_repository.stable"
2019/05/01 10:40:38 [TRACE] dag/walk: vertex "root", waiting for: "provider.helm (close)"
2019/05/01 10:40:40 [TRACE] dag/walk: vertex "provider.helm (close)", waiting for: "module.metrics_server.data.helm_repository.stable"
2019/05/01 10:40:43 [TRACE] dag/walk: vertex "root", waiting for: "provider.helm (close)"
2019/05/01 10:40:45 [TRACE] dag/walk: vertex "provider.helm (close)", waiting for: "module.metrics_server.data.helm_repository.stable"
2019-05-01T10:40:47.511-0400 [DEBUG] plugin.terraform-provider-helm_v0.9.1_x4.exe: 2019/05/01 10:40:47 [DEBUG] "stable" has been added to your repositories
```

### Expected Behavior
Resolve data provider step in a timely manner

### Actual Behavior
Resolution seems to take close to a minute.

### Steps to Reproduce
1. `terraform apply`

**Comment by jpreese** [comment]
Similarly, it doesn't seem like it uses the cached values. Every `terraform apply` updates the repositories yaml and downloads a new chart `.tar.gz`

**Comment by rporres** [comment]
Can you elaborate on what "slow" means?

> Similarly, it doesn't seem like it uses the cached values. Every terraform apply updates the repositories yaml and downloads a new chart .tar.gz

The `helm_repository` data source deals with indexes files, not with chart packages. It needs to download the index as you may want to upgrade to a new version and it needs to know how to download it.

**Comment by jpreese** [comment]
The slowness, to me, as highlighted in the TRACE log above is the 1 minute to resolve the data provider. In its defense, the index.yaml that it seems to download is 4.5MB, but even then it should be pretty quick (http://kubernetes-charts.storage.googleapis.com/index.yaml)

I'd also think it wouldnt have to download it everytime. If I define in my terraform that I want version 1, and I have an index that contains version 1 -- then it should just move onto the next step without needing to download a new index. If this makes sense and this is not the current behavior, feature request?

This leads me into a slight segway of, is it possible to download a chart and have the provider use a local copy? It doesn't give me a lot of warm and fuzzies that our `terraform apply` statements depend on a network connection.

**Comment by jpreese** [comment]
Looks like this has already been suggested and discussed briefly

https://github.com/terraform-providers/terraform-provider-helm/issues/212
