### ISSUE TITLE
repository_url does not add repo locally

### ISSUE THREAD

**Issue by rporres** [hashicorp/terraform-provider-helm#27]
### Terraform Version
`Terraform v0.10.3`
`terraform-provider-helm v0.3.2`

### Affected Resource(s)
`helm_chart`

### Terraform Configuration Files
```hcl
resource "helm_chart" "bblfsh_dashboard" {
  name           = "bblfsh-dashboard"
  repository_url = "https://src-d.github.io/charts/"
  chart          = "srcd/bblfsh-dashboard"
  version        = "0.1.0"

  set {
    name  = "service.loadBalancerIP"
    value = "1.2.3.4"
  }
}
```

### Debug Output
```
* helm_chart.bblfsh_dashboard: no cached repo found. (try 'helm repo update'). open /Users/rporres/.helm/repository/cache/srcd-index.yaml: no such file or directory
```

If I name the chart without the slash

```
* helm_chart.bblfsh_dashboard: Non-absolute URLs should be in form of repo_name/path_to_chart, got: bblfsh-dashboard
```

### Expected Behavior
Terraform deploys the chart using helm

### Actual Behavior
Terraform does not deploy chart

### Workaround

You can manually add the repo. In above case

```
helm repo add srcd https://src-d.github.io/charts
```

If it's needed in terraform itself, the above command can be executed via [local-exec](https://www.terraform.io/docs/provisioners/local-exec.html) provisioner

**Comment by mcuadros** [comment]
The correct HCL is as follow:

```
resource "helm_chart" "bblfsh_dashboard" {
  name           = "bblfsh-dashboard"
  repository = "https://src-d.github.io/charts/"
  chart          = "srcd/bblfsh-dashboard"
  version        = "0.1.0"

  set {
    name  = "service.loadBalancerIP"
    value = "1.2.3.4"
  }
}
```

`repository_url` is and leftover, I am remove it from the code and the examples.
