### ISSUE TITLE
Need to be able to control --kube-context

### ISSUE THREAD

**Issue by kraney** [hashicorp/terraform-provider-helm#28]
When running terraform it currently just uses the default helm host and kube-context. There should be a way to override the kube-context with something else. That way you can have two chart resources installed in different namespaces by different user accounts / contexts with different permissions.

**Comment by jeffmhastings** [comment]
You can do this: https://github.com/mcuadros/terraform-provider-helm/blob/master/docs/index.html.md#statically-defined-credentials

Not exactly what you're asking for but could work.

**Comment by mcuadros** [comment]
@kraney if I am right, you want to configure the context, by `release` and not a provider level?

**Comment by kraney** [comment]
Yes, that's right. Something finer-grained than at the provider level.

**Comment by sagikazarmark** [comment]
I believe the proper solution would be defining multiple providers with different aliases and contexts and using those provider aliases in the resources.

**Comment by burdiyan** [comment]
Definitely agree with @sagikazarmark. If you want to specify a kube context at the release level, wrap you release as a Terraform module and embed the helm provider configuration there, configurable with a variable and provider alias.

**Comment by sagikazarmark** [comment]
I don't think a terraform module is necessary, but it certainly provides better separation.

**Comment by paaloeye** [comment]
Multi providers solution is the right way to handle such use-case.

Should this issue be closed? @mcuadros @meyskens @alexsomesan

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
