### ISSUE TITLE
`set` Attribute breaks in Terraform 0.12.0.

### ISSUE THREAD

**Issue by alexnovak** [hashicorp/terraform-provider-helm#284]
### Terraform Version

`Terraform v0.12.0`

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "redis" {
  name    = "${local.redis_host}"
  chart   = "stable/redis"
  version = "4.2.1"

  set = {
    name  = "image.tag"
    value = "4.0"
  }

  set = {
    name  = "cluster.slaveCount"
    value = 2
  }
}
```

### Panic Output

```
Error: Attribute redefined

  on redis.tf line 35, in resource "helm_release" "redis":
  35:   set = {

The argument "set" was already set at redis.tf:30,3-6. Each argument may be
set only once.
```
### Expected Behavior

Expected no syntax failures, and for a plan or apply to go through.
### Actual Behavior

Was presented with syntax failures for repeated attributes.
### Steps to Reproduce

1. Create any helm release with multiple set blocks within.
2. Run a `terraform plan` or `terraform apply`

### Important Factoids

Saw there was a diff for getting this provider .12-compliant (linked below), but it didn't seem to cover this, and documentation makes no mention of this.

### References

- #229

**Comment by meyskens** [comment]
I haven't yet found the time to test this but can you try 
```
set {
    name  = "image.tag"
    value = "4.0"
  }

  set {
    name  = "cluster.slaveCount"
    value = 2
  }
```

**Comment by alexnovak** [comment]
Well color me embarrassed. That worked perfectly! Thanks for the assist @meyskens!

**Comment by legal90** [comment]
Just for further reference - that's described on the _Upgrading to Terraform v0.12_ page:
https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks
