### ISSUE TITLE
Helm support for atomic release install/update.

### ISSUE THREAD

**Issue by eugenekainara** [hashicorp/terraform-provider-helm#287]
### Terraform Version
Terraform v0.11.14
provider.helm 0.9.1

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "example_release" {
  chart = "stable/example"
  name = "ex"
  version = "0.1.0"
  atomic = true
}
```

### Question
It's just a question about any plans to support atomic(safe) install/upgrades which was introduced in Helm [2.13.0](https://github.com/helm/helm/releases/tag/v2.13.0)
Thanks!

**Comment by rporres** [comment]
Current SDK used is 2.14.1, we should be ready for this

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
