### ISSUE TITLE
 Helm terraform provider supports "helm_repository" as a  datasource in doc.

### ISSUE THREAD

**Issue by sakshiag** [hashicorp/terraform-provider-helm#291]
Hi, 
I see the latest release is 0.6.0 which supports helm_repository as a resource but in the terraform doc it is a datasource.

Is this the change supported in future release.. When can we expect the new release?

I see there are tags created with 0.9.1 but they contains only the source code.

**Comment by rporres** [comment]
`helm_repository` as a resource is still supported although deprecated, you should move out from using it.

Current release is `0.10.2`, you can safely use `helm_repository` datasource
