### ISSUE TITLE
documentation error: missing 'data.'

### ISSUE THREAD

**Issue by TheSantacloud** [hashicorp/terraform-provider-helm#292]
in https://www.terraform.io/docs/providers/helm/repository.html

example usage:
```
repository = "${helm_repository.incubator.metadata.0.name}"
```

is missing data., i.e.,
```
repository = "${data.helm_repository.incubator.metadata.0.name}"
```

didn't work for us otherwise.

thanks!

**Comment by invidian** [comment]
Seems to be fixed now.

**Comment by rporres** [comment]
Thx for reporting. This is fixed now
