### ISSUE TITLE
helm_template data source (templating-only mode for helm)

### ISSUE THREAD

**Issue by dee-kryvenko** [hashicorp/terraform-provider-helm#298]
Just to state obvious - people are using Helm ~wrong~ for templating only. We'll keep it out of this discussion whether it is a good or bad practice. To make the matters worse, people are using Helm for things completely outside of K8s, basically as a templating engine. Of course, Terraform has it's own templating engine, but sometimes you got to deal with what others already done and for whatever reason they picked Helm for it.

Good example is Spinnaker, they are using Helm just like that (i.e. `helm template | kubectl apply` in the nutshell).

To support this scenarios and enable TF to keep it's gluing role, I propose to introduce a new data source.

A data source `helm_template` would be similar to `helm_release` resource, it takes all that input and does `helm template` and outputs resulting documents. Optionally, split by `---` into different objects and packed as an array.

**Comment by aaronmell** [comment]
Helm 3.0 removes tiller. Would this still be needed when Helm 3.0 drops?

**Comment by dee-kryvenko** [comment]
@aaronmell the `helm_template` data source would still make sense. Tiller is not technically going away, it's just being incorporated with the K8s API server itself. There's still use cases when you'd want to have something in the middle after rendering a Helm chart and actually applying it, or just have it applied in your own custom way (for instance if you manage deployments with Spinnaker). Also there's a case when helm is used as a templating engine to produce something entirely else, not a k8s objects (leaving out of the scope "why").

`helm_apply` would be still needed to support a case to apply rendered result after extra-processing, but chances are that the reason people would need the after-processing would likely go away in Helm 3. Only time will tell...

On top of that, Helm 2 is not going to go away overnight, and splitting up the `helm_release` resource does not sounds like a big deal, so hence the pros and cons has to be weighted.

**Comment by barryib** [comment]
Another way to support the so called **Tillerless** https://github.com/terraform-providers/terraform-provider-helm/pull/339

**Comment by invidian** [comment]
>A resource helm_apply would be doing the same helm template thing and apply it directly to the cluster. Optionally, some of the Spinnaker's behaviour can be replicated - such as tracking objects in the TF state for the purpose of handling renaming/deleting resources.

I agree regarding `helm_template` resource, but I think applying should be then done by the `kubernetes` provider (even though it currently does not support creating custom resource IIRC), as applying seems out of scope for this provider.

`helm_template` would take values, chart etc as an input and simply split out YAML files as an output, which can be then used in any way: pass to kubernetes provider, save as files and do `kubectl apply` etc.

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.

**Comment by dee-kryvenko** [comment]
This is still relevant in helm 3.

**Comment by mcuadros** [comment]
Then can you change the name of the issue? Since speaks about the tiller.

**Comment by dee-kryvenko** [comment]
@mcuadros sorry, got buried in my inbox. I changed description and a subject. I also removed `kubectl apply` resource proposition. Seems like after all there will be a support for CRDs in here https://github.com/terraform-providers/terraform-provider-kubernetes/issues/215#issuecomment-578145601 - so there is no need to have it in the helm provider which it never felt like belonging here anyway.

**Comment by Sytten** [comment]
I still think it could be useful because the terraform issue has been open for quite some time without any progress and speaking for myself I could this landing faster.

**Comment by gorge511** [comment]
Hello, guys https://github.com/hashicorp/terraform-provider-helm/pull/483 was merged more than a month ago. When do you plan to **release** it? This feature is the one which we currently need, so new release will be very beneficial. 🥺 🙏 
cc: @jrhouston
