### ISSUE TITLE
Provider fails after failed chart deployment

### ISSUE THREAD

**Issue by calind** [hashicorp/terraform-provider-helm#3]
The provider fails after a chart fails. Here is a sample `.tf` file.

```
resource "helm_chart" "core-nginx-ingress" {
  namespace   = "nginx-ingress"
  name        = "core-ingress"
  chart       = "stable/nginx-ingress"
  value {
      name    = "controller.podAnnotations.\"prometheus\\.io/scrape\""
      content = "true"
  }
}
```

Now if you try applying it, first time helm fails with 
```
* helm_chart.core-nginx-ingress: 1 error(s) occurred:

* helm_chart.core-nginx-ingress: rpc error: code = Unknown desc = release core-ingress failed: Deployment in version "v1beta1" cannot be handled as a Deployment: [pos 364]: json: expect char '"' but got char 't'
```

A `helm ls --all core-ingress` yields:
```
NAME        	REVISION	UPDATED                 	STATUS	CHART              	NAMESPACE
core-ingress	1       	Mon Aug  7 17:54:34 2017	FAILED	nginx-ingress-0.7.0	nginx-ingress
```

Running `terraform apply` a second time, tries to create a new helm release, which obviously fails because it is already created:
```
* helm_chart.core-nginx-ingress: 1 error(s) occurred:

* helm_chart.core-nginx-ingress: rpc error: code = Unknown desc = a release named core-ingress already exists.
Run: helm ls --all core-ingress; to check the status of the release
Or run: helm del --purge core-ingress; to delete it
```

**Comment by mcuadros** [comment]
I must admit that I am not sure how to handle this kind of situations, since at helm, this is the behavior. (Is not nice but it's what it's).

Maybe It can delete the release if it's fails, with an option to disable it.

**Comment by calind** [comment]
If I manually run
`helm upgrade --namespace nginx-ingress core-ingress stable/nginx-ingress -f nginx-ingress.yaml` the helm release get fixed, so that `helm ls --all core-ingress` now shows:
```
NAME        	REVISION	UPDATED                 	STATUS  	CHART              	NAMESPACE
core-ingress	2       	Mon Aug  7 18:20:54 2017	DEPLOYED	nginx-ingress-0.7.0	nginx-ingress
```

But `terraform plan` insists on creating a new release:
```
  + helm_chart.core-nginx-ingress
      chart:                    "stable/nginx-ingress"
      keyring:                  "/Users/calin/.gnupg/pubring.gpg"
      metadata.#:               "<computed>"
      name:                     "core-ingress"
      namespace:                "nginx-ingress"
      timeout:                  "300"
      value.#:                  "1"
      value.2273204518.content: "true"
      value.2273204518.name:    "controller.podAnnotations.\"prometheus\\.io/scrape\""
```

My take on the semantics of this provider is that it should be the same of a `helm upgrade --install`.

**Comment by mcuadros** [comment]
Yep, I was reading about this, I can remove the pure install logic and make always as `helm upgrade --install `

**Comment by mcuadros** [comment]
Fixed by https://github.com/mcuadros/terraform-provider-helm/commit/bf485792e09e32ef1ced2be222f2071eddfcdba5
