### ISSUE TITLE
Submit the provider to the Terraform Registry

### ISSUE THREAD

**Issue by burdiyan** [hashicorp/terraform-provider-helm#30]
Could you publish this provider to the Terraform Registry (registry.terraform.io)? This will help a lot dealing with the provider with latest versions of Terraform.

**Comment by mcuadros** [comment]
This provider is in process to be merge as a built-in provider. And looks like registry is for modules and not for providers.

**Comment by subesokun** [comment]
@mcuadros Are there any information you can share with us regarding the merge? Like a timeline or a status update.

**Comment by mcuadros** [comment]
Yes people from terraform, starred to do the review a few weeks ago, so hopefully will merge any time soon.

**Comment by subesokun** [comment]
These are awesome news! 🎉
