### ISSUE TITLE
Release v0.10.1?

### ISSUE THREAD

**Issue by bmcustodio** [hashicorp/terraform-provider-helm#301]
It would be awesome if v0.10.1 could be cut sometime soon, as  4cdce557ef515783c1683fb14b37969d089ca6fa and 77d0573cc4ef6050d38d34cd61def1ec2a4958f3 represent pretty important fixes to v0.10.0. Thoughts?

**Comment by aaronmell** [comment]
Any update?

**Comment by aaronmell** [comment]
@mcuadros @meyskens @alexsomesan @rporres

**Comment by chreichert** [comment]
I also wonder, when a new release of the provider is coming?
The update to Helm >=2.14.1 is very important to us, as the harbor chart does not work with Helm 2.14.0 due to that breaking change, see #288 .
