### ISSUE TITLE
Helm provider is not respecting `load_config_file`

### ISSUE THREAD

**Issue by osdemah** [hashicorp/terraform-provider-helm#303]
Terraform helm provider is still loading config files when it's set to be false.

### Terraform Version
Terraform v0.12.3
terraform-provider-helm_v0.10.0_x4

### Affected Provider
- helm_provider

### Terraform Configuration Files
```hcl
provider "helm" {
  install_tiller  = "true"
  tiller_image    = "gcr.io/kubernetes-helm/tiller:v2.14.0"
  service_account = module.tiller.service_account
  kubernetes {
    load_config_file       = false
    host                   = module.eks1.cluster_endpoint
    token                  = data.external.aws_iam_authenticator1.result["token"]
    cluster_ca_certificate = base64decode(module.eks1.cluster_certificate_authority_data)
  }
}
```

### Expected Behavior
`k8sGet(d, "load_config_file").(bool)` must return `false, true` when `load_config_file` is `false`.

### Actual Behavior
it's returning `true, true`.

### Steps to Reproduce
set the `load_config_file` to be `false` and add some debug information for the return value of `k8sGet` function.

### Reason
`GetOk` function assumes the attributes with zero values are not Ok. As the `DefaultFunc` for `load_config_file` is `EnvDefaultFunc("KUBE_LOAD_CONFIG_FILE", true)`, when the `KUBE_LOAD_CONFIG_FILE` is absent it will replace the value with true. 

We need to use `GetOkExists` for boolean attributes.

**Comment by rporres** [comment]
Fixed in https://github.com/terraform-providers/terraform-provider-helm/pull/307
