### ISSUE TITLE
EOF Error causes incorrect TF state

### ISSUE THREAD

**Issue by aaronmell** [hashicorp/terraform-provider-helm#308]
We are seeing random EOF errors when applying helm_releases. We are attempting to update the image tag. When the EOF issue happens, the image tag is not updated in helm, and the next time we run terraform, it doesn't retry to update the image tag.

`
  resource "helm_release" "example_release" {
  name       = "example_release_name"
  repository = "example_release_name_repo"
  chart      = "example_release_name_chart"
  namespace  = "example_release_name_namespace"
  depends_on = ["null_resource.some_null_resource"]
  version    = "example_release_name.version"
  values = [
  "yaml for chart loaded from file",
]

 set {
    name  = "containerDefinition.image.repository"
    value = "${var.container_image_repository}"
  }

  set {
    name  = "containerDefinition.image.tag"
    value = "${var.container_image_tag}"
  }
`

We have some additional sets in a typical config, but for this example they are not important.

Now when I look at the TF state file after the error occurs I see the following
"metadata.0.values" tag: 1.2.69\n   has the image tag that is currently deployed and matches helm

However the set has the value that we were attempting to change to, rather than the value that exists in helm. 
"set.4006280493.value": "1.2.70", 

This is what terraform does
If the Update callback returns with or without an error, the full state is saved. If the ID becomes blank, the resource is destroyed (even within an update, though this shouldn't happen except in error scenarios).

I'm guessing because we pass in 1.2.70 the next time we run, it sees that the value was already set, and doesn't do anything.  When we do a ReleaseRead operation we only update the version, namespace, status and metadata. Since the status is never set to failed, and the version of the chart didn't change, no update would be required.

I can think of a few solutions on how to fix it, but I'm not sure of the ramifications of making such a change.

1. If Helm fails for some reason during the deployment, and the status did not change of the release, set the status value to something like "Unknown" so it forces a redeploy the next time.

2. call d.set and update all of the values in d.set during a read operation. This feels like the more correct option, but its also a big change, and I am not sure of the reasoning behind not updating the set during a read. 

### Terraform Version
Terraform v0.11.13

### Affected Resource(s)
- helm_release

**Comment by aaronmell** [comment]
I'm thinking about adding a retry to the provider, so if the EOF issue occurs, or the Context Deadline issue occurs, both which seem to be random failures, the provider can simply retry the operation. Any thoughts?

**Comment by aaronmell** [comment]
Retry didn't work. I got a custom version wired up with a retry, and the EOF error did not trigger a retry, so its happening somewhere else. More digging

**Comment by aaronmell** [comment]
Okay, I think I'm dealing with a concurrency issue with helm. The EOF issue occurs when trying to load the chart inside the getChart function. when chartutil.Load is called it returns an EOF.

**Comment by aaronmell** [comment]
https://github.com/helm/helm/issues/6140

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.

**Comment by mauriciopoppe** [comment]
As a workaround you can download the chart manually to a temp location and then install the chart from the filesystem, in the following example a new temp directory is created for every new chart version

```hcl
resource "random_string" "random" {
  length = 16
  special = false
  keepers = {
    version = "${var.chart_version}"
  }
}

locals {
  chart_location = "/tmp/${random_string.random.result}"
}

resource "null_resource" "helm_pull" {
  triggers = {
    version = "${var.chart_version}"
  }

  provisioner "local-exec" {
    command = "mkdir -p ${local.chart_location}"
  }

  provisioner "local-exec" {
    command = "helm repo add myrepo ${var.myrepo_url}"
  }

  provisioner "local-exec" {
    command = "helm repo update"
  }

  provisioner "local-exec" {
    command = "helm fetch myrepo/mychart --version ${var.chart_version} --destination ${local.chart_location} --untar"
  }
}

resource "helm_release" "mychart" {
  ...
  chart = "${local.chart_location}/mychart"
  ...
}
```
