### ISSUE TITLE
helm_release does not run local-exec provisioner if defined

### ISSUE THREAD

**Issue by jeffb4** [hashicorp/terraform-provider-helm#313]
### Terraform Version

$ terraform -v
Terraform v0.12.6
+ provider.aws v2.22.0
+ provider.helm v0.10.1
+ provider.kubernetes v1.8.1
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.rancher2 v1.3.0
+ provider.random v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "cert_manager" {
  name       = "cert-manager"
  repository = data.helm_repository.jetstack.metadata.0.name
  chart      = "cert-manager"
  namespace  = "cert-manager"
  provisioner "local-exec" {
    command = "touch ~/tmp/provisioner-run;kubectl apply -f ${path.module}/data_files/cert-manager-crd.yaml > .command"
    environment = {
      KUBECONFIG = module.saas_cluster.kubeconfig_filename
    }
  }
}
```

### Debug Output
info level

https://gist.github.com/jeffb4/098893e749e5b5cfbdf973d7b9477739

### Expected Behavior

Local file should be touched, CRDs should be loaded prior to helm chart

### Actual Behavior

No evidence that local-exec provisioner ever ran, CRDs not created on cluster

### Steps to Reproduce

1. `terraform apply`

I have no tried to isolate this to a minimum viable bug report. 

### Important Factoids

If anyone runs into this and needs a workaround, I created a null_resource with the provisioner code and put a `depends_on` in `helm_release`. Not ideal but it works.

### References

- GH-1234

**Comment by rivernews** [comment]
Same here, can confirm using `null_resource` plus `depends_on` will work though. 

Might worth mentioning that for `when = "destroy"` local-exec provisioner, it WILL execute when run `terraform destroy`.

```terraform
resource "helm_release" "project_cert_manager" {

  # ...

  provisioner "local-exec" {
    when    = "destroy"
    command = ". ./my-kubectl.sh delete customresourcedefinitions.apiextensions.k8s.io certificates.certmanager.k8s.io clusterissuers.certmanager.k8s.io issuers.certmanager.k8s.io orders.certmanager.k8s.io && sleep 10"
  }

  # ...

}
```

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
