### ISSUE TITLE
helm_release "set-string" regression when setting a comma separated string

### ISSUE THREAD

**Issue by chreichert** [hashicorp/terraform-provider-helm#316]
### Terraform Version
Terraform v0.12.6
+ provider.azuread v0.5.1
+ provider.azurerm v1.32.1
+ provider.helm v0.10.2
+ provider.http v1.1.1
+ provider.k8sraw v0.2.0
+ provider.kubernetes v1.8.1
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.rke v0.13.0
+ provider.template v2.1.2
+ provider.tls v2.0.1

### Affected Resource(s)
- helm_resource

### Terraform Configuration Files
```hcl
data "helm_repository" "stable" {
  name = "stable"
  url  = "https://kubernetes-charts.storage.googleapis.com"
}

data "azurerm_resource_group" "cnee-rg" {
  name = "${var.name_prefix}-resources"
}

data "azurerm_public_ip" "rancher-ingress" {
  name                = "${var.name_prefix}-rancher-ingress"
  resource_group_name = data.azurerm_resource_group.cnee-rg.name
}

data "azurerm_virtual_network" "cnee-vnet" {
  name                = "${var.name_prefix}-vnet"
  resource_group_name = data.azurerm_resource_group.cnee-rg.name
}

resource "helm_release" "nginx-ingress" {
  name       = "${var.name_prefix}-ingress"
  repository = data.helm_repository.stable.name
  chart      = "nginx-ingress"
  version    = "1.12.1"
  namespace  = var.namespace

  set_string {
    name = "controller.config.whitelist-source-range"
    value = "217.111.62.149,79.175.106.38,217.9.45.106,80.147.177.110,82.135.25.218,78.43.125.55,130.180.82.18,213.3.5.15,212.236.40.194,213.200.250.8,195.122.152.136,213.179.132.115,213.140.134.225,80.249.216.174,10.244.0.0/16,${data.azurerm_public_ip.rancher-ingress.ip_address},${join(",",data.azurerm_virtual_network.cnee-vnet.address_space)},10.0.0.0/8"
  }
}
```

### Expected Behavior
Terraform apply runs successfully

### Actual Behavior
Terraform plan does not show any errors and plan shows successful addition of CIDR value:

```
      - set_string {
          - name  = "controller.config.whitelist-source-range" -> null
          - value = "217.111.62.149,79.175.106.38,217.9.45.106,80.147.177.110,82.135.25.218,78.43.125.55,130.180.82.18,213.3.5.15,212.236.40.194,213.200.250.8,195.122.152.136,213.179.132.115,213.140.134.225,80.249.216.174,10.244.0.0/16,52.236.175.74,10.112.16.0/22" -> null
        }
      + set_string {
          + name  = "controller.config.whitelist-source-range"
          + value = "217.111.62.149,79.175.106.38,217.9.45.106,80.147.177.110,82.135.25.218,78.43.125.55,130.180.82.18,213.3.5.15,212.236.40.194,213.200.250.8,195.122.152.136,213.179.132.115,213.140.134.225,80.249.216.174,10.244.0.0/16,52.236.175.74,10.112.16.0/22,10.0.0.0/8"
```
Terraform apply shows an error then:

```
module.ingress.helm_release.nginx-ingress: Modifying... [id=cnee-ingress]

Error: failed parsing key "controller.config.whitelist-source-range" with value 217.111.62.149,79.175.106.38,217.9.45.106,80.147.177.110,82.135.25.218,78.43.125.55,130.180.82.18,213.3.5.15,212.236.40.194,213.200.250.8,195.122.152.136,213.179.132.115,213.140.134.225,80.249.216.174,10.244.0.0/16,52.236.175.74,10.112.16.0/22,10.0.0.0/8, key "38" has no value (cannot end with ,)

  on modules/ingress/main.tf line 27, in resource "helm_release" "nginx-ingress":
  27: resource "helm_release" "nginx-ingress" {
```

### Steps to Reproduce

Resource has already been deployed before using helm provider v0.10.1
1. add an additional CIDR to the config
2. terraform plan -out tfplan
3. terraform apply tfplan

### Important Factoids
Problem started after PR #310 

### References
- PR #310
- Issue #265 
- Issue #226 (seems to be broken again)
- PR #227

**Comment by stuart-c-moore** [comment]
I've just hit the same problem. My "problem" terraform code in a test environment:

```
  set_sensitive {
    name = "secrets.localUsers"
    value = "${var.concourse_username}:${random_string.concourse_password.result},someuser:somepassword"
  }
```

This has worked for many previous versions, but now breaks with:

```
Error: failed parsing key "secrets.localUsers" with sensitive value, key "someuser:somepassword" has no value

  on helm-concourse.tf line 29, in resource "helm_release" "concourse":
  29: resource "helm_release" "concourse" {
```

Plugins in use:

```
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "kubernetes" (terraform-providers/kubernetes) 1.8.1...
- Downloading plugin for provider "random" (terraform-providers/random) 2.1.2...
- Downloading plugin for provider "tls" (terraform-providers/tls) 2.0.1...
- Downloading plugin for provider "google" (terraform-providers/google) 2.12.0...
- Downloading plugin for provider "google-beta" (terraform-providers/google-beta) 2.12.0...
- Downloading plugin for provider "acme" (terraform-providers/acme) 1.3.5...
- Downloading plugin for provider "helm" (terraform-providers/helm) 0.10.2...
```

**Comment by eaterm** [comment]
Seems the automatic escaping of comma's has been removed. 
In commit: 74f0b6ca789b2bfb6e4811467f4118c0586e38b8

Comma's now need to be escaped manually (using \\) in the set block.

**Comment by rporres** [comment]
Regression related commit was rolled back in https://github.com/terraform-providers/terraform-provider-helm/releases/tag/v0.10.2

Closing this.

**Comment by chreichert** [comment]
Sorry, but this is not correct. The regression was again introduced with this commit. With v 0.10.2 of the provider it is not possible to set a comma separated string value using set-string. Please check my original issue post at the top, where the error is described.
/reopen

**Comment by eaterm** [comment]
> Sorry, but this is not correct. The regression was again introduced with this commit. With v 0.10.2 of the provider it is not possible to set a comma separated string value using set-string. Please check my original issue post at the top, where the error is described. /reopen

It is still possible if you escape the comma using double \\
We also had this issue and resolved it using something like "test\\\\,test2\\\\,test3" as string.

**Comment by rporres** [comment]
@eaterm is correct. We tried to avoid the double back-slash escaping but introduced a further problem, hence the rollback.
