### ISSUE TITLE
Provider cannot handle conflict with existing chart

### ISSUE THREAD

**Issue by olib963** [hashicorp/terraform-provider-helm#318]
# Terraform Version
0.11.14 & 0.12.2

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
Any with a `helm_release"

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Helm can start installing a chart and recover from a failure.

### Actual Behavior

Occasionally helm will fail with `rpc error: code = Unavailable desc = transport is closing`. This is fine, however it actually installs the chart, then on the next rerun of `terraform apply` it fails because the chart already exists. I think allowing the equivalent to `helm upgrade --install` instead of `helm install` would solve this issue and let it pick up where it left off.

### Steps to Reproduce
Intermittent networking errors causing helm to start the install but timeout before successful creation. I am not sure how to reproduce

### Important Factoids
Running on GKE

We run a daily recreation of our entire environment so would be fine with the intermittent networking issues if the provider could just start from where it left off with no manual intervention.

### References
N/A

**Comment by rporres** [comment]
That depends on the state of the release. There's code to handle this situation properly in  https://github.com/terraform-providers/terraform-provider-helm/blob/master/helm/resource_release.go#L244

It would be interesting to know the state of things in this case to see if we have missed any case there that is properly covered in `helm` command

As a workaround, does destroying the failed release help?

**Comment by olib963** [comment]
It does "work" as a work around. It just means every other day (it's failing roughly 50/50) we have to manually go to our production cluster and `helm delete --purge` then kickstart the rebuild job. It would be nice to not have to do that.

What happens is in terraform:

```
Error: rpc error: code = Unavailable desc = transport is closing

  on terraform/datadog.tf line 32, in resource "helm_release" "datadog-agent":
  32: resource "helm_release" "datadog-agent" {
```

Then if you `helm list`

```
my-chart	1       	Mon Oct 21 16:39:13 2019	DEPLOYED datadog-1.38.1       	6.14.0     	default
```

Then if you start the terraform process up again it complains because the chart installed correctly but terraform is not aware of that fact. I expect it's some `409` equivalent?

```
Error: rpc error: code = Unknown desc = a release named my-chart	already exists.
Run: helm ls --all my-chart; to check the status of the release
Or run: helm del --purge my-chart; to delete it
```

Strangely from the line of code you linked I think that should work, but it doesn't :/

**Comment by olib963** [comment]
This seems to not be working. I have tried a minikube setup locally so this should be a way to do the minimal setup locally:

```
provider "kubernetes" {
  version = "1.8.1"
}

resource "kubernetes_service_account" "tiller" {
  automount_service_account_token = true

  metadata {
    name      = "tiller-service-account"
    namespace = "kube-system"
  }
}

resource "kubernetes_cluster_role_binding" "tiller" {

  metadata {
    name = "tiller-cluster-rule"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "cluster-admin"
  }

  subject {
    kind      = "ServiceAccount"
    name      = kubernetes_service_account.tiller.metadata[0].name
    api_group = ""
    namespace = kubernetes_service_account.tiller.metadata[0].namespace
  }
}
provider "helm" {
  version = "0.10.4"

  service_account = kubernetes_service_account.tiller.metadata[0].name
}

# resource "helm_release" "datadog-agent" {
#   name    = "datadog"
#   chart   = "stable/datadog"
#   version = "1.38.1"
#   keyring = ""

#   depends_on = [
#     kubernetes_cluster_role_binding.tiller
#   ]
# }
```

If you run that terraform on a cluster, then in a separate terminal run `helm install stable/datadog --version 1.38.1 --name datadog` (which replicates the initial install that our terraform runs before having a networking issue). If you then uncomment the helm release and run terraform again you get 

```
helm_release.datadog-agent: Creating...

Error: rpc error: code = Unknown desc = a release named datadog already exists.
Run: helm ls --all datadog; to check the status of the release
Or run: helm del --purge datadog; to delete it

  on main.tf line 39, in resource "helm_release" "datadog-agent":
  39: resource "helm_release" "datadog-agent" {
```

@rporres please advise :D I am going to try to catch up with google about the issues we are seeing communicating with a GKE cluster shortly after it has been created but I think this issue still needs to be tackled.

**Comment by olib963** [comment]
Since this was causing 50% of our build to fail and need manual intervention I decided we had to stop using this provider and replaced it with the kubernetes provider instead.

I still think this issue needs addressing though, from the code it seems this was a situation it was intended to handle but doesn't

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
