### ISSUE TITLE
Invalid repository cache path

### ISSUE THREAD

**Issue by duxet** [hashicorp/terraform-provider-helm#319]
### Terraform Version

Terraform v0.12.6
+ provider.helm v0.10.2

### Affected Resource(s)

- helm_repository

### Terraform Configuration Files
```hcl
provider "helm" {
  home         = "${path.root}/.helm"
}

data "helm_repository" "stable" {
  name = "stable"
  url  = "https://kubernetes-charts.storage.googleapis.com"
}

data "helm_repository" "rimusz" {
  name = "rimusz"
  url  = "https://charts.rimusz.net"
}

```

### Debug Output

https://gist.github.com/duxet/15005bbd91393462f9c9328f7a0cd47a

### Expected Behavior

`.helm/repository/cache/` path should be used for repository cache

### Actual Behavior

repository cache path gets "duplicated": `.helm/repository/cache/.helm/repository/cache/` and breaks repository data loading process

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

`home = "${path.root}/.helm"` configuration was working fine with Terraform 0.11

**Comment by duxet** [comment]
`home = "${abspath(path.root)}/.helm"` works fine, so looks like `home` cannot be set to relative path with Terraform 0.12

**Comment by eskp** [comment]
Using a repo URL in repository param should work.

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
