### ISSUE TITLE
Feature Request: Option to Run helm template command to generate manifests locally and run kubectl apply 

### ISSUE THREAD

**Issue by anoopl** [hashicorp/terraform-provider-helm#320]
I was looking for a feature to run `helm template ...` command then generate the manifests locally and apply with `kubectl apply -f`. This is required in the cases where we cannot use Tiller.
 I think we can do this with local exec provider. But it would be a good feature if implemented.

**Comment by dominik-lekse** [comment]
I am currently working on this feature an expect a PR in the next few days. This feature has also been mentioned in #298.

**Comment by anoopl** [comment]
Thanks @dominick-lekse waiting for the PR

**Comment by dominik-lekse** [comment]
@anoopl PR https://github.com/terraform-providers/terraform-provider-helm/pull/323 is submitted and needs to be reviewed now.

**Comment by anoopl** [comment]
Thanks @dominik-lekse. I will wait for it to be merged

**Comment by nikhilbalekundargi** [comment]
PR #323 is not merged yet. Waiting for helm_template resource

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
