### ISSUE TITLE
Helm inside terraform without tiller

### ISSUE THREAD

**Issue by dhineshbabuelango** [hashicorp/terraform-provider-helm#325]
Hi All, We are using terraform to provision AWS EKS. 
We thought of using helm inside terraform, but the helm which we are using is tillerless helm which needs helm tiller run before all helm commands. can this be achieved in terraform

**Comment by barryib** [comment]
I you are using vanilla terraform, this will probably helps you https://github.com/gruntwork-io/terragrunt/issues/856#issue-490948280

**TL;DR;**
- Run tiller locally with external data source (or with null_resource with local-exec)
- Setup your helm provider to use the local tiller
- Use your helm releases

This ok, but I think the best way to support this is to add the tillerless support within the provider.

Here is a blog post explaining this https://xinau.ch/notes/terraform-with-tillerless-helm/

**Comment by barryib** [comment]
@dhineshbabuelango A first to try to handle this https://github.com/terraform-providers/terraform-provider-helm/pull/339. It's working for me (for now).

**Comment by dhineshbabuelango** [comment]
Thanks @barryib. Let me test this.

**Comment by barryib** [comment]
@dhineshbabuelango here is a release If you want a release to test it https://github.com/Polyconseil/terraform-provider-helm/releases/tag/v0.10.2-poly-20190917-2

**Comment by dhineshbabuelango** [comment]
Hi @barryib, In the below technote you suggested, there is no tiller port mentioned.

https://xinau.ch/notes/terraform-with-tillerless-helm/

Can I use 44140

and when I used the port the next error which I got is below.

![image](https://user-images.githubusercontent.com/51995628/65399563-ff338700-ddef-11e9-823f-2f67395b0088.png)

Below is my TF code.

![image](https://user-images.githubusercontent.com/51995628/65399583-11adc080-ddf0-11e9-9a80-16c3bbeda227.png)

**Comment by dhineshbabuelango** [comment]
> @dhineshbabuelango here is a release If you want a release to test it https://github.com/Polyconseil/terraform-provider-helm/releases/tag/v0.10.2-poly-20190917-2

Hi @barryib, is this the tillerless helm release.

**Comment by dhineshbabuelango** [comment]
When I try to use the below technote for tillerless helm, getting this error[can't find external program tiller]

![image](https://user-images.githubusercontent.com/51995628/65587163-fa213400-dfb7-11e9-9d68-f9e90545b2ae.png)

The below is my terraform code.

![image](https://user-images.githubusercontent.com/51995628/65587216-16bd6c00-dfb8-11e9-9f46-b84cd5e23ec0.png)

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
