### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by marcelloromani** [hashicorp/terraform-provider-helm#326]
Hi,
    I am wondering why the latest "release" is 0.6.0 while there have been quite a few tags since then.
Trying to understand what's changed (and most importantly what's been fixed) between tags is quite hard as no changelog has been written.

Are there a technical reasons for this or has the release process changed?

Thanks

**Comment by legal90** [comment]
As far as I know, the release procedure was changed after the provider repo was transferred to `terraform-providers` organization. Now it's released according to Hashicorp standards - they don't use GitHub Releases feature and put changelog to `CHANGELOG.md` file.

https://github.com/terraform-providers/terraform-provider-helm/issues/197#issuecomment-462282352

But I agree - it still looks a bit confusing :)

**Comment by rporres** [comment]
@legal90 is quite correct. The old repo used releases and they got stalled when it was transferred

I'll see what can be done to avoid that confusion, it's not the first time that happens and it's a bad user experience

cc @alexsomesan

**Comment by marcelloromani** [comment]
Thanks for the quick reply.

As a note to myself (and potentially others):
* Don't look for a changelog in the standard github "releases" tab: just read https://github.com/terraform-providers/terraform-provider-helm/blob/master/CHANGELOG.md

**Comment by florianrusch** [comment]
You could do it like the kubernetes terraform provider and provide both:
- <https://github.com/terraform-providers/terraform-provider-kubernetes/releases>
- <https://github.com/terraform-providers/terraform-provider-kubernetes/tags>

**Comment by byF** [comment]
I strongly suggest following @florianrusch recommendation. It's confusing AF ;)

**Comment by rporres** [comment]
Hashicorp is currently discussing coming into a standard using GH releases too, see https://github.com/terraform-providers/terraform-provider-helm/issues/331#issuecomment-529394252

I'll close this issue and continue the discussion there.
