### ISSUE TITLE
Node Selector For Kubernetes w/ Windows Nodes

### ISSUE THREAD

**Issue by cwiederspan** [hashicorp/terraform-provider-helm#328]
Now that we can use Terraform to create a Kubernetes cluster with Windows nodes, there needs to be a way to pin the Tiller pods to Linux node types. Is there any way to do this now?

**Comment by aaronmell** [comment]
There isn't currently. Provider needs to implement the override command. Honestly, we prefer to bootstrap tiller outside of helm. V3 of helm is getting rid of tiller anyways. 

Edited, because I was wrong, the provider does provide an override command

**Comment by aaronmell** [comment]
You could also look into tillerless helm. Haven't investigated it, but it seems like a reasonable solution. Not sure if it works with the plugin though.

**Comment by cwiederspan** [comment]
So, my needs are totally selfish. I have an extensive demo environment that I use that create the Kubernetes cluster (AKS), and then uses the helm provider to install a complete application. The trick is that I can do it completely with one terraform apply and don't have to manually setup anything from start-to-finish. That's why I'm hoping to add Windows nodes into the demo and still keep things working.

That said, can I use the override setting to set the nodeSelector in the manifest...? I'm trying something like this, but doesn't seem to work:
```
provider "helm" {
  version = "0.10"

  kubernetes { ... }

  tiller_image    = "gcr.io/kubernetes-helm/tiller:v2.14.1"
  service_account = "tiller"

  override = [
    "spec.template.spec.nodeSelector.\"beta.kubernetes.io/os\"=\"linux\""
  ]
}
```

And thank you for the help!!!

**Comment by aaronmell** [comment]
Ah, I see your issue. 

try double backslashing the periods in the beta.kubernetes.io Thats how I handle periods in the resources that aren't meant to indicate a new line and indent in the yaml

"spec.template.spec.nodeSelector.\"beta\\\\.kubernetes\\\\.io/os\"=\"linux\""

**Comment by cwiederspan** [comment]
Looks like I got this working - thanks for the pointer @aaronmell!!!

```
provider "helm" {
  version = "0.10"

  kubernetes { ... }

  tiller_image    = "gcr.io/kubernetes-helm/tiller:v2.14.1"
  service_account = "tiller"

  override = [
    "spec.template.spec.nodeSelector.beta\\.kubernetes\\.io/os=linux"
  ]
}
```
