### ISSUE TITLE
feature request: support timeouts on helm_release

### ISSUE THREAD

**Issue by jhoblitt** [hashicorp/terraform-provider-helm#329]
As of `0.10.2`, the `helm_release` does not support a `timeouts` block.

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "jenkins" {
  name      = "jenkins"

  ...

  timeouts {
    create = "2h"
    delete = "2h"
  }
}
```

### Debug Output
```
Error: Error running plan: 1 error occurred:
	* helm_release.jenkins: 1 error occurred:
	* helm_release.jenkins: [ERR] Error decoding timeout: Timeout Key (delete) is not supported
```

**Comment by yves-vogl** [comment]
You can use the ```timeout``` attribute for this.

**Comment by aclowkey** [comment]
@yves-vogl  It doesn't work work for terraform 0.11, it just kills it after 5m leaving a broken state.
