### ISSUE TITLE
Publish GitHub releases during provider releases

### ISSUE THREAD

**Issue by pdecat** [hashicorp/terraform-provider-helm#331]
Releases are published by updating the changelog, pushing a binary, and making a GitHub "tag" release.
Users can't subscribe to these releases automatically, though: https://github.community/t5/How-to-use-Git-and-GitHub/Not-getting-release-notification-despite-quot-Watching-releases/td-p/19665.

It would be awesome to publish rich releases on GitHub, allowing users to subscribe.

Both the [Azure](https://github.com/terraform-providers/terraform-provider-azurerm/releases) and [AWS](https://github.com/terraform-providers/terraform-provider-aws/releases) providers do this already.

Note: it used to be done until [release 0.6.0](https://github.com/terraform-providers/terraform-provider-helm/releases/tag/v0.6.0) of the helm provider which currently appears as the latest one despite several tagged releases:

![image](https://user-images.githubusercontent.com/318490/64331391-ff035100-cfd2-11e9-8ed9-8929e867b3c7.png)

**Comment by rporres** [comment]
cc @alexsomesan This is something that should be standardised from a Hashicorp perspective

**Comment by alexsomesan** [comment]
I agree. This is something we're considering and have started discussing to come to a common standard.

**Comment by marcelloromani** [comment]
Pardon my peskyness, but I don't see the need to wait for a global decision on whether to use GH releases or not to start using them again, considering:
* AWS and Azure are (still) using them, as mentioned
* They were used up to 0.6.0, and it's not clear why this has stopped
* Using GH releases clearly provides a much better user experience than tags alone

**Comment by rporres** [comment]
> They were used up to 0.6.0, and it's not clear why this has stopped

That happened when repository was transferred from the original developer's github account to the official terraform-providers organization. At that moment the common practise was adopted but the old releases were not removed, hence the confusion

**Comment by marcelloromani** [comment]
Thanks @rporres for the explanation.

**Comment by pdecat** [comment]
Current work-around: subscribe to https://github.com/terraform-providers/terraform-provider-helm/tags.atom with a feed reader

**Comment by pdecat** [comment]
> it used to be done until release 0.6.0 of the helm provider which currently appears as the latest one despite several tagged releases

What about [deleting the old releases](https://help.github.com/en/articles/editing-and-deleting-releases#deleting-a-release) to eliminate the confusion until a long term solution is implemented?

**Comment by marcelloromani** [comment]
@pdecat Very much against it, as that would suddenly break things for the poor souls still deploying 0.6.0 :-)

**Comment by rporres** [comment]
@marcelloromani I fail to see how people will deploy `0.6.0` if it's not manually as it is not in the official release page https://releases.hashicorp.com/terraform-provider-helm/. `0.6.1` is actually the same thing as `0.6.0` but released as the official provider

I agree with @pdecat that current situation is the worse of the two worlds, so I'd prefer to delete old releases (which do not correspond to anything officially released by hashicorp) to avoid confusion, but we need @alexsomesan input here

**Comment by pdecat** [comment]
Hi, I just meant deleting the Github releases, not the tags, nor the artifacts available at https://releases.hashicorp.com/terraform-provider-helm/

**Comment by pdecat** [comment]
Oh, I did not notice 0.6.0 and older release artifacts were not available at https://releases.hashicorp.com/terraform-provider-helm/

**Comment by rporres** [comment]
I'm not sure if they can be uploaded or not as it will need to be a manual process and that belongs to Hashicorp internals :)

**Comment by marcelloromani** [comment]
Surely putting a note pointing to https://releases.hashicorp.com/terraform-provider-helm/ won't hurt?

**Comment by pdecat** [comment]
Github releases are now published during the release process since v0.10.3 :tada:

https://github.com/terraform-providers/terraform-provider-helm/releases
