### ISSUE TITLE
Sensitive values leaked on `terraform plan` 

### ISSUE THREAD

**Issue by alexsn** [hashicorp/terraform-provider-helm#333]
### Terraform Version
0.12.8

### Affected Resource(s)

- helm_release

### Expected Behavior
Sensitive value should be hidden on `terraform plan` / `terraform apply`

### Actual Behavior
Sensitive value echoed on `terraform plan`

### Steps to Reproduce

1. Use helm_release with set_sensitive block.
2. `terraform apply`
3. `terraform plan` echoes back sensitive value in metadata section.

**Comment by gordonbondon** [comment]
Related https://github.com/terraform-providers/terraform-provider-helm/issues/251

**Comment by rporres** [comment]
@alexsn Is there any difference with #251 or can close this issue in favor of that one?
