### ISSUE TITLE
helm release with value file not work 

### ISSUE THREAD

**Issue by sebglon** [hashicorp/terraform-provider-helm#342]
### Terraform Version
terraform v0.11.14
provider.helm v0.10.2

### Affected Resource(s)

- helm_release
- local_file

### Terraform Configuration Files
```hcl
resource "local_file" "helm_config" {
  content  = "aa: aa "
  filename = "tf-helm-values.yaml"
}

resource "helm_release" "main" {
  name = "my-release"

  chart     = "my-chart"
  namespace = "my-namespace"

  values = [
    "${file(local_file.helm_config.filename)}",
  ]

  depends_on = [
    "local_file.helm_config",
  ]
}
```

### Debug Output
```
terraform apply

Error: Error running plan: 1 error occurred:
	* helm_release.main: 1 error occurred:
	* helm_release.main: file: open tf-helm-values.yaml: no such file or directory in:

${file(local_file.helm_config.filename)}

```

### Expected Behavior
The `terraform plan` not check il the file already exist and respect the dependency tree.

### Actual Behavior
the plan try to read file created by a parent resources
### Steps to Reproduce

1. `terraform apply`

**Comment by meyskens** [comment]
Looking at the content of https://www.terraform.io/docs/providers/local/r/file.html
Can you try
```
values = [
    "${local_file.helm_config.content}",
  ]
```
