### ISSUE TITLE
Helm dependency build is not run on helm_release

### ISSUE THREAD

**Issue by sebglon** [hashicorp/terraform-provider-helm#343]
### Terraform Version
terraform: 0.11.14
helm provider: 0.10.2

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "main" {
  name = "my-release"

  chart     = "./my-chart"
  namespace = "my-namespace"
}

```

My chart have some requirement and i have no charts folder on my local.

### Expected Behavior
When i run terraform apply, i want it run a helm dep build to download all requirement on the local charts folder.

### Actual Behavior
we have an error

### Steps to Reproduce

1. `terraform apply`

A workaroud can be to add a local-exec like that:
```hlc
resource "null_resource" "helm_update" {
  triggers = {
    always_run = "${timestamp()}"
  }

  provisioner "local-exec" {
    command = "cd ${local.helm_chart_path} && helm dep build"
  }
}
```

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
