### ISSUE TITLE
Helm 3 in terraform

### ISSUE THREAD

**Issue by dhineshbabuelango** [hashicorp/terraform-provider-helm#344]
Hi All, we are using helm inside terraform to provision our applications. We are using helm Verson 3. I have a chart named normal-update. When I put the chart details inside terraform and run terraform plan, it shows like this, but when I ran terraform apply it is saying creating for a very long time, but no resources were created. But if I directly use helm command like
helm install test it is working, can someone help.

![image](https://user-images.githubusercontent.com/51995628/65401008-0363a280-ddf8-11e9-866b-99c12fde1e5e.png)

output while apply:

![image](https://user-images.githubusercontent.com/51995628/65401018-0c547400-ddf8-11e9-90e6-46a55f6cbb87.png)

My terraform code
![image](https://user-images.githubusercontent.com/51995628/65401024-16767280-ddf8-11e9-829e-1029aa51652f.png)

**Comment by meyskens** [comment]
We do not yet support Helm 3, so I suspect that is the reason. More info about planning to support this is in #299

**Comment by rporres** [comment]
Closing this in favor of #299
