### ISSUE TITLE
resources will be re-created issue for local helm charts

### ISSUE THREAD

**Issue by hkailantzis** [hashicorp/terraform-provider-helm#353]
Hi there,

Terraform v0.12.9
+ provider.azurerm v1.30.1
+ provider.helm v0.9.1
+ provider.kubernetes v1.7.0

I have the following issue, when creating resources, with local helm charts. First time running:
`terraform plan -out=tfplan -var-file=variables.tfvars` and then `terraform apply "tfplan"`, runs successfully and any local helm charts are installed successfully on the aks cluster. 

Without changing anything, running the same plan command again, shows that resources with local helm charts will be re-created again, when they shouldn't. For remote charts or any other resources this is not the case. Any idea, why ? TF state shows the resources the first time, so any hint on why the second time running `terraform plan`, local helm chart will get recreated again ? This will lead to an error if continued with apply ,as the resources already exist on the cluster. 

Thanks in advance.

**Comment by hkailantzis** [comment]
One hint worth mentioning is that `helm list`, doesn't display any local charts that were installed, even though the resources have been created. This is not the case for 'remote' charts, these are shown when issuing `helm list`.

**Comment by goblain** [comment]
@hkailantzis did you try `helm list --all` ?

**Comment by hkailantzis** [comment]
Hi @goblain, thanks for your response, no i didn't. But will close this I think, as I switched to installing via kubectl apply instead...but I'm curious as this doesn't seem to work as expected.
