### ISSUE TITLE
[resolved] Error: repo jetstack not found

### ISSUE THREAD

**Issue by JulienBreux** [hashicorp/terraform-provider-helm#354]
## Solution

https://github.com/terraform-providers/terraform-provider-helm/issues/354#issuecomment-541534473

### Terraform Version
`Terraform v0.12.10`

### Affected Resource(s)
- helm_repository

### Terraform Configuration Files

```
provider "helm" {
  version = "~> 0.10"
}

data "helm_repository" "jetstack" {
  name = "jetstack"
  url  = "https://charts.jetstack.io"
}

resource "helm_release" "cert_manager" {
  repository = data.helm_repository.jetstack.metadata.0.name
  name       = "cert-manager"
  chart      = "cert-manager"
  namespace  = "cert-manager"
  version    = "v0.11.0-beta.0"
}
```

### Expected Behavior

Release created with repo.

### Actual Behavior

```
Error: repo jetstack not found
```

### References

- https://github.com/terraform-providers/terraform-provider-helm/issues/163#issuecomment-487903040
- https://github.com/terraform-providers/terraform-provider-helm/issues/271
- https://github.com/terraform-providers/terraform-provider-helm/pull/272

**Comment by JulienBreux** [comment]
Thanks to @duxet here:
https://github.com/terraform-providers/terraform-provider-helm/issues/319#issuecomment-523766938

**Comment by JulienBreux** [comment]
**SOLUTION**

```
provider "helm" {
  version = "~> 0.10"

  # ...

  home = "${abspath(path.root)}/.helm"

  # ...
}
```

**Comment by legal90** [comment]
Just if anyone else is running into it:   Using a repo URL in `repository` param should also work:
```
provider "helm" {
  version = "~> 0.10"
}

resource "helm_release" "cert_manager" {
  repository = "https://charts.jetstack.io"
  name       = "cert-manager"
  chart      = "cert-manager"
  namespace  = "cert-manager"
  version    = "v0.11.0-beta.0"
}
```

P.S.
Actually, I think that should be the recommended way, instead of using `helm_repository` data/resource. It's even faster because terraform doesn't spent time on refreshing the state of `helm_repository` every time.

**Comment by JulienBreux** [comment]
@legal90 big thanks for this info!

And I think that's more clear to read 😉

**Comment by arturrez** [comment]
> Actually, I think that should be the recommended way, instead of using `helm_repository` data/resource. It's even faster because terraform doesn't spent time on refreshing the state of `helm_repository` every time.

The only problem with this approach is lack of basic auth support. It's not possible to use https://www.terraform.io/docs/providers/helm/repository.html#username and  https://www.terraform.io/docs/providers/helm/repository.html#password without `data helm_repository`
