### ISSUE TITLE
context deadline exceeded on cnnection cut due to timeout

### ISSUE THREAD

**Issue by goblain** [hashicorp/terraform-provider-helm#355]
### Terraform Version
v0.12.9

### Affected Resource(s)
- helm_resource
- helm_repository

### Terraform Configuration Files
```hcl
data "helm_repository" "stable" {
    name = "stable"
    url  = "https://kubernetes-charts.storage.googleapis.com"
}

resource "helm_release" "test01" {
  name       = "redis-release01"
  repository = "${data.helm_repository.stable.metadata.0.name}"
  chart      = "redis"
  set {
    name = "cluster.enabled"
    value = "false"
  }
}

resource "null_resource" "delay" {
  depends_on = ["helm_release.test01"]
  provisioner "local-exec" {
    command = "sleep 300s"
  }
}

resource "helm_release" "test02" {
  depends_on = ["null_resource.delay"]
  name       = "redis-release02"
  repository = "${data.helm_repository.stable.metadata.0.name}"
  chart      = "redis"
}

```
### Expected Behavior
both helm_releases are applied

### Actual Behavior
second helm_release instance is not applied due to 
```
Error: context deadline exceeded
```
which is a result of kubernetes portforwarder tunnel dropped from kube api on  our AKS clusters (~4min timeout on connections via Azure LoadBalancer). 

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Running on AKS

### Solutions
As portforwarder is initiated once when provider initializes, if something (like LB inactivity timeout) causes tunnel TCP connection to drop, this error is consistently thrown. The simplest solution that works for me is to implement a "keepalive" GetVersion requests that are sent every N seconds to make sure the tunnel stays alive. Retry/recovery from a failure would probably be preferred but a bit more complex to implement. Quickfix I use for my env is in https://github.com/tradeix/terraform-provider-helm/commit/f4348483ecf5ed7224abd4f00febb12b912f805e , if you're willing to merge this kind of workaround I can open a PR for this.

**Comment by shaneramey** [comment]
I created https://github.com/terraform-providers/terraform-provider-helm/pull/359 which fixed this issue for me.

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
