### ISSUE TITLE
Cannot set the version parameter, it is always be overriden to the latest version

### ISSUE THREAD

**Issue by ruccoon** [hashicorp/terraform-provider-helm#358]
### Terraform Version
Terraform v0.12.9

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```
resource "helm_release" "prometheus" {
  name      = "monitoring-prometheus"
  namespace = "monitoring"
  chart     = "stable/prometheus-operator"
  version   = "6.10.0"
```

### Expected Behavior
prometheus-operator version 6.10.0 will be installed

### Actual Behavior
prometheus-operator-6.11.0 is installed

### Steps to Reproduce
`terraform apply`

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
