### ISSUE TITLE
Update helm/tiller to 2.15.0

### ISSUE THREAD

**Issue by aeneasr** [hashicorp/terraform-provider-helm#360]
Helm was recently released as version 2.15.0 which fixes an important issue with Kubernetes 1.16 (installing Helm version 2.14.* is not possible on Kubernetes 1.16+).

Not filling out the rest of the issue template because this is pretty straight forward I think. Happy to provide a PR.

**Comment by JulienBreux** [comment]
Hi @aeneasr!

Wait for review: https://github.com/terraform-providers/terraform-provider-helm/pull/361

+ Upgrade Travis to Go 1.12.x
+ Upgrade Helm to 2.15.1
+ Upgrade Kubernetes to 1.15.5

**Comment by meyskens** [comment]
Tiller has also been updated in https://github.com/terraform-providers/terraform-provider-helm/pull/365
Closing this now
