### ISSUE TITLE
Outdated installation instructions

### ISSUE THREAD

**Issue by subesokun** [hashicorp/terraform-provider-helm#363]
Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html. -->

The README suggests to install the version `v0.7.0` as binary but this binary doesn't exist, see [terraform-provider-helm_v0.7.0_linux_amd64.tar.gz](https://github.com/terraform-providers/terraform-provider-helm/releases/download/v0.7.0/terraform-provider-helm_v0.7.0_linux_amd64.tar.gz).

On the releases page, there is a `v0.10.2` but `v0.6.0` is tagged as "latest release". Which version should I use?

Just asking out of interest, is there any progress on moving this provider directly into the Terraform ecosystem to avoid this manual installation?

Thanks a lot!

**Comment by meyskens** [comment]
These instructions should be removed as they are no longer needed since Terraform now will get it from the official repo.
I made a PR to fix the readme: https://github.com/terraform-providers/terraform-provider-helm/pull/364

**Comment by subesokun** [comment]
@meyskens Awesome! Then I'll switch to the official repo 👍

**Comment by meyskens** [comment]
PR merged, closing this
