### ISSUE TITLE
Feature Request: Support exec Authentication (client-go Credential Plugins) 

### ISSUE THREAD

**Issue by danylohetmantsev** [hashicorp/terraform-provider-helm#376]
https://github.com/terraform-providers/terraform-provider-kubernetes/issues/161

can you add the same functionality of kubernetes block into helm provider?

**Comment by legal90** [comment]
It seems it was done in #300, but not merged yet.

**Comment by nick4fake** [comment]
That PR is closed but, it is not supported for Helm2.

**Comment by aareet** [comment]
Per https://github.com/terraform-providers/terraform-provider-helm/pull/300 this is now supported for Helm 3. Helm 2 support is deprecated in the provider as of v1.0.0. Closing.
