### ISSUE TITLE
Helm v3

### ISSUE THREAD

**Issue by aeneasr** [hashicorp/terraform-provider-helm#377]
Now that Helm v3 is finally released, we can avoid lots of the problems arising from mismatching server (tiller) / client versions and adjacent issues (e.g. incompatibility with Kubernetes 1.16 because of some Tiller annotation). This will also remove the need to constantly update this repository.

Is there a plan to move to Helm v3 with this provider?

**Comment by thorker** [comment]
WIP: #299
