### ISSUE TITLE
Support deleting releases

### ISSUE THREAD

**Issue by dploeger** [hashicorp/terraform-provider-helm#381]
### Terraform Version
```
Terraform v0.12.12
+ provider.azurerm v1.28.0
+ provider.helm v0.10.4
+ provider.kubernetes v1.7.0
```

### Affected Resource(s)

- helm_release

### Expected Behavior
When a release resource is deleted from the terraform directory, the release should be deleted in the cluster as well.

### Actual Behavior
On running `terraform apply` the following error message is presented:

    Error: Reference to undeclared resource
    A managed resource "helm_release" "elasticsearch" has not been declared in the
    root module.

### Steps to Reproduce
1. Set up a new helm_release resource
2. `terraform apply`
3. Delete the helm_release resource by commenting it out
4. `terraform apply`

### Important Factoids
I'm running an Azure AKS cluster.

**Comment by meyskens** [comment]
Deleting releases is supported, the error you get seems not related to the provider. Could you tell us more about your module structure and used code? Thanks

**Comment by dploeger** [comment]
Oh, okay. I was already wondering why it wouldn't. 😄 
I'll check my code again and get back to you.

**Comment by dploeger** [comment]
Hm. Very strange. After another try, it all works as expected.
Thanks!
