### ISSUE TITLE
there is no way to download dependencies without using an external helm command

### ISSUE THREAD

**Issue by sushilkm** [hashicorp/terraform-provider-helm#384]
Basically, there is no way to update dependencies for a chart for eg. https://github.com/helm/charts/tree/master/stable/wordpress while using helm_release

Terraform Version: Terraform v0.12.16
Affected Resource(s): helm_release
Terraform Configuration Files
```
resource "helm_release" "wordpress" {
  name       = "wordpress"
  chart      = "wordpress"
}
```
Expected Behavior, since this chart is dependent on mariadb so there should be a way in resource helm_release to instruct to the system to download the dependency chart

Actual Behavior:
Error ==>
```
Error: found in requirements.yaml, but missing in charts/ directory: mariadb

  on ../../../modules/azure/helm/main.tf line 72, in resource "helm_release" "wordpress":
  72: resource "helm_release" "wordpress" {

```

Steps to Reproduce
```terraform apply```

**Comment by paaloeye** [comment]
@sushilkm, thank you for reporting this issue. 

Could you please provide more details and the steps to reproduce?

Here is a template for you: https://github.com/terraform-providers/terraform-provider-helm/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by sushilkm** [comment]
Updated, thanks

**Comment by paaloeye** [comment]
@sushilkm You don't use the official `stable/wordpress` chart, do you?

The official `wordpress` chart does have the charts folder. See the output below. 
```console
$ helm fetch stable/wordpress
$ tar tf wordpress-8.0.3.tgz
wordpress/Chart.yaml
wordpress/values.yaml
wordpress/templates/NOTES.txt
wordpress/templates/_helpers.tpl
wordpress/templates/deployment.yaml
wordpress/templates/externaldb-secrets.yaml
wordpress/templates/ingress.yaml
wordpress/templates/pvc.yaml
wordpress/templates/secrets.yaml
wordpress/templates/servicemonitor.yaml
wordpress/templates/svc.yaml
wordpress/templates/tests/test-mariadb-connection.yaml
wordpress/templates/tls-secrets.yaml
wordpress/.helmignore
wordpress/README.md
wordpress/requirements.lock
wordpress/requirements.yaml
wordpress/values.schema.json
wordpress/charts/mariadb/Chart.yaml
wordpress/charts/mariadb/values.yaml
wordpress/charts/mariadb/templates/NOTES.txt
wordpress/charts/mariadb/templates/_helpers.tpl
wordpress/charts/mariadb/templates/initialization-configmap.yaml
wordpress/charts/mariadb/templates/master-configmap.yaml
...
```

It seems your chart is corrupted 'cause Helm CLI would refuse to assemble a chart with **non-empty** `requirements.json` and **empty** `charts` folder.

```console
$ helm package .
Error: found in requirements.yaml, but missing in charts/ directory: mariadb
```

Your immediate solution would be to repackage the chart with `-u` argument. 
```console 
$ helm package -u .
```

**Overall**, it doesn't look like there is something to improve here for `terraform-provider-helm`. 
As far as I'm concerned, this issue should be closed. 
@sushilkm, let me know what you think.

cc: @mcuadros @meyskens @alexsomesan @rporres

**Comment by aareet** [comment]
Thank you for your help @pbrit, closing this issue. @sushilkm please reopen if this is still an issue.
