### ISSUE TITLE
Error: data helm repository doesn't work as expected

### ISSUE THREAD

**Issue by Jyoti492** [hashicorp/terraform-provider-helm#387]
Hi Team,

I am trying to deploy the helm charts from ACR using the terraform-provider-helm but it fails with below error. Can someone please let me know if I am doing anything wrong because I am not able to understand why is this searching for mcpshareddcr-index.yaml ?

### Terraform Version
0.12.18

### Affected Resource(s)
- helm_release
- helm_repository

### Terraform Configuration Files
```
# Cluster RBAC helm Chart repository
data "helm_repository" "cluster_rbac_helm_chart_repo" {
  name = "mcpshareddcr"
  url  = "https://mcpshareddcr.azurecr.io/helm/v1/repo"
  username = var.ARM_CLIENT_ID
  password = var.ARM_CLIENT_SECRET
}

# Deploy Cluster RBAC helm chart onto the cluster
resource "helm_release" "cluster_rbac_helm_chart_release" {
  name  = "mcp-rbac-cluster"
  repository = data.helm_repository.cluster_rbac_helm_chart_repo.metadata[0].name
  chart = "mcp-rbac-cluster"
  version = "0.1.0"
}
```
module usage:
```
provider "azurerm" {
  version                    = "=1.36.0"
  tenant_id                  = var.ARM_TENANT_ID
  subscription_id            = var.ARM_SUBSCRIPTION_ID
  client_id                  = var.ARM_CLIENT_ID
  client_secret              = var.ARM_CLIENT_SECRET
  skip_provider_registration = true
}

data "azurerm_kubernetes_cluster" "aks_cluster" {
  name                = var.aks_cluster
  resource_group_name = var.resource_group_aks
}

locals {
  kubeconfig_path = "/tmp/kubeconfig"
}

resource "local_file" "kubeconfig" {
  filename = local.kubeconfig_path
  content  = data.azurerm_kubernetes_cluster.aks_cluster.kube_admin_config_raw
}

provider "helm" {
  home = "./.helm"
  kubernetes {
    load_config_file = true
    config_path = local.kubeconfig_path
  }
}

// Module to deploy Stratus offered helmcharts in AKS cluster
module "mcp_resources" {
  source = "modules\/helm\/mcp-resources"
  ARM_CLIENT_ID = var.ARM_CLIENT_ID
  ARM_CLIENT_SECRET = var.ARM_CLIENT_SECRET
  ARM_SUBSCRIPTION_ID = var.ARM_SUBSCRIPTION_ID
  ARM_TENANT_ID = var.ARM_TENANT_ID
}
```

### Expected Behavior
Deploy of helm charts on AKS fetching from ACR.

### Actual Behavior
**Error:** Looks like "***/helm/v1/repo" is not a valid chart repository or cannot be reached: open .helm/repository/cache/.helm/repository/cache/mcpshareddcr-index.yaml: no such file or directory

### Steps to Reproduce
1. `terraform plan`

**Comment by blairham** [comment]
I too am experiencing this, as I would like to install a chart that is not in chart hub. You should be able to point to an arbitrary location such as a GitHub repo.

**Comment by IbraheemAlSaady** [comment]
@Jyoti492 I had a similar problem with this all of yesterday. 

**Problem** 
ACR doesn't manage a helm repository, by that I mean there is no index.yaml file. I believe you have followed the documentation by Microsoft [here](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos)

**Solution** 
What you need to do is use the ACR helm 2 way of pushing to the ACR, and then consume the charts with the Terraform Helm Provider (Helm 3), just tested it, and it worked.

Check the helm 2 docs [here](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos#use-the-helm-2-client)

Check the steps below. I tested it with the stable/wordpress chart:

```
1) az acr helm repo add -n mcpshareddcr
2) helm fetch stable/wordpress (This will download a tgz file of the chart)
3) az acr helm push -n mcpshareddcr [path_to_the_tgz_downloaded_file]
```
You should see a `{ "saved": "true" }` message when you do that. 

To check if your charts are actually there. 
```
1) az acr helm repo add -n mcpshareddcr (you already did that above, but sometimes you need it to refresh)
2) helm search mcpshareddcr
```

You should be able to see the wordpress chart there

Below is the Terraform

```
data "helm_repository" "acr" {
  name = "mcpshareddcr"
  url  = "https://mcpshareddcr.azurecr.io/helm/v1/repo"

  username = var.acr_username
  password = var.acr_password
}


resource "helm_release" "prometheus_operator" {
  name       = "wordpress"
  repository = data.helm_repository.acr.metadata[0].name
  chart      = "wordpress"
  version    = "9.0.3"

  repository_username = var.acr_username
  repository_password = var.acr_password
}
```

Might not be the best way, but its a way that worked for me now. 

I hope it helps

**Comment by mbarrien** [comment]
Note that in #466 the helm_repository data source has been deprecated, with the new recommended way is putting the repo URL directly in as the "repository" field of the helm_release.

**Comment by aareet** [comment]
@Jyoti492 there are some good responses here to help with the issue. Closing since there doesn't seem to be any remaining actions to be taken here. Please comment if I got it wrong.
