### ISSUE TITLE
Helm V3 support?

### ISSUE THREAD

**Issue by lmgnid** [hashicorp/terraform-provider-helm#390]
When will Helm V3 be supported? Thanks.

**Comment by Comradin** [comment]
Helm 3 support would be great. I ran into this issue when using the provider without having tiller installed.

A note in the readme would be great that the provider is currently helm_v2 only.

**Comment by legal90** [comment]
Hi! You can see the progress of helm 3 support in this PR: https://github.com/terraform-providers/terraform-provider-helm/pull/378#issuecomment-576419319

**Comment by jrhouston** [comment]
This is resolved in the latest release.
