### ISSUE TITLE
Helm provider tries to recreate already deployed applications in EKS cluster

### ISSUE THREAD

**Issue by qubusp** [hashicorp/terraform-provider-helm#397]
### Terraform Version

terraform 12.20
### Affected Resource(s)

- helm_release
- helm_repository

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Expected Behavior

terraform should have updated my helm releases 
### Actual Behavior

terraform tried taint my releases 
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

EKS
### References

- GH-1234

**Comment by kksudo** [comment]
I had same problems.
In my case, the version of `provider.helm v1.0.0` was updated and had same behavior.

Temp fix: downgrade and persistent the provider version.
Smth like this:
```
terraform {
  required_providers {
    helm     = "= 0.10.4"
  }
}
```

**Comment by kksudo** [comment]
`provider.helm v1.0.0` [No longer supports helm v2 (#378)](https://github.com/terraform-providers/terraform-provider-helm/blob/master/CHANGELOG.md#100-february-05-2020)

**Comment by qubusp** [comment]
Did what you said, it's still trying to recreate the deployments

**Comment by kksudo** [comment]
@qubusp 
After `terraform state list` you should see the target app in list out.

You need delete actual plugin and download new plugin.
`rm -rf ./.terraform`
`terraform init`
After that `terraform version` you should view 
```
Terraform v0.12.20
+ provider.helm v0.10.4
```

**Comment by qubusp** [comment]
@kksudo 
this is what i do before every push, im running it in travis: 

```
  - wget https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip
  - echo "46bd906f8cb9bbb871905ecb23ae7344af8017d214d735fbb6d6c8e0feb20ff3 terraform_0.12.20_linux_amd64.zip" | sha256sum --check --status
  - unzip terraform_0.12.20_linux_amd64.zip
  - sudo mv ./terraform /usr/local/bin/terraform
  - rm terraform_0.12.20_linux_amd64.zip
  - gem install overcommit travis
  - mkdir -p $HOME/bin $HOME/.terraform.d/plugins && export PATH=$HOME/bin:$PATH
  - wget -O $HOME/bin/aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
  - wget -O $HOME/.terraform.d/plugins/terraform-provider-kubectl https://github.com/gavinbunney/terraform-provider-kubectl/releases/download/v1.0.1/terraform-provider-kubectl-linux-amd64
  - wget -O $HOME/.terraform.d/plugins/terraform-provider-restapi https://github.com/Mastercard/terraform-provider-restapi/releases/download/v1.10.0/terraform-provider-restapi_v1.10.0-linux-amd64
  - chmod +x $HOME/bin/* $HOME/.terraform.d/plugins/*
  - sudo wget -O /usr/local/bin/tfsec https://github.com/liamg/tfsec/releases/download/v0.13.0/tfsec-linux-amd64
  - echo "f98bf4c526742ee29fcd272b093df555831bbf3886dbdc5eb7ae0ff679ea48fd /usr/local/bin/tfsec" | sha256sum --check --status
  - sudo chmod +x /usr/local/bin/tfsec
  - overcommit --sign
  - overcommit --sign pre-commit
  - echo "Installing tflint now"
  - sudo chmod +x tflint_install.sh
  - sh tflint_install.sh
  - sudo pip install grafyaml```

I don't cache locally.

**Comment by kksudo** [comment]
And after the `terraform state list` command you see the target app (state should know is that you app already installed) in the list ?

**Comment by aareet** [comment]
@qubusp can you provide us with debug output with TF_LOG set to TRACE so we can see what's happening here? https://www.terraform.io/docs/internals/debugging.html

**Comment by aareet** [comment]
Closing since it has been a month. Please reopen if this is still an issue.
