### ISSUE TITLE
home/.kube/config: no such file or directory

### ISSUE THREAD

**Issue by heoelri** [hashicorp/terraform-provider-helm#402]
### Terraform Version

0.12.20

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
provider "helm" {
  kubernetes {
    host                   = azurerm_kubernetes_cluster.deployment.kube_config.0.host
    username               = azurerm_kubernetes_cluster.deployment.kube_config.0.username
    password               = azurerm_kubernetes_cluster.deployment.kube_config.0.password
    client_certificate     = base64decode(azurerm_kubernetes_cluster.deployment.kube_config.0.client_certificate)
    client_key             = base64decode(azurerm_kubernetes_cluster.deployment.kube_config.0.client_key)
    cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.deployment.kube_config.0.cluster_ca_certificate)
  }
}

data "helm_repository" "stable" {
  name = "stable"
  url  = "https://kubernetes-charts.storage.googleapis.com"
}

resource "helm_release" "nginx-ingress" {
  name       = "nginx-ingress"
  repository = data.helm_repository.stable.metadata[0].name
  chart      = "nginx-ingress"
  version    = "1.30.0"

  set {
    name  = "rbac.create"
    value = "true"
  }

  set {
    name  = "controller.autoscaling.enabled"
    value = "true"
  }

  set {
    name  = "controller.service.loadBalancerIP"
    value = "true"
  }
}
```

### Expected Behavior

Terraform should use Helm to deploy the nginx-ingress Chart to my Azure Kubernetes Service Cluster.

### Actual Behavior

```console
Error: stat /github/home/.kube/config: no such file or directory

  on kubernetes.tf line 82, in resource "helm_release" "nginx-ingress":
  82: resource "helm_release" "nginx-ingress" {
```

### Steps to Reproduce

`terraform validate` and `terraform plan` finish successfuly. Only the `terraform apply` steps fails with the error message i pasted above.

### Important Factoids

* Azure Kubernetes Service
* Deployment using GitHub Actions

**Comment by eeeschwartz** [comment]
@heoelri I encountered the same issue and was able to fix the issue by manually writing the `~/.helm/config` file as described in #400. 

The issue also describes further issues I had with the helm config but YMMV.

**Comment by heoelri** [comment]
Thanks @eeeschwartz I spent some more time on troubleshooting this. Removing all sets solved the problem so it seemed like it's not an authentication issue.

Step-by-step adding all sets back pointed to the annotations i've tried to set to configure the LB as an Internal Load Balancer. This issue helped me to fix it: https://github.com/terraform-providers/terraform-provider-helm/issues/125

**Comment by IbraheemAlSaady** [comment]
Just to put this out there. You need to disable loading the config file

```terraform
provider "helm" {

  kubernetes {
    load_config_file = false
    ...
  }
```

Gotta admit, its a bit of a weird behavior because if credentials are provided, it shouldn't look at the config file. But the above is working for me

**Comment by h4wkmoon** [comment]
Same issue even with 
```
provider "helm" {

  kubernetes {
    load_config_file = false
    ...
  }
```

**Comment by IbraheemAlSaady** [comment]
@h4wkmoon do you have your kubeconfig in the `~/.kube/config` path?
You can also try exporting the config like: `export KUBECONFIG=[path to config file]` 

Also, make sure this variable `KUBE_LOAD_CONFIG_FILE` is not set to true anywhere. 

Have a look [here](https://www.terraform.io/docs/providers/helm/index.html#config_path)

That's the steps I would take, I hope that helped in some way.

**Comment by h4wkmoon** [comment]
My bad, I had set an alias for the helm provider, and did not set it in every helm releases in my project.
That's an obvious pebkac.
My apologies for the time wasted and the spam.
