### ISSUE TITLE
Creating an ingress prevents helm_release from completing successfully

### ISSUE THREAD

**Issue by enicc** [hashicorp/terraform-provider-helm#403]
### Terraform Version
```
terraform -v
Terraform v0.12.20
+ provider.aws v2.48.0
+ provider.helm v0.10.4
```
provider.helm pinned due to helm2 compatibility

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
provider "aws" {
  version = "~> 2.28"
  region  = "eu-west-1"
}

provider "helm" {
  version = "~>0.10"
  kubernetes {
    config_path = "<REDACTED>"
  }
}

resource "helm_release" "ingress_bug" {
  name       = "ingress-bug-terra-helm"
  namespace  = "ingress-bug-terra-helm-ns"
  chart      = "./chart"
  wait = true
  set {
      name = "ingress.enabled"
      value = true
  }
  set {
      name = "ingress.paths[0]"
      value = "/"
  }
}
```

### Debug Output
https://gist.github.com/enicc/09e9d0bf29adc1374a5d77943776976a

### Panic Output
N/A

### Expected Behavior
The helm release should complete successfully

### Actual Behavior
The ingress appears to get created successfully, however the helm release never completes successfully.

### Steps to Reproduce
```
helm create chart
terraform plan
terraform apply
```
if we replace
```
  set {
      name = "ingress.enabled"
      value = true
  }
```
with:
```
  set {
      name = "ingress.enabled"
      value = false
  }
```
it does not seem possible to reproduce the issue

### Important Factoids
- All investigation / repro steps completed running as an assumed role in aws, against eks v1.14
- This appears to be the simplest repro configuration but for completeness, this is a contrived example to illustrate an issue experienced with a more complicated deployment

### References
I was not able to identify related issues - open or closed

**Comment by alexsomesan** [comment]
This issue seems very hard to reproduce without access to the specific environment and chart described here. Closing for now. Please re-open if additional data becomes available.
