### ISSUE TITLE
Helm provider fails on creating CRD after its been destroyed once

### ISSUE THREAD

**Issue by andrewhertog** [hashicorp/terraform-provider-helm#411]
### Terraform Version

```
Terraform v0.12.20
```
### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl

provider "helm" {
  version = ">= 1.0.0" # 1.0.0 or later is helm3, anything prior to 1.0.0 is helm 2

  kubernetes {
    host                   = data.aws_eks_cluster.eks.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.eks.token
    load_config_file       = false
  }
}

resource "helm_release" "helm-operator" {
  name         = "helm-operator"
  repository   = "https://charts.fluxcd.io"
  chart        = "helm-operator"
  namespace    = module.k8s-namespace.namespace_name
  force_update = true

  set_string {
    name  = "createCRD"
    value = var.helmOperatorCreateCRD
  }
  set_string {
    name  = "allowNamespace"
    value = var.helmOperatorallowNamespace
  }
  set_string {
    name  = "helm.versions"
    value = "v3"
  }
}

```

### Debug Output

https://gist.github.com/andrewhertog/96bc6cfb17ca3234e56ae489f0176d6f

### Expected Behavior

After deleting the helm resources, I would expect the resources to return as defined in terraform through a `terraform apply`

### Actual Behavior

`terraform apply` fails with the following error:
```
helm_release.flux: Creating...
helm_release.flux: Still creating... [10s elapsed]
helm_release.flux: Creation complete after 19s [id=flux]

Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: helmreleases.helm.fluxcd.io

  on main.tf line 105, in resource "helm_release" "helm-operator":
 105: resource "helm_release" "helm-operator" {
```

### Steps to Reproduce

1. `terraform apply` to create the initial resources
2. `terraform destroy` to destroy them
3. `kubectl delete crd helmreleases.helm.fluxcd.io` to destroy the crd
4. `terraform apply` to create the resources again

### Important Factoids

S3/DynamoDB state locking

Installing the chart via helm3 directly works fine

**Comment by andrewhertog** [comment]
Ok after further testing this was a problem with our implementation of a chart that had values backwards compatible with Helm2, and the `skip_crd` parameter conflicted with this trying to create the CRD twice

**Comment by emohammad** [comment]
@andrewhertog what was the solutions for this? I am running in to same issue when trying to create fluxcd release

**Comment by andrewhertog** [comment]
@emohammad 
Depends on what helm version you are working with:
Helm2 - Set `skip_crd` to `true`
Helm3 - Leave `skip_crd` the default value, and use the new Helm method of managing CRD's (https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/)

**Comment by emohammad** [comment]
Thanks @andrewhertog . I left the skip_crds to default value and set createCRD to false/default value
