### ISSUE TITLE
Upgrade to helm 3.1.0

### ISSUE THREAD

**Issue by karuppiah7890** [hashicorp/terraform-provider-helm#412]
Currently helm v3.0.3 is being used.

Latest version is v3.1.0

I will raise a PR for this 😄

**Comment by relu** [comment]
Here's a draft I've been working on which also includes implementation of the new features from v3.1.0: https://github.com/terraform-providers/terraform-provider-helm/pull/410

**Comment by karuppiah7890** [comment]
Ah. Didn't notice it

**Comment by karuppiah7890** [comment]
Ah. Didn't notice it
