### ISSUE TITLE
helm_release error when values.yml file is generated through template_dir

### ISSUE THREAD

**Issue by IbraheemAlSaady** [hashicorp/terraform-provider-helm#414]
I'm running into a situation where my values.yml file is generated through a `template_dir` resource. I understand why this behavior is in place

The error is below: 

```
on helm.tf line 40, in resource "helm_release" "lb_internal":
  40:     file("${template_dir.external_dns.destination_dir}/lb-internal.yml")
    |----------------
    | template_dir.external_dns.destination_dir is "./helm"

Call to function "file" failed: no file exists at helm/lb-internal.yml.

```

**Work Around**

What I had to do, for now, is target apply on the template_dir then apply

`terraform apply -target template_dir.external_dns`
then
`terraform apply`

Terraform Version: 0.12.20
Provider Version: 1.0.0

**Comment by c4m4** [comment]
I have the same issue, but Using template_file, even using depends_on in helm_release doesn't works
