### ISSUE TITLE
Cut new 0.10.x release

### ISSUE THREAD

**Issue by servo1x** [hashicorp/terraform-provider-helm#415]
We're running into context timeout issues on helm v2 and the `connection_timeout` #374 was merged in November 2019 but a new release was never made.

Could someone make a new 0.10.x release?

**Comment by matthew-palmer** [comment]
It seems like there was a range of additions made after the current 0.10.x release, but it does look like the focus is on helm 3.x now, so as I would also appreciate a new helm 2.x update for this provider, I am not holding my breath.

**Comment by dak1n1** [comment]
v0.10.5 was released today https://github.com/hashicorp/terraform-provider-helm/releases
