### ISSUE TITLE
Terraform errors when applying install of helm chart for NGINX

### ISSUE THREAD

**Issue by iexperiment** [hashicorp/terraform-provider-helm#419]
### Terraform Version
v0.12.21

### Azure Kubernetes Version
1.14.8

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
provider "helm" {
  version = "~> 1.0"
  kubernetes {
    load_config_file       = "false"
    host                   = azurerm_kubernetes_cluster.iexperiment.kube_config.0.host
    client_certificate     = base64decode(azurerm_kubernetes_cluster.iexperiment.kube_config.0.client_certificate)
    client_key             = base64decode(azurerm_kubernetes_cluster.iexperiment.kube_config.0.client_key)
    cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.iexperiment.kube_config.0.cluster_ca_certificate)
  }
}

data "helm_repository" "stable" {
  name = "stable"
  url  = "https://kubernetes-charts.storage.googleapis.com"
}

resource "helm_release" "nginx" {
  name       = "iexperiment"
  chart      = "stable/nginx-ingress"
  repository = data.helm_repository.stable.metadata[0].name

  set {
    name  = "controller.service.externalTrafficPolicy"
    value = "Local"
  }
  
  set {
    name  = "controller.service.loadBalancerIP"
    value = azurerm_public_ip.kube_public_ip.ip_address
  }
  
}
```

### Expected Behavior
nginx should have been installed into the kubernetes cluster

### Actual Behavior
Message from Terraform Cloud Log:

Error: Provider produced inconsistent final plan

When expanding the plan for helm_release.nginx to include new values learned
so far during apply, provider "registry.terraform.io/-/helm" produced an
invalid new value for .version: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce
1. Terraform apply the chart above into Azure kubernetes cluster

**Comment by iexperiment** [comment]
I've found the issue with this - this is resolved for me:

It was this line (which I got from the documentation - was a little confusing): 

`repository = data.helm_repository.stable.metadata[0].name`

changing to the line below fixed my issue:

`repository = data.helm_repository.stable.url`

**Comment by adeshreddy** [comment]
Thanks, @iexperiment  I tried by referencing to URL attribute. But now it complaining that it can't find stable/Nginx-ingress in the repository. When I do `helm search repo stable` I can see the nginx-ingress.
Is something wrong with the configuration.

`Error: chart "stable/nginx-ingress" not found in https://kubernetes-charts.storage.googleapis.com repository`
```
provider "helm" {
  version = "1.0.0"
  kubernetes {
    host                   = azurerm_kubernetes_cluster.shrd_aks.kube_config.0.host
    client_key             = "${base64decode(azurerm_kubernetes_cluster.shrd_aks.kube_config.0.client_key)}"
    client_certificate     = "${base64decode(azurerm_kubernetes_cluster.shrd_aks.kube_config.0.client_certificate)}"
    cluster_ca_certificate = "${base64decode(azurerm_kubernetes_cluster.shrd_aks.kube_config.0.cluster_ca_certificate)}"
    load_config_file       = false
  }
}


data "helm_repository" "incubator" {
  name = "stable"
  url  = "https://kubernetes-charts.storage.googleapis.com"
}
resource "helm_release" "ingress" {
  repository = data.helm_repository.incubator.url
  chart = "stable/nginx-ingress"
  name = "test"
}
```

**Comment by iexperiment** [comment]
@adeshreddy you are correct the name should have been "nginx-ingress" and not "stable/nginx-ingress"

This and the fact that the repository attribute above should have been a URL and not a name (as implied in the docs) was the issue. I am able to install this into my cluster now.

**Comment by aareet** [comment]
Thanks for getting back and reporting your success here @iexperiment, closing this issue. Perhaps there is a note here to improve the documentation.
