### ISSUE TITLE
No trace or debug logging for Error: Kubernetes cluster unreachable

### ISSUE THREAD

**Issue by smurfralf** [hashicorp/terraform-provider-helm#420]
### Terraform Version
v0.12.20

### Affected Resource(s)
provider "helm"

### Terraform Configuration Files
```hcl
provider "helm" {
  version = "~>1.0.0"
  kubernetes {
    host                   = data.terraform_remote_state.aks.outputs.kube_config.0.host
    client_certificate     = base64decode(data.terraform_remote_state.aks.outputs.kube_config.0.client_certificate)
    client_key             = base64decode(data.terraform_remote_state.aks.outputs.kube_config.0.client_key)
    cluster_ca_certificate = base64decode(data.terraform_remote_state.aks.outputs.kube_config.0.cluster_ca_certificate)
  }
}
```

### Stderr Output
Error: Kubernetes cluster unreachable

### Debug Output
2020/02/24 11:28:10 [DEBUG] helm_release.this: apply errored, but we're indicating that via the Error pointer rather than returning it: Kubernetes cluster unreachable

### Expected Behavior
Debug output should show the connection information that is failing.

### Actual Behavior
No debug or trace logging performed by provider. Note that when default ~/.kube/config file is used for connection information, error information is more verbose. The lack of details seems to apply to the static configuration use.

### Steps to Reproduce
1. `terraform apply`

**Comment by vfiset** [comment]
found anything yet @smurfralf ?

**Comment by dak1n1** [comment]
Offhand, this looks like it's passing the error directly from helm to the user. This is the helm error:

https://github.com/helm/helm/blob/298f574606aca21e397ea1cd78d66568a19806db/pkg/kube/client.go#L95

We could add something a little more user-friendly on the provider side, that would show the kubernetes client config.

This is where we show the error message to the user:

https://github.com/hashicorp/terraform-provider-helm/blob/9d4719bc7ac906abfe0b7728fbad05c5573e366c/helm/provider.go#L320

**Comment by naresh-rupeek** [comment]
Any updates on this issue??
Facing the same while using helm_release with EKS cluster.
