### ISSUE TITLE
Make atomic the default

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform-provider-helm#422]
Since `atomic` is false by default, no rollbacks are done when doing an `helm upgrade`.
Is there a reason why this is set to false?

I borked up my kubernetes installation and had to manually rollback, instead of having a GitOps operation where things are undone on failure.
Errors such as: `rendered manifests contain a resource that already exists. Unable to continue with install` or `namespace name already exists`

```hcl
resource "helm_release" "istio_init" {
  name        = "istio-init"
  repository  = data.helm_repository.istio.metadata[0].name
  chart       = "istio-init"
  version     = var.istio_version
  namespace   = var.istio_namespace
  
  atomic          = true
  cleanup_on_fail = true
  recreate_pods   = true
  verify          = false
}
```

**Comment by jrhouston** [comment]
Thanks for opening this @hazcod. The reason this defaults to false is simply that the helm CLI also defaults this to false [here](https://github.com/helm/helm/blob/master/cmd/helm/upgrade.go#L182). We try to be consistent with the upstream project so people aren't surprised by the behaviour of the provider.

**Comment by hazcod** [comment]
..
