### ISSUE TITLE
Metadata output contains sensitive values

### ISSUE THREAD

**Issue by evgeni-sladkovski-cs** [hashicorp/terraform-provider-helm#424]
### Terraform Version

0.12.17

### Affected Resource(s)

helm_release

### Terraform Configuration Files

```hcl
resource "helm_release" "my-release" {
  ...  
  values       = [file("values.yaml")]

  set {
    name  = "image.version"
    value = file("app.version")
  }

  set_sensitive {
    name  = "variables.secrets.DB_PASSWORD"
    value = "pa$$word"
  }
}
```
### Expected Behavior

when I do terrafrom apply it shows update plan with changes. In that plan metadata output is exposed and that metadata contains previous values and additional sets. I expect that sensitive keys are somehow obfuscated and don't show in the logs.

### Actual Behavior

The problem is that sensitive values are in plain text.
helm_release.hello-cloud will be updated in-place
```hcl
  ~ resource "helm_release" "my-release" {
        ....
        metadata              = [
            {
                ...
                values    = jsonencode(
                    {
                            ........
                            secrets = {
                                DB_PASSWORD = "pa$$word"
                            }
                        }
                    }
                )
        ]

       set_sensitive {
            name  = "variables.secrets.DB_PASSWORD"
            value = (sensitive value)
        }
....
}
```
### Steps to Reproduce

1. `terraform apply`

**Comment by evgeni-sladkovski-cs** [comment]
I found this https://github.com/terraform-providers/terraform-provider-helm/pull/340 but it's still not merged, and similar issue https://github.com/terraform-providers/terraform-provider-helm/issues/333 is closed even though problem is still there.

**Comment by bjaworski3** [comment]
Any plans to get a change into a future release that would fix this? I've been using a custom built helm provider based off of https://github.com/terraform-providers/terraform-provider-helm/pull/340 but it would be great to have proper support for hiding secrets in the metadata.
