### ISSUE TITLE
Feature: Allow upgrading of already applied charts

### ISSUE THREAD

**Issue by MadOtis** [hashicorp/terraform-provider-helm#428]
Feature request to add a flag to the helm_release chart to allow overwriting existing artifacts if applied prior to migrating to Helm 3.  Previous `terraform apply` using the Helm 2 provider installed charts fail with migrated to Helm 3 capable terraform provider if they have been manually migrated using the helm 2to3 plugin.

### Terraform Version
terraform v0.12.20

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "datadog" {
  name          = "datadog"
  version       = "1.38.2"
  chart         = "stable/datadog"
  namespace     = kubernetes_namespace.datadog.metadata.0.name
  recreate_pods = true
  force_update  = true

  values = [<<YAML
image:
  repository: datadog/agent
  tag: 6.14.1-jmx
  pullPolicy: IfNotPresent
clusterAgent:
  containerName: cluster-agent
  image:
    repository: datadog/cluster-agent
    tag: 1.3.1
    pullPolicy: IfNotPresent
  enabled: true
  metricsProvider:
    enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi
datadog:
  apiKeyExistingSecret: datadog-api-key
  apmEnabled: true
  appKeyExistingSecret: datadog-app-key
  collectEvents: true
  env:
    - name: DD_APM_IGNORE_RESOURCES
      value: "GET /webjars/.*, GET /v2/api-docs, GET /swagger-resources, GET /actuator/health, GET /_health, GET /manifest"
    - name: DD_KUBELET_TLS_VERIFY
      value: "false"
    - name: DD_COLLECT_EC2_TAGS
      value: "true"
    - name: DD_CUSTOM_SENSITIVE_WORDS
      value: "authorization"
    - name: DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE
      value: "true"
  leaderElection: true
  logsConfigContainerCollectAll: true
  logsEnabled: true
  logLevel: INFO
  name: datadog
  nonLocalTraffic: true
  processAgentEnabled: true
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2Gi
  tags:
    - env:${var.environment}
    - cluster:<my_cluster>
  confd:
    disk.yaml: |-
        init_config:
        instances:
          - use_mount: true
            mount_point_whitelist:
              - /$
    vault.yaml: |-
        init_config:
        instances:
          - api_url: https://<some_vault_url>/v1
    istio.yaml: |-
        init_config:
        instances:
          - istio_mesh_endpoint: http://istio-telemetry.istio-system:42422/metrics
            mixer_endpoint: http://istio-telemetry.istio-system:15014/metrics
            galley_endpoint: http://istio-galley.istio-system:15014/metrics
            pilot_endpoint: http://istio-pilot.istio-system:15014/metrics
            citadel_endpoint: http://istio-citadel.istio-system:15014/metrics
            send_histograms_buckets: true
            send_monotonic_counter: true
  useCriSocketVolume: true
daemonset:
  enabled: true
  tolerations:
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: "NoExecute"
    - key: "node-role.kubernetes.io/etcd"
      operator: "Exists"
      effect: "NoExecute"
    - key: "node-role.kubernetes.io/<node_taint>"
      operator: "Exists"
      effect: "NoSchedule"
  useConfigMap: true
  customAgentConfig:
    listeners:
      - name: kubelet
    config_providers:
      - name: kubelet
        polling: true
    apm_config:
      enabled: false
      apm_non_local_traffic: true
    jmx_use_cgroup_memory_limit: true
    logs_config:
      open_files_limit: 500
  updateStrategy:
     type: RollingUpdate
  useHostPort: true
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  rbac:
    create: false
  serviceAccount:
    create: false
    name: "${kubernetes_service_account.kube-state-metrics.metadata.0.name}"
rbac:
  create: false
  serviceAccountName: "${kubernetes_service_account.datadog-cluster-agent.metadata.0.name}"
YAML
  ]

  lifecycle {
    ignore_changes = [
      keyring,
    ]
  }
}
```

### Expected Behavior
Helm 3 provider should apply the terraform

### Actual Behavior
Received error on "terraform apply" that existing resource could not be applied due to a name collision in ConfigMaps.

### Steps to Reproduce
1. `terraform apply using older Helm 2 provider` - results in successfully deployed datadog agent in cluster
2. Use Helm 3.x 2to3 plugin to migrate the Helm 2 in-place to Helm 3.
3. `terraform apply using latest Helm 3 provider` without altering any of the terraform.
4. receive the error that ConfigMaps already exist and cannot be overwritten.

### Work Around
1. `helm delete` already installed chart
2. `terraform apply` chart successfully
3. subsequent `terraform apply`s seem to work fine.

### Important Factoids
This only seems to affect charts applied with older terraform helm providers prior to 1.0.x and doesn't seem to affect new charts deployed with terraform after the upgrade to the latest 1.0.x provider.  New charts get applied properly; previously applied charts fail if they contain any ConfigMaps or Secrets that get created during the "helm" portion of the terraform apply.  The DO "terraform plan" successfully, but fail on "terraform apply".

**Comment by serjN** [comment]
I had the same problem and I have found workaround, before executing 2to3 plugin you need to upgrade Tiller to latest version (2.17)

**Comment by tushar-door** [comment]
Are there any official or informal guidelines on tiller-less helm v3 migration? I am interested to know if we upgrade to helm 3 under the hood, will the new terraform provider version >= 1.0.0 still destroy and re create or will see resources as existing and re-write state file?

**Comment by tushar-door** [comment]
@aareet : Is there a way to migrate already applied charts with older version (that uses Tiller) to new one. 

Is there a manual step like `terraform import` or new provider will just pick up the change done by helm2-3 plugin and modify state file accordingly?

**Comment by stobias123** [comment]
I implemented this as a new resource [here](https://github.com/stobias123/terraform-provider-helm/commit/b9f12ffa28afd9cbb3e7d3c1bfcf4fbfd4c75ed1).

Needs some better testing etc. But would love input from the repo owners to see if theres interest in merging into the provider.
