### ISSUE TITLE
Provider does not support "gs:" protocol for private repos

### ISSUE THREAD

**Issue by SubatomicHero** [hashicorp/terraform-provider-helm#430]
### Terraform Version
`terraform v0.12.20`

### Affected Resource(s)
- helm_repository

### Terraform Configuration Files
```hcl
variable "repo_name" {
  type = string
}

variable "repo_url" {
  type = string
}

data "helm_repository" "repo" {
  name = var.repo_name
  url  = var.repo_url
}

output "name" {
  value = data.helm_repository.repo.metadata[0].name
}

output "url" {
  value = data.helm_repository.repo.metadata[0].url
}
```

```hcl
module "beta_repo" {
  source = "./helm/repositories"
  repo_name = "some_private_name"
  repo_url = "gs://{REDACTED}"
}
```
### Debug Output
https://gist.github.com/SubatomicHero/20e7c969c92ccd3bc9f6c69f066ac0e2

### Expected Behavior
The scheme should be recognised, and depend on the underlying OS to provide plugin support

### Actual Behavior
Terraform/Provider refused to proceed

### Steps to Reproduce
1. `terraform apply`

**Comment by SubatomicHero** [comment]
Any response to this??

**Comment by moein** [comment]
In my company we wanted to start moving to helm3 but we can't since we use terraform to install the charts and for some reason with the new version of this provider we can not use gs protocol.
Any reason the behaviour was changed after upgrading to helm3 upgrade?

**Comment by vipulagarwal** [comment]
This feature will be very helpful for us to create opinionated GKE clusters with default deployments on them.

**Comment by Jenishk56** [comment]
@jrhouston Just wondering, If there is any update on this enhancement. This is really very important for few essential deployments needed on top of kubernetes cluster.
