### ISSUE TITLE
Documentation formatting incorrect

### ISSUE THREAD

**Issue by aaronmell** [hashicorp/terraform-provider-helm#432]
The documentation in https://www.terraform.io/docs/providers/helm/index.html is messed up. The settings after debug are not on separate lines

**Comment by jrhouston** [comment]
Thanks @aaronmell, this is resolved [here](https://github.com/terraform-providers/terraform-provider-helm/commit/6fdfab7f3ddfb17a748a11060cbe7d4db312ff56). The website will get updated when we do the next release (soon).
