### ISSUE TITLE
Helm connects to wrong cluster

### ISSUE THREAD

**Issue by piizei** [hashicorp/terraform-provider-helm#434]
### Terraform Version

0.12.21

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Expected Behavior

Helm should connect to Kubernetes cluster that is being provisioned by terraform

### Actual Behavior

Helm connects to cluster that has been last accessed (from kubectl config)

### Steps to Reproduce

1. Get credentials of any cluster
2. Provision a  new Kubernetes cluster with terraform and try to do helm release
3. Helm releases to the cluster of step 1.

**Comment by jrhouston** [comment]
Thanks for opening this @piizei. Could you share more details about how your provider block is set up?

**Comment by piizei** [comment]
Simply
provider "helm" {}
as the client certs were removed on 1.0.0 release.

**Comment by relu** [comment]
This is actually the intended behaviour. You need to explicitly configure the provider to connect to your terraform provisioned cluster. It has no way of knowing which cluster you want to connect to (what if you provision multiple clusters in the same terraform module?). See [here for details](https://www.terraform.io/docs/providers/helm/index.html#statically-defined-credentials).
And here's an example using an EKS provisioned cluster (also note the `load_config_file` attribute):

```hcl

resource "aws_eks_cluster" "cluster" {
  ...
}

data "aws_eks_cluster_auth" "auth" {
  name = aws_eks_cluster.cluster.name
}

provider "helm" {
  kubernetes {
    host                   = aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(aws_eks_cluster.cluster.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.auth.token
    load_config_file       = false
  }
}
```

**Comment by piizei** [comment]
@relu thanks for clarifying. It was bit unclear from documentation that mainly references the obsolete client creds. The example is very helpful!
