### ISSUE TITLE
How can a JSON file's content be passed as a value to helm?

### ISSUE THREAD

**Issue by sbstp** [hashicorp/terraform-provider-helm#435]
I want to deploy the `external-dns` chart in my repository. It has a value named `google.serviceAccountKey` which is a JSON document that contains the information for external-dns to contact google's DNS.

I'm trying to pass the value to the chart using something like:
```
data "local_file" "external-dns-credentials" {
  filename = "${path.root}/google_credentials.json"
}

...

  set {
    name  = "google.serviceAccountKey"
    value = <<EOF
${data.local_file.external-dns-credentials.content}
EOF
  }

```

However I keep getting errors during the apply phase of the terraform,
```
Error: failed parsing key "google.serviceAccountKey" with value {
  "type": "service_account",
  ...
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "..."
}

, key "\n\n" has no value
```

How can I pass a JSON document as a string to helm values?

**Comment by jrhouston** [comment]
Thanks for opening this issue @sbstp.

It looks like it doesn't like the newlines in the JSON. 

A workaround I found for this was to decode then re-encode the contents of the file:

```hcl
set  {
   name = "key"
   value = jsonencode(jsondecode(file("file.json")))
}
```

I suspect this is happening [here](https://github.com/terraform-providers/terraform-provider-helm/blob/master/helm/resource_release.go#L665) where we're making an assumption that the value is not going to have any newlines in it before trying to marshal into a `values.yaml`.

**Comment by sbstp** [comment]
I tried what you suggested but I'm getting another kind of error now.

```
Error: rpc error: code = Unknown desc = render error in "external-dns/templates/secret.yaml": template: external-dns/templates/secret.yaml:19:58: executing "external-dns/templates/secret.yaml" at <b64enc>: wrong type for value; expected string; got []interface {}

  on apps/external-dns.tf line 5, in resource "helm_release" "external_dns":
   5: resource "helm_release" "external_dns" {
```

The secret template expects the JSON to be a string because it shoves it in a base64 encoder for the secret.

**Comment by sbstp** [comment]
I found a work around in the meantime by creating the secret myself

**Comment by ttauveron** [comment]
I had exactly the same issue as @sbstp, solved it like this : 
```hcl
values = [
    "google.serviceAccountKey: ${base64decode(google_service_account_key.external-dns.private_key)}"
  ]
```

**Comment by aareet** [comment]
@sbstp seems this issue is now resolved. I'll close it, but please reopen if this is not the case.
