### ISSUE TITLE
data helm_repository requires helm repo update

### ISSUE THREAD

**Issue by mllu** [hashicorp/terraform-provider-helm#438]
### Terraform Version

Terraform v0.12.23

### Affected Resource(s)

helm_repository

### Terraform Configuration Files

```
data "helm_repository" "my_repo" {
  name = "$MY_REPO_NAME"
  url  = "https://$MY_REPO_CHART.com"
}

resource "helm_release" "my_release" {
  name       = "my-release"
  repository = data.helm_repository.my_repo.metadata[0].name
  chart      = "$MY_CHART_NAME"
  ...
  depends_on = [
    data.helm_repository.my_repo,
  ]
}
```

### Debug Output

```
Terraform v0.12.23
Initializing plugins and modules...
2020/03/12 01:01:26 [DEBUG] Using modified User-Agent: Terraform/0.12.23 TFC/1fc524aa9c
helm_release.my_release: Modifying... [id=my-release]

Error: failed to download "$MY_REPO_NAME/$MY_CHART_NAME" (hint: running `helm repo update` may help)
```

### Expected Behavior

helm_repository data resource should help download required charts

### Actual Behavior

The corresponding `terrafoom apply` on Terraform cloud showed the above error message asking to run `helm repo update`

**Comment by busbyjon** [comment]
+1 also seeing this issue

**Comment by kevincheema** [comment]
+1 also seeing this as well

**Comment by mllu** [comment]
I kinda work around by appending uuid after the name value of helm_repository, but the side effect is it get updated every time.

**Comment by jrhouston** [comment]
I suspect this is the same issue as https://github.com/terraform-providers/terraform-provider-helm/issues/416

**Comment by miguel-chacon** [comment]
Replacing `data.helm_repository.my_repo.metadata[0].name` by `data.helm_repository.my_repo.metadata[0].url` works

**Comment by nagonzalez** [comment]
I'm ditching the `data helm_repository` altogether and just hardcoding the chart info. See below:

```
# install kube2iam helm chart
resource "helm_release" "kube2iam" {

  repository = "https://kubernetes-charts.storage.googleapis.com"
  chart      = "kube2iam"
  version    = var.eks_addon_kube2iam_helm_version
  name       = "kube2iam"
  namespace  = "kube-system"

  values = [
    <<EOT
extraArgs:
  auto-discover-base-arn: ''
  default-role: ${module.iam_assumable_role_default.this_iam_role_name}
host:
  iptables: true
  interface: eni+
rbac:
  create: true
verbose: true
EOT
  ]
}
```

**Comment by timmjd** [comment]
Thanks for the hint!
Taking the `URL` for the repository seems to work only if you also apply the `version`.

If version is missing:
```
Error: failed to download "https://kubernetes-charts.storage.googleapis.com/jenkins-1.9.24.tgz" (hint: running `helm repo update` may help)

  on .terraform/modules/jenkins/main.tf line 13, in resource "helm_release" "helm":
  13: resource "helm_release" "helm" {
```

The root of the issue seems to be:
* The `data "helm_repository"` is triggering the download of the chart.
* If you use this data as input for the `resource "helm_release"` this will lead to an error if you simply follow the [example](https://www.terraform.io/docs/providers/helm/r/release.html):
  * If you make use of `terraform plan -out out.plan` copy the `out.plan` to a different machine and do trigger the `terraform apply out.plan` there.

Doing so will lead to the error:
```
Error: failed to download "stable/jenkins" (hint: running `helm repo update` may help)

  on .terraform/modules/jenkins/main.tf line 18, in resource "helm_release" "helm":
  18: resource "helm_release" "helm" {
```

So the requirement to checkout the chart is part of the `terraform plan` and the dependency to checkout is not stored within the outputted plan `out.plan`.

**Comment by MajorBreakfast** [comment]
We're running into this issue as well. We have exactly a setup as @timmjd describes: In our case we're running GitLab. We have a plan and an apply ci job and they both run in Docker containers. The plan job generates the plan which is then passed as an artifact to the apply job. Then, the apply job fails applying it with an error like above.

**Comment by Bluesboy** [comment]
As a workaround I defined URL to chart in the **chart** field like that:
```
resource "helm_release" "external_dns" {
  name       = "dns-bot"
  chart      = "https://kubernetes-charts.storage.googleapis.com/external-dns-2.14.1.tgz"
  namespace  = "kube-system"
  values = [
    "${file("external-dns/values.yaml")}"
  ]
}
```
Everything works fine. However I use terraform-0.12.24. Hope it helps.

**Comment by mbarrien** [comment]
Note that in #466 the helm_repository data source has been deprecated, with the new recommended way is putting the repo URL directly in as the "repository" field of the helm_release.

**Comment by MajorBreakfast** [comment]
With the docs now clearly saying that the repo data source is deprecated and the example on the helm_release page updated without it, I think this issue can be closed.

**Comment by mllu** [comment]
sounds good to me, will close this issue.

**Comment by tcoates1362** [comment]
Posting this in case someone else lands here looking for answers.

I was still having issues after removing the data source and converting to using the repo url in the "repository" field.

Example:
```
resource "helm_release" "gitlab" {
  name = "gitlab"
  repository = "https://charts.gitlab.io"
  chart = "gitlab"
  version = "3.3.3"
  namespace = "gitlab"
...
}
```

would yield:
```
helm_release.gitlab: Creating...

Error: failed to download "https://gitlab-charts.s3.amazonaws.com/gitlab-3.3.3.tgz" (hint: running `helm repo update` may help)

  on tf\gitlab.tf line 60, in resource "helm_release" "gitlab":
  60: resource "helm_release" "gitlab" {
```

I ended up clearing out my helm cache which resolved the issue. Apparently if you've installed the chart prior to converting, there are some remnants left that cause issues.
