### ISSUE TITLE
Wait for all resources before declaring successful completion

### ISSUE THREAD

**Issue by thedrow** [hashicorp/terraform-provider-helm#44]
When I deploy to production I usually use `helm install <myrelease> --wait --timeout <reasonable timeout for deployment>`.
This provider does not provide those options as of yet.
I think that providing those options will improve UX.

**Comment by sagikazarmark** [comment]
There is a timeout option: https://github.com/mcuadros/terraform-provider-helm/blob/master/helm/resource_release.go#L107

Also, wait looks like to be hard coded with true value: https://github.com/mcuadros/terraform-provider-helm/blob/master/helm/resource_release.go#L267

**Comment by mcuadros** [comment]
Exactly the wait, isn't optional because Terraform should always wait until everything is setup and running. 
As documented (https://github.com/mcuadros/terraform-provider-helm/blob/master/docs/release.md), the timeout option is supported.

Thanks @sagikazarmark
