### ISSUE TITLE
Helm provider in version 1.0.0 is not able to install chart.

### ISSUE THREAD

**Issue by hetii** [hashicorp/terraform-provider-helm#441]
I heve provider configured like:

    provider "helm" {
      version = "1.0.0"
      kubernetes {
        host                   = yamldecode(var.kube_config)["clusters"][0]["cluster"]["server"]
        token                  = yamldecode(var.kube_config)["users"][0]["user"]["token"]
        cluster_ca_certificate = base64decode(yamldecode(var.kube_config)["clusters"][0]["cluster"]["certificate-authority-data"])
        load_config_file       = false
      }
    }

and the resources like:

    data "helm_repository" "stable" {
      name = "stable"
      url  = "https://kubernetes-charts.storage.googleapis.com"
    }

    resource "helm_release" "metallb" {
      name       = "metallb"
      repository = data.helm_repository.stable.name
      # chart           = "stable/metallb"
      chart     = "metallb"
      namespace = "metallb-system"
      timeout   = 600
      verify    = false
      wait      = false
    }

when verify = false terraform apply produce:

	module.k8s-test01-postinstall.helm_release.metallb: Creating...
	module.k8s-test01-postinstall.helm_release.metallb: Still creating... [10s elapsed]
	module.k8s-test01-postinstall.helm_release.metallb: Creation complete after 12s [id=metallb]

	Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

But none of resources is created on my cluster:

when verify = true terraform apply produce:

	module.k8s-test01-postinstall.data.helm_repository.stable: Refreshing state...
	module.k8s-test01-postinstall.helm_release.metallb: Refreshing state... [id=metallb]

	An execution plan has been generated and is shown below.
	Resource actions are indicated with the following symbols:
	  + create

	Terraform will perform the following actions:

	  # module.k8s-test01-postinstall.helm_release.metallb will be created
	  + resource "helm_release" "metallb" {
	      + atomic                = false
	      + chart                 = "metallb"
	      + cleanup_on_fail       = true
	      + dependency_update     = false
	      + disable_crd_hooks     = false
	      + disable_webhooks      = false
	      + force_update          = false
	      + id                    = (known after apply)
	      + keyring               = "/home/dev/.gnupg/pubring.gpg"
	      + max_history           = 0
	      + metadata              = (known after apply)
	      + name                  = "metallb"
	      + namespace             = "metallb-system"
	      + recreate_pods         = false
	      + render_subchart_notes = true
	      + replace               = false
	      + repository            = "stable"
	      + reset_values          = false
	      + reuse_values          = false
	      + skip_crds             = false
	      + status                = "deployed"
	      + timeout               = 600
	      + verify                = true
	      + version               = (known after apply)
	      + wait                  = true
	    }

	Plan: 1 to add, 0 to change, 0 to destroy.

	Do you want to perform these actions?
	  Terraform will perform the actions described above.
	  Only 'yes' will be accepted to approve.

	  Enter a value: yes

	module.k8s-test01-postinstall.helm_release.metallb: Creating...

	Error: failed to download "stable/metallb" (hint: running `helm repo update` may help)

**Comment by jrhouston** [comment]
Thanks for opening this @hetii. Does the `metallb-system` namespace already exist on your cluster? There's currently a bug that causes the release to fail silently if the namespace does not already exist. A fix for this will be in the next release.

**Comment by hetii** [comment]
No, I don't have it. So now I add this namespace manually.
Now when verify = true is set then still get error:

    Error: failed to download "stable/metallb" (hint: running `helm repo update` may help)

but when `verify = true` is purged out by commenting it, so I believe it's false by default,
my chart is provisioned fine, so maybe we have here a second bug regarding verify flag.

Regards.

**Comment by jrhouston** [comment]
When I try to install that chart just using `helm` with `--verify` I encounter the same problem:

```zsh
~/d/h/t/example ❯❯❯ helm version                                                                                                                
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.14"}
~/d/h/t/example ❯❯❯ helm repo add stable https://kubernetes-charts.storage.googleapis.com                                                       
"stable" has been added to your repositories
~/d/h/t/example ❯❯❯ helm install metallb stable/metallb --verify                                                                                
Error: failed to download "stable/metallb" (hint: running `helm repo update` may help)
~/d/h/t/example ❯❯❯ helm repo update                                                                                                        
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
~/d/h/t/example ❯❯❯ helm install metallb stable/metallb --verify
Error: failed to download "stable/metallb" (hint: running `helm repo update` may help)
```

It works without `--verify` so this could be a problem with the chart, or helm itself.

**Comment by whitefirer** [comment]
Hey gus, I have the same problem yesterday, but it seems sloved.

First,  I user the terraform with the kuberneters plugin of vscode, and disappered the same probelm.
And then, I found the heml vesrsion is diffrent with other terminal.the kuberneters plugin of vscode give a helm 3.0.2 and the system helm is 3.1.2.
So I replace the helm of vscode, nothing better.
And I do the `helm repo update` for the system helm and  remove the " verify = true".
Finally do the `terraform apply` again.

It works!

**Comment by aareet** [comment]
@hetii please let us know if this is still reproducible for you.

**Comment by asafhm** [comment]
@aareet I can confirm the problem still exists with provider version 1.2.3

**Comment by aareet** [comment]
@NightmareCinema does the chart apply successfully when applied directly with helm and the `--verify` option?

**Comment by aareet** [comment]
Closing since it has been a month - please reopen if this is still an issue.
