### ISSUE TITLE
Support chart diffs

### ISSUE THREAD

**Issue by dippynark** [hashicorp/terraform-provider-helm#444]
Currently if I apply a Helm provider chart and delete one of the created Kubernetes resources manually using `kubectl`, the provider does not notice the change on the next apply. Since this functionality does not seem to be in Helm, I can see why it isn't in the provider, but if it were to be supported it would be very powerful in terms of verifying a cluster is in the expected state. I suspect it could be implemented in the same way as [`kubectl diff`](https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/#kubectl-diff).

Is this functionality something which would fit in this provider?

### Terraform Version
v0.12.20

### Affected Resource(s)
- helm_release

### Terraform Configuration Files

Any example would work, from the README:
```hcl
resource "helm_release" "my_database" {
    name      = "my-database"
    chart     = "stable/mariadb"

    set {
        name  = "mariadbUser"
        value = "foo"
    }

    set {
        name = "mariadbPassword"
        value = "qux"
    }

    set_string {
        name = "image.tags"
        value = "registry\\.io/terraform-provider-helm\\,example\\.io/terraform-provider-helm"
    }
}
```

### Expected Behavior
Provider should notice a change and recreate the deleted resource (maybe by upgrading the chart)

### Actual Behavior
Resource is not recreated

### Steps to Reproduce
1. `terraform apply`
2. `kubectl delete statefulset my-database-mariadb-slave`
3. `terraform apply`

**Comment by aristosvo** [comment]
That would be awesome! Have you seen https://github.com/databus23/helm-diff?

**Comment by jrhouston** [comment]
Thanks for opening this @dippynark. 

This is an interesting idea, but I suspect we will end up re-inventing the kubernetes provider so that we can store and render diffs for the individual kubernetes resources in the chart. 

If this is the degree of granularity you're looking for in your terraform diff, then it might be better to use the kubernetes provider and package things into terraform modules rather than using helm charts at all. Though, I will concede that at the moment this is not possible for certain use-cases like CRDs, but will be soon.

That being said, if this sort of functionality becomes part of helm's core and gets exposed through its package then we would certainly want to support it in this provider.

**Comment by dippynark** [comment]
@jrhouston makes sense - have floated a PR linked above that returns a different status if resources are missing on a dry-run upgrade. This should allow a dry-run upgrade to be run when reading to determine if action is required. This won't calculate diffs but it would add quite a lot I think.

@aristosvo I hadn't, but looks pretty powerful when doing things non-programatically.

**Comment by dippynark** [comment]
Thinking again, the Helm release contains the rendered manifests as part of a release which the provider already has access to: https://github.com/helm/helm/blob/master/pkg/release/release.go#L33

So assuming that string stays constant, its hash could be stored as part of the state and compared. If it does not stay constant (for example Helm is randomly generating something on each run) a new field could tell the provider to ignore manifest diffs so it wouldn't keep trying to apply.

So the logic could be:
- on read, if release exists, dry-run update
- if manifest comparison is not disabled, check dry-run hash against terraform state hash
- if manifest hashes are not equal, there has been a client-side change to the chart, so trigger update
- if manifest hashes are equal, check release status
- if release status indicates resources are missing (implemented in linked PR), trigger update

This would not help with server-side diffs still but I believe it would handle server side deletes and all client side chart changes.

**Comment by aareet** [comment]
Depends on resolution of https://github.com/terraform-providers/terraform-provider-helm/issues/305

**Comment by jrhouston** [comment]
Closing as this was added as an experimental feature in v2.1.0.
