### ISSUE TITLE
"heal_release" work unstable with error "Kubernetes cluster unreachable" sometime

### ISSUE THREAD

**Issue by lmgnid** [hashicorp/terraform-provider-helm#445]
Hello, my code most time work but some time will fail with this kind of error:
"helm_release.xxxxxx": Kubernetes cluster unreachable

Terraform: 0.11.14

`provider "helm" {
  version = "1.0"
  alias = "default"
  kubernetes {
    host                   = "${aws_eks_cluster.eks-cluster.endpoint}"
    cluster_ca_certificate = "${base64decode(aws_eks_cluster.eks-cluster.certificate_authority.0.data)}"
    token                  = "${data.aws_eks_cluster_auth.eks-cluster.token}"
    load_config_file       = false
  }
}

resource "helm_release" "nginx-controller" {
  provider = "helm.default"
  name       = "nginx-controller"
  chart      = "${path.module}/charts/nginx-controller"
  force_update = true
  atomic     = true
  timeout    = 1200

...

  depends_on = ["aws_eks_node_group.eks-node-group"]

}`

BTW: When this happens, a rerun will pass.
Cannot find how to get debug logs and also curious if any retry logic in the helm provider?
Or something wrong in my codes?

**Comment by lmgnid** [comment]
FYI: After remove "atomic = true", seems solved. Didn't get why.

**Comment by aareet** [comment]
@lmgnid you can view debug logs as shown here: https://www.terraform.io/docs/internals/debugging.html if that helps

**Comment by alexsomesan** [comment]
no response on request for details - closing
