### ISSUE TITLE
Helm 1.0.0 don't provision gitlab runner when upper case letter are used in name of helm_release resource.

### ISSUE THREAD

**Issue by hetii** [hashicorp/terraform-provider-helm#446]
Hi.

I use below code to deploy gitlab runners.

    data "helm_repository" "gitlab" {
      name = "gitlab"
      url  = "https://charts.gitlab.io"
    }

    resource "rancher2_namespace" "gitlab" {
      name             = "gitlab"
      description      = "Gitlab namespace"
      project_id       = rancher2_cluster.cluster.default_project_id
      wait_for_cluster = true
      timeouts {
        create = "30m"
        delete = "30m"
      }
    }

    resource "helm_release" "gitlab_runner" {
      for_each = { for s in var.gitlab_tokens : substr(s, 0, 5) => s }
      # NOTE: From some unknow reason for me the name must be always lowercase.
      # If not then this resource is not deployed even when terrafrom claim it is :!
      name       = lower(format("tf-%s", each.key))
      chart      = "gitlab-runner"
      namespace  = rancher2_namespace.gitlab.name
      repository = data.helm_repository.gitlab.name
      timeout    = 600
      wait       = true
      # verify     = true
      depends_on = [
        rancher2_namespace.gitlab
      ]
      set {
        name  = "gitlabUrl"
        value = var.gitlab_url
      }
      set {
        name  = "runnerRegistrationToken"
        value = each.value
      }
      set {
        name  = "runners.tags"
        value = format("k8s\\,kubernetes\\,%s", var.cluster_name)
      }
    }

I notice when name property of helm_release contains some upper case letters then terraform don't create such resource.
There are no errors and he claim that resource is created what is not true. 
Wrapping value by lower() function solve the problem, but still it's something that should be investigated.

**Comment by legal90** [comment]
I'm pretty sure it was fixed recently by https://github.com/terraform-providers/terraform-provider-helm/pull/406. But there is no released version with this fix yet.

@jrhouston Do you have any estimations for releasing the next provider version?

**Comment by jrhouston** [comment]
Yes, this issue should be resolved by the fix @legal90 mentioned. 

The release will happen this week. 😄

**Comment by aareet** [comment]
The fix for this should have been released - please comment if you are able to reproduce with the latest version.
