### ISSUE TITLE
Helm provider 1.1 constantly updating helm_release

### ISSUE THREAD

**Issue by 23doors** [hashicorp/terraform-provider-helm#448]
# Terraform Version
0.12.24

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "cert_manager" {
  name      = "cert-manager"
  chart     = "jetstack/cert-manager"
  namespace = kubernetes_namespace.cert_manager.id
  version   = "v0.13.0"
```

### Expected Behavior
No changes after chart has been applied.

### Actual Behavior
Every time chart is read as `cert-manager`. Same for `stable/*` charts.
This only happens in newly released 1.1 version.

```
  # helm_release.cert_manager will be updated in-place
  ~ resource "helm_release" "cert_manager" {
        atomic                     = false
      ~ chart                      = "cert-manager" -> "jetstack/cert-manager"
```

**Comment by 23doors** [comment]
Temporary fix (not really that ideal) is to add:
```
  lifecycle {
    ignore_changes = [chart]
  }
```

**Comment by legal90** [comment]
It seems that at some point this provider stopped supporting the chart reference in the format `<repo>/<chart>`. Try using a separate `repository` argument instead:

```hcl
resource "helm_release" "cert_manager" {
  name      = "cert-manager"
  namespace = kubernetes_namespace.cert_manager.id

  repository = "https://charts.jetstack.io"
  chart      = "cert-manager"
  version    = "v0.13.0"
  #...
```

**Comment by jrhouston** [comment]
Thanks for opening this @23doors . Looks like we've accidentally introduced this [here](https://github.com/terraform-providers/terraform-provider-helm/pull/394/files#diff-70e42ed4d5009a76bddc6fb6c16b913bR628) when we added the import feature.

The fix here is to move the setting of the chart name to the import function itself, as the repository that the chart came from gets lost in the metadata helm actually stores. I think we do still want to support this format, but I suspect the best practise here is to set the `repository` attribute explicitly. We should also add a test for this format, as we weren't actually covering this in our acceptance tests.

**Comment by 23doors** [comment]
Thanks, setting repository explicitly is a good enough fix for me for now!
