### ISSUE TITLE
Using raw yaml values results in parsing error

### ISSUE THREAD

**Issue by IBMRob** [hashicorp/terraform-provider-helm#45]
We are hitting a bug with the values parameter which is blocking us supply a values.yaml file for a helm chart. The charts we have used are quite large but it appear someone else has already provided a simple re-create in one of the pull request discussions - https://github.com/mcuadros/terraform-provider-helm/pull/15#issuecomment-325701798

### Terraform Version
Terraform v0.11.1

### Affected Resource(s)
helm provider

### Terraform Configuration Files
```hcl
resource "helm_release" "kube-prometheus" {
  count = "${var.prometheusDashboard}"
  name      = "kube-prometheus"
  chart     = "coreos/kube-prometheus"
  namespace = "monitoring"
  recreate_pods = "true"
  raw_values = "kube-prometheus-values.yaml"
  depends_on = ["helm_repository.coreos"]
}
```

values.yaml
```
hub:
  cookieSecret: "blah"
token:
  proxy: "blah"
singleuser:
  image:
    name: us.gcr.io/blah/blah
    tag: v2.2
```

Using the same files using the helm cli works fine.

Our yaml is built off a much more complex document - based on https://raw.githubusercontent.com/coreos/prometheus-operator/master/helm/prometheus/values.yaml

### Expected Behavior
What should have happened?

Helm chart should deploy.

### Actual Behavior
Error: Error applying plan:
``
1 error(s) occurred:

* helm_release.kube-prometheus: 1 error(s) occurred:

* helm_release.kube-prometheus: error unmarshaling JSON: json: cannot unmarshal string into Go value of type map[string]interface {}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by burdiyan** [comment]
@IBMRob you need to pass raw string of the yaml itself, not path to a file. Like this:

```
raw_values = "${file("kube-prometheus-values.yaml")}"
```
