### ISSUE TITLE
error validating "": error validating data: unknown object type "nil"

### ISSUE THREAD

**Issue by Wiston999** [hashicorp/terraform-provider-helm#451]
### Terraform Version

```
Terraform v0.12.23
+ provider.azuread v0.8.0
+ provider.azurerm v2.0.0
+ provider.helm v1.1.0
+ provider.kubernetes v1.11.1
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Expected Behavior
Setting `null` value for a given key should remove that key from rendered template, as documented in https://helm.sh/docs/chart_template_guide/values_files/ ("Deleting a default key" section)

### Actual Behavior
Setting `null` value for a given key in both `values` array or `set` block fails with error
```error validating "": error validating data: unknown object type "nil"```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running in AKS

**Comment by Dids** [comment]
This is still an issue and very relevant, imo.

There are numerous cases where you would want to remove a default value from a Helm deployment, instead of simply changing it, such as when the default value is `ClusterIP: ""` and you want to remove this restriction.
