### ISSUE TITLE
helm_release changes always with local charts

### ISSUE THREAD

**Issue by PSanetra** [hashicorp/terraform-provider-helm#452]
# Terraform Version
0.12.24

### Affected Resource
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "my-release" {
  name = "my-release"
  chart = "${path.module}/my-chart-directory"
  version = "0.1.0"

  namespace = "default"
}
```

### Expected Behavior
1. The state of the "my_release" resource should contain a chart property with a value like `./my-chart-directory`.
2. When I create a new plan it should show `./my-chart-directory` as value for the chart property and not try to update that property.

### Actual Behavior
0. The initial plan shows the correct chart value
```
  # helm_release.my-release will be created
  + resource "helm_release" "my-release" {
      + chart                      = "./my-chart-directory"
      [...]
    }
```
1. The state of the "my_release" resource contains a chart property with a value like `my-chart` (which is the actual chart name).
```json
{
  [...]
  "resources": [
    {
      "mode": "managed",
      "type": "helm_release",
      "name": "my-release",
      "provider": "provider.helm",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "chart": "my-chart",
            [...]
          }
        }
      ]
    }
  ]
}
```
2. When I create a new plan the provider wants to update the chart property again
```
 # helm_release.my-release will be updated in-place
  ~ resource "helm_release" "my-release" {
      ~ chart                      = "my-chart" -> "./my-chart-directory"
        [...]
    }
```

I can not ignore the chart property as a workaround as the provider would try to find a `my-chart` chart in its repositories during the next update.

**Comment by mhulscher** [comment]
I have the same issue since I upgraded to v1.1.0 of this helm provider.

**Comment by jrhouston** [comment]
Looks like this is the same issue as https://github.com/terraform-providers/terraform-provider-helm/issues/448. The [fix](https://github.com/terraform-providers/terraform-provider-helm/commit/8ecdf8a6f5d33e56a12070f00ad11452978b4910) for this has been merged.

**Comment by PSanetra** [comment]
@jrhouston yes, I guess that patch will fix this issue, too.
