### ISSUE TITLE
support scheme acr  in helm_repository

### ISSUE THREAD

**Issue by liuyangc3** [hashicorp/terraform-provider-helm#457]
I am using this plugin https://github.com/AliyunContainerService/helm-acr in terraform helm, 

### Terraform Version
Terraform v0.12.24

### Affected Resource(s)

- helm_repository

### Terraform Configuration Files
```hcl
data "helm_repository" "alicloud" {
  name = "alicloud"
  url  = "acr://my_alicloud_repo"
  username = var.HELM_REPO_USERNAME
  password = var.HELM_REPO_PASSWORD
}
```

### Debug Output
```shell
terr apply

data.helm_repository.alicloud: Refreshing state...
Error: plugin "bin/helmpush" exited with error

  on helm.tf line 1, in data "helm_repository" "alicloud":
  1: data "helm_repository" "alicloud" {
```

### Important Factoids
this plugin requires environment HELM_REPO_PASSWORD and HELM_REPO_USERNAME be set up even if use `username` and `password` in helm_repository .

### References

- https://github.com/AliyunContainerService/helm-acr/issues/10

**Comment by aareet** [comment]
@liuyangc3 can you clarify what behaviour you expect here? Also please run the apply with TF_LOG set to TRACE and share the log with us.

https://www.terraform.io/docs/internals/debugging.html

**Comment by aareet** [comment]
Closing since this has not received a response in 21 days. Please reopen if this is still an issue.
