### ISSUE TITLE
failed to create: namespaces "my-release" not found

### ISSUE THREAD

**Issue by Goodsmileduck** [hashicorp/terraform-provider-helm#468]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

v0.11.14
### Provider Version
v1.1.1
### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```
resource "helm_release" "my-release" {
  name       = "my-release"
  repository = "${var.repository}"
  chart      = "${var.chart_name}"
  version    = "${var.chart_version}"
  namespace  = "my-release"
  values     = [ "${data.template_file.values.rendered}" ]
  force_update = "false"
}

```

### Expected Behavior

Create namespace and deploy helm release
### Actual Behavior

Fails with 
```
helm_release.my-release: create: failed to create: namespaces "my-release" not found
```

### Steps to Reproduce

1. `terraform apply`

### References

- GH-1234

**Comment by legal90** [comment]
@Goodsmileduck The namespace creation is out of the provider's scope.
Unlike Helm 2, Helm 3 does not create the namespace.

See the discussion: https://github.com/terraform-providers/terraform-provider-helm/issues/399

**Comment by Goodsmileduck** [comment]
@legal90 ah, I was thinking https://github.com/helm/helm/pull/7648 already released. Thanks anyway
