### ISSUE TITLE
Upgrade to 3.2.0 (security issue)

### ISSUE THREAD

**Issue by aristosvo** [hashicorp/terraform-provider-helm#478]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently helm v3.1.1 is being used, and an issue is found which affects the security of v3.0.0-v3.1.2.

Latest version is v3.2.0

### References

Security Issue: https://github.com/helm/helm/security/advisories/GHSA-q8q8-93cv-v6h8

**Comment by aristosvo** [comment]
Awesome, @relu is already busy implementing v3.2.0: https://github.com/terraform-providers/terraform-provider-helm/pull/477 👏

**Comment by aareet** [comment]
Merged in #477
