### ISSUE TITLE
Upgrade Helm 2 Version

### ISSUE THREAD

**Issue by buremba** [hashicorp/terraform-provider-helm#481]
### Terraform Version and Provider Version
Terraform v0.12.21
+ provider.helm v0.10.4
+ provider.kubernetes v1.10.0

The version v0.10.4 uses Helm 2.15.1 but it's broken because of this error: https://github.com/helm/helm/issues/6361

Is it possible to update the Helm version to 2.16.3 as it resolves the issue?

**Comment by djsly** [comment]
2.16.6 brings in a annoying fix about Configmal and Secret not being handled properly. 

https://github.com/helm/helm/issues/6031

**Comment by dak1n1** [comment]
We did a release today that upgraded helm to version 2.16.8 https://github.com/hashicorp/terraform-provider-helm/releases
