### ISSUE TITLE
metadata field in plan exposes sensitive values

### ISSUE THREAD

**Issue by etwillbefine** [hashicorp/terraform-provider-helm#485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform 0.12.24
Helm 1.1.1

### Affected Resource(s)

- helm_repository

### Terraform Configuration Files
```hcl
resource "helm_release" "my_release" {
    ...
    dynamic "set_sensitive" {
        content {
            name = "a-secret"
            value = "secret"
        }
    }
}
```

### Expected Behavior
Secrets injected via `set_sensitive` are always hidden in plans as per https://github.com/terraform-providers/terraform-provider-helm/issues/80

### Actual Behavior
`terraform plan` produces a field `metadata` which contains all helm values including plain secrets

```
  # module.release.helm_release.my_release will be updated in-place
  ~ resource "helm_release" "my_release" {
        ...
        metadata                   = [
            {
                ...
                values    = jsonencode(
                    {
                        a-secret = "plain visible value"
                    }
                )
            }
        ]
        set_sensitive {
            name = "a-secret"
            value = (sensitive value) 
        }
    }
```
   
### Steps to Reproduce

1. Create a resource `helm_release`
2. Set a value using `set_sensitive`
3. Apply plan
4. Plan again and see `metadata` field diff 

### Important Factoids
Using `dynamic` to attach the sensitive value

**Comment by aareet** [comment]
I believe this should be fixed by https://github.com/terraform-providers/terraform-provider-helm/pull/480 in the next release

**Comment by etwillbefine** [comment]
Sorry forgot to lookup closed issues. Looks like this is fixed in the next release, thanks. 👍
