### ISSUE TITLE
Chart.yaml: apiVersion is required. The value must be either "v1" or "v2"

### ISSUE THREAD

**Issue by shd4** [hashicorp/terraform-provider-helm#492]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.12.24
### Provider Version
+ provider.google v3.20.0
+ provider.helm v1.2.1
+ provider.kubernetes v1.11.2
### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl

resource "helm_release" "nginx_ingress" {
  name            = "nginx-ingress"
  chart           = "nginx-ingress"
  repository      =  "https://kubernetes-charts.storage.googleapis.com"
  version         = "0.30.0"
}
```

### Expected Behavior

Run the plan with no errors.

### Actual Behavior

```
------------------------------------------------------------------------

Error: malformed chart or values: 
        Chart.yaml: apiVersion is required. The value must be either "v1" or "v2"

  on ingress-controllers.tf line 1, in resource "helm_release" "nginx_ingress":
   1: resource "helm_release" "nginx_ingress" {
```
### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This works on provider v1.1.1,  but not in v1.2.0 or v1.2.1

**Comment by red8888** [comment]
kind of surprised this hasn't seen more traction. I'm getting the same issue.  v1.1.1 does work for me.

Have the last 2 versions of this provider seriously been broken for the last 18+ days?

**Comment by matthiasdv** [comment]
I'm getting exactly the same issue using the latest helm provider, and using v1.1.1 fixes this.
