### ISSUE TITLE
setting a joined list is breaking with version > 1.2.0

### ISSUE THREAD

**Issue by IbraheemAlSaady** [hashicorp/terraform-provider-helm#495]
I'm currently using 1.1.1 and doing the following was working fine:

```terraform
set {
    name = "dnsNames"
    value = "{${join(",", concat([var.hostname], var.ssl_certificates_hosts))}}"
  }
```

The dnsNames in the helm template is as follows:
```yaml
 dnsNames:
    {{- range .Values.dnsNames }}
    - {{ . | quote }}
    {{- end }}
```

I recently was testing an upgrade to 1.2.1, with the same configuration above, I started getting the following error when I do `terraform apply` 

```bash
Error: Provider produced inconsistent final plan

When expanding the plan for helm_release.ingressgateway_cert to include new
values learned so far during apply, provider "registry.terraform.io/-/helm"
produced an invalid new value for .set: planned set element
cty.ObjectVal(map[string]cty.Value{"name":cty.StringVal("secretName"),
"type":cty.NullVal(cty.String),
"value":cty.StringVal("ingressgateway-certs")}) does not correlate with
any element in actual.
```

The plan output is the following:

```bash
- set {
      - name  = "dnsNames" -> null
      - value = "{something.example.com}" -> null
 }
+ set {
      + name  = "dnsNames"
      + value = "{something.example.com}"
 }
```

Only the apply is failing. 

Versions:

```
Terraform Version: 0.12.20
Helm Provider: 1.2.1
```

**Comment by jrhouston** [comment]
I'm trying to reproduce this but not having any luck. I noticed that the value producing the error is `secretName` not `dnsNames`. Are you able to share more of your terraform config? Can you add a gist of the apply run with TF_LOG=DEBUG enabled?

**Comment by IbraheemAlSaady** [comment]
@jrhouston I actually got a list of errors on each set I had (sorry I shared the wrong error)

```
Error: Provider produced inconsistent final plan

When expanding the plan for helm_release.ingressgateway_cert to include new
values learned so far during apply, provider "registry.terraform.io/-/helm"
produced an invalid new value for .set: planned set element
cty.ObjectVal(map[string]cty.Value{"name":cty.StringVal("dnsNames"),
"type":cty.NullVal(cty.String),
"value":cty.StringVal("{something.example.com}")}) does not correlate with
any element in actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker
```

I went through the helm provider code and actually I see there is a new property called `type`, I added the  `type = "string"` on all sets except the `dnsNames` and it worked. :/ 

**Update**: 

The first run worked fine, but if you run it again it fails with the error above. I also put the `type=string` and then it worked

**Comment by lober-io** [comment]
We faced the same issue. Any Updates on this?

**Comment by gopher194** [comment]
Same issue: First Apply: OK, Second Apply: 
`Error: Provider produced inconsistent final plan
When expanding the plan for module.aks_k8sinfra.helm_release.ingress_statpip
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/helm" produced an invalid new value for .set:
planned set element
cty.ObjectVal(map[string]cty.Value{"name":cty.StringVal("controller.service.annotations.service\\.beta\\.kubernetes\\.io/azure-load-balancer-resource-group"),
"type":cty.NullVal(cty.String),
"value":cty.StringVal("rg-cac-azint-aks-networking")}) does not correlate with
any element in actual.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.`

Using a dynamic block to declare this set:
`  dynamic set {
    for_each = var.piping_name == "" ? [] : [true]
    content {
        name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/azure-load-balancer-resource-group"
        value = data.azurerm_public_ip.ing_pip[0].resource_group_name
    }
  }`

Will try with a `dynamic values {}` block, to see if it solves the issue.
provider helm { version = "\~> 1.3.1" }, provider kubernetes { version = "\~> 1.11" },
authentication through host / client_certificate / client_key / cluster_ca_certificate

**Comment by gopher194** [comment]
I could solve the problem with 2 solutions:

- switching from `set` to **`set_string`**:
`dynamic set_string {
    for_each = var.piping_name == "" ? [] : [true]
    content {
        name = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/azure-load-balancer-resource-group"
        value = data.azurerm_public_ip.ing_pip[0].resource_group_name
        }
    }`
   but `set_string` has a deprecation warning
- adding reference to the iterator (**`set.value`**) in the content block:
`  dynamic set {
    for_each = var.piping_name == "" ? [] : ["0"]
    content {
      name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/azure-load-balancer-resource-group"
      value = data.azurerm_public_ip.ing_pip[set.value].resource_group_name
      }
    }`
I believe the helm provider needs an iterator in the dynamic block to be happy.

**Comment by rhysjtevans** [comment]
Hi folks, I had a similar issue and I added `type = "string"` to the `set` block and problem went away.

**Comment by mrobinson513** [comment]
I'm having a similar problem in provider version 2.0.2 that might be reproducible:

Attempting to deploy the [Reloader helm chart](https://github.com/stakater/Reloader/tree/master/deployments/kubernetes/chart/reloader)

They provide a value `reloader.ignoreNamespaces` which takes a comma separated list of namespaces. The logical thing to do here is generate your list however, then join the elements together into a string to pass into this value.

Using `set`:
```hcl
  set {
    name  = "reloader.ignoreNamespaces"
    value = join(",", local.reloader.ignore_namespaces)
    type  = "string"
  }
```
Results in this plan:

```
  # module.services.helm_release.reloader will be created
  + resource "helm_release" "reloader" {
      + atomic                     = false
      + chart                      = "reloader"
      + cleanup_on_fail            = false
      + create_namespace           = true
      + dependency_update          = false
      + disable_crd_hooks          = false
      + disable_openapi_validation = false
      + disable_webhooks           = false
      + force_update               = false
      + id                         = (known after apply)
      + lint                       = false
      + max_history                = 0
      + metadata                   = (known after apply)
      + name                       = "reloader"
      + namespace                  = "reloader"
      + recreate_pods              = false
      + render_subchart_notes      = true
      + replace                    = false
      + repository                 = "https://stakater.github.io/stakater-charts"
      + reset_values               = false
      + reuse_values               = false
      + skip_crds                  = false
      + status                     = "deployed"
      + timeout                    = 300
      + verify                     = false
      + version                    = "v0.0.81"
      + wait                       = true
      + set {
          + name  = "ignoreNamespaces"
          + type  = "string"
          + value = "kube-system,kube-public,kube-node-lease"
Plan: 1 to add, 0 to change, 0 to destroy.
------------------------------------------------------------------------
```
That sure looks like it's going to pass a comma-separated string of namespaces, right?

However, upon applying:

```
[...]
module.services.helm_release.reloader: Creating...

Error: failed parsing key "ignoreNamespaces" with value kube-system,kube-public,kube-node-lease, key "kube-public" has no value (cannot end with ,)
```
Unfortunately using `type=string` did not work for me.

I've been able to work around this by rendering a template file, enclosing my var in quotes like so:
```yaml
reloader:
  ignoreNamespaces: "${ignore_namespaces}"
```

```hcl
data "template_file" "reloader_values" {
  template = file("${path.module}/values/reloader.yaml")

  vars = {
    ignore_namespaces = join(",", local.reloader.ignore_namespaces)
  }
}

resource "helm_release" "reloader" {
  name             = "reloader"
  repository       = "https://stakater.github.io/stakater-charts"
  chart            = "reloader"
  version          = "v0.0.81"
  namespace        = local.reloader.namespace
  create_namespace = true

  values = [data.template_file.reloader_values.rendered]

}
```

This plans and applies successfully.

Kind of reminds me of the default behaviour of using `helm install --set key1=val1,key2=val2`. I wonder if `type=string` is supposed to enclose `value` in double quotes? This behaviour suggests that it isn't, unfortunately I lack the golang experience to triage the code.

(edit: was missing the `helm_release` resource call)

**Comment by viatcheslavmogilevsky** [comment]
Comma can be escaped by `\\`, for example:

```
  set {
    name  = "grafana.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/success-codes"
    value = "200\\,302\\,303"
  }
```

**Comment by RonLek** [comment]
In case anyone is still facing this issue. Adding `type = "string"` solved this for me.
