### ISSUE TITLE
 ```kubernetes {load_config_file   = false}``` have no effects (and envar can't be boolean)

### ISSUE THREAD

**Issue by dhardy92** [hashicorp/terraform-provider-helm#500]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Step #0 - "terraform": Status: Downloaded newer image for hashicorp/terraform:light
Step #0 - "terraform": docker.io/hashicorp/terraform:light
Step #0 - "terraform": 2020/05/18 09:50:24 [INFO] Terraform version: 0.12.25  
Step #0 - "terraform": 2020/05/18 09:50:24 [INFO] Go runtime version: go1.12.13

### Provider Version
Step #0 - "terraform": 2020/05/18 09:50:28 [DEBUG] found provider "terraform-provider-google_v2.18.1_x4"
Step #0 - "terraform": 2020/05/18 09:50:28 [DEBUG] found provider "terraform-provider-helm_v1.2.1_x4"
Step #0 - "terraform": 2020/05/18 09:50:28 [DEBUG] found provider "terraform-provider-kubernetes_v1.11.2_x4"

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
provider are eset in main config resource define in sub-modules
```hcl
provider "kubernetes" {
  host                   = "https://${data.terraform_remote_state.gke.outputs.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(data.terraform_remote_state.gke.outputs.ca_certificate)
  load_config_file       = false
  version                = "~> 1.11"
}

provider "helm" {
  alias   = "provider"
  kubernetes {
    host  = "https://${data.terraform_remote_state.gke.outputs.endpoint}"
    token = data.google_client_config.default.access_token
    client_certificate = base64decode(data.terraform_remote_state.gke.outputs.ca_certificate)
    load_config_file   = false
  }
}
[...]
module "mailer" {
  source                           = "../../modules/ce-mailer-golang"
  project                          = var.project
  namespace                        = var.namespace
  region                           = var.region
  subnetwork                       = var.subnetwork
  istio_ingress_url                = var.istio_ingress_url
  main_zone_project                = data.google_dns_managed_zone.main_zone.project
  main_zone_dns_name               = data.google_dns_managed_zone.main_zone.dns_name
  main_zone_name                   = data.google_dns_managed_zone.main_zone.name
  sql_outputs_master_instance_name = data.terraform_remote_state.sql.outputs.master_instance_name
}
```
in the module :
```hcl
module "mailer_redis" {
  source             = "../../modules/redis"
  app_name           = "ce-mailer-golang"
  project            = var.project
  namespace          = var.namespace
  region             = var.region
  subnetwork         = var.subnetwork
  main_zone_project  = var.main_zone_project
  main_zone_dns_name = var.main_zone_dns_name
  main_zone_name     = var.main_zone_name
}
```
in the sub-module : 
```hcl
resource "helm_release" "redis" {
  name        = local.redis_name
  repository  = "https://charts.bitnami.com/bitnami"
  chart       = "redis"
  version     = "10.6.12"
  // Redis v5.0.9 -> https://charts.bitnami.com/bitnami/index.yaml
  namespace   = var.namespace
  max_history = 10
  timeout     = 120
  values      = [
    file("${path.module}/default.config.yaml")
  ]

  set {
    name  = "size"
    value = var.size
  }
  set {
    name  = "loadBalancerIP"
    value = google_compute_address.redis_internal_ip.address
  }
  set {
    name  = "password"
    value = random_password.redis_password.result
  }
  set {
    name  = "master.resources.cpu"
    value = var.resource.cpu
  }
  set {
    name  = "master.limits.cpu"
    value = var.resource.cpu_limit
  }
  set {
    name  = "master.resources.memory"
    value = var.resource.memory
  }
  set {
    name  = "master.limits.memory"
    value = var.resource.memory_limit
  }
}
```
```
```
### Debug Output
https://gist.github.com/dhardy92/bdeb622678c0d0f89e44081ab037049c

### Expected Behavior
helm resource should not try to load ~/.kube/config according to provider settings

### Actual Behavior
when creating resource from a module, helm try to load config file that does not exists.

### Steps to Reproduce
1. run cloudbuild with config
```
steps:
# Terraform apply CE infra
- id: "terraform"
  waitFor: ['-']
  name: hashicorp/terraform:light
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      set -e
      cd ./${_ENV}/terraform/
      terraform init && terraform validate && terraform apply -auto-approve
```

### Important Factoids
We run terraform on Google Cloudbuild with GKE target. 
Kubernetes provider (provide for comparaison) is confirgure the same way and is working properly to create kubernetes resources (secrets, etc)
BTW I also trry to set envar HELM_LOAD_CONFIG_FILE as [documented](https://www.terraform.io/docs/providers/helm/index.html#load_config_file) but Go complains with string is not bool type (and is right) so I suspect envar setting cannot work as (always strings)

**Comment by js-timbirkett** [comment]
Maybe I'm missing something but I see in your provider config:
```
  alias   = "provider"
```
But I don't see you using that alias anywhere in your module references 🤔 - Is there a reason you're setting an alias on the Helm provider? If not, you should probably try removing it and the config will apply to the default Helm provider instance.

You can see how to reference an alias provider in a module declaration in the Terraform docs at: https://www.terraform.io/docs/configuration/providers.html#selecting-alternate-providers

**Comment by dhardy92** [comment]
My appologies. I can read now that kubernetes and helm configuration differ in certificates parameter name. Close This.

**Comment by dhardy92** [comment]
My appologies. I can read now that kubernetes and helm configuration differ in certificates parameter name. Close This.
