### ISSUE TITLE
Statically defined credentials fails for helm provider with unknown error

### ISSUE THREAD

**Issue by Ivasan7** [hashicorp/terraform-provider-helm#503]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
```console
Terraform v0.12.25
+ provider.google v3.22.0
+ provider.helm v1.2.1
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "google_container_cluster" "cluster" {
  name     = "test"
  location = var.deployment-zone

  initial_node_count       = 2

  master_auth {
    username = ""
    password = ""

    client_certificate_config {
      issue_client_certificate = false
    }
  }
}

provider "helm" {
  kubernetes {
    host = google_container_cluster.cluster.endpoint

    client_certificate     = base64decode(google_container_cluster.cluster.master_auth.0.client_certificate)
    client_key             = base64decode(google_container_cluster.cluster.master_auth.0.client_key)
    cluster_ca_certificate = base64decode(google_container_cluster.cluster.master_auth.0.cluster_ca_certificate)
    load_config_file = false
  }
}

resource "helm_release" "test" {
  name  = "dev"
  chart = "../../../../chart"
  namespace = "default"
  version         = "0.1.0"

  values = [
    file("../../../../chart/values.yaml")
  ]

   provisioner "local-exec" {
    command = "helm test dev"
  }
}
```

### Debug Output
```console
2020-05-22T14:39:05.409+0200 [DEBUG] plugin.terraform-provider-helm_v1.2.1_x4: 2020/05/22 14:39:05 [DEBUG] Installing Chart
2020-05-22T14:39:05.409+0200 [DEBUG] plugin.terraform-provider-helm_v1.2.1_x4: 2020/05/22 14:39:05 [INFO] Successfully initialized config
2020/05/22 14:39:06 [DEBUG] module.cluster.helm_release.tgrid: apply errored, but we're indicating that via the Error pointer rather than returning it: unable to build kubernetes objects from release manifest: unknown
2020/05/22 14:39:06 [ERROR] module.cluster: eval: *terraform.EvalApplyPost, err: unable to build kubernetes objects from release manifest: unknown
2020/05/22 14:39:06 [ERROR] module.cluster: eval: *terraform.EvalSequence, err: unable to build kubernetes objects from release manifest: unknown

Error: unable to build kubernetes objects from release manifest: unknown

  on ../../modules/cluster/main.tf line 29, in resource "helm_release" "tgrid":
  29: resource "helm_release" "tgrid" {
```

### Panic Output
No panic.

### Expected Behavior
Deploy the helm chart. 
With `helm install dev ./chart` is succesful

### Workaround
Due to the static initialisation of the cluster I would expect that it is working with the setting
`load_config_file = false`. 

If I do the manual config on the machine so `${HOME}/.kube/config` is present then the deployment is succesful AND set 
`load_config_file = true`.
(NOTE: This only works, if there has been a failure once so the GKE engine is already running)
### Actual Behavior
Error:
```console
Error: unable to build kubernetes objects from release manifest: unknown

  on ../../modules/cluster/main.tf line 29, in resource "helm_release" "test":
  29: resource "helm_release" "test" {
```
### Steps to Reproduce
1. `terraform apply`

### Important Factoids
It is running on a Google Kubernetes Engine

**Comment by Ivasan7** [comment]
I found actually the problem, the [documentation](https://www.terraform.io/docs/providers/helm/index.html) is obsolete. If the `token` is defined than it works.

**Comment by mccricardo** [comment]
If the file **~/.kube/config** exists (no matter what the content is) it also works. `load_config_file` seems to be ignored.

**Comment by alexsomesan** [comment]
Implementing this would improve the experience in these situations: https://github.com/hashicorp/terraform-provider-helm/issues/562
