### ISSUE TITLE
HELM_BIN set to helm provider breaks helm plugins

### ISSUE THREAD

**Issue by pib** [hashicorp/terraform-provider-helm#506]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Provider Version
All versions are effected, since `HELM_BIN` has been set to `os.Args[0]` for plugins since the beginning (v0.1.0 of this provider).

### Affected Resource(s)

- helm_repository
- helm_release

### Terraform Configuration Files
With the [helm-git plugin](https://github.com/aslafy-z/helm-git) installed, anything along these lines:
```hcl
data "helm_repository" "example" {
  name = "example"
  url  = "git+ssh://git@github.com/whatever@?ref=v1.0.0"
}
```

### Debug Output
Not actual debug output, but I edited the helm-git plugin to write out the value of HELM_BIN that it gets, and it is `/conf/.terraform.d/plugins/terraform-provider-helm_v0.10.4_x4`, which is where the helm provider is installed in the container where I'm running terraform.

According to the Helm docs, the HELM_BIN environment variable is "[guaranteed to be set](https://helm.sh/docs/topics/plugins/#environment-variables)" to the path to the helm command, but it also assumes that it was called as "helm" rather than used as a library.

### Expected Behavior
It should work :smile: 

I'm not sure what the "correct" behavior here should be. Since the helm provider could be used on a system without the actual `helm` executable installed, it's not safe to assume that it will be on the path. Perhaps a way of overriding it in the provider settings?

### Actual Behavior
The provider freezes as the plugin tries to call the provider as if it were helm. In fact, I just checked and I have 16 copies of `/conf/.terraform.d/plugins/terraform-provider-helm_v0.10.4_x4 version -c --short` still running in the background.

### Steps to Reproduce

1. Install the `helm-git` helm plugin.
2. Add a `helm_repository` or `helm_release` resource that uses a git+ URL.
3. `terraform apply`

### References
- https://github.com/terraform-providers/terraform-provider-helm/blob/master/vendor/helm.sh/helm/v3/pkg/cli/environment.go#L103 is where the HELM_BIN environment variable is set for plugins.

**Comment by pib** [comment]
The clarify, this issue will occur with any helm plugin that uses HELM_BIN to try and run helm commands.

**Comment by Nuru** [comment]
I think the correct behavior is that the Terraform provider should use the system-installed `helm` (`HELM_BIN` if it is set, otherwise `helm` if it is on the `PATH`), because the system installed Helm will have plugins and chart repositories installed, and Terraform should take advantage of that. 

If, instead, you want Terraform completely isolated from the system, then you need to override all the environment variables Helm uses to find plugins and chart repositories and other settings (`HELM_HOME`, `HELM_VALUES_PATH`, `HELM_PATH_CACHE`, `HELM_PATH_CONFIG`, `HELM_PATH_DATA`), but then you also will want a way to install helm plugins, since you probably want `helm-diff` at least.

**Comment by aslafy-z** [comment]
@pib can you please re-open this issue?
