### ISSUE TITLE
Error: query: failed to query with labels: Unauthorized

### ISSUE THREAD

**Issue by krzysztof-miemiec** [hashicorp/terraform-provider-helm#508]
I noticed potential issue with Helm Provider 1.0.0. When I run `terraform apply`, forget about it being open, then return to Terminal after a while and type `yes`, Helm Provider crashes with `Error: query: failed to query with labels: Unauthorized`. I suppose it's caused by Kubernetes token not being refreshed before installing/upgrading helm chart. I use exec auth with `aws eks get-token ...`, which returns a token valid for about 15 minutes or so.
I guess that solution is to run exec command and grab a new token every time when Helm gets Unauthorized error and it may need fixing in Helm itself. 🤔 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

`v0.12.25`

### Provider Version
`1.0.0` (I'm not able to run with latest 1.2.1)

### Affected Resource(s)

- `helm_release`

### Terraform Configuration Files

Any `helm_release` resource should work, for example:

```hcl

resource "helm_release" "this" {
  name = "datadog"
  chart        = "datadog"
  version      = "2.3.5"
  repository   = "https://kubernetes-charts.storage.googleapis.com"
  namespace    = "datadog"
  wait         = true
  verify       = false
  values       = [file("${path.module}/values.yaml")]

  verify = false
}
```

### Debug Output

not provided

### Panic Output

n/a

### Expected Behavior

Helm pulls new Kubernetes credentials instead of relying on old, expired token.

### Actual Behavior

I 
`Error: query: failed to query with labels: Unauthorized` is written to output. I don't know what would happen if I had long-running (15+ minutes) helm chart installation with `wait=true` flag.

### Steps to Reproduce

1. `terraform apply`

### References

- n/a

**Comment by aareet** [comment]
Relates to https://github.com/hashicorp/terraform-provider-kubernetes/issues/918

**Comment by krzysztof-miemiec** [comment]
## Cause
Now when I got back to this issue, I think that it's be my fault using data source as credential source.
That’s my `kubernetes.config.tf` file which I include in my K8s-related Terragrunt components:

```tf
/**
 BASE CONFIG FOR KUBERNETES ENVIRONMENTS
 This configuration file is included by Terragrunt during
 deployment of any component located beneath.
*/
# --------------------------------------------------------
# INPUT VARIABLES
# Safe defaults should be set in `terragrunt.hcl` file
# Values can be overridden with local terraform.tfvars
# --------------------------------------------------------
variable "cluster_id" {
  type        = string
  description = "EKS Cluster ID used to configure Helm & Kubernetes providers."
}
# --------------------------------------------------------
# PROVIDERS
# Safe defaults should be set in `terragrunt.hcl` file
# Values can be overridden with local terraform.tfvars
# --------------------------------------------------------
data "aws_eks_cluster" "cluster" {
  name = var.cluster_id
}
data "aws_eks_cluster_auth" "cluster" {
  name = var.cluster_id
}
provider "kubernetes" {
  version = "~> 1"
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
}
provider "helm" {
  version = "1.2.3"
  kubernetes {
    load_config_file       = false
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.cluster.token
  }
}
```

As you can see, I’m using data resources to obtain cluster token, which AFAIK is discouraged in docs/by community, as Terraform only fetches it in plan phase and apply phase simply uses (15+ minute old) plan.

## ~Workaround for now~ Currently available solution

<details>
<summary>
My previous thoughts dump
</summary>
I guess that solution would be to prepare aws config & aws credentials files in `.gitignore`d path in project, along with `kubeconfig` and set proper env vars/provider settings in Terraform :thinking_face:

I also wonder how it could be integrated with Vault (AFAIK there’s no Kubernetes Secret Engine, which would allow us to create temporary Service Accounts), however I’m already using AWS Secret Engine, so… A bit of bash magic, use of `vault-agent`/`consul-template` and we may get:
* `.aws/credentials` / `.aws/config` files
* kubeconfig created with `aws eks update-kubeconfig`
</details>

I realized that instead of passing data source to provider, we can just make use of `exec` block available in Kubernetes and Helm providers. See this example: https://github.com/hashicorp/terraform-provider-helm/pull/560#issuecomment-686354382

## Additional solution (to be implemented in Kubernetes/Helm Providers)

*What if we we could pass kubeconfig directly to kubernetes/helm providers?* I use [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks/) module to create EKS clusters. If you go to [master/local.tf#L145](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf#L145) you’ll see a `kubeconfig` file being generated from `templatefile`. We can either save it as a Terraform output, or pass it further.

What I mean, is a new option to pass `kubeconfig` not only as file path, but also as `kubeconfig_content` field. The closest analogy I can think of now are `source_content` and `source_content_filename` in [archive_file](https://registry.terraform.io/providers/hashicorp/archive/latest/docs/data-sources/archive_file) data source. Currently our providers only support an equivalent of `source_content_filename`.

Assuming that this option is present, we may skip creating `kubeconfig` manually or via `local_file` (current solution provided by `terraform-aws-eks`). As a result, my `terragrunt.hcl` (with some parts redacted) looks like:

```hcl
# ...

dependency "cluster" {
  config_path = "../cluster"
}

# aforementioned kubernetes.config.tf file
generate "kubernetes-config" {
  path           = "generated-kubernetes.config.tf"
  comment_prefix = "#"
  if_exists      = "overwrite_terragrunt"
  contents       = file("../kubernetes.config.tf")
}

inputs = {
  kubeconfig = dependency.cluster.outputs.kubeconfig # `local.kubeconfig` generated by `terraform-aws-eks` module
}
```

and new `kubernetes.config.tf` may look like:

```tf
/**
 BASE CONFIG FOR KUBERNETES ENVIRONMENTS
 This configuration file is included by Terragrunt during
 deployment of any component located beneath.
*/

# --------------------------------------------------------
# INPUT VARIABLES
# Safe defaults should be set in `terragrunt.hcl` file
# Values can be overridden with local terraform.tfvars
# --------------------------------------------------------

variable "kubeconfig" {
  type        = string
  description = "Kubeconfig file contents stored as YAML string."
}

# --------------------------------------------------------
# PROVIDERS
# Safe defaults should be set in `terragrunt.hcl` file
# Values can be overridden with local terraform.tfvars
# --------------------------------------------------------

provider "kubernetes" {
  version = "~> 1"
  config_content = var.kubeconfig
}

provider "helm" {
  version = "1.2.3"
  kubernetes {
    config_content = var.kubeconfig
  }
}
```

**Comment by krzysztof-miemiec** [comment]
This might work: https://github.com/krzysztof-miemiec/terraform-provider-helm/commit/e09465edbd56ff6236a847958c9ac16b061e1e03
