### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest: unknown

### ISSUE THREAD

**Issue by ooOOJavaOOoo** [hashicorp/terraform-provider-helm#513]
### Terraform Version and Provider Version
Terraform version: 0.12.24

### Provider Version
provider.helm v1.2.1

### Affected Resource(s)
- provider
- helm_release
### Terraform Configuration Files
```hcl
provider "helm" {
  kubernetes {
    host     = var.openshift_server
    username = var.openshift_admin
    password = var.openshift_password
  }
}
resource "helm_release" "main" {
  name = "sumologic"
  repository = "https://kubernetes-charts.storage.googleapis.com/"
  chart     = "sumologic-fluentd"
  namespace = "logging"

  values = [
    "${file("${path.module}/values.yml")}"
  ]
}
```

### Debug Output
```
12:47:33 [DEBUG] Installing Chart
2020-05-29T12:47:33.101-1000 [DEBUG] plugin.terraform-provider-helm_v1.2.1_x4: 2020/05/29 12:47:33 [INFO] Successfully initialized config
2020/05/29 12:47:34 [DEBUG] module.sumo_test.helm_release.main: apply errored, but we're indicating that via the Error pointer rather than returning it: unable to build kubernetes objects from release manifest: unknown
2020/05/29 12:47:34 [ERROR] module.sumo_test: eval: *terraform.EvalApplyPost, err: unable to build kubernetes objects from release manifest: unknown
2020/05/29 12:47:34 [ERROR] module.sumo_test: eval: *terraform.EvalSequence, err: unable to build kubernetes objects from release manifest: unknown

Error: unable to build kubernetes objects from release manifest: unknown

  on ../main.tf line 8, in resource "helm_release" "main":
   8: resource "helm_release" "main" {


2020-05-29T12:47:34.492-1000 [DEBUG] plugin: plugin process exited: path=/helm_charts/sumo-fluentd/example/.terraform/plugins/darwin_amd64/terraform-provider-helm_v1.2.1_x4 pid=71709
```

### Expected Behavior
fluentd helm chart is deployed

### Actual Behavior
Error: unable to build kubernetes objects from release manifest: unknown

### Steps to Reproduce
1. `terraform apply`

**Comment by msldn** [comment]
I'm facing same issue. I'm using latest helm provider and deploying the latest bitnami nginx chart. I was able to deploy it to the same cluster with helm install from my workstation. but when running from terraform ( also on my local machine) , I'm getting This  error
Error: unable to build kubernetes objects from release manifest: unknown

**Comment by romainframe** [comment]
+1, same here !

```
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]

  on main.tf line 1, in resource "helm_release" "example":
   1: resource "helm_release" "example" {


[terragrunt] 2020/07/29 13:18:33 Hit multiple errors:
exit status 1
```

Using:
- ```terragrunt version v0.23.31```
- ```Terraform v0.12.29```
- ```version = "~> v1.2.4"```

Anyone has an idea of the source of this issue ? Workaround possible ?

**Comment by shvgn** [comment]
I see this error as well. Let me share my examples. 

When I specify credentials in helm provider, I get the same error

```
provider "helm" {
  version = "1.2.4"

  kubernetes {
    host     = "https://${google_container_cluster.cluster.endpoint}"
    insecure = false

    load_config_file       = false
    client_key             = base64decode(google_container_cluster.cluster.master_auth[0].client_key)
    client_certificate     = base64decode(google_container_cluster.cluster.master_auth[0].client_certificate)
    cluster_ca_certificate = base64decode(google_container_cluster.cluster.master_auth[0].cluster_ca_certificate)
  }
}

resource "helm_release" "rabbitmq" {
  name       = "rabbitmq"
  namespace  = kubernetes_namespace.rabbitmq.metadata[0].name
  chart      = "rabbitmq-ha"
  repository = "https://kubernetes-charts.storage.googleapis.com"
  ...
}
```

This results in 

```
Error: unable to build kubernetes objects from release manifest: unknown
```

If I keep the configuration below (without explicit credentials), helm release creates as expected

```
provider "helm" {
  version = "1.2.4"

  kubernetes {
    host     = "https://${google_container_cluster.cluster.endpoint}"
    insecure = false
  }
}
```

<details><summary>my guess that did not reproduce</summary>
I have a guess that the http client in the helm provider uses these credentials for fetching charts packages. And if they are stored in a sophisticated cloud storage (e.g. GCS) it can cause this problem. The cloud API might be sensitive to credentials event though the addressed charts are public. 

Also I met another problem described in #561. Terraform logs that helm cannot fetch a chart URL from "stable". That chart URL can be successfully fetched by curl without auth. Might be the same problem there.

Again, mixed auth credentials this is just a guess, I did not have a chance to dive into the code. 
</details>

One might try to rely on local access configs instead of passing the credentials explicitly.

**Comment by sergiorc** [comment]
Same behaviour, but at least in my case, it was my fault.

I was creating the k8s cluster with this config (GKE with google_container_cluster resource):

```    
resource "google_container_cluster" "xxx" {

    master_auth {
        client_certificate_config 
        {  
            issue_client_certificate = false  
        }  
    }
```

So the k8s state didn't contain client certificates :)

**Comment by matteovivona** [comment]
Same issue here with `hashicorp/helm: version = "~> 1.3.2"`, Terraform Cloud VCS and ingress-nginx chart

**Comment by asafhm** [comment]
Reproduces with `terraform version 0.14.3`, `hashicorp/helm version v2.0.1`
Any leads?

**Comment by rtrive** [comment]
same error here.
`terraform version 0.14.6`
`hashicorp helm v2.0.1`
`k8s: 1.18.12-gke.1205`

Every time that i run some changes my cluster disappear for while and master nodes start to auto repair causing downtime.
Also i get more frequently error like this `unable to recognize "": no matches for kind`

If i run same chart with helm cli it works

**Comment by athak** [comment]
Same here. Something is causing the GKE masters to cascade crash, rendering the whole cluster unmanageable for a while until they recover. Happens with both v1.3.x and v2.x of the provider.

**Comment by rtrive** [comment]
is there a change to continue to use helm provider in some way? Because right now it's useless

**Comment by MikiLoz92** [comment]
In my case this error reproduced because I was using v1 of the Kubernetes provider and v2 of the Helm provider. Changing both to the same version (in my case v1) resolved the issue.

**Comment by rtrive** [comment]
@MikiLoz92 are you using GKE?

**Comment by MikiLoz92** [comment]
@rtrive yup, that's right

**Comment by rtrive** [comment]
@MikiLoz92 i can confirm that when i upgrade both provider to version 2.x.x it seems to work well. Before that i had kubernetes provider 1.x.x and helm provider 2.x.x
Thanks!

**Comment by DominikBB** [comment]
+1 Getting the same issue here, setting up a consul chart on DigitalOcean DOKS.

```
provider "helm" {

  kubernetes {
    host  = var.cluster-endpoint
    client_certificate  = var.cluster-config.client_certificate
    client_key = var.cluster-config.client_key
    cluster_ca_certificate = base64decode(
      var.cluster-config.cluster_ca_certificate
    )
  }
}

```
```
resource "helm_release" "consul" {
  name      = "consul"
  repository = "https://helm.releases.hashicorp.com"
  chart = "consul"
  namespace = kubernetes_namespace.consulNS.metadata.0.name

  set {
    name = "global.name"
    value = "consul"
  }
  set {
    name = "server.replicas"
    value = 3
  }
  set {
    name = "connecInject"
    value = true
  }
}
```
Providers:
- **Kubernetes** provider v2.0.3
- Tried **Helm** providers v2.1.0, v2.0.3, v2.0.2
- **DOKS**  v1.20.2-do.0

Happens with both Terraform Cloud remote backend and the local.


---
Direct installation with Helm CLI works wonderfully.

---

Found that a fix to this issue is using _token_ for authentication of the provider. The issue #503 points to this, should really be fixed soon!

**Comment by kg-ops** [comment]
Same issue with `bitnami-mongodb` chart on EKS cluster as well. The local chart installation works just fine via helm CLI install. 
```
unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```
- Terraform v0.14.10
- EKS 1.18

**Comment by BarnumD** [comment]
Confirmed that using token worked for me rather than client_certificate and client_key.  Thank you @DominikBB

**Comment by ondrejsika** [comment]
I've got this weird error when I had the wrong authorization in the provider. This patch work for me.
<img width="823" alt="Screenshot 2021-08-18 at 17 02 53" src="https://user-images.githubusercontent.com/1665772/129922915-28ee95d2-29d2-45a0-b0de-3f2355d8bb05.png">
