### ISSUE TITLE
Unable to deploy helm release from git-sourced module

### ISSUE THREAD

**Issue by brabster** [hashicorp/terraform-provider-helm#517]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v0.12.25

### Provider Version
+ provider.helm v1.2.2

### Affected Resource(s)

- helm_release

### Terraform Configuration Files

Importing module:
```hcl
module "example-workflow" {
  source         = "git::git@a-private-git/example-workflow.git?ref=4dc16b3f"
  release        = "example-workflow"
  namespace      = "tf-example-workflow"
  schedule       = "0 10 * * *"
  suspend        = var.example_workflow_suspend
  who            = "Terraformer"
}
```
Imported module:
```hcl
resource "helm_release" "workflow" {
  name      = var.release
  namespace = var.namespace

  chart = "${path.module}/helm-chart"

  set {
    name  = "schedule"
    value = var.schedule
  }

  set {
    name  = "suspend"
    value = var.suspend
  }

  set {
    name  = "defaultName"
    value = var.who
  }

  postrender {
    binary_path = "${path.module}/helm-chart/post-render-argo.sh"
  }

}
```

### Debug Output

Don't have this available yet, but when I reviewed this output earlier I didn't see anything useful. Will probably have to come up with a simple replication on Github to share this.

### Panic Output

No panic.

### Expected Behavior

```
 module.example-workflow.module.example_workflow.helm_release.workflow: Creation complete after 2s [id=example-workflow]
```

### Actual Behavior

```
Error: Provider produced inconsistent final plan
 When expanding the plan for module.example-workflow.helm_release.workflow to
 include new values learned so far during apply, provider
 "registry.terraform.io/-/helm" produced an invalid new value for .version: was
 known, but now unknown.
 This is a bug in the provider, which should be reported in the provider's own
 issue tracker.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
- This appears to affect a git-sourced module. If I copy the template into a directory in the local project and source it from there, I get the expected successful creation. I've verified by switching the K8s namespace back and forth, git-sourced reliably fails and local reliably succeeds.
- I tried reverting to `1.1.1` of this provider to see if it was a recently-introduced issue, but the same problem.

**Comment by brabster** [comment]
Although a different error, this issue had the same characteristics as #520, i.e. it worked on my Fedora machine, but failed on the Alpine-based build server image. I'll leave it open as I guess it probably shouldn't break in the way it did, but I suspect a postrender Bash script on an Alpine-based image was the underlying problem.

**Comment by c0deaddict** [comment]
I think i'm encountering the same problem. This works in the Terraform "root" main.tf:

```terraform
resource "helm_release" "ingress-nginx" {
  name              = "ingress-nginx"
  repository        = "https://kubernetes.github.io/ingress-nginx"
  dependency_update = true
  chart             = "ingress-nginx"
  namespace         = "ingress-nginx"
  create_namespace  = true
  values            = [file("ingress-nginx/values.yaml")]
}
```

But doesn't when loading it from a module:

main.tf
```terraform
module "ingress-nginx" {
  source = "./ingress-nginx"
}
```

ingress-nginx/main.tf
```terraform
resource "helm_release" "ingress-nginx" {
  name              = "ingress-nginx"
  repository        = "https://kubernetes.github.io/ingress-nginx"
  dependency_update = true
  chart             = "ingress-nginx"
  namespace         = "ingress-nginx"
  create_namespace  = true
  values            = [file("${path.module}/values.yaml")]
}
```

The providers gives this weird error message:

```
module.ingress-nginx.helm_release.ingress-nginx: Creating...

Error: Chart.yaml file is missing

  on ingress-nginx/main.tf line 1, in resource "helm_release" "ingress-nginx":
   1: resource "helm_release" "ingress-nginx" {
```
