### ISSUE TITLE
helm chart changes does not trigger terraform update

### ISSUE THREAD

**Issue by SandipGorde** [hashicorp/terraform-provider-helm#519]
### Terraform Version and Provider Version
terraform version: 0.12.20

### Provider Version
helm provider

### Affected Resource(s)
- helm_release

I have fluentbit working on my Kubernetes cluster which was deployed through terraform helm release. Now I updated fluentBit configuration in the helm chart and re-triggered terraform apply. Terraform does not recognized new changed in the helm chart and just refreshed state file.

**Comment by aareet** [comment]
@SandipGorde can you please post your debug log with the plan and apply with TF_LOG set to TRACE?

https://www.terraform.io/docs/internals/debugging.html

**Comment by aareet** [comment]
Closing since it has been 21 days since request. Please reopen if this is still an issue.
