### ISSUE TITLE
Keyring constantly changing

### ISSUE THREAD

**Issue by apenney** [hashicorp/terraform-provider-helm#52]
Hi,

Is there a way to force an attribute for all instances of helm_release{}? Every time we run terraform as a different user it wants to change keyring in every helm_release, which is kind of annoying.  It's a value we don't set, but it defaults to your homedirectory.  Failing that, if it stored it as `~/.gnupg` instead of the expanded path, it wouldn't need to change for different users.

**Comment by burdiyan** [comment]
I think this was addressed in some of the PRs that was adding verify option to the release, which is now by default is set to false.

https://github.com/mcuadros/terraform-provider-helm/blob/master/helm/resource_release.go#L95

Is it still happening in version 0.5 of the provider? @apenney

**Comment by apenney** [comment]
I believe it still happens in 0.5!  There's two of us that have verified we're on 0.5 and we've seen it flip between us.  I'll check in with the third person and update this ticket again to make sure he's not a straggler on 0.4!

Oh, and one more thing we noticed:

```
+ provider.helm (unversioned)
```

We had to guesstimate by release date :)

**Comment by apenney** [comment]
Checked, all 3 of us were on 0.5.

**Comment by burdiyan** [comment]
Yes it still happening, although validate is set to false, the default value for keyring is changing constantly on different environments. Maybe the provider shouldn't store keyring in Terraform state file at all and use what's setup in the current environment.

**Comment by apenney** [comment]
We'd be :+1: on that!

**Comment by vcardenas** [comment]
As a workaround, I'm setting the keyring empty.
``` terraform
resource "helm_release" "my_release" {
    ...
    keyring = ""
    ...
}
```
That cause the provider to ignore it hence not causing the updates (in 0.5.0)

**Comment by walkafwalka** [comment]
This is still present in 0.7.
