### ISSUE TITLE
Compare currently deployed helm release metadata to decide if the helm_release should be updated or not

### ISSUE THREAD

**Issue by j-martin** [hashicorp/terraform-provider-helm#523]
### Description

We currently use the `terraform-provider-helm` to set up our production, staging, UATs, etc. with an helm_release. It setups some resources like bootstrapping service account with GKE Workload Identity, specify some values like external resources to the cluster (e.g. db, some caches, etc.). 

We then do deployments outside of terraform, directly via helm where we change the value versions of some services. To avoid terraform updating for no reason, we also have a small script that checks the current version of services from the current helm release values currently deploy that populates the `values` `helm_release` arguments. 

Our chart `values.yaml` look something like this:

```
---
environment: staging

serviceA:
  version: 20200605-031242-6a98615

serviceB:
  version: 20200605-031242-6a98615
```

Unfortunately in its current state the helm provider only cares about changes between the plan of our terraform configuration and the state. This triggers unnecessary changes in the plan. For example, if:

1. We install version 1 of all services with `terraform apply`.
2. We deploy the version out of band to version 2
3. Run `terraform plan` (it uses our script to tell what is the new version).

**Expected:** No change needs to done. As the values in the desired state and the actual state of the release on the cluster matches.

**Actual:** Because the provider ignores the values currently in use in the release on the cluster, terraform will want to do an in-place update to match the current state.

From experience with other providers AWS, GCP, Vault, the decision to do an update in-place or replace is based on the state returned by the APIs and not the internal terraform state. We can do changes out of band, if necessary, and as long the final, desired, terraform state matches the actual of the external state of the resource the final plan will be a no-op/ no change necessary.

We were expecting that an `helm_release` to use the actual state of the release, coming from helm, as opposed to the previous terraform state.

With our script, it is not the end of the world since the `terraform apply` even if it updates the resource is a no-op and takes ~30s to apply, but it's confusing for people not familiar with the behavior and the version(s) can changes multiple times per hour.

We can see some challenges since the `helm_release.app.metadata[0].values` is a composite of the `values` and all the `set` arguments.

This would not be an issue if we used terraform as our only way to deploy everything, but we do not want to require a `terraform apply` for every deployment nor would we want to grant our deployment CD workers the privileges to a full `terraform apply`. Nor do we want to modify terraform config multiple times per hour. Also, `reuse_values` has been shown in our experimentation to be very cumbersome as it ignores new values set by the charts default `values.yaml`.

### Potential Terraform Configuration

```hcl
resource "helm_release" "app" {
  for_each = var.sub_environments

  chart           = local.app_chart
  name            = each.key
  namespace       = each.key
  timeout         = 45 * 60 # seconds, loading the initial backup will take a while.
  cleanup_on_fail = true
  atomic          = true

  set {
    name  = "isProduction"
    value = var.is_production
  }

  set {
    name  = "domain"
    value = trimsuffix(google_dns_record_set.app[each.key].name, ".")
  }

  dynamic "set" {
    for_each = var.sub_environments[each.key]
    content {
      name  = set.key
      value = set.value
    }
  }

  values = compact([
    data.external.app_version[each.key].result.yaml,
  ])

  depends_on = [
    module.k8s_db_service_account,
    module.k8s_serviceA_service_account,
    helm_release.app_shared,
    kubernetes_namespace.app,
  ]

  provider = helm.primary
}

data "external" "app_version" {
  for_each = toset(keys(var.sub_environments))
  working_dir = abspath("../../../")
  program = [
    "python3.7",
    "-m", "utils.helm_get_current_or_latest_version",
    "--project", module.gke_cluster_primary.cluster.project,
    "--region", module.gke_cluster_primary.cluster.location,
    "--cluster-name", module.gke_cluster_primary.cluster.name,
    "--release-name", each.key,
    "--json-wrapper"
  ]
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mmerickel** [comment]
This is a really important issue. It seems that the helm provider does not detect drift properly at all right now. We're running into https://github.com/hashicorp/terraform-provider-kubernetes/issues/918 which is causing helm to fail to apply a change due to an Unauthorized error. This would be fine, but unfortunately due to this issue, the helm provider seems to be updating the state file anyway. On a subsequent apply the helm provider does a refresh and detects no changes despite the previous changes failing. This is obviously a huge violation of the expectations of a terraform provider doing a refresh. To fix it we have to taint the resource to get the helm provider to re-apply the correct config.

I really think this should be triaged as a bug rather than an enhancement.

**Comment by jw-maynard** [comment]
We're also experiencing the same issue as @mmerickel. If we run into the Unauthorized issue it looks like the Helm provider is updating the state file even though it doesn't up date the cluster. Further runs detect no changes to be applied because the provider only compares with the state file and doesn't bother to check the actual state of the cluster.

@j-martin @dak1n1  I also think this is a bug rather than an enhancement.

**Comment by iBrandyJackson** [comment]
@mmerickel @jw-maynard @j-martin 

We suspect this issue should now be resolved. If you are still running into this issue, please let us know so that we can prioritize and investigate further, if this problem no longer exists please confirm and close this issue. Thanks!

**Comment by j-martin** [comment]
@iBrandyJackson Yes, as far as I am concerned https://github.com/hashicorp/terraform-provider-helm/pull/702 solved my use case (and more). Did the flag graduate beyond being experimental?

**Comment by iBrandyJackson** [comment]
@j-martin - thanks for the feedback. Still experimental for the moment. 

Closing issue as this helps our maintainers find and focus on the active issues.  If you have found a problem that seems related to this change, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
