### ISSUE TITLE
helm_release fails without depends_on

### ISSUE THREAD

**Issue by kaushalringle** [hashicorp/terraform-provider-helm#535]
### Terraform Version and Provider Version
terraform 0.12.26

### Provider Version
provider.aws  "2.67.0"
provider.helm  "1.2.3"
provider.kubernetes  "1.11.3"

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl

terraform {
  required_version = ">= 0.12.20"
}

provider "aws" {
  version = ">= 2.48.0"
}

provider "helm" {
  version = ">= 1.1"
}

provider "kubernetes" {
  version = ">= 1.11"
}

resource "kubernetes_namespace" "kube_ns" {
  metadata {
    name = "sonarqube-test"
    annotations = {
      Name = "sonarqube-namespace"
    }
  }
}

resource "helm_release" "sonarqube" {
  name = "sonarqube"
  namespace = kubernetes_namespace.kube_ns.metadata[0].name
  chart = "../chart"
  dependency_update = true
  values = [
    file("../chart/values.yaml")
  ]
}

data "kubernetes_service" "kube_svc" {
  metadata {
    namespace = kubernetes_namespace.kube_ns.metadata[0].name
    name      = "${helm_release.sonarqube.name}-sonarqube"
  }
}


output "chart" {
  value = helm_release.sonarqube.metadata
}
```

### Debug Output
https://gist.github.com/kaushalringle/338ff78544e9178a58fe4eaae8e99514

### Expected Behavior
When using helm_release terraform should wait or recognize kubernetes service created by helm_release.

### Actual Behavior
The helm_release fails with an error that it does not find the service created by helm_release. 

Error: services "sonarqube-sonarqube" not found

  on main.tf line 36, in data "kubernetes_service" "kube_svc":
  36: data "kubernetes_service" "kube_svc" {

### Steps to Reproduce
1. `terraform apply`

### Important Factoids

helm_release succeeds if depends_on is used 

```hcl
data "kubernetes_service" "kube_svc" {
  metadata {
    namespace = kubernetes_namespace.kube_ns.metadata[0].name
    name      = "${helm_release.sonarqube.name}-sonarqube"
  }
  depends_on = [helm_release.sonarqube]
}
```

**Comment by imw** [comment]
I believe this also applies to CRDs created via helm_release. Using the name output of the release as input to another resource or module does not guarantee that the release is already in the successful state (or that the CRDs are propagated).

**Comment by alexsomesan** [comment]
Have you tried setting `wait = true` on the `helm_release` resource? It might help in this case.

**Comment by JesterOrNot** [comment]
For the namespace not sure if this helps but instead of directly creating the namespace try putting the name of the desired namespace in the `helm_release` and adding `create_namespace = true`

**Comment by kaushalringle** [comment]
Thanks @alexsomesan  @JesterOrNot 

Using `wait = true` in the resource `helm_release` without using `depends_on` worked for me.

**Comment by kaushalringle** [comment]
Sorry i should have checked it earlier, by default value for wait `wait = true `. 
terraform destroy gave me the same error. 

If anyone else is able to solve this please let me know.

**Comment by ilyar** [comment]
Same problem, got "Error: rpc error: code = Unavailable desc = transport is closing":

```
resource "kubernetes_namespace" "cert_manager" {
  metadata {
    name = "cert-manager"
  }
}
resource "helm_release" "cert_manager" {
  name       = "cert-manager"
  repository = "https://charts.jetstack.io"
  chart      = "cert-manager"
  namespace  = kubernetes_namespace.cert_manager.metadata.0.name

  wait = true

  values = [<<EOF
installCRDs: true
global:
  leaderElection:
    namespace: ${kubernetes_namespace.cert_manager.metadata.0.name}
EOF
  ]
}
resource "kubernetes_manifest" "cert_manager_issuer" {
  provider = kubernetes-alpha

  depends_on = [
    helm_release.cert_manager,
  ]

  manifest = {
    "metadata" = {
      "name" = "letsencrypt"
    }
    "apiVersion" = "cert-manager.io/v1"
    "kind"       = "ClusterIssuer"
    "spec" = {
      "acme" = {
        "preferredChain" = ""
        "privateKeySecretRef" = {
          "name" = "letsencrypt-issuer-account-key"
        }
        "server" = "https://acme-v02.api.letsencrypt.org/directory"
        "solvers" = [
          {
            http01 = {
              "ingress" = {
                "class" = "nginx"
              }
            }
          },
        ]
      }
    }
  }
}
```
