### ISSUE TITLE
using set for comma separated variables fails

### ISSUE THREAD

**Issue by MeNsaaH** [hashicorp/terraform-provider-helm#547]
### Provider Version
1.2.3
### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "azure_ingress" {
  name             = "azure-ingress"
  repository       = "https://appgwingress.blob.core.windows.net/ingress-azure-helm-package"
  chart            = "ingress-azure"

  set {
     name  = "kubernetes.watchNamespace"
     value = "default,dev"
   }
}
```

### Panic Output

```bash
Error: failed parsing key "kubernetes.watchNamespace" with value default,dev, key "dev" has no value                                                                                          
```

### Expected Behavior

Should set to `kubernetes.watchNamespace` value to `default,dev` as required by azure ingress
### Steps to Reproduce

1. `terraform apply`

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by MeNsaaH** [comment]
My current work around is to use 
```hcl
locals {
  watch_ns = "default,dev"
  values = {
    kubernetes = {
      watchNamespace = local.watch_ns
    }
  }
}
```
then set the 
```hcl
resource "helm_release" "azure_ingress" {
  name             = "ingress-azure"
  repository       = "https://appgwingress.blob.core.windows.net/ingress-azure-helm-package"
  chart            = "ingress-azure"


  values = [yamlencode(local.values)]
```

**Comment by fabianedl777** [comment]
Maybe needs scape separated character https://github.com/hashicorp/terraform-provider-helm/issues/461#issuecomment-611131596

**Comment by MeNsaaH** [comment]
Okay @fabianedl777 , I'll try this
