### ISSUE TITLE
Add proxy support in the provider config

### ISSUE THREAD

**Issue by bugok** [hashicorp/terraform-provider-helm#552]
### Description

Today, the way to configure a proxy for the helm provider is to define the `http_proxy` and `https_proxy` environment variables when executing terraform. I'd like to suggest to add `http_proxy` and `https_proxy` configuration options for the helm provider.

I'm not sure if this is a helm issue or a helm-provider issue, but the usage of the `http_proxy` and `https_proxy` environment variables is less common than using the `HTTP_PROXY` and `HTTPS_PROXY` environment variables. Being able to use the capitalized versions might also be useful.

### Potential Terraform Configuration

```hcl
provider "helm" {
  kubernetes {
    config_path = "/path/to/kube_cluster.yaml"
  }
  http_proxy = myproxy:8080
  https_proxy = myproxy:8080
}```

### References

None.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by teddylear** [comment]
I'll look into issue.

**Comment by teddylear** [comment]
I created a small PR for change and ran tests locally using `make build`. I'm not sure what other testing has to be added to this PR to make sure that this change is working correctly. @bugok Please let me know if I'm missing anything on the PR so that I can add and address issues.

**Comment by bugok** [comment]
@teddylear: Thanks for doing this!

Looking at the code, I see a few things:

- The code seems to be what's needed. Trying to run `helm` with `HTTPS_PROXY` and `HTTP_PROXY` seem to be working - but that's unrelated to the provider code. I can check this - by building the provider myself and using it in my terraform code, but I'm not sure how to do this. Do you know where I can read about 1. building the provider myself and 2. How to run terraform with local/dev-versions of providers?
- Documentation of this change in the README.md file is missing.
- There's a failed test in the CI: https://github.com/hashicorp/terraform-provider-helm/pull/574/checks

**Comment by teddylear** [comment]
@bugok the [contributing guidelines](https://github.com/hashicorp/terraform-provider-helm/blob/master/_about/CONTRIBUTING.md) cover how to develop the guidelines locally. I believe there is some changes required in the CHANGELOG.md, not the README.md. However, I'm not sure if those are automated or not. Also all the CI tests are failing on PRs due to a known issue with the test framework. @jrhouston @aareet  Is there anything that I am missing for this PR to get merged? Also does this PR have to wait for the test updates as well?
