### ISSUE TITLE
verify flag throws `Error: failed to download (hint: running `helm repo update` may help)` 

### ISSUE THREAD

**Issue by onlydole** [hashicorp/terraform-provider-helm#554]
### Provider Version

```sh
Terraform v0.12.29
+ provider.datadog v2.12.0
+ provider.google v3.32.0
+ provider.google-beta v3.32.0
+ provider.helm v1.2.4
+ provider.http v1.2.0
+ provider.kubernetes v1.11.4
+ provider.null v2.1.2
+ provider.random v2.3.0
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
provider "helm" {
  kubernetes {
    host                   = "https://${module.gke_cluster.endpoint}"
    token                  = data.google_client_config.default.access_token
    cluster_ca_certificate = base64decode(module.gke_cluster.ca_certificate)
  }
}

resource "helm_release" "datadog_agent" {
  name      = "datadog-agent"
  chart     = "stable/datadog"
  version   = "2.3.41"
  namespace = kubernetes_namespace.xxx.id
  verify = true
  set_sensitive {
    name  = "datadog.apiKey"
    value = var.datadog_api_key
  }
}
```

### Debug Output

`Error: failed to download "stable/datadog" (hint: running `helm repo update` may help)`

### Expected Behavior

The Helm chart should have installed without issue.

### Actual Behavior

`Error: failed to download (hint: running `helm repo update` may help)`

### Steps to Reproduce

1. Create a Kubernetes cluster
2. Ensure you can authenticate to that cluster
3. Use the code example above
4. `terraform apply`

### Important Factoids

This **ONLY** occurs when `verify = true` is in use. If it is set to `false` then this works without issue and installs properly.

### References
- #537 
- #441 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
@onlydole does this only occur with terraform or does the chart exhibit the same behaviour when the --verify option is used directly with helm?

**Comment by onlydole** [comment]
@aareet - good catch! I do get an error with Helm when adding `--verify`

```sh
helm install datadog-agent --set datadog.apiKey=xxx stable/datadog --verify

Error: failed to download "stable/datadog" (hint: running `helm repo update` may help)
```

**Comment by aareet** [comment]
Thanks for checking @onlydole , I think we can close this one since it seems to be an upstream issue with the chart. That's what we found with issues similar to this one in the past as well.

**Comment by onlydole** [comment]
Absolutely agree - thank you, @aareet!
