### ISSUE TITLE
Quick inner Dev Loop for Chart Developers

### ISSUE THREAD

**Issue by meysholdt** [hashicorp/terraform-provider-helm#557]
### Description

When I edit [local charts](https://www.terraform.io/docs/providers/helm/r/release.html#example-usage-local-chart) and install them via `helm_release` resource and `terraform apply`, I would like `terraform` to apply them in-place every time anything inside the chart changes. For example, changes to the template files or any file from the helm context should cause the chart to be applied again in-place. I could simply not use Terraform, but Terraform supplies many values of my helm chart, so it's convenient to run helm through Terraform.

Workarounds:
* run `helm delete` on my chart before I run `terraform apply`
* manually taint the chart in Terraform
* increase the version number of the chart each time I make a change.

### Potential Terraform Configuration

```hcl
resource "helm_release" "local" {
  name       = "my-local-chart"
  chart      = "./charts/example"
}
```

### Community Note

Did I miss something and this is already possible?

**Comment by jrhouston** [comment]
If I've understood correctly, I think you're asking for terraform to diff on the contents of a local chart directory. So this is a duplicate of https://github.com/hashicorp/terraform-provider-helm/issues/346.
