### ISSUE TITLE
Upgrading helm releases rather than replacing them

### ISSUE THREAD

**Issue by jamesla** [hashicorp/terraform-provider-helm#568]
When I taint a helm_release it wants to replace (Destroy then create) the helm release which doesn't really work for stateful resources like stateful sets as there would be data loss when you want to change something trivial such as a URL.

Helm handles this by performing an upgrade. This provider should do the same. Is this currently supported?

**Comment by aareet** [comment]
@jamesla this is the expected behaviour of our taint command (https://www.terraform.io/docs/commands/taint.html)
```
The terraform taint command manually marks a Terraform-managed resource as tainted, forcing it to be destroyed and recreated on the next apply.
```

What are the helm CLI steps that you'd like to replicate with Terraform so we can understand your use case a bit better?

**Comment by sebglon** [comment]
For me the case will be `helm upgrade` and not `heml delete --purge && helm install`
But I am not sure this is a good solution.

**Comment by jamesla** [comment]
> @jamesla this is the expected behaviour of our taint command (https://www.terraform.io/docs/commands/taint.html)
> 
> ```
> The terraform taint command manually marks a Terraform-managed resource as tainted, forcing it to be destroyed and recreated on the next apply.
> ```
> 
> What are the helm CLI steps that you'd like to replicate with Terraform so we can understand your use case a bit better?

Ok thinking about it a bit more the way it works now via taint is right - my bad!

Thanks for your help I'll close this.
