### ISSUE TITLE
Cert-Manager release hanging

### ISSUE THREAD

**Issue by sam-cogan** [hashicorp/terraform-provider-helm#570]
### Terraform Version and Provider Version
0.12.28

### Provider Version
1.2.4
### Affected Resource(s)
Helm Package

### Expected Behavior
Cert-Manager release deploys succesfully

### Actual Behavior
There is a known issue with the cert-manager chart (or any chart with large amounts of nested CRD's) that causes Kubectl or Helm to hang. This is fixed in version 3.3.1 of Helm.  We are seeing this issue occur when attempting to upgrade the cert-manager helm deployment using Terraform, the release hangs indefinately. The 3.3.1 version of Helm is installed on the machine doing the deployment.

Does the Helm provider use the version of Helm on the machine it is running on, or does it bundle it's own version in the provider? If it uses it's own version that would explain the issue.

A manual upgrade using the Helm CLI works as expected.

### Steps to Reproduce

Attempt to upgrade a helm release of version 0.16.0 of Cert-Manager to 0.16.1 using Terraform

### References

- https://github.com/kubernetes/kubernetes/issues/91615

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mcfedr** [comment]
I'm having this same issue. The provider users the helm go api, not the installed app, you can see the version here - [`helm.sh/helm/v3 v3.2.0`](https://github.com/hashicorp/terraform-provider-helm/blob/master/go.mod#L9)

**Comment by sam-cogan** [comment]
Ok, makes sense why it is causing a problem then. Guess this needs updating. Have added a feature request for this to be done.

**Comment by aareet** [comment]
@sam-cogan I'll close this in favour of #571 to avoid duplication - we're tracking progress on that issue.
