### ISSUE TITLE
Update Helm to 3.3.1

### ISSUE THREAD

**Issue by sam-cogan** [hashicorp/terraform-provider-helm#571]
### Description

There is a known issue with older versions of Helm and Kubectl where they will hang when processing large nested CRD's. This is impacting deployment of charts such as cert-manager. 

The Helm library should be updated to the 3.3.1 release.

### References
https://github.com/kubernetes/kubernetes/issues/91615
https://github.com/hashicorp/terraform-provider-helm/issues/570

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mcfedr** [comment]
https://github.com/hashicorp/terraform-provider-helm/pull/572

**Comment by sam-cogan** [comment]
@mcfedr  would be good to get that bumped to 3.3.1, as it's this change that fixes the issue:

> Bump Kubernetes to v0.18.8 + Bump jsonpatch

**Comment by ajchiarello** [comment]
Upvoting this, as helm 3.3.1 is a requirement for upgrading cert-manager to v1.

**Comment by dex4er** [comment]
I think now some workaround might be to install CRDs with Kubernetes alpha provider (https://www.hashicorp.com/blog/deploy-any-resource-with-the-new-kubernetes-provider-for-hashicorp-terraform) and install cert-manager chart without CRDs but it is really ugly hack.

**Comment by mcfedr** [comment]
@dex4er would be much easier to do that if https://github.com/hashicorp/terraform-provider-http/issues/15 was fixed, and you could download the crds yaml, otherwise you need to manually download the yaml and store it. If that was fixed I'd probably stop using helm to install cert-manager, just the plain yaml install with kubernetes-alpha
