### ISSUE TITLE
Helm chart repository for ingress-nginx is not recognized

### ISSUE THREAD

**Issue by rokerkony** [hashicorp/terraform-provider-helm#573]
### Terraform Version and Provider Version
Terraform v0.12.26
+ provider.google v3.37.0
+ provider.helm v1.2.4
+ provider.kubernetes v1.12.0

**Helm version:**
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}

### Affected Resource(s)
- helm_release
- helm_repository

### Terraform Configuration Files
```hcl
provider "helm" {
  kubernetes {}
}

resource "helm_release" "ingress-nginx" {
  name       = "ingress-nginx"
  repository = "https://kubernetes.github.io/ingress-nginx/"
  chart      = "ingress-nginx/ingress-nginx"
}
```

### Expected Behavior
It should find the chart in the repository and install ingress

### Actual Behavior
It fails with "chart not found"

```sh
helm_release.ingress-nginx: Creating...

Error: chart "ingress-nginx/ingress-nginx" not found in https://kubernetes.github.io/ingress-nginx/ repository

  on helm.tf line 8, in resource "helm_release" "ingress-nginx":
   8: resource "helm_release" "ingress-nginx" {
```

**Important note to mention:**
When I use a deprecated `data helm_repository` as:
```hcl
data "helm_repository" "ingress" {
  name = "ingress"
  url  = "https://kubernetes.github.io/ingress-nginx/"
}
```
and reference it as `repository = data.helm_repository.ingress.metadata.0.name` in the `helm_release`, terraform will successfully install everything

### Steps to Reproduce
1. `terraform apply` with the resource above on an empty GKE cluster

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by redeux** [comment]
Thanks for opening this issue @rokerkony.  The chart should just be `ingress-nginx` rather than `ingress-nginx/ingress-nginx`.  When you use Helm and you specify a chart like `ingress-nginx/ingress-nginx` the format is `<repository>/<chart>`, but in the `helm_release` resource you're already specifying the repo directly through the URL.

It is also possible to use the `<repository>/<chart>` format here if you are running Terraform on a system that the repository has been added to with `helm repo add` but this is not recommended.

**Comment by rokerkony** [comment]
hi @Redeux thank you for fast response and it was working for `ingress-nginx`.

I will just add for a reference how to install helm charts from a stable repository (if someone else would have similar issue) as the repository field has to be filled as well otherwise it fails with:
```
Error: failed to download "oauth2-proxy" (hint: running `helm repo update` may help)

  on helm.tf line 24, in resource "helm_release" "helm-github-oauth":
  24: resource "helm_release" "helm-github-oauth" {
```

So the (hopefully) correct way of installing anything from stable is (notice URL for stable repo):
```hcl
resource "helm_release" "helm-github-oauth" {
  name  = "helm-github-oauth"
  repository = "https://kubernetes-charts.storage.googleapis.com"
  chart = "oauth2-proxy"
}
```

Not sure if I was missing some part of the documentation or it is indeed missing there and can be improved. Feel free to close the issue.

**Comment by redeux** [comment]
Thanks for the feedback.  We'll take a look at the docs and see if we can improvements in this area.
