### ISSUE TITLE
With local chart, the version upgrade on the resource not trigger a diff

### ISSUE THREAD

**Issue by sebglon** [hashicorp/terraform-provider-helm#575]
### Provider Version
version 1.3.0

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "onboarder" {
  name              = local.pfid
  chart             = "${path.module}/local-chart"
  namespace         = local.pfid
  dependency_update = true
  version = var.version
  values = [
    file("values.yaml"),
  ]

}
```

### Expected Behavior

If I change the variable `version`, I need to trigger an update. 
Even without changing the version in the chart.yaml file (always with 0.0.0-0).

### Actual Behavior

No diff detected and the same if i change a file on my local chart
 
### Steps to Reproduce

1. `terraform apply` with var.version=0.0.1 ==> release is created
2. `terraform apply` with var.version=0.0.2 ==> release is not updated

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sebglon** [comment]
A possible solution will be to set the code like that [here](https://github.com/hashicorp/terraform-provider-helm/blob/f8549984f98e59bc46c8dbaa61370d190416ddf2/helm/resource_release.go#L682):
```
	// Set desired version from the resource or the Chart metadata if available
	if len(cpo.Version) > 0 {
		return d.SetNew("version", cpo.Version)
	} else if len(c.Metadata.Version) > 0 {
		return d.SetNew("version", c.Metadata.Version)
	}
```

**Comment by aareet** [comment]
Thanks for this issue @sebglon , we like your proposed implementation for this feature. If you'd like to submit a PR, we'd be happy to review, otherwise this had been added to our queue.
