### ISSUE TITLE
Dependency are not downloaded when we update the local chart

### ISSUE THREAD

**Issue by sebglon** [hashicorp/terraform-provider-helm#576]
### Provider Version
1.3.0

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "onboarder" {
  name              = local.pfid
  chart             = "${path.module}/local-chart"
  namespace         = local.pfid
  dependency_update = true
  version = var.version
  values = [
    file("values.yaml"),
  ]
}
```

### Expected Behavior

Dependency are downloaded and helm release is upgraded if we change a chart or update values without the charts folder

### Actual Behavior

Terraform fail because the ./charts folder does not exists and dependency are not found
```
Error: found in Chart.yaml, but missing in charts/ directory: mysql, mysql, mysql, elasticsearch
```

### Steps to Reproduce

1. `terraform apply` with the first chart version => release is created
2. On the local chart delete the folder ./charts
3. `terraform apply` now it fail on the release update because dependency are not downloaded

It seems related to this code [here](https://github.com/hashicorp/terraform-provider-helm/blob/f8549984f98e59bc46c8dbaa61370d190416ddf2/helm/resource_release.go#L472) that is not called on the update function [here](https://github.com/hashicorp/terraform-provider-helm/blob/f8549984f98e59bc46c8dbaa61370d190416ddf2/helm/resource_release.go#L554)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Nadavpe** [comment]
Hey,

We need this fix too. When do you expect it to be release ?

**Comment by sebglon** [comment]
@aareet @dak1n1 Can we have your help to unlock many issued and contributions?

**Comment by techdragon** [comment]
Anyone found workarounds? I've got a number of charts doing this.

Edit: I found somewhat of a workaround for my case, I was able to include the other file in the local copy since the charts I had were local, however this does make things less reusable since effectively I have to manually update the version of the chart that has been vendored into my terraform configuration so it would be better to have this properly fixed.

**Comment by kjetillilleby** [comment]
Hi, 
I had the same problem, and managed to solve it with the 'external' data source. Where I was able to run 'helm dep update'
I also calculated the hash of the  local helm folder, so I could use it as an annotation to make sure  any changes were applied.

```terraform
# Jaeger distributed tracing
data "external" "jaeger-config" {
  program = [
    "./helm_update.sh", "jaeger"
  ]
}

resource "helm_release" "jaeger" {
  name       = "jaeger"
  chart      = "./jaeger"
  namespace  = kubernetes_namespace.istio-system.id
  dependency_update = true

  set {
    name = "jaeger.query.annotations.checksum/jaeger"
    value = data.external.jaeger-config.result["hash"]
  }
}
```

helm_update.sh
```bash
#!/bin/sh

# helm dependency update
helm dep update $1 > /dev/null

# hash of all files in the given folder
hash=$(find $1 -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | cut -d " " -f1)
jq -n --arg h "$hash" '{ hash: $h }'

```

**Comment by hanzala1234** [comment]
@kjetillilleby Great solution!
I wonder what if someone has to run terraform in CI/CD pipeline. how we can manage in that case?
