### ISSUE TITLE
Add additional validation to chart name in helm_release

### ISSUE THREAD

**Issue by jrhouston** [hashicorp/terraform-provider-helm#583]
### Description

In some cases it is not valid to use the `<repo>/<chartname>` notation as the chart name, i.e when the `repository` field is set, but this is currently allowed by the provider schema and is causing some confusion. 

Related to #537 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dak1n1** [comment]
Since I'm looking into upgrading the helm version, I found this new validation added in helm's changelog. https://github.com/helm/helm/commit/c4ef82be13a0a3b6b42ce92bdd0357f4f6ac9e62

It seems not to allow a `/` in the chart name anymore.
