### ISSUE TITLE
There is no options to add labels and annotation to the namespace

### ISSUE THREAD

**Issue by c4m4** [hashicorp/terraform-provider-helm#584]
In few words, I would to add annotations and labels to my app namespace, Now we have create_namespace option to create the namespace, but We don't have other options to add labels and annotions

**Comment by redeux** [comment]
Hi.  Thanks for opening this issue.  After some research it doesn't appear that Helm 3 provides this functionality. We'll discuss whether or not it's appropriate to add to the Helm provider, in the meantime I suggest you use the [Kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/1.12.0/docs/resources/namespace) to create the namespace with the labels and annotations you want, then target the namespace with the `helm_release` resource.  

An example config could look like this:

```hcl

provider "kubernetes" {}
provider "helm" {}

resource "kubernetes_namespace" "example" {
  metadata {
    annotations = {
      name = "example-annotation"
    }

    labels = {
      mylabel = "label-value"
    }

    name = "terraform-example-namespace"
  }
}

resource "helm_release" "example" {
  name = "redis"
  chart = "https://charts.bitnami.com/bitnami/redis-10.7.16.tgz"
  namespace = kubernetes_namespace.example.metadata[0].name
}
```

**Comment by c4m4** [comment]
Hi @Redeux thanks for your quick response, it could be nice to use only the helm provider to do this, in the mean time I am using the kubernetes provider :)
