### ISSUE TITLE
using set for array of maps

### ISSUE THREAD

**Issue by nimrodishi** [hashicorp/terraform-provider-helm#586]
## Extend `set` to support more complex values
[This might be doable now, if so please help me understand how and I'll even document it as I spent a lot of time trying to figure this out]

I tried using set to set an array of maps.
The result I want eventually is:
`
image:
    pullSecrets:
        - name: SOME_SECRET
`
I tried using set:
`
set {
    name = "image.pulSecrets"
    value = VALUE
}
`
where I tried with:
`
VALUE = "-name: SOME_SECRET"
VALUE = "{name: SOME_SECRET}"
`
and some more.
Finally I switched to use the values field and using a multiline string there to set this.

How can this be done using set?

**Comment by lbesson** [comment]
```
set {
    name = "image.pullSecrets[0].name"
    value = "SOME SECRET"
}
```

**Comment by sebglon** [comment]
This issue seems related to this doc: https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set

**Comment by alexsomesan** [comment]
The provider will just pass the value of name in a set block verbatim to Helm. In conclusion, any expression that works with Helm will work with the provider.
