### ISSUE TITLE
Workflow advice

### ISSUE THREAD

**Issue by adrien-barret** [hashicorp/terraform-provider-helm#587]
### Description

My compagny start using k8s and, all the infrastructure part is made with Terraform. 
But we have a problem to decide if we choose or not terraform to deploy our micro-services.

Using terraform will give us one way to rules them all but it remove all the k8s tools such as tilt, skaffold, etc.
Skaffold can create a pipeline itself as terraform do in some way so it can be a good way but it's more code, yaml, etc to maintain. 

Question is how do you manage that kind of use inside  Hashicorp ?  
What process did you choose to get the live build/debug to your developper when they work on kubernetes apps ?
Is it a trick with Terraform which give us the terraform usage and code but keeping the live code/debug of skaffold or tilt ?

Ty,
Hk

**Comment by aareet** [comment]
Hi @Hkyx , thanks for this - this looks like a topic for our [community forums](https://discuss.hashicorp.com/c/terraform-core/27). We try to reserve these issues for enhancements/bugs. I'll close this for now.
