### ISSUE TITLE
Not able to use the set function with list

### ISSUE THREAD

**Issue by jknott-terraform** [hashicorp/terraform-provider-helm#588]
### Terraform Version and Provider Version
terraform 13.0

### Provider Version
provider version 1.21

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
`resource "helm_release" "logstash" {
  depends_on = [
    kubernetes_namespace.logging,
  ]
  name      = local.logstash_helm_release_name
  chart     = local.logstash_helm_chart_name
  version   = local.logstash_helm_chart_version
  repository = "https://helm.elastic.co"
  namespace = local.logstash_logging_namespace
  timeout   = 300

   values = [
    "${file("../../../modules/common/platform/logging/configuration/${var.environment}-logstash-values.yaml")}"
  ]

set {
  name = "extraEnvs.name[0].AWS_ACCESS_KEY_ID"
  value = jsondecode(data.aws_secretsmanager_secret_version.logstash.secret_string)["AWS_ACCESS_KEY_ID"]
  }

set {
  name = "extraEnvs.name[0].AWS_SECRET_ACCESS_KEY"
  value = jsondecode(data.aws_secretsmanager_secret_version.logstash.secret_string)["AWS_SECRET_ACCESS_KEY"]
  }

}
`

### Error
did not find expected '-' indicator

Trying to set this list from the values.yaml file
extraEnvs: 
```
      - name: AWS_ACCESS_KEY_ID 
        value: ""
      - name: AWS_SECRET_ACCESS_KEY
        value: ""
```

**Comment by sebglon** [comment]
This is related to this part of helm doc: https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set

**Comment by jknott-terraform** [comment]
Here is the answer to my question in case someone else has the problem.

```
    dynamic "set" {
    for_each = {
      "extraEnvs[0].name"  = "AWS_ACCESS_KEY_ID"
      "extraEnvs[0].value" = local.access_key_id
      "extraEnvs[0].name"  = "AWS_SECRET_ACCESS_KEY"
      "extraEnvs[0].value" = local.secret_access_key
    }
    content {
      name  = set.key
      value = set.value
    }
  }
}
```
