### ISSUE TITLE
Support `repository_update` property which issues a `helm repo update`

### ISSUE THREAD

**Issue by thecosmicfrog** [hashicorp/terraform-provider-helm#596]
### Description

Support `repository_update` property to `helm_release` resource which mirrors functionality provided by `helm repo update` subcommand.

Use case: We use a private Helm repository manager (JFrog Artifactory) which requires authentication to pull Helm charts. We would like to avoid adding the `repository`, `repository_username` and `repository_password` properties if possible, as this requires an **additional** place to be concerned with secrets in our CI/CD system. The Terraform provider for Helm should be able to work with repositories added using `helm repo add`.

### Potential Terraform Configuration

```hcl
resource "helm_release" "my_release" {
  chart             = "helm-repo/my_chart"  # <-- "helm-repo" already configured using "helm repo add"
  version           = "1.2.3"
  name              = "my_release"
  description       = "My release"
  namespace         = "namespace"
  repository_update = true  # <-- new property
}
```

### References

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi! We're trying to steer away from adding functionality to the provider that explicitly requires external actions (outside of Terraform). I know there are some vestiges like that still in the provider, but long term we want to move away from them.

My suggestion would be, since you're already doing `helm repo add` outside of Terraform, to just add a `helm repo update` step to you CI system right before the terraform step. Of course, you also always have the option of incorporating the credentials and the repo URL into the `helm_release` resource and just use that.

**Comment by thecosmicfrog** [comment]
Hi @alexsomesan! Thanks for the response. Yes, we are looking at just using `helm repo update` as part of the CI pipeline as you mentioned. I figured I'd just ask to see if there was any interest in a dedicated property for the provider.

Thanks again! - Aaron

**Comment by thecosmicfrog** [comment]
Going to leave this open in case there are any discussions/counterpoints which can potentially take place. If this is unwanted, feel welcome to close.

**Comment by aareet** [comment]
Thanks @thecosmicfrog, no offense meant, but we'd prefer it closed since it's not a path that we will consider taking right now. Discussion can absolutely still continue regardless and we can reopen to reevaluate if a compelling use case emerges.

**Comment by thecosmicfrog** [comment]
Not at all - thanks @aareet!
