### ISSUE TITLE
config_path not being used

### ISSUE THREAD

**Issue by andrewrynhard** [hashicorp/terraform-provider-helm#6]
I am trying to specify an alternative path to the kubeconfig:
```
provider "helm" {
  kubernetes {
    config_path = "~/path/to/config"
  }
}
```
but I am seeing this:
```
Error running plan: 1 error(s) occurred:

* provider.helm: error creating tunnel: "Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp [::1]:8080: getsockopt: connection refused"
```

### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- provider

**Comment by calind** [comment]
I think you should be using terraform 0.10.0 or grater.

**Comment by andrewrynhard** [comment]
@calind You might be correct. Just double checked the requirements.

**Comment by andrewrynhard** [comment]
although, I don't see any logic for handling that here: https://github.com/mcuadros/terraform-provider-helm/blob/master/helm/provider.go#L195-L243

**Comment by mcuadros** [comment]
I am fixing it right now. Thanks for reporting it.

**Comment by andrewrynhard** [comment]
@mcuadros I see Terraform 0.10 as a requirement. Unfortunately, Terragrunt does not work with that version of TF yet. I am seeing some strange things with this provider and I don't know if it could be due to the fact that I am using TF 0.9.11. When I create charts, I get errors that some resources already exist (a `ConfigMap` for example). I am also seeing that a TF `plan` thinks it needs to install charts that already have been created successfully. Has something changed in TF 0.10 that would cause this? I can create another issue if I need to.

**Comment by mcuadros** [comment]
The provider was created for TF 0.10, but I must to say that is completely untested from my side, I never used. I am starting to use this days.

The logic is not very complex, so I don't see why should fail with the plans, anyways as I said, let me use it first.

**Comment by mcuadros** [comment]
I am closing this, if you have more issues, can you open another issue. Thanks!

**Comment by andrewrynhard** [comment]
@mcuadros This issue still exists. #8 fixed the issues I have in the comment, but not the `config_path` issue.

**Comment by mcuadros** [comment]
https://github.com/mcuadros/terraform-provider-helm/releases/tag/v0.2.0

Can you use this version, I just committed the fix.

**Comment by andrewrynhard** [comment]
Ahh yes. Thank you for this provider! Has really fit into our workflow nicely.
