### ISSUE TITLE
CSR Approval Required for Helm Chart

### ISSUE THREAD

**Issue by ghbrown60640** [hashicorp/terraform-provider-helm#603]
Having the same issue as #96 in  version 1.3.2 of the plugin (Same application - CockroachDB) the pods require CSR approval in order to get into a "Running" state. The terraform script ends up timing out. Is there a way to either have the plugin approve the CSRs or not wait to get into "Running" state?

**Comment by jrhouston** [comment]
Thanks for opening this @ghbrown60640 you should be able to set `wait = false` on the helm_release so that it doesn't wait. Let me know if that works for you. 

There isn't a way to auto-approve CSRs with the provider, as we would defer to Helm itself on how CSRs should be auto-approved.

**Comment by aareet** [comment]
I'm going to close this issue since it's a problem upstream and it has been about a month since John posted the workaround.
