### ISSUE TITLE
Helm upgrade question

### ISSUE THREAD

**Issue by FLavalliere** [hashicorp/terraform-provider-helm#606]
We are using helm 3.3.4 and terraform 0.13.3

We are seeing a weird behavior when updaring the chart (path) and some env variables.

Is the helm provider supposed to do an helm upgrade? or does it an helm delete + helm install or an helm upgrade?

**Comment by FLavalliere** [comment]
It seems its doing an helm upgrade but somehow all the Pod's in the Deployment gets deleted. Not too sure why its happening.

**Comment by FLavalliere** [comment]
Here are my understanding of what happening.

When using terraform  helm_release to deploy here what is happening.

Let say I have an deploymet with replicaset of 4 and i want to do 25% rollingUpdate strategy.

When the upgrades occurs the current running pods of the old replicaset goes into Terminating state and the old replicaset creates 4 new pods. (i can see this due to the hashes in the pods names).

Then at the same time the new ReplicaSet create its 4 new pods.

At that moment there is an issue where no active endpoints exists.


Though updating the deployment manually (via kubectl edit deployment). The correct behavior occurs.

**Comment by alexsomesan** [comment]
@FLavalliere Are you able to achieve the same operations with just standalone Helm? It would be helpful to know that so that we can narrow down the issue to the provider or the chart itself.

**Comment by ACenterA-SLNet** [comment]
Havent yet tried with standalone helm. I'll have to work on it though.

I believe it is an helm issue more than an terraform-helm but hard to tell as i havent used helm manually to deploy.

If i manually edit the k8s 'deployment' to update something such as the docker image it works well, ie: perform the rolling update as needed.

But either terraform or helm recreate the 'old replicaset' which terminates all the existing pods with the OLD image and then recreate with the OLD image. Then perfom the creation of new replicaset with the new IMAGE doing rolling update.

**Comment by FLavalliere** [comment]
Havent yet tried with standalone helm.

I believe it is an helm issue more than an terraform-helm but hard to tell as i havent used helm manually to deploy.

If i manually edit the k8s 'deployment' to update something such as the docker image it works well, ie: perform the rolling update as needed.

But either terraform or helm recreate the 'old replicaset' which terminates all the existing pods with the OLD image and then recreate with the OLD image. Then perfom the creation of new replicaset with the new IMAGE doing rolling update.

**Comment by alexsomesan** [comment]
With the information at hand, I cannot tell for certain if this issue is also present in Helm, but it seems very unlikely to be a provider issue, going by the details above.
I would be inclined to think this is an issue of how the chart is designed. We would need to reproduce and A/B test against Helm alone. For that we would need some reproduction scenario or instructions.

I'm going to close this now as there isn't much to go any further by. Please feel free to reopen if you can supply us a reproduction chart or additional instructions. Thanks!
