### ISSUE TITLE
Enable/Disable release deployment

### ISSUE THREAD

**Issue by ranrubin** [hashicorp/terraform-provider-helm#607]
### Description

I'm new to terraform so it's possible that there is a solution to this and I just couldn't find it.

I'm using Terraform to deploy a k8s cluster. As part of this deployment, I also deploy a few Helm charts. 
In some cases, I would like only some of the charts to be deployed. I think that controlling whether to deploy a certain chart with a variable could be nice.

### Potential Terraform Configuration

```hcl
resource "helm_release" "k8s-device-plugin" {
  name       = "k8s-device-plugin"
  chart      = "https://nvidia.github.com/k8s-device-plugin/stable/nvidia-device-plugin-0.7.0.tgz"
  namespace = "kube-system"
  enable =  var.enable_k8s_device_chart
}
```

### References

[This issue](https://github.com/hashicorp/terraform/issues/12906) might be related 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by zentale** [comment]
Hi, reading this should help you out: https://blog.gruntwork.io/terraform-tips-tricks-loops-if-statements-and-gotchas-f739bbae55f9

**Comment by ranrubin** [comment]
Thanks!
