### ISSUE TITLE
Add better docs for using set block

### ISSUE THREAD

**Issue by jrhouston** [hashicorp/terraform-provider-helm#612]
### Description

We should provide some more detailed examples on how to supply more complex values to a release, and make reference to the helm docs: https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by FixItDad** [comment]
Please include a comment about needing to escape characters in the "name" field especially when adding annotations. I lost a day of work before figuring this out. I noticed the 1 example at the bottom that illustrates after I figured out what was going on.
The example is on the providers/hashicorp/helm/latest/docs/resources/release page of registry.terraform.io
Thanks!

**Comment by nichoio** [comment]
This would be highly appreciated. It is also not quite clear when it is required to use `set` or `values` respectively. For example, I needed to pass a list as Helm value and this only worked through `values`, but not `set`.
