### ISSUE TITLE
Add better docs for using Helm Plugins

### ISSUE THREAD

**Issue by jrhouston** [hashicorp/terraform-provider-helm#613]
### Description

The provider will let you use additional plugins such as S3 and GCS for repositories, but we don't document how this is supposed to work anywhere. We should add some documentation on how this works and it's limitations, and link through to the Helm documentation and the respective plugin documentation.

- [x] S3 Example
- [x] GCS Example

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by koalalorenzo** [comment]
Might sound stupid but, How do we use plugins? I am looking for GCS examples :D 
I would love to help with a PR and adds more documentation, but I can't find anything to know how to do it!

Any help?
