### ISSUE TITLE
support timeouts for helm charts

### ISSUE THREAD

**Issue by tibers** [hashicorp/terraform-provider-helm#615]
### Description

See https://www.terraform.io/docs/configuration/resources.html#operation-timeouts

### Potential Terraform Configuration

Please support something like
```hcl
resource "helm_release" "mydatabase" {
  name  = "mydatabase"
  chart = "stable/mariadb"
  timeouts {
    create = "60m"
    delete = "2h"
  }
...
}
```

### References

This is probably related to https://github.com/hashicorp/terraform-provider-helm/issues/463

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
@tibers as you mentioned, this seems related to #463. I'll close this issue in favour of that since we should track it in a single place.
