### ISSUE TITLE
I cannot terraform a previously existing release

### ISSUE THREAD

**Issue by djhaskin987-at-sling** [hashicorp/terraform-provider-helm#62]
I want to be able to run `terraform apply` and have a previously existing helm release be managed by Terraform, rather then Terraform throwing an error saying that the release already exists.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

terraform-chart-b $ terraform -v
Terraform v0.11.5
+ provider.helm (unversioned)

### Affected Resource(s)

Please list the resources as a list, for example:
- module.release_a.helm_release.ops_a
- helm_release.ops_b

### Terraform Configuration Files

I created two terraform modules, one called `terraform-chart-a` and one called `terraform-chart-b`.

Each module contained a chart and a tf state file to install that chart.

The charts were created simply by calling `helm create`, as in `helm create a` and `helm create b`.

The files in `terraform-chart-a`:

```
terraform-chart-a $ tree
.
├── charts
│   └── a
│       ├── Chart.yaml
│       ├── charts
│       ├── templates
│       │   ├── NOTES.txt
│       │   ├── _helpers.tpl
│       │   ├── deployment.yaml
│       │   ├── ingress.yaml
│       │   └── service.yaml
│       └── values.yaml
└── main.tf
```

`terraform-chart-a/main.tf`:

```hcl
resource "helm_release" "ops_a" {
    name = "x"
    chart = "${path.module}/charts/a"
}
```

The files in `terraform-chart-b`:

```
terraform-chart-b $ tree
.
├── charts
│   └── b
│       ├── Chart.yaml
│       ├── charts
│       ├── templates
│       │   ├── NOTES.txt
│       │   ├── _helpers.tpl
│       │   ├── deployment.yaml
│       │   ├── ingress.yaml
│       │   └── service.yaml
│       └── values.yaml
├── main.tf
├── terraform.tfstate
├── terraform.tfstate.backup
└── terraform.tfstate.d
    └── jenkins

6 directories, 10 files
```

`terraform-chart-b/main.tf`:

```hcl
module "release_a" {
    source = "git::ssh://<redacted>/terraform-chart-a.git?ref=master"
}

resource "helm_release" "ops_b" {
    name = "b"
    chart = "${path.module}/charts/b"
    depends_on = ["module.release_a"]
}
```

### Debug Output

https://gist.github.com/djhaskin987-at-sling/b3190dd59a219363f45fdfc16c2979f9

### Steps to Reproduce

The following steps provide a way to simulate a situation where there are pre-existing releases in helm and I am trying to write a terraform module to manage them.

1. Go into terraform-chart-b repository.
2. Run terraform apply.
3. Delete the terraform state files.

Now, we have an environment where there are previously-existing releases which terraform knows nothing about within Tiller/Helm.

Now, I *want* to be able to do this:

1. Go into terraform-chart-b repository.
2. Run `terraform apply`.

### Expected Behavior
- Have the terraform state files get updated to reflect that there's a release which already exists.
- Have the terraform apply be a no-op; it doesn't re-install since there is already a release present.

### Actual Behavior

See the debug output. Basically, helm says "I tried to create those releases, but they already exist". Terraform throws an error; see the debug output in the gist above.

### Important Factoids
Running in minikube on the latest version of master for the provider and Terraform 0.11.5 .

### Remarks
This functionality can be implemented either by the plugin supporting terraform import, or it would be cool if there were some way to tell the plugin to run `helm upgrade --install` instead of `helm install` on a create, so that if a previous release already existed, terraform would "swallow" it instead of erroring.

**Comment by djha-skin** [comment]
I ended up solving this problem by writing my own terraform provider, here: https://github.com/djhaskin987/terraform-provider-helmcmd

**Comment by gregdhill** [comment]
I was able to circumvent this issue by running `terraform refresh` before `terraform apply`.

**Comment by rporres** [comment]
This provider still lacks of importing. Working on it on https://github.com/terraform-providers/terraform-provider-helm/pull/150

Closing this in favour of https://github.com/terraform-providers/terraform-provider-helm/issues/113
