### ISSUE TITLE
Add capability to set environment variables through provider

### ISSUE THREAD

**Issue by Aidan-Pasquale99** [hashicorp/terraform-provider-helm#621]
When invoking a Helm chart through a `helm_release` resource, there doesn't seem to be a way to set custom environment variables for the pods. The `set` block only sets properties that can be in the chart's values file.

**Comment by jrhouston** [comment]
Hi @Aidan-Pasquale99 thanks for opening an issue. I'm not entirely sure what you're asking for here. Environment variables are usually handled at the chart level and are typically exposed with a `env` block somewhere in the values file. Helm doesn't have a generic way to specify environment variables for pods inside a chart as far as I know.

**Comment by aareet** [comment]
Closing issue since it has been 2 months.
