### ISSUE TITLE
Repo forced to Helm.sh

### ISSUE THREAD

**Issue by h4wkmoon** [hashicorp/terraform-provider-helm#622]
### Terraform Version and Provider Version
Terraform v0.13.5

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "karma" {
  name       = "karma-${terraform.workspace}"
  repository = "https://kubernetes-charts.storage.googleapis.com"
  chart      = "karma"
  timeout    = var.helm_timeout
  namespace  = kubernetes_namespace.prometheus.metadata[0].name
  values     = [data.template_file.karma-values.rendered]
}
```

### Debug Output

```
helm_release.karma: Creating...
helm_release.prometheus: Creating...

Error: failed to fetch https://charts.helm.sh/stable/karma-1.7.2.tgz : 404 Not Found

  on karma.tf line 1, in resource "helm_release" "karma":
   1: resource "helm_release" "karma" {
```

No addition output is produced, even with HELM_DEBUG=1

### Expected Behavior
Download chart from the repo set in the hcl. Not from Helm.sh

### Actual Behavior
Helm.sh is used

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
None that I know of.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by h4wkmoon** [comment]
It looks like it is a pebkac, and I'm sorry for that.
The charts I need are not in the repo i've set in the hcl anymore. This explains the "failed to fetch" part of the error message.
Still, I don't understand why the url shown in the error message shows another repo. Nevermind.

Any way, It's my bad. I sincerely apologize.

**Comment by Sean12697** [comment]
No worries @h4wkmoon, Helm have recently moved their chart locations, being one day before you opened up this issue (I had the same issue that lead me here). Their blog post might be useful to read through as well (especially for others that stumble across this issue): [New Location For Stable and Incubator Charts](https://helm.sh/blog/new-location-stable-incubator-charts/)

**Comment by yves-vogl** [comment]
Hi, I guess there's still a problem with `hashicorp/helm v1.3.2`

As mentioned in the link:


Name | Old Location | New Location
-- | -- | --
stable | https://kubernetes-charts.storage.googleapis.com | https://charts.helm.sh/stable
incubator | https://kubernetes-charts-incubator.storage.googleapis.com | https://charts.helm.sh/incubator


Test with `aws-alb-ingress-controller`

New URL: https://charts.helm.sh/incubator/aws-alb-ingress-controller-1.0.4.tgz

```
curl -I https://charts.helm.sh/incubator/aws-alb-ingress-controller-1.0

HTTP/2 404
content-type: text/html; charset=utf-8
server: GitHub.com
x-origin-cache: HIT
etag: "5f9757f1-247b"
access-control-allow-origin: *
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'
x-proxy-cache: MISS
x-github-request-id: 45F8:B6B9:846FF2:8C686B:5FBF9D6D
accept-ranges: bytes
date: Thu, 26 Nov 2020 12:19:57 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-ams21023-AMS
x-cache: MISS
x-cache-hits: 0
x-timer: S1606393198.786901,VS0,VE93
vary: Accept-Encoding
x-fastly-request-id: 16df3421067fe57a88c03017ac64b5697e400a82
content-length: 9339
```

Old URL: https://kubernetes-charts-incubator.storage.googleapis.com/aws-alb-ingress-controller-1.0.4.tgz

```
curl -I https://kubernetes-charts-incubator.storage.googleapis.com/aws-alb-ingress-controller-1.0.4.tgz
HTTP/2 200
x-guploader-uploadid: ABg5-UyRCV7iDbUGH0zzR34cKSDjI0MLwlnmtZ7zS0Gxvz9Pis4x5OvJvr2Rh7Ft8JSWMGtiwBmiZZpeqdRt9NswmMw
expires: Thu, 26 Nov 2020 13:20:56 GMT
date: Thu, 26 Nov 2020 12:20:56 GMT
cache-control: public, max-age=3600
last-modified: Mon, 16 Nov 2020 16:11:38 GMT
etag: "c9e0617d8744158fcc2c465f2119d747"
x-goog-generation: 1605543098732327
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 6020
x-goog-meta-goog-reserved-file-mtime: 1605542901
content-type: application/x-tar
x-goog-hash: crc32c=dMkH8A==
x-goog-hash: md5=yeBhfYdEFY/MLEZfIRnXRw==
x-goog-storage-class: STANDARD
accept-ranges: bytes
content-length: 6020
server: UploadServer
alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

So as of today the new URL gives a 404 whereas the old URL still works in manual test.

But it seems that the terraform provider is ignoring the specified repository.

```
resource "helm_release" "main" {
  name       = "aws-alb-ingress-controller"
  repository = "https://kubernetes-charts-incubator.storage.googleapis.com"
  chart      = "aws-alb-ingress-controller"
  namespace  = "kube-system"
}
```

This plans to (shortened):

```
resource "helm_release" "main" {
        atomic                     = false
        chart                      = "aws-alb-ingress-controller"
        id                         = "aws-alb-ingress-controller"
        # (…)
        name                       = "aws-alb-ingress-controller"
        repository                 = "https://kubernetes-charts-incubator.storage.googleapis.com"
        #(…)
}
```

…which looks OK but apply errors with:

```Error: failed to download "https://charts.helm.sh/incubator/aws-alb-ingress-controller-1.0.4.tgz" (hint: running `helm repo update` may help)```


So the repository URL is ignored like @h4wkmoon mentioned.

**Comment by yves-vogl** [comment]
We use a workaround provided by @arne21a:

```
resource "helm_release" "main" {
  name = "aws-alb-ingress-controller"
  #repository = "https://kubernetes-charts-incubator.storage.googleapis.com"
  #version   = var.chart_version
  chart     = "https://kubernetes-charts-incubator.storage.googleapis.com/aws-alb-ingress-controller-1.0.4.tgz"
}
```
