### ISSUE TITLE
Allow custom headers when chart is a URL

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform-provider-helm#623]
### Description

Some HTTP hostings like GitLab expect a header to be set providing a token usually. So I currently have to pull down tgz using curl and then run terraform using a local folder as chart reference. I wish I can just specify a custom header and submit a tgz to terraform directly

### Potential Terraform Configuration

```hcl
resource "helm_release" "example" {
  name             = "test"
  chart            = "https://gitlab.example.com/api/v4/projects/111/packages/generic/test/0.0.1/test.tgz"
  namespace        = var.environment
  reuse_values     = true
  create_namespace = true
  wait             = true

  custom_pull_header {
    name = "PRIVATE-TOKEN"
    value = "123"
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Thanks for opening an issue @vladimirtiukhtin. This is an interesting request. Can you share any more about the header that has to be supplied to the server you are using?

As far as I can see there isn't a way to do this with helm itself, as the options are outlined here: https://pkg.go.dev/helm.sh/helm/v3/pkg/action#ChartPathOptions

If there is a compelling case for this though we could have the provider download the chart before calling through to helm.

**Comment by jamiegwatkin** [comment]
We have the same request, we currently tag our helm charts in Gitlab, to authenticate with GItlab the PRIVATE-TOKEN header has to be set.

Without it we're not able to use tagged builds in our TF code which is a real shame.

I'm sure the functionality could be used with Github too.

More than happy to answer any Qs you have about it @jrhouston
