### ISSUE TITLE
Cannot update chart version while a local copy exists

### ISSUE THREAD

**Issue by armsnyder** [hashicorp/terraform-provider-helm#624]
### Terraform Version and Provider Version
```
Terraform v0.12.29
+ provider.helm v1.3.2
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.this.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.this.token
    load_config_file       = false
  }
  version = "~> 1.3.2"
}

resource "helm_release" "rancher" {
  name             = "rancher"
  repository       = "https://releases.rancher.com/server-charts/latest"
  chart            = "rancher"
  version          = "2.5.1" # Changing this to "2.5.2" results in no changes to the Terraform plan.
  namespace        = "cattle-system"
  create_namespace = true

  set {
    name  = "hostname"
    value = "example.com"
  }

  set {
    name  = "ingress.tls.source"
    value = "secret"
  }
}
```

### Debug Output

https://gist.github.com/armsnyder/1afe9e00ad7d7c59900f0ba7bda1afa4

### Expected Behavior

I expect to see a Terraform plan change when I update the "version" argument.

### Actual Behavior

There is no plan, and no way I can tell to update a release version after the initial install.

```
No changes. Infrastructure is up-to-date.
```

### Steps to Reproduce

Reproduced in a new test case here: https://github.com/armsnyder/terraform-provider-helm/commit/f663452ce41ed42f05c5c814b9047f736482fa15

### References

- May be related to #575

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by armsnyder** [comment]
I'm not familiar with this codebase, but I looked at the `resourceDiff` function and found where I think it is suppressing the `version` argument change:

https://github.com/hashicorp/terraform-provider-helm/blob/v1.3.2/helm/resource_release.go#L681-L684

```go
// Set desired version from the Chart metadata if available
if len(c.Metadata.Version) > 0 {
	return d.SetNew("version", c.Metadata.Version)
}
```

However, I can't verify this bug with a test. I wrote a test, but it's passing, on `v1.3.2`.

```go
func TestAccResourceRelease_versionChange(t *testing.T) {
	namespace := fmt.Sprintf("%s-%s", testNamespace, acctest.RandString(10))
	defer deleteNamespace(t, namespace)

	config := `
resource "helm_release" "rancher" {
  name             = "rancher"
  repository       = "https://releases.rancher.com/server-charts/latest"
  chart            = "rancher"
  version          = %q
  namespace        = %q
  create_namespace = true

  set {
    name  = "hostname"
    value = "example.com"
  }

  set {
    name  = "ingress.tls.source"
    value = "secret"
  }
}
`

	resource.Test(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t, "") },
		Providers: testAccProviders,
		Steps: []resource.TestStep{{
			Config: fmt.Sprintf(config, "2.5.1", namespace),
			Check: resource.ComposeAggregateTestCheckFunc(
				resource.TestCheckResourceAttr("helm_release.rancher", "metadata.0.revision", "1"),
				resource.TestCheckResourceAttr("helm_release.rancher", "metadata.0.version", "2.5.1"),
			),
		}, {
			Config: fmt.Sprintf(config, "2.5.2", namespace),
			Check: resource.ComposeAggregateTestCheckFunc(
				resource.TestCheckResourceAttr("helm_release.rancher", "metadata.0.revision", "2"),
				resource.TestCheckResourceAttr("helm_release.rancher", "metadata.0.version", "2.5.2"),
		}},
	})
}
```

Is it possible that the Terraform test SDK is behaving differently than the Terraform CLI, at least for version `v0.12.29` which I am using?

**Comment by armsnyder** [comment]
I found my issue. I had a local copy of the `rancher` chart in the directory where I was running Terraform. That's why it wouldn't reproduce in the test. The `resourceDiff` function calls `LocateChart`, which is returning the local copy instead of the remote chart with the version specified in the resource arguments, so it is overwriting the version with whatever is in the local copy.

This seems like unintended behavior for the provider, and could still use a fix IMO.

**Comment by armsnyder** [comment]
I don't have an idea for how to fix this, but I wrote a failing test that reproduces the issue, for whoever is able to take a look at this.

https://github.com/armsnyder/terraform-provider-helm/commit/f663452ce41ed42f05c5c814b9047f736482fa15

```
=== RUN   TestAccResourceRelease_remoteChartWithVersion
    provider_test.go:162: [DEBUG] Creating namespace terraform-acc-test-pdxhbv8xy4
    resource_release_test.go:241: Step 1/1 error: Check failed: 1 error occurred:
        	* Check 2/3 error: helm_release.test: Attribute 'metadata.0.version' expected "7.0.1", got "0.0.1"
        
--- FAIL: TestAccResourceRelease_remoteChartWithVersion (3.27s)
FAIL

Process finished with exit code 1
```

I think ideally the provider would handle fetching the chart with the correct version, if there are `repository` and `version` resource arguments specified. The problem is that the provider uses the `action.LocateChart` Helm SDK function, which will short circuit if it finds a local chart with a matching name.

**Comment by aareet** [comment]
As you've identified, this is a behaviour of LocateChart, so unfortunately, this is an issue upstream, and not something we can fix in the provider, unless we replace the use of LocateChart.
