### ISSUE TITLE
Changes to a single set{} block causes all blocks to appear in the terraform plan output

### ISSUE THREAD

**Issue by ksvladimir** [hashicorp/terraform-provider-helm#627]
### Terraform Version and Provider Version

Terraform v0.13.5 and v0.14.0-rc1

### Provider Version

v1.3.2

### Affected Resource(s)

- helm_release

### Terraform Configuration Files

```hcl
resource "helm_release" "example" {
  name       = "my-redis-release"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "redis"
  version    = "12.0.1"

  set {
    name  = "cluster.enabled"
    value = "true"  # <<< CHANGE HERE
  }

  set {
    name  = "metrics.enabled"
    value = "true"
  }

  set {
    name  = "service.annotations.prometheus\\.io/port"
    value = "9127"
  }
}
```

### Steps to Reproduce

1. `terraform apply`
2. change true to false next to "<<< CHANGE HERE" above
3. `terraform plan`

### Expected Behavior

I expect to see that only one `set` block has changed.

### Actual Behavior

Terraform plan shows all `set` blocks being removed and added:

```
      + set {
          + name  = "cluster.enabled"
          + value = "false"
        }
      - set {
          - name  = "cluster.enabled" -> null
          - value = "true" -> null
        }
      - set {
          - name  = "metrics.enabled" -> null
          - value = "true" -> null
        }
      + set {
          + name  = "metrics.enabled"
          + value = "true"
        }
      - set {
          - name  = "service.annotations.prometheus\\.io/port" -> null
          - value = "9127" -> null
        }
      + set {
          + name  = "service.annotations.prometheus\\.io/port"
          + value = "9127"
        }
```

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by psr-tv2** [comment]
Seeing the same issue.

**Comment by tculp** [comment]
This is still an issue present in the latest version

**Comment by pawelpesz** [comment]
This is still a problem. And a significant one, IMHO.

**Comment by TheQueenIsDead** [comment]
This provider has been super (for me) ever since the [duplicate ticket](https://github.com/hashicorp/terraform-provider-helm/issues/915) was resolved by the [v2.8.0 release](https://github.com/hashicorp/terraform-provider-helm/releases/tag/v2.8.0).

For those of you still encountering issues, it would be worth specifying your versions and config, as the following example code and versions worked nicely for me:

Versions
```console
$ terraform version
Terraform v1.4.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/helm v2.9.0
```

Config
```terraform
resource "helm_release" "example" {
  name       = "my-release"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "redis"
  version    = "17.9.2"

  set {
    name  = "cluster.enabled"
    value = "true"  # <<< CHANGE HERE
  }

  set {
    name  = "metrics.enabled"
    value = "true"
  }

  set {
    name  = "service.annotations.prometheus\\.io/port"
    value = "9127"
  }
}

terraform {
  required_providers {
    helm = {
      source = "hashicorp/helm"
      version = "2.9.0"
    }
  }
}

provider "helm" {
  # Configuration options
  kubernetes {
    config_path = "~/.kube/config"
  }
}

```


The resultant diff was like so
```terraform
$ tf plan
helm_release.example: Refreshing state... [id=my-release]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # helm_release.example will be updated in-place
  ~ resource "helm_release" "example" {
        id                         = "my-release"
        name                       = "my-release"
        # (27 unchanged attributes hidden)

      - set {
          - name  = "cluster.enabled" -> null
          - value = "true" -> null
        }
      + set {
          + name  = "cluster.enabled"
          + value = "false"
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```


While it could be more concise (Showing a singular `set { value = "*" }` change), only showing the changed set blocks instead of ones that had no change has made this plugin much more usable, solving this issue

**Comment by pawelpesz** [comment]
> only showing the changed set blocks instead of ones that had no change has made this plugin much more usable, solving this issue

Exactly, that would be the expected behaviour. Thanks @TheQueenIsDead 👍

**Comment by TheQueenIsDead** [comment]
@pawelpesz , that is not simply the _expected_ behavior, that is the _**current**_ behavior as of this morning

**Comment by pawelpesz** [comment]
@TheQueenIsDead sorry, I misquoted your comment. I would expect a **more concise plan**, instead of:
```
# helm_release.example will be updated in-place
~ resource "helm_release" "example" {
      id                         = "my-release"
      name                       = "my-release"
      # (27 unchanged attributes hidden)

    - set {
        - name  = "cluster.enabled" -> null
        - value = "true" -> null
      }
    + set {
        + name  = "cluster.enabled"
        + value = "false"
      }

      # (1 unchanged block hidden)
  }
```
something like this:
```
# helm_release.example will be updated in-place
~ resource "helm_release" "example" {
      id                         = "my-release"
      name                       = "my-release"
      # (27 unchanged attributes hidden)

    ~ set {
        name  = "cluster.enabled"
        ~ value = "true" -> "false"
      }

      # (1 unchanged block hidden)
  }
```
Obviously the current behaviour is **much better** then before v2.8.0 but still, I do think this is still worth taking care of 😄
