### ISSUE TITLE
Support for charts in local directory

### ISSUE THREAD

**Issue by stensson** [hashicorp/terraform-provider-helm#63]
**Background**

We use a bunch of local helm charts, currently located in a directory structure in our Git repository.

When starting to adopt Terraform and installing our helm releases using terraform-provider-helm, we discovered that this structure of local charts is not supported.

Even though https://godoc.org/k8s.io/helm/pkg/chartutil#Load supports both directory and file, it seems that terraform-provider-helm requires a tar.gz representation of the chart. This requires us to zip each chart directory before installing any helm release, which seems unecessary.

**Feature request**

Could terraform-provider-helm also support local directories without requiring them in tar.gz form?

**Comment by worrel** [comment]
FWIW I've not had any issues installing local charts e.g 
```
resource "helm_release" "my-release" {
    name      = "dev-app"
    chart     = "./charts/api"
}
```
works for me, with `./charts/api` being just a regular chart directory not an archive.

**Comment by stensson** [comment]
Yes, it seems this was a misunderstanding on my part. Got it working now. 

Thanks for the help! Closing the ticket.
