### ISSUE TITLE
Add registry support (OCI)

### ISSUE THREAD

**Issue by evilezh** [hashicorp/terraform-provider-helm#633]
Seems helm3 OCI registry is working properly. I would be nice to be able to deploy from docker repos. 
I might be missing something,  I tried some combinations with repo, but nothing wokred out. So - I expect this is probably new feature.

I got idea, that it is experimental feature, but as meny experimental features, which work  - it will stay forever.

**Comment by alexsomesan** [comment]
Would you be willing to try out whether enabling the feature in Helm like described here https://helm.sh/docs/topics/registries/#enabling-oci-support would be sufficient?
This means setting that environment variable and trying to do an apply with a helm_release resource that references such a chart.

**Comment by wd** [comment]
I have tried to push a chart to aws ECR follow [this guide](https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html),  and it's working. 

But I haven't try to install the chart from ECR, this is [the guide](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_EKS.html#using-helm-charts-eks) .

**Comment by owenthereal** [comment]
I was looking for this but found that the Helm registry code is currently in an `internal` package so it can't be accessed by this project yet...: https://github.com/helm/helm/blob/master/cmd/helm/root.go#L191-L195 & https://github.com/helm/helm/blob/master/cmd/helm/root.go#L32

**Comment by Pluies** [comment]
> I was looking for this but found that the Helm registry code is currently in an `internal` package so it can't be accessed by this project yet...: https://github.com/helm/helm/blob/master/cmd/helm/root.go#L191-L195 & https://github.com/helm/helm/blob/master/cmd/helm/root.go#L32

Good news, [as of Helm 3.8.0](https://github.com/helm/helm/releases/tag/v3.8.0), support for OCI repositories is now generally available! 🎉 

This should enable the Helm provider to support it as a first-class construct.

**Comment by xxbarsey-tieto** [comment]
Any update on this one?
