### ISSUE TITLE
Conditional set

### ISSUE THREAD

**Issue by psr-tv2** [hashicorp/terraform-provider-helm#634]
### Description

Is it possible to have a `set`-block that actually only takes effect under some condition?

Perhaps [dynamic blocks](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks) could be used, but it seems a bit messy. 

I guess it can be achieved indirectly by packaging things up in a json/yaml object, like this: https://github.com/hashicorp/terraform-provider-helm/issues/564

### Potential Terraform Configuration

Suppose we have a chart `test` with an `values.yaml` containing:

```yaml
optional_value: "hello world"
```

Suppose in some environment that I want to override this value:

```hcl
resource "helm_release" "test" {
  name         = "test"
  chart        = "${path.module}/charts/test"
  version      = "0.0.1"

  set {
    name  = "optional_value"
    value = var.env == "test" ? "special" : "hello world"
  }
}
```

Now the value `"hello world"` is duplicated. Would it be possible to have something like:

```hcl
resource "helm_release" "test" {
  name         = "test"
  chart        = "${path.module}/charts/test"
  version      = "0.0.1"

  set {
    condition = var.env == "test"
    name  = "optional_value"
    value = "special"
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi,

You might be able to resolve this kind of use-case using the method suggested here: https://github.com/hashicorp/terraform/issues/19853

Let us know if that's useful in your case or you need further help.

**Comment by psr-tv2** [comment]
Hi,

It's a bit of a long thread, but if I read it correctly, the suggestion is to just use the dynamic blocks? I find it a bit ugly to use a `for_each` and some iterator, and it takes up more space, but okay. 

So in my case I would write something like this?

```hcl
resource "helm_release" "test" {
  name         = "test"
  chart        = "${path.module}/charts/test"
  version      = "0.0.1"

  dynamic "set" {
    for_each = var.env == "test" ? [var.env] : []
    content {
      name  = "optional_value"
      value = "special"
    }
  }
}
```

**Comment by jrhouston** [comment]
@psr-tv2 Yeah I think this is the canonical solution at the moment. I agree that it's cumbersome but I think a `conditional` attribute is something we would want to solve Terraform wide not just in this provider. I'd recommend opening another issue on the main Terraform repo with your use case if you want to advocate for a better user experience for this.

**Comment by psr-tv2** [comment]
That is probably a good idea. Thank you for the input. Let's just close this one then.
