### ISSUE TITLE
helm_release values file doesn't get created when used within the "file-function" from Terraform

### ISSUE THREAD

**Issue by avodaqstephan** [hashicorp/terraform-provider-helm#641]
### Terraform, Provider, Kubernetes and Helm Versions

```
terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.20.0
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

Kubernetes version: 1.17
Helm version: 3.2.0
```

I know that Terraform v0.13.5 is outdated but some parts e.g. VPC of the AWS module won't work with 0.14.0.

### Affected Resource(s)
- helm_release (values)

### Terraform Configuration Files
```hcl
resource "local_file" "dynatrace-values" {
  count     = var.enable_dynatrace_dynatrace ? 1 : 0
  content   = templatefile("${path.module}/dynatrace-values.tmpl", {
    # Some variables
  })
  filename = "${path.module}/.dynatrace/dynatrace-values.yaml"
}

resource "helm_release" "dynatrace-operator" {
  count      = var.enable_dynatrace_dynatrace ? 1 : 0
  name       = "dynatrace-oneagent-operator"
  repository = "https://raw.githubusercontent.com/dynatrace/helm-charts/master/repos/stable"
  chart      = "dynatrace-operator"
  namespace  = "dynatrace"
  create_namespace = true
  wait       = true
  timeout = 600
  values = [
    # Does not create the values file. Currently I need to run "terraform apply -target local_file.dynatrace-values" first
    file(local_file.dynatrace-values[0].filename)
    # Creates the file, but isn't able to use it here because I need to pass the content instead of the filename
    # local_file.dynatrace-values[0].filename
  ]
  depends_on = [local_file.dynatrace-values]
}
```

### Debug Output
https://gist.github.com/avodaqstephan/d01f2799242329994d8225ef31a6b7dd

### Steps to Reproduce
1. Try to pass values.yaml to the helm provider by using the [file-function](https://www.terraform.io/docs/configuration/functions/file.html) from Terraform.
2. `terraform apply`

### Expected Behavior

- File should be created beforehand
- File should be recognized and used to provide additional values for the helm_release

### Actual Behavior

- File doesn't get created when inside of the `file-function` of terraform

### Workaround

As a workaround I just created a data source of the created local_file and read its content within the helm_release values area. But this needs an additional resource which shouldn't be necessary.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by subesokun** [comment]
Got it working without the intermediate `local_file`

```terraform
resource "helm_release" "dynatrace-operator" {
  count      = var.enable_dynatrace_dynatrace ? 1 : 0
  name       = "dynatrace-oneagent-operator"
  repository = "https://raw.githubusercontent.com/dynatrace/helm-charts/master/repos/stable"
  chart      = "dynatrace-operator"
  namespace  = "dynatrace"
  create_namespace = true
  wait       = true
  timeout = 600
  values = [templatefile("${path.module}/dynatrace-values.tmpl", {
    some_var_a = "a"
    some_var_b = "b"
  })]
}
```
