### ISSUE TITLE
[feature] ignore key in yaml (lifecycle)

### ISSUE THREAD

**Issue by clementlecorre** [hashicorp/terraform-provider-helm#642]
### Description

I use helm and terraform to deploy my applications at @habx. 

I want to ignore values in yaml like the [lifecycle feature](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html#ignore_changes). 

In my case I would like to ignore the image because it is changed with something other than helm, I have to fix the diffs manually.

### Potential Terraform Configuration

For example a parameter: `ignores = ["image"]`

```hcl
resource "helm_release" "my-app" {
  chart     = "my-app/deployment"
  name      = "my-app"
  namespace = var.namespace
  version   = "1.2.0"
  values = [
    <<EOF
name: my-app
image: my-app:latest
EOF
    ,
  ]
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by redeux** [comment]
Hi @clementlecorre, thanks for opening this feature request.  We discussed this during our weekly triage, and I'd like to better understand your use case and workflow.  If you have some time I'd love to speak with you directly.  Feel free to put some time on my calendar directly, using the link below.  If anyone else would like to speak to me about this request, please feel free to schedule some time as well. 

https://calendly.com/philsautter/30min

**Comment by clementlecorre** [comment]
@redeux Any Update?
