### ISSUE TITLE
Upgrade helm package to 3.4.x

### ISSUE THREAD

**Issue by jrhouston** [hashicorp/terraform-provider-helm#646]
### Description

Helm package is 1 minor version behind now, newest version contains some changes to deal with the sunsetting of the stable repository.

### References

https://github.com/helm/helm/releases/tag/v3.4.0

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
Succeeded by #677
