### ISSUE TITLE
v0.10.5 is failing due to stable repo move

### ISSUE THREAD

**Issue by dfry** [hashicorp/terraform-provider-helm#649]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 0.13.05
Provider version: 0.10.5
Kubernetes version:  1.15.2
Helm version: 2.16.8
```

### Affected Resource(s)

- the helm provider on version 0.10.5 has a hardcoded repository to https://kubernetes-charts.storage.googleapis.com/index.yaml.  This repo does not resolve anymore so this breaks at the time of loading the provider.  Please release a new version with the repository updated to the new stable: https://charts.helm.sh/stable

Error: error initializing local helm home: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
Hi @dfry, as of our v2.0.0 provider release, we are no longer supporting Helm 2. It is explained in our [upgrade guide](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/guides/v2-upgrade-guide#helm-2)

**Comment by ludflu** [comment]
I'm seeing this error using helm v3.3.3 also.

**Comment by bfjoren** [comment]
I'm seeing this with helm version v3.4.4

**Comment by aareet** [comment]
Does running `helm repo update` help?

**Comment by jrhouston** [comment]
Looks like the old URL is hard-coded into the 0.10.5 version of the provider here: https://github.com/hashicorp/terraform-provider-helm/blob/v0.10.5/helm/provider.go#L452

Based on their [blog post](https://helm.sh/blog/new-location-stable-incubator-charts/) it sounds like the stable repo is deprecated and will eventually be garbage collected, but they're going to keep what's there around as an archive.

I'm going to cut a hotfix release to change the URL in the old provider so folks stuck maintaining legacy aren't left hanging, but after this please upgrade to the latest provider version! You'll have to fork this repo to keep supporting this if you don't.

**Comment by ludflu** [comment]
@aareet For me, the error comes before any repos exist. I run terraform in a docker container, so its fresh everytime. There are no repos to update with `helm repo update`

**Comment by sergio-dreamcode** [comment]
I'm now checking on upgrading to Helm3 right now, but as mentioned the url is hardcoded in 0.10.x provider version, anyhow if this can help somehow I had a [local cache of that file](https://gist.githubusercontent.com/sergio-dreamcode/ab49edc76e5cb6dd98ff5ef4301ed8ba/raw/eeff2d71e9871e3b2e39d4dc48b8532cd57eae43/index.yaml) from some days ago.

**Comment by savvys** [comment]
Provider 0.10.5
I understand the URLs are hardcoded.
Post the fix, will we be able to use the Provider 0.10.5 ? Or the fix will be done only for the latest release of helm provider which is version 2.0.1++?

**Comment by jrhouston** [comment]
I am cutting a release for v0.10.6 now @savvys.

**Comment by savvys** [comment]
Thanks a lot @jrhouston

**Comment by sergio-dreamcode** [comment]
Thank you so much @jrhouston.

I have one question, I noticed that your PR for 0.10.6 was already merged but now when I try to use it from Terraform seems that it's not found yet, is there some review process or similar before it's publicly available?

**Comment by aareet** [comment]
@sergio-dreamcode you'll need to wait until it appears here: https://releases.hashicorp.com/terraform-provider-helm/0.10.6/ (which it has now)

**Comment by jrhouston** [comment]
@sergio-dreamcode There is a release pipeline that happens after the merge that builds all the appropriate binaries and uploads them to a CDN. I was just able to pull it down so it should be available now – sometimes it can take a few minutes to roll out so try again in a few.

**Comment by dfry** [comment]
Thanks for the quick turnaround @jrhouston , the provider is working as expected again.  We have been working to convert to helm3 but we have a very large number helm deploys to regression test on helm3 and this repo becoming unavailable caught us at the worst time (during a prod release, of course).  Thanks again for the speedy resolution.

**Comment by jrhouston** [comment]
No problem @dfry thanks for contributing. Good luck with your upgrades! 🤠🔧

**Comment by rsood-conga** [comment]
helm init --client-only --skip-refresh
    helm repo rm stable
    helm repo add stable https://charts.helm.sh/stable
