### ISSUE TITLE
Upgrade Helm from v2 to v3

### ISSUE THREAD

**Issue by duskox** [hashicorp/terraform-provider-helm#651]
Hi, probably a question that is answered in some documentation I didn't find, but as I am trying to upgrade helm to v3, and due to that from terraform files I am removing Tiller installation, I am wondering will everything work just out of the box or there is something I need to define so that images are successfully installed without Tiller?

Also, not sure if this fits to ask here but due to changes in Docker repository access, I had to change a repo for helm3 to https://charts.helm.sh/stable as was suggested when doing `repo list` but I don't see how to do it when I have to set this through terraform file?

Thanks.

**Comment by adamrushuk** [comment]
For the helm migration, I found these useful:

- https://helm.sh/docs/topics/v2_v3_migration/
- https://github.com/helm/helm-2to3

**Comment by alexsomesan** [comment]
Provider is now using Helm v3
