### ISSUE TITLE
Unable to deploy the helm3 charts from azure container registery

### ISSUE THREAD

**Issue by basavarajb** [hashicorp/terraform-provider-helm#655]
Guide me to deploy the charts from azure acr.
in the screen shot i've attached the error

![image](https://user-images.githubusercontent.com/9286143/104323540-49bca380-550c-11eb-8619-92d5ea95fcce.png)

**Comment by jrhouston** [comment]
Hi @basavarajb it looks like Azure's container registry supports Helm charts via OCI, which is currently an experimental feature of Helm. You could try enabling it by setting `export HELM_EXPERIMENTAL_OCI=1` in your environment.

**Comment by basavarajb** [comment]
yes i executed  command  on windows 10 **set HELM_EXPERIMENTAL_OCI=1**

is my below code correct while getting the chart form acr
```
resource "helm_release" "example" {
  name       = "shopingcart"
   chart      = "https://xxxxxxx.azurecr.io/helm/shopingcart:v1"
  values     = [local.helm_chart_values]
}
```

**Comment by jemag** [comment]
Having the same issue on Linux with HELM_EXPERIMENTAL_OCI=1. 

However, it is really hard to get actual feedback on what is happening when trying to download the chart. Even if I were to enter a totally wrong repository like : 
``` terraform
resource "helm_release" "buildkit" {
  name 		 = "buildkit"
  repository = "zing.buzz.io"
  chart      = "buildkit-chart"
}

```
The feedback will still remain : 
![image](https://user-images.githubusercontent.com/7985687/105891919-28b18380-5fdf-11eb-8dae-8196269e7fd7.png)

No additional details seems to be provided, even with TF_LOG=TRACE.

If I were to do the same with Helm, I would get some basic feedback that could orient me in the right direction:
![image](https://user-images.githubusercontent.com/7985687/105892047-53034100-5fdf-11eb-9a83-e21208156de0.png)

So it may be that OCI is not supported at all with helm_release, or we are entering URLs that do not fit what is expected and fails continuously what that same error message.

Either way, I am guessing this is a problem for both ACR and ECR users. Would love to know if anyone found a workaround

**Comment by sziegler-skyhook** [comment]
I'm also running into this issue in Azure ACR, can anyone confirm if the Terraform Helm provider supports installing Helm charts from an OCI repository?

**Comment by val3r10** [comment]
It is not clear at all if the ACR is supported or what the format of the url should look like:
![image](https://user-images.githubusercontent.com/44226207/123384510-c7dda580-d594-11eb-81b7-40d0af8ee79b.png)

resource "helm_release" "nginx-acr-private" {
  name  = "ingress-nginx"
  chart = "ingress-nginx"
  repository  = "https://xxxxxxxxxxxxx.azurecr.io/helm/nginx:v1"
  repository_username = var.acr_admin_username
  repository_password = var.acr_admin_password
}
