### ISSUE TITLE
failed to download (hint: running `helm repo update` may help)

### ISSUE THREAD

**Issue by lwsanty** [hashicorp/terraform-provider-helm#658]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v0.14.4
Provider version: 2.0.1
Kubernetes version: 1.17.13-gke.2600
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "grafana" {
  name       = "grafana"
  chart      = "grafana"
  namespace  = "grafana"
  version    = "5.5.7"
  repository = var.chart_repo // we use ours https://${token}@raw.githubusercontent.com/${org}/helm-repo/tmp/
  timeout    = var.chart_timeout
  depends_on = [
    kubernetes_namespace.namespace,
    var.module_depends_on
  ]
  // vars
}
```

### Debug Output

```
Error: failed to download "https://${token}@raw.githubusercontent.com/${org}/helm-repo/tmp/grafana-5.5.7.tgz" (hint: running `helm repo update` may help)


2021-01-13T12:26:05.297+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-13T12:26:05.297+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-13T12:26:05.298+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-13T12:26:05.298+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

Changes have been applied successfully.

### Actual Behavior

1) error appears
```
Error: failed to download "https://${token}@raw.githubusercontent.com/${org}/helm-repo/tmp/grafana-5.5.7.tgz" (hint: running `helm repo update` may help)


2021-01-13T12:26:05.297+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-13T12:26:05.297+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-13T12:26:05.298+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-13T12:26:05.298+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```
2) after re-run of `terraform apply` the update plan is up to date(no changes detected), seems like it updates the state during the failed run

### Important Factoids

- it was working before 2.0.1
- dynamically reproduced in majority of cases
- we have CD with the similar steps to the local ones with terraform initialization and this error is not reproduced there

### References

- https://github.com/hashicorp/terraform-provider-helm/issues/630
- https://github.com/hashicorp/terraform-provider-helm/issues/472
- https://github.com/hashicorp/terraform-provider-helm/issues/554
- https://github.com/hashicorp/terraform-provider-helm/issues/465

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by eprokofev** [comment]
tested on provider 2.0.0, same error

**Comment by eprokofev** [comment]
helm provider 1.3.2 - same behaviour

**Comment by eprokofev** [comment]
added variable `HELM_DEBUG=1` and did apply one more time. Got more specific error 
`Error: no cached repo found. (try 'helm repo update'): open /Users/****/Library/Caches/helm/repository/incubator-index.yaml: no such file or directory`
  `on helm.tf line 1, in resource "helm_release" "alb_ingress_controller":
   1: resource "helm_release" "alb_ingress_controller" {`

After that I've tried to run`helm repo update` manually and got an error:  `...Unable to get an update from the "incubator" chart repository (https://kubernetes-charts-incubator.storage.googleapis.com):
        failed to fetch https://kubernetes-charts-incubator.storage.googleapis.com/index.yaml : 403 Forbidden`

So I removed that incubator repo from my helm config. 
After that I've applied helm chart with terraform successfully.

**Comment by aareet** [comment]
thanks for reporting your resolution @bigvandi. @lwsanty are you still facing this issue?

**Comment by lwsanty** [comment]
@aareet seems like the solution of @bigvandi helps, thank you

**Comment by aareet** [comment]
Great, thank you. In that case, I'll close this
