### ISSUE TITLE
helm cannot find remote module after terraform destroy when using previous terraform state

### ISSUE THREAD

**Issue by tantweiler** [hashicorp/terraform-provider-helm#662]
```
Terraform version: 0.14.4
Provider version: v2.0.1
Kubernetes version: AKS 1.18.14
Helm version: 3.5.0
```

### Steps to Reproduce

I created a pipeline in GitLab with terraform modules which use the providers azurerm, kubernetes and helm. The modules are located in remote GitLab projects and are being imported via git:

```
module "helm" {
  source            = "git::https://gitlab.mydomain.com/terraform-modules/azure/helm.git?ref=v1.0"
}

```
If the pipeline starts with a fresh or empty state, the provider is able to import the module as expected. When I run the "terraform destroy" stage in my pipeline and want to restart the pipeline afterwards so that the environment is being set up again, the helm provider complains that the helm releases I would like to install do not exists:

```
Warning: Release does not exist
Release name: nginx-ingress does not exist. It may have been deleted outside
of Terraform
Warning: Release does not exist
Release name: nginx-ingress-internal does not exist. It may have been deleted
outside of Terraform
Warning: Release does not exist
Release name: cert-manager does not exist. It may have been deleted outside of
Terraform
Warning: Release does not exist
Release name: cert-mgr-clusterissuers does not exist. It may have been deleted
outside of Terraform
Warning: Release does not exist
Release name: prometheus-operator does not exist. It may have been deleted
outside of Terraform
```

All the the other providers (azurerm and kubernetes) are able to reuse the terraform state and redeploy their resources. The only way to fix this issue for the helm provider is to delete the state. 

If I use a local modules repository instead of a remote modules repository this issue doe snot occur! 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by IceBear2k** [comment]
Ran into the same issue. Temporary workaround that works for me is downgrading to 1.3.2 as 2.0.0 is also affected:
```
terraform {
  required_providers {
    helm = {
      source = "hashicorp/helm"
      # FIXME: Pinned version due to Helm provider bug in 2.0.0 & 2.0.1 regarding existing Terraform state
      # "Warning: Release does not exist"
      # See: https://github.com/hashicorp/terraform-provider-helm/issues/662
      version = "= 1.3.2"
    }
}
```

**Comment by maurelio1234** [comment]
I have the same problem, we have a couple of charts installed with the helm provider. 
When we uninstall them with `helm uninstall` the provider is not able to reinstall them again.

I was forced to revert to v1.3.2 again.

**Comment by kaskavalci** [comment]
In our case downgrading did not work. We had to remove helm release from tfstate file and terraform happily recreated the release. This is a dangerous operation as it may break your terraform state. We did it on a dev env with no impact.

**Comment by romankydybets** [comment]
the same is happens for  me.

**Comment by jrhouston** [comment]
#674 should fix this

**Comment by larssb** [comment]
Then we just patiently wait for this to get out 👍
