### ISSUE TITLE
terraform plan fails when no cluster is existent

### ISSUE THREAD

**Issue by tillepille** [hashicorp/terraform-provider-helm#668]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 0.14.3
Provider version: 2.0.2
Kubernetes version: 1.19.3
Helm version: 3.5.0
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files

Provider config

```hcl
provider "helm" {
  kubernetes {
    host     = module.kubernetes.host
    username = module.kubernetes.username
    password = module.kubernetes.password

    client_certificate     = base64decode(module.kubernetes.client_certificate)
    client_key             = base64decode(module.kubernetes.client_key)
    cluster_ca_certificate = base64decode(module.kubernetes.cluster_ca_certificate)
  }
}
```

Module which has one `helm_release` inside
```hcl
module "externaldns" {
  source      = "../../modules/k8s-deployments/externaldns"
  namespace   = "kube-system"
  values_file = file("helm_values/externaldns.yaml")

  azure_dns_tenantId        = var.azure_dns_tenantId
  azure_dns_subscriptionId  = var.azure_dns_subscriptionId
  azure_dns_resourceGroup   = var.azure_dns_resourceGroup
  azure_dns_aadClientId     = var.azure_dns_aadClientId
  azure_dns_aadClientSecret = var.azure_dns_aadClientSecret
}
```

the `helm_release` inside this module
```hcl
resource "helm_release" "exernaldns" {
  name             = "externaldns"
  repository       = "https://charts.bitnami.com/bitnami"
  chart            = "external-dns"
  version          = "3.6.0"
  create_namespace = true
  namespace        = var.namespace

  values = [var.values_file]

  set {
    name  = "azure.tenantId"
    value = var.azure_dns_tenantId
  }
  set {
    name  = "azure.subscriptionId"
    value = var.azure_dns_subscriptionId
  }
  set {
    name  = "azure.resourceGroup"
    value = var.azure_dns_resourceGroup
  }
  set {
    name  = "azure.aadClientId"
    value = var.azure_dns_aadClientId
  }
  set {
    name  = "azure.aadClientSecret"
    value = var.azure_dns_aadClientSecret
  }
}

```

### Debug Output

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

Debug captured with `TF_LOG=trace HELM_DEBUG=1 terraform plan > debug_output.txt 2>&1`

<https://gist.github.com/tillepille/39e4983ba588f399f9203e2375133b6a>

### Steps to Reproduce

Create new environment, state only contains a network at that point.

1. `terraform plan`

### Expected Behavior

plan should successfully run and produce the output that x helm releases have to be added.

### Actual Behavior

`terraform plan` fails with 

```shell
error: code = Unavailable desc = transport is closing
```

**When there is a K8S Cluster already in place, the plan runs successfully.**
**When I comment out the modules (helm_releases), plan also runs successfully.**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
> 2021/01/21 09:04:36 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/hashicorp/kubernetes-alpha"

It looks like you're using the kubernetes-alpha provider somewhere in your config? I think this may be the hidden issue. In its current state the kubernetes-alpha provider relies on server side planning, so it requires the cluster to be available at plan time. We are working to address this in https://github.com/hashicorp/terraform-provider-kubernetes-alpha/pull/41, but it will take some time.

**Comment by tillepille** [comment]
@aareet You're totally right, thank you for that hint!
