### ISSUE TITLE
Postrender ignored

### ISSUE THREAD

**Issue by teu** [hashicorp/terraform-provider-helm#675]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 0.12.24
Provider version: 2.0.2
Kubernetes version: 1.17
Helm version: {Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "influxdb" {
  repository = "https://helm.influxdata.com"
  chart      = "influxdb"
  version    = "4.4.11"

  name             = "influxdb"
  namespace        = "default"
  timeout          = 120
  create_namespace = true

  force_update = false

  postrender {
    binary_path = "${path.module}/kustomize.sh"
  }

  values = [
    local.helm_values //omited
  ]
}
```

### Debug Output

https://gist.github.com/teu/6919c4183ff9a60d920ff91ad563b262

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
Applied what's in out.yaml it seems to be ignored. If I hand-edit and add this change in the k8s resource directly and re-run terraform, again this is not applied rather the original version is.

### Actual Behavior
Applied what's in in.yaml

### Important Factoids
Used postrender script (kustomize.sh)
```bash
#!/bin/bash
# removes mounted config volume in the stateful set from  https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/templates/statefulset.yaml#L124
cat <&0 > ./in.yaml
#essentially since kustomize is useless, run sed to remove a mountVolumes element
tac ./in.yaml | docker run --rm -i alpine:3.7 sed '/mountPath: \/etc\/influxdb/,+1 d' | tac > ./out.yaml

cat ./out.yaml

```

### Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
@teu Can you confirm if this is a problem when you use the `helm` cli directly and supply your script with the `--post-renderer` flag? All the provider does here is pass along your script to helm and it is responsible for surfacing any errors.

**Comment by djfinnoy** [comment]
Terraform does not track changes to the Helm release implemented via the postrender script. If you have already applied the chart before you added the postrender, it won't do anything. Try destroying and recreating it.

**Comment by soleares** [comment]
This is still an issue. It does work if you add `manifest = true` to your Helm provider config.
```
provider "helm" {
  experiments {
    manifest = true
  }
}
```

Keep in mind that will affect all of your charts. If you only want it to affect a single chart I think you can use an aliased provider with that chart.

See the following somewhat related issue: https://github.com/hashicorp/terraform-provider-helm/issues/346

**Comment by sherifkayad** [comment]
@soleares I can confirm that with a posrender that alters the manifests using the `mainfest = true` really helps and lets the provider behave in the desired way.

Are there any negative implications for setting that flag all across the board? .. What did you mean by `Keep in mind that will affect all of your charts and that's maybe not what you want so you can used aliased providers to control this.`?

**Comment by soleares** [comment]
@sherifkayad I've updated my comment so it's hopefully not confusing. My main point was more that if you update the provider that it will affect all charts - `helm_release` resources. If you only want it to affect a single chart then I think you could use an aliased provider with that chart.

My concern about it having unintended side-effects on other charts came from these comments: https://github.com/hashicorp/terraform-provider-helm/issues/346#issuecomment-846623193
https://github.com/hashicorp/terraform-provider-helm/issues/346#issuecomment-1054534251

I don't really understand though why it would cause more diffs/updates in other charts.

**Comment by sherifkayad** [comment]
@soleares I found a side effect just now, the helm templates (even with secrets and stuff) are printed to the console and saved in the state potentially exposing sensitive information ..

**Comment by sherifkayad** [comment]
is there any option to mark the `manifest` as sensitive or so?
