### ISSUE TITLE
No in-cluster authentication support?

### ISSUE THREAD

**Issue by jsleeio** [hashicorp/terraform-provider-helm#68]
We deploy stuff with Buildkite agents that run in Kubernetes pods, therefore serviceaccount authetication is used.

I had a look through `terraform-provider-helm` code here and it looked like in-cluster auth is not supported.

If you don't already have this somewhere on a roadmap, I'll get to work on a PR. Thanks for creating and sharing this provider!

Related: should the Kube API endpoint default to `https://kubernetes` ?

**Comment by mcuadros** [comment]
A PR is always welcome!

**Comment by rporres** [comment]
This is still pending as #76 does not use https://godoc.org/k8s.io/client-go/rest#InClusterConfig to get the credentials k8s gives to pods

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
