### ISSUE TITLE
Since helm provider/resource provides values.yaml templating, a tool to test chart in CLI would be super nice

### ISSUE THREAD

**Issue by notjames** [hashicorp/terraform-provider-helm#680]
Personally, I wouldn't have allowed the ability to template-ize the `values.yaml` file since helm doesn't allow it. Unfortunately, some people on our team use this functionality. Those of us which need to help maintain things, though, now have to find a way to run with it. The problem is, now, if I want to run `helm template` on the chart with our templatized `values.yaml` files, I have to either edit all the values files and remove the templatized blocks or find some way (purpose of this issue) to run the values files through a pre-processor to dereference the template variables. So, this request is a feature request to either remove the ability to templatize the `values.yaml` file or provide a CLI tool or ability to output the chart like when one runs `helm template` on a chart.

**Comment by jrhouston** [comment]
Hi @James I feel your templating pain here – mixing Helm's templating with Terraform's templating is a tough spot to be in.

> So, this request is a feature request to either remove the ability to templatize the values.yaml file

Unfortunately this is not something we can really address in the provider as the template functionality is a feature of Terraform itself and there isn't a way to limit where it gets used in your config. This is something you could perhaps solve yourself in CI by having a script to parse the HCL and checking if template() is used inside a `helm_release` to prevent people from doing it but I suspect that would be quite high effort to implement.

> or provide a CLI tool or ability to output the chart like when one runs helm template on a chart.

There is already an open issue for adding the `helm template` functionality if you want to add your use case here: https://github.com/hashicorp/terraform-provider-helm/issues/298

**Comment by notjames** [comment]
FYI, that ticket is closed. But the point about what provides the templating is good to know.
