### ISSUE TITLE
Configuring the provider is broken

### ISSUE THREAD

**Issue by marksalpeter** [hashicorp/terraform-provider-helm#681]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version:  v0.14.6
Provider version:  v0.14.6
Kubernetes version: v1.20.2
Helm version: v3.5.2
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
terraform {
	required_providers {
		kubernetes = {
			source = "hashicorp/kubernetes"
			version = ">=2.0.2"
		}
		heml = {
			source = "hashicorp/helm"
			version = ">=2.0.2"
		}
	}
}

# the following works fine
provider "kubernetes" {
  config_path = "~/.kube/config"
}

resource "kubernetes_namespace" "staging" {
	metadata {
		name = "staging"
	}
}

# the following fails with the following error:
# Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

resource "helm_release" "nginx_ingress" {
  name       = "nginx-ingress-controller"

  repository = "https://charts.bitnami.com/bitnami"
  chart      = "nginx-ingress-controller"

  set {
    name  = "service.type"
    value = "ClusterIP"
  }
}
```

### Debug Output

[Debug Output](https://gist.github.com/marksalpeter/ec4ed13baad38acc5516c8bbd6a72058)

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

This should create a kubernetes namespace called "staging" and an nginx_ingress from the bitnami helm chart.

### Actual Behavior

The staging namespace is created correctly with the kubernetes provider, but the helm provider, which was given the same working configuration file the kubernetes provider was given, fails with the following error message:
```zsh
Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
> heml = {

Is this a typo in what you pasted or a typo in your configuration?

**Comment by marksalpeter** [comment]
Thanks @aareet! I'll see myself out
*slowly backs out of the room in shame
