### ISSUE TITLE
Datadog agent is not installing in kubernetes cluster

### ISSUE THREAD

**Issue by a-ritomar** [hashicorp/terraform-provider-helm#682]
Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

helm_release.datadog_agent: Creating...

Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

resource "helm_release" "datadog_agent" {
  name       = "datadog-agent"
  chart      = "datadog"
  repository = "https://helm.datadoghq.com"
  version    = "2.4.15"
  namespace  = kubernetes_namespace.xxx.id
  set_sensitive {
    name  = "datadog.apiKey"
    value = var.datadog_api_key
  }
}

Expected Behaviour:
The Helm chart should have installed without issue.

Actual Behaviour:
Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

I keep getting this issue while running "terraform apply" command. Could someone please suggest what I am missing here?
I have already set KUBECONFIG environment variable.

**Comment by jrhouston** [comment]
> I have already set KUBECONFIG environment variable.

You need to either set this explicitly in the provider block like this:

```hcl
provider helm {
  kubernetes {
    config_path = "path/to/kubeconfig"
  }
}
```

or set it via the `KUBE_CONFIG_PATH` environment variable.
