### ISSUE TITLE
Helm provider from version 2.x failing at terraform plan/apply because built-in objects like `Capabilities` failing

### ISSUE THREAD

**Issue by md2k** [hashicorp/terraform-provider-helm#685]
### Terraform, Provider, Kubernetes and Helm Versions
```
Terraform version:  0.14.7
Provider version:
  * azuread v0.11.0
  * azurerm v2.47.0
  * hashicorp/helm v2.0.2
  * kubernetes v2.0.2
  * random v3.0.1
Kubernetes version: 1.18
Helm version: v3.5.1
```

### Affected Resource(s)
- helm_release

### Debug Output
https://www.dropbox.com/s/enixp1w29u1bjn1/debug_helm_provider.txt?dl=0

### Steps to Reproduce
simple template
```go
{{- if .Values.crd_manifest }}
{{- if .Capabilities.APIVersions.Has .Values.crd_manifest.apiVersion }}
---
apiVersion: {{ .Values.crd_manifest.apiVersion }}
kind: {{ .Values.crd_manifest.kind }}
metadata:
  name: {{ .Values.crd_manifest.name }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/release: {{ .Release.Name }}
    helm.sh/revision: {{ .Release.Revision | quote }}
    {{- if .Values.crd_manifest.labels }}
    {{- range $name, $value := .Values.crd_manifest.labels }}
    {{ $name }}: {{ $value | quote}}
    {{- end }}
    {{- end }}
  {{- if .Values.crd_manifest.annotations }}
  annotations:
    {{- range $a_key, $a_val := .Values.crd_manifest.annotations }}
    {{ $a_key }}: {{ tpl $a_val . | quote }}
    {{- end }}
  {{- end }}
spec:
{{ toYaml .Values.crd_manifest.spec | indent 2 }}

{{- else }}
  {{- fail  (printf "Cluster do not have API for: %s! Probably CRD for it not deployed." .Values.crd_manifest.apiVersion) }}
{{- end }}
{{- end }}
```
Values example:
```yaml
crd_manifest:
  apiVersion: mongodb.com/v1
  kind: MongoDBOpsManager
  name: ops-manager
  spec:
    adminCredentials: ops-manager-admin-credentials
    applicationDatabase:
      featureCompatibilityVersion: "4.2"
```

### Expected Behavior
expecting same behaviour as from `helm upgrade --install <releasename> -f ./custom_values_file.yam chart/location`

### Actual Behavior
failure, because template function of helm checking against standard Kubernetes API only and not defined by CRD
As possible work around 

### References
* Helm build-in objects https://helm.sh/docs/chart_template_guide/builtin_objects/
* https://github.com/mgoltzsche/khelm/issues/7
* https://github.com/helm/helm/issues/3377
* MongoDB Operator: https://github.com/mongodb/mongodb-enterprise-kubernetes 
NOTE:  in fact with any custom CRD/Operator will work, like traefik/mongodb, prometheus and so on.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@md2k Unless I'm missing something, it looks like the supplied debug log doesn't capture the actual failure / errors from the provider. Would you mind reviewing / updating the debug log to include more details (e.g. the actual errors logged by the provider).

Thanks!

**Comment by md2k** [comment]
@alexsomesan , ok i'll build custom example to get the logs, because debug from my run include data i can't share.
