### ISSUE TITLE
Doc for wait argument: waits for jobs ?

### ISSUE THREAD

**Issue by gberche-orange** [hashicorp/terraform-provider-helm#694]
### Terraform, Provider, Kubernetes and Helm Versions

v2.0.2
https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#wait

### Affected Resource(s)
- helm_release

### Expected behavior

As a terraform user
* in order to discover if terraform-provider-helm has an equivalent of the `--wait-for-jobs` helm cli argument

```
helm install --help
[...]
      --wait-for-jobs                if set and --wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as --timeout
```
* I need the [helm_release.wait attribute documentation](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#wait) to detail the helm behavior applied, ie whether K8S jobs will be waited for.

### Actual behavior

https://github.com/hashicorp/terraform-provider-helm/blob/c781ebdd2a8fd1b8ff8af391ae9c350ec3b54be2/website/docs/r/release.html.markdown#L113-L113

does not precise the wait behavior (w.r.t. jobs) nor mapping of this attribute to the helm cli flags

I did not find terraform test covering job wait cases into https://github.com/hashicorp/terraform-provider-helm/blob/9c3d6760f462926438f18ffb1c91b3b8f19562f4/helm/resource_release_test.go#L611-L1127

<details>
<summary>Suspecting from source code analysis that jobs are not waited for</summary>

https://github.com/hashicorp/terraform-provider-helm/blob/9c3d6760f462926438f18ffb1c91b3b8f19562f4/helm/resource_release.go#L584

https://github.com/hashicorp/terraform-provider-helm/blob/9c3d6760f462926438f18ffb1c91b3b8f19562f4/helm/resource_release.go#L520-L522

https://github.com/hashicorp/terraform-provider-helm/blob/9c3d6760f462926438f18ffb1c91b3b8f19562f4/vendor/helm.sh/helm/v3/pkg/action/install.go#L172-L352

https://github.com/hashicorp/terraform-provider-helm/blob/9c3d6760f462926438f18ffb1c91b3b8f19562f4/vendor/helm.sh/helm/v3/pkg/kube/client.go#L116-L127

https://github.com/hashicorp/terraform-provider-helm/blob/9c3d6760f462926438f18ffb1c91b3b8f19562f4/vendor/helm.sh/helm/v3/pkg/kube/wait.go#L52-L150

Wondering whether explicit call to watching jobs is missing
https://github.com/hashicorp/terraform-provider-helm/blob/9c3d6760f462926438f18ffb1c91b3b8f19562f4/vendor/helm.sh/helm/v3/pkg/kube/client.go#L295-L313

</details>

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
I believe this is implemented in #720
