### ISSUE TITLE
Locally configured kubectl is not a requirement but docs say it is

### ISSUE THREAD

**Issue by redeux** [hashicorp/terraform-provider-helm#697]
### References

https://registry.terraform.io/providers/hashicorp/helm/latest/docs#requirements

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mnaser** [comment]
Fixed: https://github.com/hashicorp/terraform-provider-helm/pull/673
