### ISSUE TITLE
Support downloader plugins for value files.

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-provider-helm#699]
### Description

Currently the terraform provider want to read the yaml files directly. Helm supports values files on remote locations via https or on custom locations like gcs, s3 or git through helm downloader plugins.  

https://helm.sh/docs/topics/plugins/#downloader-plugins

Source Code Part: https://github.com/helm/helm/blob/6e4a61f21279560b4a4cf7b84088c9e7e75757a9/pkg/cli/values/options.go#L107-L121

### Potential Terraform Configuration

```hcl
resource "helm_release" "example" {
  value_files = [
    "gcs://.../values.yaml",
    "git+https://.../values.yaml",
  ]
}
```
or

```hcl
resource "helm_release" "example" {
  value_file {
    protocol = "gcs"
    location = ".../values.yaml",
  }
  value_file {
    protocol = "git+https"
    location = ".../values.yaml",
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
For some URL types you might be able to get a similar experience by using data sources like the HTTP data source, or S3, etc.
We'll look into what's needed to implement this in the provider, but it's not a high priority at the moment.
