### ISSUE TITLE
Error executing complicated template from inside terraform, but 'helm template' works

### ISSUE THREAD

**Issue by spenczar** [hashicorp/terraform-provider-helm#701]
### Terraform, Provider, Kubernetes and Helm Versions
```
Terraform version: Terraform v0.14.6
Provider version: registry.terraform.io/hashicorp/helm v2.0.2
Kubernetes version: n/a
Helm version: v3.5.2
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    helm = {
      source = "hashicorp/helm"
      version = "2.0.2"
    }
  }
}

provider "helm" {}

resource "helm_release" "jupyterhub" {
  name             = "jhub"
  namespace        = "jhub"
  chart            = "jupyterhub"
  repository       = "https://jupyterhub.github.io/helm-chart/"
  version          = "0.11.1"
  set {
    name = "proxy.secretToken"
    value = "dummy"
  }
}
```

### Debug Output
https://gist.github.com/spenczar/7a433a3f1868b7b4ccf42a29bec3d101

### Steps to Reproduce
Compare `terraform apply` running `helm template` directly:

```
helm template \
        jhub jupyterhub/jupyterhub \
        --namespace jhub \
        --version=0.11.1 \
        --set proxy.secretToken=dummy
```

### Expected Behavior

Running `helm template` succeeds, so I expect `terraform apply` to succeed as well.

### Actual Behavior

Terraform errors with this message:

```
helm_release.jupyterhub: Creating...

Error: template: jupyterhub/templates/proxy/deployment.yaml:28:32: executing "jupyterhub/templates/proxy/deployment.yaml" at <include (print $.Template.BasePath "/hub/secret.yaml") .>: error calling include: template: jupyterhub/templates/hub/secret.yaml:12:52: executing "jupyterhub/templates/hub/secret.yaml" at <$values.custom>: wrong type for value; expected map[string]interface {}; got interface {}
```

### Important Factoids

I'm using a third-party chart, here. The line that is erroring is here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/0.11.1/jupyterhub/templates/hub/secret.yaml#L12

I confess that this looks like some complex template magic, and I don't understand it. But since it works with `helm`, I think it ought to work with `terraform-provider-helm`.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by spenczar** [comment]
If I add this to `resource "helm_release"`, everything works:
```hcl
set {
  name  = "custom.whatever"
  value = "doesntmatter"
}
```
This works because it makes sure that an empty `map[string]interface{}` exists under the name `custom`. That ensures that ` {{- $_ := set $values "custom" (merge dict $values.custom .Values.hub.extraConfigMap) }}` will work - it makes sure that `$values.custom` is referring to a dict, so that `merge dict` doesn't error out.

The mystery, to me, is that this works in `helm` just fine. Why doesn't it work inside Terraform?

**Comment by chrisbulgaria** [comment]
Hi ,
It’s a bug , same as https://github.com/hashicorp/terraform-provider-helm/issues/665.
Introduced in version 2 . Please upvote it such that it receives some attention. See as well the linked jupyterhub issue .
Best,
Chris

**Comment by spenczar** [comment]
Agh, yes, thanks for the pointer. It is indeed the same as https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1998.
