### ISSUE TITLE
Option to specify multiple helm repository in helm_release resource

### ISSUE THREAD

**Issue by sajuptpm** [hashicorp/terraform-provider-helm#706]
Option to specify multiple helm repository in helm_release resource

in helm, we can configure multiple repository
$helm repo list

**Comment by alexsomesan** [comment]
Have you tried setting the repository on the `helm_release` resource using the `repository` attribute? Would that resolve the issue for you?

**Comment by matchan26** [comment]
I am having the same problem.
I'm trying to install datadog agent via terraform helm provider. datadog agent requires two repositories as a prerequisite: kube-state-metrics and datadog agent.
However, in the repository attribute, only single repository can be set. I tried to set this `repository` with list(string), but it didn't work.

**Comment by sajuptpm** [comment]
> Have you tried setting the repository on the `helm_release` resource using the `repository` attribute? Would that resolve the issue for you?

yes I am using it. But there we can specify only one repo, right ?
I want to configure multiple helm repos.

**Comment by zimbatm** [comment]
I'm hitting the same issue with this chart: https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/README.md

It depends on both:
* https://grafana.github.io/helm-charts
* https://prometheus-community.github.io/helm-charts

**Comment by zimbatm** [comment]
This is silly. Auto-closing issues won't make them go away. It's putting silly metrics like open issues over the time we spent reporting this limitation.
