### ISSUE TITLE
Getting Wrong Error: chart [...] version [...] not found in [...] repository

### ISSUE THREAD

**Issue by pathob** [hashicorp/terraform-provider-helm#707]
### Terraform, Provider, Kubernetes and Helm Versions
```
Terraform version: 0.14.8
Provider version: 2.0.3
Kubernetes version: 1.19.1
Helm version: 3.5.2
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "2.0.3"
    }
  }
}

provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

resource "helm_release" "nginx_ingress" {
  name       = "nginx-ingress"
  repository = "https://kubernetes.github.io/ingress-nginx"
  chart      = "nginx-ingress"
  version    = "3.24.0"
  namespace  = "kube-system"

  values = [
    file("helm/nginx-ingress/values.yml")
  ]
}
```

### Debug Output
For full log see:
- [DEBUG Log](https://github.com/pathob/tf_helm/runs/2100471523?check_suite_focus=true)
- [TRACE Log](https://github.com/pathob/tf_helm/runs/2095542326?check_suite_focus=true)

I cannot find any useful information there but:
```bash
2021-03-13T03:19:40.079Z [DEBUG] plugin: starting plugin: path=.terraform/providers/registry.terraform.io/hashicorp/helm/2.0.3/linux_amd64/terraform-provider-helm_v2.0.3_x5 args=[.terraform/providers/registry.terraform.io/hashicorp/helm/2.0.3/linux_amd64/terraform-provider-helm_v2.0.3_x5]
2021-03-13T03:19:40.081Z [DEBUG] plugin: plugin started: path=.terraform/providers/registry.terraform.io/hashicorp/helm/2.0.3/linux_amd64/terraform-provider-helm_v2.0.3_x5 pid=13458
2021-03-13T03:19:40.082Z [DEBUG] plugin: waiting for RPC address: path=.terraform/providers/registry.terraform.io/hashicorp/helm/2.0.3/linux_amd64/terraform-provider-helm_v2.0.3_x5
2021-03-13T03:19:40.147Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: configuring server automatic mTLS: timestamp=2021-03-13T03:19:40.147Z
2021-03-13T03:19:40.223Z [DEBUG] plugin.terraform-provider-helm_v2.0.3_x5: plugin address: address=/tmp/plugin426193591 network=unix timestamp=2021-03-13T03:19:40.223Z
2021-03-13T03:19:40.223Z [DEBUG] plugin: using plugin: version=5
2021-03-13T03:19:40.301Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/03/13 03:19:40 [DEBUG] [resourceDiff: nginx-ingress] Start: timestamp=2021-03-13T03:19:40.300Z
2021/03/13 03:19:40 [WARN] Provider "registry.terraform.io/hashicorp/helm" produced an invalid plan for helm_release.nginx_ingress, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .atomic: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .lint: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .verify: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .wait: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .cleanup_on_fail: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .replace: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .timeout: planned value cty.NumberIntVal(300) does not match config value cty.NullVal(cty.Number)
      - .dependency_update: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .disable_webhooks: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .force_update: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .disable_crd_hooks: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .skip_crds: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .disable_openapi_validation: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .recreate_pods: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .reuse_values: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .create_namespace: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .max_history: planned value cty.NumberIntVal(0) does not match config value cty.NullVal(cty.Number)
ty.NullVal(cty.Bool)
      - .reset_values: planned value cty.False does not match config value cty.NullVal(cty.Bool)
helm_release.nginx_ingress: Creating...
2021/03/13 03:19:40 [DEBUG] EvalApply: ProviderMeta config value set
2021/03/13 03:19:40 [DEBUG] helm_release.nginx_ingress: applying the planned Create change
2021-03-13T03:19:40.367Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/03/13 03:19:40 [DEBUG] setting computed for "metadata" from ComputedKeys: timestamp=2021-03-13T03:19:40.366Z
2021-03-13T03:19:40.367Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/03/13 03:19:40 [DEBUG] [resourceReleaseCreate: nginx-ingress] Started: timestamp=2021-03-13T03:19:40.367Z
2021-03-13T03:19:40.367Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/03/13 03:19:40 [DEBUG] [resourceReleaseCreate: nginx-ingress] Getting helm configuration: timestamp=2021-03-13T03:19:40.367Z
2021-03-13T03:19:40.367Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/03/13 03:19:40 [DEBUG] [INFO] GetHelmConfiguration start: timestamp=2021-03-13T03:19:40.367Z
2021-03-13T03:19:40.367Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/03/13 03:19:40 [DEBUG] Using kubeconfig: /home/runner/.kube/config: timestamp=2021-03-13T03:19:40.367Z
2021-03-13T03:19:40.367Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/03/13 03:19:40 [INFO] Successfully initialized kubernetes config: timestamp=2021-03-13T03:19:40.367Z
2021-03-13T03:19:40.367Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/03/13 03:19:40 [DEBUG] [INFO] GetHelmConfiguration success: timestamp=2021-03-13T03:19:40.367Z
2021-03-13T03:19:40.367Z [INFO]  plugin.terraform-provider-helm_v2.0.3_x5: 2021/03/13 03:19:40 [DEBUG] [resourceReleaseCreate: nginx-ingress] Getting chart: timestamp=2021-03-13T03:19:40.367Z
2021/03/13 03:19:40 [DEBUG] helm_release.nginx_ingress: apply errored, but we're indicating that via the Error pointer rather than returning it: chart "nginx-ingress" version "3.24.0" not found in https://kubernetes.github.io/ingress-nginx repository

Error: chart "nginx-ingress" version "3.24.0" not found in https://kubernetes.github.io/ingress-nginx repository

  on main.tf line 16, in resource "helm_release" "nginx_ingress":
  16: resource "helm_release" "nginx_ingress" {


2021-03-13T03:19:40.404Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-03-13T03:19:40.405Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/helm/2.0.3/linux_amd64/terraform-provider-helm_v2.0.3_x5 pid=13458
2021-03-13T03:19:40.405Z [DEBUG] plugin: plugin exited
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

### Steps to Reproduce
1. Use `https://kubernetes.github.io/ingress-nginx` as a `helm_release` repository with chart `nginx-ingress` and version `3.24.0`
2. See https://github.com/pathob/tf_helm/blob/main/main.tf
3. See https://github.com/pathob/tf_helm/blob/main/.github/workflows/test.yml
4. See https://github.com/pathob/tf_helm/runs/2095542326?check_suite_focus=true

### Expected Behavior
1. Terraform should find the chart like e.g. with using repository `https://helm.nginx.com/stable` and chart `nginx-ingress` and version `0.8.0` (but there is something else odd with this chart);
2. See https://github.com/pathob/tf_helm/blob/working/main.tf
3. See https://github.com/pathob/tf_helm/blob/working/.github/workflows/test.yml
4. See https://github.com/pathob/tf_helm/runs/2093139142?check_suite_focus=true

### Actual Behavior
Terraform cannot find the chart like mentioned in the expected behaviour, although I'm using the same chart / version / repo with Helm / Helmfile and the chart with that version in that repo definetly exists, see https://kubernetes.github.io/ingress-nginx/index.yaml

#### Workaround

I'm currently using the full chart URL as the chart without repo and version like so: `https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-3.24.0/ingress-nginx-3.24.0.tgz`

### Important Factoids
I think none.

### References
I think none.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by andybritton** [comment]
Facing the same issue, it only seems to be on some charts.  I tried importing the resource after deploying the chart manually and got the same error trying to modify the terraform state as well:

```
Acquiring state lock. This may take a few moments...
helm_release.aws-load-balancer-controller: Modifying... [id=aws-load-balancer-controller]

Error: failed to download "https://aws.github.io/eks-charts/aws-load-balancer-controller-1.1.5.tgz" (hint: running `helm repo update` may help)

  on networking.tf line 11, in resource "helm_release" "aws-load-balancer-controller":
  11: resource "helm_release" "aws-load-balancer-controller" {

```

**Comment by andybritton** [comment]
@pathob I think this might actually be a helm issue, I hadn't noticed that one of the helm repo's I'd added from an s3 bucket was having permissions issues.  Once I'd fixed that and could run a successful repo update this issue didn't happen.  I also forced the provider version to the previous 2.0.2 and had the same issue prior to fixing the repo permission.

**Comment by pathob** [comment]
Sorry for the late reply, I was in vacations...

@andybritton andybritton I could imagine that this is a Helm issue but then only in an older version (including the bundled one in this provider). In current Helm versions I can use the repo as described here while I cannot use the repo with this provider.

**Comment by serhiiromaniuk** [comment]
Hello @pathob ! My workaround is to downgrade to 1.3.2 https://registry.terraform.io/providers/hashicorp/helm/1.3.2/docs/data-sources/repository and using `helm_repository` data resource.

**Comment by jinglejengel** [comment]
Anyone happen to find other workaround to this?

Don't really want to revert to the 1.x provider but the Datadog Agent helm chart as an example is also splendidly broken with this now ):

Other options I considered were a local exec to run helm but that seems equally as gross as reverting back to 1.x.

Example resource block:

```
resource "helm_release" "datadog" {
    name = "datadog"
    repository = "https://helm.datadoghq.com"
    chart = "datadog/datadog"
    version = "2.11.2"
    namespace = kubernetes_namespace.datadog.metadata[0].name

    values = [
<redacted for brevity>
    ]
}
```

**Comment by carlosjgp** [comment]
> Hello @pathob ! My workaround is to downgrade to 1.3.2 https://registry.terraform.io/providers/hashicorp/helm/1.3.2/docs/data-sources/repository and using `helm_repository` data resource.

EDIT: Ignore this post... this was working locally because Terraform Helm was using my local Helm configuration which has the configuration for ChartMuseum. Check this post instead https://github.com/hashicorp/terraform-provider-helm/issues/707#issuecomment-844548333

:-1: 

I can confirm that this solution worked for me. Using a private ChartMuseum repository with basic HTTP auth and it does not with the provider versions

```
terraform: 0.12.31
helm: 2.1.2
```

Not working
```
helm provider: 2.1.2

helm_release xxx {
  repository          = "https://chartmuseum.domain.com/"
  repository_username = data.aws_secretsmanager_secret_version.chartmuseum_credentials["username"].secret_string
  repository_password = data.aws_secretsmanager_secret_version.chartmuseum_credentials["password"].secret_string
}
```

Working
```
helm provider: 1.3.2

helm_release xxx {
  repository = data.helm_repository.chartmuseum.metadata[0].name
}

data helm_repository chartmuseum {
  name     = "chartmuseum"
  URL      = "https://chartmuseum.domain.com/"
  username = data.aws_secretsmanager_secret_version.chartmuseum_credentials["username"].secret_string
  password = data.aws_secretsmanager_secret_version.chartmuseum_credentials["password"].secret_string
}
```

**Comment by aidan-melen** [comment]
I was getting the same error. My work around was to do away with the repository and version arguments.

Instead of this

```hcl
resource "helm_release" "nginx_ingress" {
  name       = "nginx-ingress"
  repository = "https://kubernetes.github.io/ingress-nginx"
  chart      = "nginx-ingress"
  version    = "3.24.0"
  namespace  = "kube-system"

  values = [
    file("helm/nginx-ingress/values.yml")
  ]
}
```

I retrieved the install link from [Artifacthub](https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx?modal=install) and supplied that to the chart argument

```hcl
resource "helm_release" "nginx_ingress" {
  name       = "nginx-ingress"
  chart      = "https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-3.24.0/ingress-nginx-3.24.0.tgz"
  namespace  = "kube-system"

  values = [
    file("helm/nginx-ingress/values.yml")
  ]
}
```
Also note that the version is part of the install link, so no need to specify the version argument as well. More about the [chart argument here](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#chart).

**Comment by JustinAvaLabs** [comment]
I noticed this happened when my specified version wasn't the latest available chart.   

i.e.  I tried using version 3.0.6, when 'helm repo update' gave me the latest chart version 3.0.7.  When I switched to use 3.0.7 it worked again.  

Maybe the provider is only searching latest versions?

**Comment by alexppg** [comment]
It's also happening to me. Exactly with the `prometheus-community`, which I know from a fact that works. I'm having problems with both prometheus-stack and prometheus-push-gateway. I'm using the latest version of the helm provider and it works as expected when using helm directly. I'd add some logs, but even with debug activated, I don't see anything relevant. The error I receive is:

```text
Error: failed to download "https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-18.0.13/kube-prometheus-stack-18.0.13.tgz" at version "18.0.13" (hint: running `helm repo update` may help)

  on prometheus-stack.tf line 68, in resource "helm_release" "prometheus_stack":
  68: resource "helm_release" "prometheus_stack" {
```

As you can check for yourselves, that url works correctly, so not sure what to do. I'll do the workaround commented in the meantime.

```hcl
resource "helm_release" "prometheus_stack" {
  name       = "ps"
  namespace  = "monitoring"
  chart      = "https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-18.0.13/kube-prometheus-stack-18.0.13.tgz"
...
```
Update: Welp, that still didn't work.
I'm using this versions, any advice will be welcomed.

```text
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/helm v2.3.0
```

**Comment by alexppg** [comment]
I'll double post instead of edit because I think it may be useful to other people. 

When using the format:
```hcl
resource "helm_release" "prometheus_stack" {
  name       = "ps"
  namespace  = "monitoring"
  repository = "https://prometheus-community.github.io/helm-charts"
  chart      = "prometheus-community/kube-prometheus-stack"
  version    = "18.0.13"
}
```
It fails with the mentioned error:
```text
Error: failed to download "https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-18.0.13/kube-prometheus-stack-18.0.13.tgz" at version "18.0.13" (hint: running `helm repo update` may help)
```

But, if you manually add your repo with helm:
```bash
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
```
And change your code to rely on your local list:
```hcl
resource "helm_release" "prometheus_stack" {
  name       = "ps"
  namespace  = "monitoring"
  chart      = "prometheus-community/kube-prometheus-stack"
  version    = "18.0.13"
}
```

It works perfectly. So it seems that whatever is the problem, is when terraform tries to add the repository. 

I was to just post this comment, but I decided to try another thing. Just to see if I could reproduce the problem, I deleted the prometheus-community repository from the `~/.config/helm/repositories.yaml` file. And then I tried again with the first method:
```hcl
resource "helm_release" "prometheus_stack" {
  name       = "ps"
  namespace  = "monitoring"
  repository = "https://prometheus-community.github.io/helm-charts"
  chart      = "prometheus-community/kube-prometheus-stack"
  version    = "18.0.13"
}
```
And it worked as expected.

Then, again to see if I can reproduce some problem, I added the repo again to the `~/.config/helm/repositories.yaml` file: 
```bash
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
```
And applied again with the last format, and it still worked as expected. 

So it seems that messing with the `~/.config/helm/repositories.yaml` file can fix the problem, even when theoretically terraform doesn't use it, since all the information is in the code.

My conclusion is, I know nothing.

**Comment by holms** [comment]
I've got the same problem in here:

```
Error: chart "external-dns/external-dns" not found in https://kubernetes-sigs.github.io/external-dns repository

```

While it works with helm:

```
helm NAME                               CHART VERSION   APP VERSION     DESCRIPTION                                       
center/bitnami/external-dns     4.5.5           0.7.6           ExternalDNS is a Kubernetes addon that configur...
center/stable/external-dns      2.20.4          0.7.0           DEPRECATED ExternalDNS is a Kubernetes addon th...
external-dns/external-dns       1.3.2           0.10.0          ExternalDNS synchronizes exposed Kubernetes Ser...
stable/external-dns             2.20.4          0.7.0           DEPRECATED ExternalDNS is a Kubernetes addon th...
holms@debian:~/Dev/contracts/setupad/devops-sdk/terraform/stag/post-infra$ helm repo list
NAME            URL                                           
elastic         https://helm.elastic.co                       
stable          https://charts.helm.sh/stable                 
ingress-nginx   https://kubernetes.github.io/ingress-nginx    
center          https://repo.chartcenter.io                   
external-dns    https://kubernetes-sigs.github.io/external-dns

```

**Comment by trolleksii** [comment]
I was having the same issue trying to install the consul. Usually to do that manually I run:
```SH
helm repo add hashicorp https://helm.releases.hashicorp.com
helm install hashicorp/consul
```
so the naive approach for me was to use following resource configuration:
```
resource "helm_release" "consul" {
  name             = "consul"
  repository       = "https://helm.releases.hashicorp.com"
  chart            = "hashicorp/consul"
}
```
It fails with the same error everyone else is having so I tried to "bruteforce" it and found the way to make it work:
```
resource "helm_release" "default" {
  name             = "consul"
  repository       = "https://helm.releases.hashicorp.com"
  chart            = "consul"
}
```
The more I think of it the more sense it makes. When I run `helm repo ls` it returns:
```
NAME                            URL
hashicorp                       https://helm.releases.hashicorp.com
```
so to install the chart from that specific repo I have to prefix my chart name with a repo name, `hashicorp/consul`, while Terraform Helm provider does not need that prefix.

**Comment by indistinctTalk** [comment]
Seconding the experience of @alexppg, experiencing this error and removing the helm repo resulted in terraform working again. I didn't try adding the helm repo back again to confirm if it still worked, though.

**Comment by ahmedatef85** [comment]
> I was having the same issue trying to install the consul. Usually to do that manually I run:
> 
> ```shell
> helm repo add hashicorp https://helm.releases.hashicorp.com
> helm install hashicorp/consul
> ```
> 
> so the naive approach for me was to use following resource configuration:
> 
> ```
> resource "helm_release" "consul" {
>   name             = "consul"
>   repository       = "https://helm.releases.hashicorp.com"
>   chart            = "hashicorp/consul"
> }
> ```
> 
> It fails with the same error everyone else is having so I tried to "bruteforce" it and found the way to make it work:
> 
> ```
> resource "helm_release" "default" {
>   name             = "consul"
>   repository       = "https://helm.releases.hashicorp.com"
>   chart            = "consul"
> }
> ```
> 
> The more I think of it the more sense it makes. When I run `helm repo ls` it returns:
> 
> ```
> NAME                            URL
> hashicorp                       https://helm.releases.hashicorp.com
> ```
> 
> so to install the chart from that specific repo I have to prefix my chart name with a repo name, `hashicorp/consul`, while Terraform Helm provider does not need that prefix.

This worked for me, i was using another repo, kept having the same error, after scrapping the prefix and just added the chart name, it worked.

**Comment by b-a-t** [comment]
> > so to install the chart from that specific repo I have to prefix my chart name with a repo name, `hashicorp/consul`, while Terraform Helm provider does not need that prefix.
> 
> This worked for me, i was using another repo, kept having the same error, after scrapping the prefix and just added the chart name, it worked.

Same issue I had with the `victoria-metrics-k8s-stack`, where:
```
helm repo add vm https://victoriametrics.github.io/helm-charts/
helm install vm-release vm/victoria-metrics-k8s-stack -f values.yaml -n monitoring
```
worked fine, but:
```
resource "helm_release" "victoria_metrics_stack" {
  name             = "vm-release"
  repository       = "https://victoriametrics.github.io/helm-charts"
  chart            = "vm/victoria-metrics-k8s-stack"
  version          = "0.8.3"
}
```
was giving exactly the same error:
```
Error: could not download chart: chart "vm/victoria-metrics-k8s-stack" version "0.8.3" not found in https://victoriametrics.github.io/helm-charts repository
with module.main.module.eks.module.chart_kube_victoria_metrics_stack[0].helm_release.victoria_metrics_stack[0]
on .terraform/modules/main.eks/modules/terraform-aws-eks-victoria-metrics/main.tf line 69, in resource "helm_release" "victoria_metrics_stack":

resource "helm_release" "victoria_metrics_stack" {
```

After removing the `vm/` prefix from the chart name I was finally able to install the helm chart.

I think this is more a bug, rather than misfeature, as you'd expect that the behavior of `helm` and `terraform` resource are consistent in the parameters and that you can directly translate one to another.

**Comment by jmuleiro** [comment]
> so to install the chart from that specific repo I have to prefix my chart name with a repo name, `hashicorp/consul`, while Terraform Helm provider does not need that prefix.

I came up with this solution as well. This could maybe be specified in the documentation as to avoid this mistake that is apparently very easy to make.

**Comment by pathob** [comment]
Sorry guys, but there is not even such a thing as a "repo name" in the helm_release resource.

And the original issue was not about accidentally adding a random prefix to the chart.

**Comment by StefanoMantero** [comment]
> I was having the same issue trying to install the consul. Usually to do that manually I run:
> 
> ```shell
> helm repo add hashicorp https://helm.releases.hashicorp.com
> helm install hashicorp/consul
> ```
> 
> so the naive approach for me was to use following resource configuration:
> 
> ```
> resource "helm_release" "consul" {
>   name             = "consul"
>   repository       = "https://helm.releases.hashicorp.com"
>   chart            = "hashicorp/consul"
> }
> ```
> 
> It fails with the same error everyone else is having so I tried to "bruteforce" it and found the way to make it work:
> 
> ```
> resource "helm_release" "default" {
>   name             = "consul"
>   repository       = "https://helm.releases.hashicorp.com"
>   chart            = "consul"
> }
> ```
> 
> The more I think of it the more sense it makes. When I run `helm repo ls` it returns:
> 
> ```
> NAME                            URL
> hashicorp                       https://helm.releases.hashicorp.com
> ```
> 
> so to install the chart from that specific repo I have to prefix my chart name with a repo name, `hashicorp/consul`, while Terraform Helm provider does not need that prefix.



The idea flows nice, but i really can't make it work using the following config:

```
resource "helm_release" "prometheus" {
  name             = "prometheus"
  repository       = "https://prometheus-community.github.io/helm-charts"
  chart            = "prometheus"
  namespace        = "metrics"
  create_namespace = true
  version          = "22.6.2"
}
```
I always end up with the error `Error: could not download chart: Chart.yaml file is missing` and if i try to insert the prefix `prometheus-community` in the chart like `prometheus-community/prometheus` i just end up in the ` could not download chart: chart "prometheus-community" version "22.6.2" not found in ....`.

The `helm repo ls` returns:
```
NAME                                 URL
prometheus-community    https://prometheus-community.github.io/helm-charts
```
meaning that if i follow the rule you mentioned, i just need to define the chart as 'prometheus'.

On the other hand if i try the `No repository url` approach, by having it installed directly in helm as [alexppg](https://github.com/alexppg) suggested, everything works perfecly.

What i'm doing wrong? Any suggestion is welcome as i'm really running out of ideas...

**Comment by StefanoMantero** [comment]
> > I was having the same issue trying to install the consul. Usually to do that manually I run:
> > ```shell
> > helm repo add hashicorp https://helm.releases.hashicorp.com
> > helm install hashicorp/consul
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so the naive approach for me was to use following resource configuration:
> > ```
> > resource "helm_release" "consul" {
> >   name             = "consul"
> >   repository       = "https://helm.releases.hashicorp.com"
> >   chart            = "hashicorp/consul"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It fails with the same error everyone else is having so I tried to "bruteforce" it and found the way to make it work:
> > ```
> > resource "helm_release" "default" {
> >   name             = "consul"
> >   repository       = "https://helm.releases.hashicorp.com"
> >   chart            = "consul"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The more I think of it the more sense it makes. When I run `helm repo ls` it returns:
> > ```
> > NAME                            URL
> > hashicorp                       https://helm.releases.hashicorp.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so to install the chart from that specific repo I have to prefix my chart name with a repo name, `hashicorp/consul`, while Terraform Helm provider does not need that prefix.
> 
> The idea flows nice, but i really can't make it work using the following config:
> 
> ```
> resource "helm_release" "prometheus" {
>   name             = "prometheus"
>   repository       = "https://prometheus-community.github.io/helm-charts"
>   chart            = "prometheus"
>   namespace        = "metrics"
>   create_namespace = true
>   version          = "22.6.2"
> }
> ```
> 
> I always end up with the error `Error: could not download chart: Chart.yaml file is missing` and if i try to insert the prefix `prometheus-community` in the chart like `prometheus-community/prometheus` i just end up in the ` could not download chart: chart "prometheus-community" version "22.6.2" not found in ....`.
> 
> The `helm repo ls` returns:
> 
> ```
> NAME                                 URL
> prometheus-community    https://prometheus-community.github.io/helm-charts
> ```
> 
> meaning that if i follow the rule you mentioned, i just need to define the chart as 'prometheus'.
> 
> On the other hand if i try the `No repository url` approach, by having it installed directly in helm as [alexppg](https://github.com/alexppg) suggested, everything works perfecly.
> 
> What i'm doing wrong? Any suggestion is welcome as i'm really running out of ideas...

Update here. I really don't know what happend. Maybe i removed some files like the `tfstate` but now it's properly working.... sorry about that.
