### ISSUE TITLE
Proposal: Checksum local charts

### ISSUE THREAD

**Issue by burdiyan** [hashicorp/terraform-provider-helm#72]
Currently the provider doesn't recognize changes in the chart if it's referenced from the local file system, even if you change the version in `Chart.yaml` file.

A possible solution could be to checksum the canonical contents of a chart and store the sum in the Terraform state. But this would imply checksum all the charts on each refresh in order to check if it was changed. Probably it's not the most efficient way of doing that.

Another approach could be at least tracking a version specified in `Chart.yaml` and compare it with the one stored in the Terraform state.

Does anyone have more ideas about how changes in a local chart could mark a Terraform resource for an update?

**Comment by emmekappa** [comment]
I have a similar issue and for now the only way is to update the version inside the `helm_release` resource every time I made a change inside the local charts, not very comfortable ;)

**Comment by Rowern** [comment]
There is a simple way to fix this, add a checksum var to your release that will depend on the content of the chart.

```hcl
data "archive_file" "chart_checksum" {
  type        = "zip"
  source_dir = "chart_path/"
  output_path = "${path.module}/chart.zip"
}

data "template_file" "service" {
  template = <<EOF
# Blabla
checksum: ${data.archive_file.chart_checksum.output_sha}
# Blabla
EOF
}

resource "helm_release" "service" {
  name = "${var.name_prefix}${var.service_name}"
  chart = "chart_path/"

  values = [
    "${data.template_file.service.rendered}"
  ]
}
```

**Comment by burdiyan** [comment]
@Rowern Thanks, that's great idea! I think this trick can solve the issue.

**Comment by panzelva** [comment]
Hello :) what is the status of this issue? Is there any plan for implementation?
