### ISSUE TITLE
Helm Deployment gets timeout error on re-deploy

### ISSUE THREAD

**Issue by DonBower** [hashicorp/terraform-provider-helm#721]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 0.13.5
Provider version: 2.1.0
Kubernetes version: 1.18.9
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Helm version: 3.5.2
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```
resource "helm_release" "thisChart" {
  name       = var.helmName
  timeout    = var.helmTimeout

  chart      = var.chartLocation
  version    = var.chartVersion
  values     = [
    file(var.helmValues)
  ]

  dynamic set {
    for_each = var.valueSets
    content {
      name  = set.key
      value = set.value
    }
  }
}
```

### Debug Output
email me for gist.
NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

Succesfull Deployment
### Actual Behavior


Error: timed out waiting for the condition

  on /Users/dobower/Developer/ent-devops-tf/tf-paas-source/k8s/helmRelease/main.tf line 1, in resource "helm_release" "thisChart":
   1: resource "helm_release" "thisChart" {

### Important Factoids

None.
But When we deploy on fresh EKS Cluster, it is successful.  and with NO changes, and run terraform apply command again, it fails with timeout.
### References

none

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi  Don,

Can you please share some more details about the chart you used when you encountered this as well as the values in `var.valueSets`?
There is little information in the original report with which to try to reproduce this.

Thanks!
