### ISSUE TITLE
Race condition on namespace creating when parallel deployments

### ISSUE THREAD

**Issue by johnmarcou** [hashicorp/terraform-provider-helm#73]
Hello,

I would like to report an issue when deploying multiple chart release in parallel to the same new created namespace. This issue seems to be a race condition, since it's not happening every time.

`count=2` or `count=3` seems to have good probability to reproduce the issue.
For some reason,  `count=10` never reproduced during my tests...

### Terraform Version
Terraform v0.11.7
Terraform Helm Provider v0.5.1

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
In a new folder, create a simple and light testing helm chart:
```
helm create app
rm app/templates/{deployment.yaml,ingress.yaml}
```

Add this Terraform code:
```hcl
resource "helm_release" "apps" {
  count     = 2
  name      = "app${count.index + 1}"
  namespace = "new-namespace"
  chart     = "${path.module}/app"
}
```

### Debug Output
```
helm_release.apps[1]: Creating...
  chart:            "" => "/tmp/test/app"
  disable_webhooks: "" => "false"
  force_update:     "" => "false"
  keyring:          "" => "/Users/john/.gnupg/pubring.gpg"
  metadata.#:       "" => "<computed>"
  name:             "" => "app2"
  namespace:        "" => "new-namespace"
  recreate_pods:    "" => "false"
  reuse:            "" => "false"
  reuse_values:     "" => "false"
  timeout:          "" => "300"
  verify:           "" => "false"
helm_release.apps[0]: Creating...
  chart:            "" => "/tmp/test/app"
  disable_webhooks: "" => "false"
  force_update:     "" => "false"
  keyring:          "" => "/Users/john/.gnupg/pubring.gpg"
  metadata.#:       "" => "<computed>"
  name:             "" => "app1"
  namespace:        "" => "new-namespace"
  recreate_pods:    "" => "false"
  reuse:            "" => "false"
  reuse_values:     "" => "false"
  timeout:          "" => "300"
  verify:           "" => "false"
helm_release.apps[1]: Creation complete after 2s (ID: app2)

Error: Error applying plan:

1 error(s) occurred:

* helm_release.apps[0]: 1 error(s) occurred:

* helm_release.apps.0: rpc error: code = Unknown desc = release app1 failed: namespaces "new-namespace" already exists

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior
The two charts should be deployed without namespace creating clash.

### Actual Behavior
Randomly, the `terraform apply` crash.

### Steps to Reproduce
```
terraform init
while true; do
    terraform apply -auto-approve; sleep 2;
    terraform destroy -force; sleep 2;
    kubectl delete ns new-namespace; sleep 5;
done
```
By watching `watch -n 1 'helm list -a | grep app'`, you will see a `failed` release deployment sometimes:
```
app1                    1               Fri May 11 17:18:42 2018        FAILED          app-0.1.0
new-namespace
app2                    1               Fri May 11 17:18:42 2018        PENDING_INSTALL app-0.1.0
new-namespace
```

### Real use-case
I have this race condition in a real context which I reproduced with that simple example.

The real context is 2 nginx ingress controller deployments in the `ingress-controllers` namespace (without a "loop count", but two separate release definition), one for internal and one for external purpose.

### Workaround:
Use two different namespaces for now:
 - `internal-ingress-controllers`
 - `external-ingress-controllers`

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
