### ISSUE TITLE
How to set initdbScripts through Terraform?

### ISSUE THREAD

**Issue by morizmartiner** [hashicorp/terraform-provider-helm#734]
Hi,

I am trying to set up mariadb-galera on Kubernetes and I want to specify a sql schema that is executed on startup. The option for doing that is setting the initdbScripts property, however, I don't know how to do it.

This is my current code:
  set {
    name = "initdbScripts"
    value = "init.sql: |${file("./modules/webapps/init.sql")}"
  }

The error I get is: error validating "": error validating data: ValidationError(ConfigMap.data): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "string", expected "map"

Thank you very much!

**Comment by jrhouston** [comment]
This worked for me:

```hcl
resource "helm_release" "test" {
  name       = "test"
  chart      = "mariadb-galera"
  repository = "https://charts.bitnami.com/bitnami"

  set {
    name = "initdbScripts.init\\.sql"
    value = file("init.sql")
  }
}
```
