### ISSUE TITLE
helm_release fails with "Chart.yml is missing" when a folder with the chart's name exists

### ISSUE THREAD

**Issue by Heleydin** [hashicorp/terraform-provider-helm#735]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: Terraform v0.14.8
Provider version: 2.1.1
Kubernetes version: 1.18.16
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "kong-resource" {
  name = "kong-release"
  repository = "https://charts.konghq.com"
  chart = "kong"
  namespace = "kong"
}
```

### Debug Output
Our Terraform plan is huge, so is the debug output. I only put here the related logs :
```
2021/04/22 18:33:11 [DEBUG] helm_release.kong-resource: apply errored, but we're indicating that via the Error pointer rather than returning it: Chart.yaml file is missing

Error: Chart.yaml file is missing

  on kong.tf line 27, in resource "helm_release" "kong-resource":
  27: resource "helm_release" "kong-resource" {
```

### Steps to Reproduce
1. Add above ressource and `terraform apply` => it works
2. Delete ressource and `terraform apply` (cleanup)
3. Create a folder in the root terraform folder with the chart's name (here "kong")
4. Add ressource and `terraform apply` => it fails

### Expected Behavior
Smooth apply

### Actual Behavior
Fail because Chart.yml is missing
I have tried with another charts repo (Datadog) with the same result (by creating a Datadog folder)

### Important Factoids
Running on GKE

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by hoeschele** [comment]
I have been experiencing this issue for a week now, the issue is with the dash in the name of your module's directory

I do have a workaround though

all of our helm release resources are in separate modules.  if you change the dash to an underscore in the directory name it seems to work

example:
```
# this doesn't work
module "eks-logger" {
  source         = "./eks-logger"
  ... etc other vars
}

#this does work
module "eks-logger" {
  source         = "./eks_logger"
  ... etc other vars
}
```

dir path for module should be **eks_logger** instead of eks-logger as well, it doesn't matter the resource name, or anything else inside your module

my eks_logger module's main.tf is

```
resource "helm_release" "eks-logger" {
  name             = "eks-logger"
  chart            = "eks-logger"
  repository       = var.chart_repo
...
}
```

**Comment by dak1n1** [comment]
I was able to reproduce this issue using the ingress-nginx chart:

```
helm_release.test: Creating...
helm_release.test: Creation complete after 10s [id=ingress-nginx]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

$ ls
main.tf  terraform.tfstate

$ helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ingress-nginx   default         1               2021-04-26 15:46:12.386254139 -0700 PDT deployed        ingress-nginx-3.29.0    0.45.0     

$ terraform destroy --auto-approve
helm_release.test: Refreshing state... [id=ingress-nginx]
helm_release.test: Destroying... [id=ingress-nginx]
helm_release.test: Destruction complete after 0s

Destroy complete! Resources: 1 destroyed.

$ mkdir ingress-nginx
$ terraform apply --auto-approve
helm_release.test: Creating...
╷
│ Error: Chart.yaml file is missing
│ 
│   on main.tf line 30, in resource "helm_release" "test":
│   30: resource "helm_release" "test" {
│ 
╵
```

It seems like the helm provider is ignoring the repository attribute in the configuration when it finds a local directory matching the given chart name.

```
$ cat main.tf
terraform {
  required_providers {
    helm = {
      source = "hashicorp/helm"
      version = "2.1.1"
    }
  }
}

provider "helm" {
  experiments {
    manifest = true
  }
  kubernetes {
    config_path = "~/.kube/config"
  }
}

resource "helm_release" "test" {
  wait       = false
  name       = "ingress-nginx"

  repository = "https://kubernetes.github.io/ingress-nginx"
  chart      = "ingress-nginx"
}
```

**Comment by dak1n1** [comment]
It turns out this behavior comes from the upstream Helm code, so unfortunately it's not something we can fix in the provider.

https://github.com/hashicorp/terraform-provider-helm/blob/3ed78b6fa11de7473bd960f2adfeb2614dbda90f/vendor/helm.sh/helm/v3/pkg/action/install.go#L631
 
We could add some validation to the provider which would warn users about this behavior when they have a directory with the same name as their chart name. If anyone would like to make a PR for this, we would be happy to accept it.

**Comment by Heleydin** [comment]
Thank you @dak1n1 for this investigation.
It's not a big issue once we understand what is happening, so I agree with the solution you suggest.
Unfortunatly my Go skills are close to nil so I won't be able to contribute.

**Comment by samwho** [comment]
I'm also experiencing this problem but with a chart I have no control over. Is there a workaround?

**Comment by iamNoah1** [comment]
FYI: this issue is not an issue related to terraform, but with helm. I am facing that issue when trying to install a chart via helm cli and there is a directory present with the same name as the chart I am trying to install ^^

**Comment by iBrandyJackson** [comment]
H all - We are closing this issue as this is something that has become a catch-all for a multitude of different related issues. We ask that if you run into further related problems, please open a new issue outlining the specifics and we will review them individually.
