### ISSUE TITLE
https://github.com/hashicorp/terraform-provider-helm/issues/346

### ISSUE THREAD

**Issue by alexmnyc** [hashicorp/terraform-provider-helm#736]
Helm upgrade must be implemented. Don't be locking issues that are extremely relevant please 

https://github.com/hashicorp/terraform-provider-helm/issues/346

**Comment by aareet** [comment]
Hi @alexmnyc, thanks for the note. My mistake - when I reopened the issue in July, I thought hashibot would automatically unlock, but it seems to not have done so. Closing in favour of #346 - we’ll track progress there.
