### ISSUE TITLE
terraform-provider-helm 2.1.2 - Error verifying GPG signature for provider "helm"

### ISSUE THREAD

**Issue by tha2015** [hashicorp/terraform-provider-helm#740]
Got below error when terraform downloading latest version of helm provider

```
Error verifying GPG signature for provider "helm"

Terraform was unable to verify the GPG signature of the downloaded provider

files using the keys downloaded from the Terraform Registry. This may mean that

the publisher of the provider removed the key it was signed with, or that the

distributed files were changed after this version was released.
```

@aareet

**Comment by MarjanJordanovski** [comment]
I'm getting the same issue today for the first time, please help!

**Comment by joshm91** [comment]
I wonder if this is something to do with the recent [signing key revocation](https://www.theregister.com/2021/04/26/hashicorp_reveals_exposure_of_private/) that Hashicorp did.

**Comment by tha2015** [comment]
> I wonder if this is something to do with the recent [signing key revocation](https://www.theregister.com/2021/04/26/hashicorp_reveals_exposure_of_private/) that Hashicorp did.

I think you are right, from that link
> "the GPG private key used for signing hashes used to validate HashiCorp product downloads... was exposed."

**Comment by joshm91** [comment]
Yeah, and looking at the list of providers my run this morning was attempting to download, helm is the only one that has done a recent release, even though trying to pin to v2.1.1 still didn't work.

**Comment by nico2610** [comment]
Pinning 1.3 worked for me : 

`
terraform {
  required_providers {
    helm = "~> 1.3"
  }`

**Comment by raetsel99** [comment]
`required_providers {
  helm = "2.1.1"
}`

Will work ok for us

**Comment by raetsel99** [comment]
> Yeah, and looking at the list of providers my run this morning was attempting to download, helm is the only one that has done a recent release, even though trying to pin to v2.1.1 still didn't work.

@joshm91 did you try = "2.1.1" or "~>2.1.1" ?

**Comment by joshm91** [comment]
@raetsel99 I tried "2.1.1" on terraform 0.12.29 but I managed to find a copy of the provider binary in another stack's cache so worked around it for now.

**Comment by aareet** [comment]
Hi all, due to the [GPG key rotation](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512), releases of Terraform providers made after today will only be verifiable on patched versions of Terraform, as described in this post: https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570. You'll need to update your terraform version to use the latest version of the provider.

**Comment by wolfulve** [comment]
This worked for us, e..g,

terraform {
         backend "s3" {}
         required_providers { helm = "2.1.1" } // added
}

**Comment by aareet** [comment]
> required_providers { helm = "2.1.1" } // added

In general, yes, we do recommend specifying version constraints for your providers - https://www.terraform.io/docs/language/providers/requirements.html#requiring-providers

**Comment by switchboardOp** [comment]
Pinning the Helm provider to `2.1.1` did not work for me. Upgrading to terraform `0.12.31` did.

**Comment by aareet** [comment]
Great, I will close this issue for now, please let me know if there are any further issues.
