### ISSUE TITLE
Helm_release cannot be destroyed.

### ISSUE THREAD

**Issue by MoShiKB** [hashicorp/terraform-provider-helm#751]
<h2>Terraform, Provider, Kubernetes and Helm Versions</h2>

```
Terraform version: v0.15.3
Provider version:v2.1.2
Kubernetes version:1.20.6
```
<h2>Affected Resource(s)</h2>
- helm_release

### Terraform Configuration Files
```
provider "helm" {
  kubernetes {
    host                   = rke_cluster.RANCHER.api_server_url
    client_certificate     = rke_cluster.RANCHER.client_cert
    client_key             = rke_cluster.RANCHER.client_key
    cluster_ca_certificate = rke_cluster.RANCHER.ca_crt
  }
}


resource "helm_release" "rancher_ui" {
  name             = "rancher"
  repository       = "https://releases.rancher.com/server-charts/stable"
  chart            = "rancher"
  namespace        = "cattle-system"
  version          = "2.5.7"
  create_namespace = "true"

  set {
    name  = "hostname"
    value = var.rancher_url
  }

  set {
    name  = "tls"
    value = "external"
  }
}
```

### Steps to Reproduce
1. `terraform destroy

### Expected Behavior
The resource should be destroyed.

### Actual Behavior
The resource returns an error, seems like he doesn't have the values he had on creation.

Error:
```
╷
│ Error: Kubernetes cluster unreachable: invalid configuration: default cluster has no server defined
│
│   with helm_release.rancher_ui,
│   on helm.tf line 11, in resource "helm_release" "rancher_ui":
│   11: resource "helm_release" "rancher_ui" {
│
```

### Important Factoids
The provider gets all his data from the RKE provider with rke_cluster resource: https://registry.terraform.io/providers/rancher/rke/latest/docs/resources/cluster

It creates the resource, with everything I needed(vars and so), but when I'm trying to destroy it, It returns an error.

**Comment by koi8** [comment]
I have same issue over GKE when when running `terraform apply` which should execute helm upgrade, so this issue related not only to `destroy`

**Comment by MoShiKB** [comment]
> I have same issue over GKE when when running `terraform apply` which should execute helm upgrade, so this issue related not only to `destroy`

I found a workaround at least for me, I'm removing the chart from the state file, it doesn't has any dependencies for me, so it is an option till fix.

**Comment by lperrin-obs** [comment]
I got the same issue using a RKE cluster with same type of provider configuration and with `terraform apply`.

It works when I do the `terraform apply` from a terminal but not when it's run by gitlab-ci.

**Comment by IuriGarcia** [comment]
Using on Azure Kubernetes Service. I am really depending on first triggering `terraform destroy -target helm_release.myrelease` and only after that: `terraform destroy`.

**Comment by Yokutto** [comment]
Idk why the bot closed this.

The issue is still good and fresh. We need some help from someone that knows how to debug this
