### ISSUE TITLE
Provider produces inconsistent final plan after upgrading to v2.1.2

### ISSUE THREAD

**Issue by mcbanderson** [hashicorp/terraform-provider-helm#752]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 0.13.5
Provider version: 2.1.2
Kubernetes version: 1.19
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "ingress_controller" {
  name       = "ingress-controller"
  chart      = "ingress-nginx"
  version    = "3.30.0"
  namespace  = "kube-system"
  repository = "https://kubernetes.github.io/ingress-nginx"
  
  values = [
    data.template_file.nginx.0.rendered
  ]
}
```

### Debug Output

```
Error: Provider produced inconsistent final plan

When expanding the plan for module.nginx.helm_release.ingress_controller[0] to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/helm" produced an invalid new value for
.wait_for_jobs: was cty.False, but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Panic Output

N/A

### Steps to Reproduce

1. `terraform apply` w/ helm provider 2.1.1
2. `terraform apply` w/ helm provider 2.1.2

### Expected Behavior

`terraform apply` completes successfully

### Actual Behavior

`terraform apply` fails with the above error.

### Important Factoids

This also occurred on a second helm_release within our hcl, but several others did not seem to be affected. I tried explicitly adding `wait_for_jobs = false` to the configuration for the affected `helm_release`s but there was no effect.

### References

N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mnaser** [comment]
We're hitting this quite often.  Even switching down to 2.1.0 continues to exhibit this behavior.  I've even tried to `taint` the resource, and it recreates successfully, but fails later if it's trying to make any changes.

Sadly, it's making the really awesome manifests feature really hard to use (but, understanding that it is a preview!)

**Comment by darkhelmet** [comment]
Experiencing this sporadically with 2.2.0, K8s 1.21, tf 1.0.4.

**Comment by chrisroat** [comment]
May be duplicate of #711 .  Solution there is to turn off manifest experiment (#702)

**Comment by cameronattard** [comment]
We're also experiencing this error and we've never had manifest experiment enabled.

**Comment by hmlkao** [comment]
I faced the same problem with **Helm provider v2.2.0**, have solved it by:

1. Pull tfm state into file
    ```
    terraform state pull > /tmp/tfm-state.json
    ```
1. Modify state of affected resource (change `"wait_for_jobs": null` to `"wait_for_jobs": false`)
1. Push tfm state back to backend 
    ```
    terraform state push /tmp/tfm-state.json
    ```
If you are using local file to store state, you can just change it there.

**Comment by smartpcr** [comment]
my tf state have false value for all "wait_for_jobs" and still failed with the following error , using `hashicorp/helm v2.4.1`

``` log
Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.prom2mdm.helm_release.prom2mdm to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/helm" produced an      
│ invalid new value for .set: planned set element cty.ObjectVal(map[string]cty.Value{"name":cty.StringVal("images.prom2mdm.tag"), "type":cty.NullVal(cty.String),
│ "value":cty.StringVal("2.0.master.20211105.1")}) does not correlate with any element in actual.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

within resource `helm_release`, I have:

``` tf
  set {
    name  = "images.prom2mdm.tag"
    value = var.converterImageTag
  }
```

**Comment by xiaodoli** [comment]
any update?

**Comment by btleedev** [comment]
For what it's worth, we encountered this bug in our own provider in very specific circumstances (albeit we're using SDKv1, so we're not 100% sure if this occurs in SDKv2 but it appears so).

1. `terraform apply` with the following conditions.
   1. For affected resource `r`, your new schema attribute `a` must be of a type that does not allow `nil` values, and also uses the `DefaultValue`.
   2. Your `*.tfstate` file must be from a provider version where this new schema attribute `a` has not been introduced (so in this case, v2.1.1).
   3. Must have resource `r` inside of a module directly from the root (may also happen in modules of modules, but we didn't test this).
   4. When applying, resource `r` must not have any changes in the plan BESIDES adding this new default value. ie state and your Kubernetes resource must match in the previous provider version.

This leads me to believe this is an issue with the SDK. It somewhat eludes to this in the comment in [terraform-plugin-sdk - schema.go](https://github.com/hashicorp/terraform-plugin-sdk/blob/v2.10.1/helper/schema/schema.go#L114).

If you're the developer of the provider, you can mitigate this issue by either
1. resorting to not having default values and treat `nil` as an acceptable value, or
2. migrating older state files using StateUpgraders, or
3. updating the value in the state file when Terraform does a refresh, ie in your `Read` method of your provider.

You could also manually update your state file to set this new attribute as mentioned in comment [#752](https://github.com/hashicorp/terraform-provider-helm/issues/752#issuecomment-905301146).

Hope this helps.
