### ISSUE TITLE
Helm chart version not found even if it exists on repo

### ISSUE THREAD

**Issue by KrustyHack** [hashicorp/terraform-provider-helm#755]
Ay,

I can't update an Helm chart even if the version exists on repo :

```
[...]
resource "helm_release" "elasticsearch-cluster-7" {
  name                = "elasticsearch-cluster-7"
  repository          = "https://helm.elastic.co"
  chart               = "elasticsearch"
  version             = "7.13.0" # Was 7.12.1 before
  namespace           = kubernetes_namespace.elasticsearch-cluster-7.metadata.0.name

  values = [
    file("${path.module}/elasticsearch-7.values.yaml"),
  ]

}
```

But when I execute the plan :

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.elasticsearch-7.helm_release.elasticsearch-cluster-7 will be updated in-place
  ~ resource "helm_release" "elasticsearch-cluster-7" {
        id                         = "elasticsearch-cluster-7"
        name                       = "elasticsearch-cluster-7"
      ~ version                    = "7.12.1" -> "7.13.0"
        # (25 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.elasticsearch-7.helm_release.elasticsearch-cluster-7: Modifying... [id=elasticsearch-cluster-7]

Error: chart "elasticsearch" version "7.13.0" not found in https://helm.elastic.co repository

  on modules/elasticsearch/elasticsearch-7/elasticsearch-7.tf line 11, in resource "helm_release" "elasticsearch-cluster-7":
  11: resource "helm_release" "elasticsearch-cluster-7" {
```

But if I check the repo :

```
[...]
<Contents>
<Key>helm/elasticsearch/elasticsearch-7.13.0.tgz</Key>
<Generation>1622064547521000</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2021-05-26T21:29:07.539Z</LastModified>
<ETag>"9293e009a09db3e87775373a0a051173"</ETag>
<Size>27421</Size>
</Contents>
[...]

Is there a problem on repo refresh on Terraform side or something like that ?

**Comment by riisi** [comment]
I had this issue as well, with v2.2.0 of the provider, with the chart below. 
I was able to use the workaround in https://github.com/hashicorp/terraform-provider-helm/issues/707#issuecomment-844548333

```tf
resource "helm_release" "metrics-server" {
  name  = "metrics-server"
  chart = "https://charts.bitnami.com/bitnami/metrics-server-5.9.2.tgz"
  # repository = "https://charts.bitnami.com/bitnami"
  # version    = "5.9.2"
  namespace         = "kube-system"
  atomic            = true
  cleanup_on_fail   = true
  reset_values      = true
  dependency_update = true
}
```

**Comment by zorgzerg** [comment]
Unfortunately, the same problem is observed with the prometheus-elasticsearch-exporter chart

```terraform
resource "helm_release" "exporter" {
  name  = "elasticsearch-exporter"
  chart = "prometheus-community/prometheus-elasticsearch-exporter"
  repository = "https://prometheus-community.github.io/helm-charts/"
  version    = "4.7.0"
  namespace  = "monitoring"
  atomic     = true
}
```

Fix it please

**Comment by b-a-t** [comment]
> Unfortunately, the same problem is observed with the prometheus-elasticsearch-exporter chart
> 
> ```terraform
> resource "helm_release" "exporter" {
>   name  = "elasticsearch-exporter"
>   chart = "prometheus-community/prometheus-elasticsearch-exporter"
>   repository = "https://prometheus-community.github.io/helm-charts/"
>   version    = "4.7.0"
>   namespace  = "monitoring"
>   atomic     = true
> }
> ```
> 
> Fix it please

For this particular one try the suggestion in #707 - i.e. use chart name without the prefix, as `prometheus-elasticsearch-exporter`. That worked for me with the VictoriaMetrics k8s stack.

**Comment by zorgzerg** [comment]
> > Unfortunately, the same problem is observed with the prometheus-elasticsearch-exporter chart
> > ```terraform
> > resource "helm_release" "exporter" {
> >   name  = "elasticsearch-exporter"
> >   chart = "prometheus-community/prometheus-elasticsearch-exporter"
> >   repository = "https://prometheus-community.github.io/helm-charts/"
> >   version    = "4.7.0"
> >   namespace  = "monitoring"
> >   atomic     = true
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Fix it please
> 
> For this particular one try the suggestion in #707 - i.e. use chart name without the prefix, as `prometheus-elasticsearch-exporter`. That worked for me with the VictoriaMetrics k8s stack.

Thanks for the reply, I already fixed it
