### ISSUE TITLE
Quoting issue with serviceAccount.annotations."eks.amazonaws.com/role-arn"

### ISSUE THREAD

**Issue by visit1985** [hashicorp/terraform-provider-helm#762]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 0.13.3
Provider version: 2.2.0
Kubernetes version: 1.20
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "appmesh_controller" {
  name       = "appmesh-controller"
  repository = "https://aws.github.io/eks-charts"
  chart      = "appmesh-controller"
  version    = "1.4.0"
  namespace = "kube-system"

  set {
    name = "region"
    value = "eu-central-1"
    type = "string"
  }

  set {
    name = "sidecar.resources.requests.cpu"
    value = "100m"
    type = "string"
  }

  set {
    name = "serviceAccount.annotations.\"eks\\.amazonaws\\.com/role-arn\""
    value = "arn:aws:iam::ACCOUNTID:role/ROLENAME"
    type = "string"
  }
}
```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

The `helm_release` gets created without error.

It resembles the following working command sequence:

```bash
helm repo add eks https://aws.github.io/eks-charts
helm repo update
helm upgrade --install appmesh-controller eks/appmesh-controller \
    --version 1.4.0 \
    --namespace kube-system \
    --set region=eu-central-1 \
    --set sidecar.resources.requests.cpu=100m \
    --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::ACCOUNTID:role/ROLENAME
```

### Actual Behavior

`Error: ServiceAccount "appmesh-controller" is invalid: [metadata.annotations: Invalid value: "\"eks.amazonaws.com/role-arn\"": prefix part a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.annotations: Invalid value: "\"eks.amazonaws.com/role-arn\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]
`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ashokkumar-sage** [comment]
Changing to the below works for me
```
{
      name  = "serviceAccount.annotations.eks\\.amazonaws\\.com\\/role\\-arn"
      value = "arn:aws:iam::ACCOUNTID:role/ROLENAME"
      type  = "string"
 }
```

**Comment by visit1985** [comment]
Thanks for pointing me in the right direction! It turned out, it is enough to escape the dots.

```
{
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = "arn:aws:iam::ACCOUNTID:role/ROLENAME"
    type  = "string"
}
```
