### ISSUE TITLE
helm_release not picking up an added yaml template

### ISSUE THREAD

**Issue by thomashoef** [hashicorp/terraform-provider-helm#769]
### Terraform, Provider, Kubernetes and Helm Versions
```
Terraform version: 0.14.6
Provider version: 2.2.0
Kubernetes version: 1.13.4
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "aws_helper_components" {

  name          = "aws-helper-components"
  chart         = "./helm/aws-helper-components"
  namespace     = "default"
  atomic        = true
  timeout       = 900
}
```

### Steps to Reproduce
1. `terraform apply`
2. Add a yaml file to ./helm/aws-helper-components or change a yaml file in the helm release folder.
3. `terraform apply` 

### Expected Behavior
The deployment added in step 2 (as a file to the helm templates folder for the chart "aws-helper-components" is applied.

### Actual Behavior
helm-release does not see the added file, nor does it see changes done in existing yaml files.

**Comment by chilicat** [comment]
I worked around the issue by creating a hash for all template files. I set the hash as helm value which forces the the provider to re-apply.

```
locals {
     // create a hash of all template files 
     charthash = sha1(join("", [for f in fileset("${path.module}/charts/", "**/*.yaml"): filesha1("${path.module}/charts/${f}")]))
}

resource "helm_release" "testapp" {
  name             = "testapp"
  chart            = "${path.module}/charts/testapp"
  namespace        = var.namespace

  set {
    name  = "charthash"
    value = local.charthash
  }

  ....
```
