### ISSUE TITLE
Helm provider does not show which resources will be created

### ISSUE THREAD

**Issue by galindro** [hashicorp/terraform-provider-helm#770]
Guys, I was reading this [blog post](https://thenewstack.io/a-better-way-to-provision-kubernetes-using-terraform/) (published in 14-07-21) before try this provider and would like to know if what was shown there is still valid: this provider isn't capable to shown to the user what Kubernetes resources will be created in plan or apply phases. If yes, is there any plans to improve it?

**Comment by jrhouston** [comment]
Hi @galindro – That is correct, however where the article says:

> Similarly, if planning a change, there’s again no way to tell what the changes to the Kubernetes resources will be.

Is wrong as the the provider will show the diff of resources that are going to be changed when a helm_release resource is updated.  

Also yes, I have plans to add rendering of the manifest at create time, too.

**Comment by galindro** [comment]
> Is wrong as the the provider will show the diff of resources that are going to be changed when a helm_release resource is updated.

Ok, so, it will show the diff however it won't consider the added helm chart's entities as resources in terraform right? For example: if a helm chart creates a service, a service account and a deployment, these 3 entities won't be a terraform resource, but only the helm chart itself.

> Also yes, I have plans to add rendering of the manifest at create time, too.
And here, you are saying that you have plans to improve the provider by adding the above capability right? Is it on the roadmap?

**Comment by jrhouston** [comment]
Yes – all the state will reside within the one `helm_manifest` resource.

**Comment by raj-saxena** [comment]
@jrhouston any updates on this? Are you working on this? If you are open for PRs, can you please guide on how to proceed?

**Comment by cen1** [comment]
Would be really nice if this was added since the initial deploy is essentially blind. Doing this in production is.. well.. not ideal to say the least.
