### ISSUE TITLE
unable to parse key: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by Borrelworst** [hashicorp/terraform-provider-helm#773]
### Terraform, Provider, Kubernetes and Helm Versions
```
Terraform version: 1.0.3
Provider version: v2.2.0
Kubernetes version: 1.19
```

### Affected Resource(s)
- aad-pod-identity
- https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts

### Terraform Configuration Files
```hcl
resource "helm_release" "aad_pod_identity" {

  name       = "aad-pod-identity"
  repository = "https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts"
  chart      = "aad-pod-identity"
  version    = "4.1.2"
  namespace  = "aad-pod-identity"

  values = [
    "${file("../../module/config/05-pod-identity-values.yaml")}"
  ]

  set {
    name = "azureIdentities.mytestidentity.namespace"
    value = "mytestidentityns"
    type = "string"
  }

  set {
    name = "azureIdentities.mytestidentity.clientID"
    value = "xxxx-xxxxx-xxxxx-xxxxxx
    type = "string"
  }
  
  set {
    name = "azureIdentities.mytestidentity.resourceID"
    value = "/subscriptions/xxxxxxx-xxxxxx-xxxxx-xxxxxx/resourcegroups/my-resource/group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/my-aks-identity"
    type = "string"
  }
   
  set {
    name = "azureIdentities.mytestidentity.type"
    value = "0"
    type = "string"
  }
  
  set {
    name = "azureIdentities.mytestidentity.binding.name"
    value = "mytestidentity-binding"
    type = "string"
  }
  
  set  {
    name = "azureIdentities.mytestidentity.binding.selector"
    value = "mytestidentity-selector"
    type = "string"
  }
}

```

### Debug Output
```
module.aks-test-cl1-config.helm_release.aad_pod_identity: Creating...
╷
│ Error: failed parsing key "azureIdentities.mytestidentity.namespace" with value mytestidentityns, unable to parse key: interface conversion: interface {} is nil, not map[string]interface {}
│ 
│   with module.aks-test-cl1-config.helm_release.aad_pod_identity,
│   on ../../module/config/05-pod-identity.tf line 7, in resource "helm_release" "aad_pod_identity":
│    7: resource "helm_release" "aad_pod_identity" {
│ 
```

### Steps to Reproduce
1. `terraform apply`

### Expected Behavior
On all other helm charts this setup works fine, this is the first chart where I experience this issue. When putting the correct data in the values.yaml file directly, there are no issues.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by MarekStrejczek-TomTom** [comment]
I'm experiencing a very similar issue, same error message. Cannot find any reason why the same code works for other charts, but  keeps failing for one. 
I'm not sure if the error is raised by Terraform Helm provider or Helm itself, though.

**Comment by rifen** [comment]
The fix for me was escaping `\\` periods. E.g.:
```
  set {
    name = "azureIdentities.mytestidentity\\.namespace"
    value = "mytestidentityns"
    type = "string"
  }
```

**Comment by c4siva** [comment]
I found the cause and workaround for this issue. You are supplying a values.yml for [values field](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#values) in helm_release resource.  In that values.yml file, You will see the same fields confured using set{} blocks. None of those fields in values.yml can be left blank. ( Ex : azureIdentities.mytestidentity.binding in this ticket ).

**Comment by Borrelworst** [comment]
Oke that makes sense. At the moment I am not working on this project where I encountered this issue, so at this point I am not able to test it. I must comment that I have not had issues with other Helm charts where I probably did similar configurations.

**Comment by lowem1** [comment]
I ran into this earlier this month with the airflow helm chart. Its an extremely ambiguous error, but try to check your values.yaml file for any value that is out of place. It's not parsing the key in the yaml file, when converting it over to a map. Once I resolved that issue it worked fine for me. If there are mandatory fields in the yaml, or an indentation error, this will pop up. 

Hope that helps.
