### ISSUE TITLE
Forbidden: updates to statefulset spec for fields other than are forbidden

### ISSUE THREAD

**Issue by nitinsh99** [hashicorp/terraform-provider-helm#774]
I have a statefulset created using the terraform helm provider. I need to update the value of an attribute (serviceName) in the statefulset but I keep getting the following error

```
Error: failed to replace object: StatefulSet.apps "value" is invalid: spec: Forbidden:
updates to statefulset spec for fields other than 'replicas', 'template', and 
'updateStrategy' are forbidden
```

Error is pretty descriptive and I understand that `serviceName` property can't be changed but then how do I update this property? I am totally fine with having a downtime and also letting helm delete all the old pods and create new ones. 

I have tried setting `force_update` and `recreate_pods` properties to `true` in my helm chart with no luck. Manually deleting the old helm chart is not an option for me. 

```
  version = "~> 1.2.4"
```

**Comment by aidan-melen** [comment]
recreate_pods isn't doing anything for me either. This provider depends on helm3 which has [apparently deprecated this upgrade option](https://github.com/helm/helm/issues/8271).

**Comment by aidan-melen** [comment]
Found [this](https://github.com/helm/helm/blob/281380f31ccb8eb0c86c84daf8bcbbd2f82dc820/pkg/action/upgrade.go#L475-L506) in the source for helm3. It looks like it is still implemented. Not sure why it isn't working.
