### ISSUE TITLE
set rbac and internal load balancer parameters to helm chart doesn't work

### ISSUE THREAD

**Issue by luckeyca** [hashicorp/terraform-provider-helm#781]
Issue: when using helm_release resource to create nginx ingress controller on azure, the "set" to enable rbac and internal load balancer parameters function doesn't work.

Details:
helm provider version: 2.2.0
helm chart: https://charts.bitnami.com/bitnami/nginx-ingress-controller
helm chart version: 7.6.19
helm chart artifacthub url: https://artifacthub.io/packages/helm/bitnami/nginx-ingress-controller

terraform helm_release set parameters:

  set {
    name  = "rbac.create"
    value = "true"
  }

  set {
    name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal"
    value = "true"
  }

Expected results: rbac enabled and load balancer uses internal ip

Actual results: rbac was not enabled and load balancer uses public ip

**Comment by jrhouston** [comment]
Hi @luckeyca could you paste a [code block](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) with your whole `helm_release` resource so I can try and reproduce this. `rbac.create` defaults to true in the values file for that chart already so I'm not sure what's going on there, but for your second value I suspect there might be a problem with the the slashes in the value name.

**Comment by luckeyca** [comment]
Hi @jrhouston, here is the code. The backslashes are to escape the backslashes needed to escape the dots as part of the annotations and was working with the old helm chart which was deprecated. The chart we used before and working fine with the code with the backslashes as is below was: https://github.com/helm/charts/tree/master/stable/nginx-ingress.
for the use of double backslash, it's also in the helm_release resource example: https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release

All I did was to upgrade the helm provider to the latest version and changed the helm chart given the old one was deprecated. no code changes in main.tf and variables.tf

main.tf

```
resource "helm_release" "release" {

  repository = var.helm_repository

  name      = var.release_info.name
  namespace = var.release_info.namespace
  chart     = var.release_info.chart
  version   = var.release_info.version

  set {
    name  = "rbac.create"
    value = "true"
  }

  set {
    name  = "controller.service.annotations.service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal"
    value = "true"
  }
}
```

**Comment by luckeyca** [comment]
variables.tf

```
variable "helm_repository" {
  type    = string
}

variable "release_info" {
  type = object({
    name      = string
    chart     = string
    namespace = string
    version   = string
  })
}
```

**Comment by luckeyca** [comment]
looks like chart issue. I keep the code as is and only changed the chart to "https://kubernetes.github.io/ingress-nginx"
  chart     = "ingress-nginx"
  version   = "4.0.3"

everything works fine including the annotation with those double backslash which was working on the old deprecated chart.
