### ISSUE TITLE
Error: User "client" cannot create resource "customresourcedefinitions"

### ISSUE THREAD

**Issue by cameronhudson8** [hashicorp/terraform-provider-helm#783]
If you prefer, you can also ask your question in the Kubernetes community Slack channel [#terraform-providers](https://kubernetes.slack.com/messages/CJY6ATQH4). ([Sign up here](http://slack.k8s.io/))

## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.0.6
Helm Provider version: 2.3.0
Kubernetes version: 1.20.9-gke.701
```
## Terraform configuration
```hcl
provider "helm" {
  kubernetes {
    host                   = "https://${var.cluster_endpoint}"
    client_certificate     = var.cluster_client_certificate
    client_key             = var.cluster_client_key
    cluster_ca_certificate = var.cluster_ca_certificate
  }
}

resource "helm_release" "nginx" {
  name             = "nginx"
  repository       = "https://helm.nginx.com/stable"
  chart            = "nginx-ingress"
  version          = var.nginx_version
  namespace        = "ingress"
  create_namespace = true
}

```

## Question

I'm trying to install the popular NGINX ingress controller via Terraform. However `terraform apply` fails with this error:

```
╷
│ Error: failed to install CRD crds/appprotect.f5.com_aplogconfs.yaml: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "client" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
│ 
│   with module.ingress.helm_release.nginx,
│   on modules/ingress/main.tf line 10, in resource "helm_release" "nginx":
│   10: resource "helm_release" "nginx" {
│ 
╵
```

However, if I manually install the helm chart as below, it installs properly.
```
helm install nginx nginx-stable/nginx-ingress -n ingress

W0919 20:16:47.070436   88463 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
W0919 20:16:48.080321   88463 warnings.go:70] networking.k8s.io/v1beta1 IngressClass is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 IngressClassList
NAME: nginx
LAST DEPLOYED: Sun Sep 19 20:16:45 2021
NAMESPACE: ingress
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The NGINX Ingress Controller has been installed.
```

but if I add the `--kube-as-user 'client'` argument, I'm able to replicate the error.
```
helm install nginx nginx-stable/nginx-ingress -n ingress --kube-as-user client

Error: INSTALLATION FAILED: failed to install CRD crds/appprotect.f5.com_aplogconfs.yaml: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "client" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

I searched everywhere for a solution, but the best I found was a 2-year-old post telling me to install Tiller. But since the provider version I'm using is supposed to be compatible with Helm 3, I didn't try going down the Tiller path. I also searched this repository for each occurrence of `"client"` (as a string), but I didn't find any. I have a suspicion that something is adding it as an argument, but I haven't been able to prove it.

Is there something wrong with my cluster setup, or is this a bug? I would greatly appreciate any guidance. :)

**Comment by jrhouston** [comment]
I would need some additional information about where the contents of the `var`s in your provider block are coming from, but this _smells_ like a credentials config problem given that you can use the `helm` command successfully locally. An easy test you can try is to specify the path to your local kubeconfig in the provider block using `config_path` to see if you get the same error.

**Comment by cameronhudson8** [comment]
Sure thing @jrhouston . I'll add the sources of my `var`s to original post (and here as well, for convenience).

```
# cluster module outputs.tf

output "cluster_endpoint" {
  value = google_container_cluster.general_purpose.endpoint
}

output "cluster_client_certificate" {
  value = base64decode(google_container_cluster.general_purpose.master_auth[0].client_certificate)
}

output "cluster_client_key" {
  value     = base64decode(google_container_cluster.general_purpose.master_auth[0].client_key)
  sensitive = true
}

output "cluster_ca_certificate" {
  value = base64decode(google_container_cluster.general_purpose.master_auth[0].cluster_ca_certificate)
}

```

BTW, my issue is nearly identical to the final issues posted on this closed thread: [
Configuring provider using another resource's outputs is not possible anymore since v2.0.0](https://github.com/hashicorp/terraform-provider-helm/issues/647)

After some experimentation, it seems that the the provider configuration properly uses the host argument, but not one or more of the arguments `client_certificate` / `cluster_client_key` / `cluster_ca_certificate arguments` (IDK which).

**Comment by cameronhudson8** [comment]
I'm closing this question because this issue is not specific to the Helm provider; affects the Kubernetes provider, as well. I opened a similar but more generic question on the GitHub repo of the Kubernetes provider:
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1424
