### ISSUE TITLE
create_namespace = true not deleting namespace on terraform destroy

### ISSUE THREAD

**Issue by madhu-ramaya** [hashicorp/terraform-provider-helm#785]
### Terraform, Provider Versions

```
Terraform version: 1.0.7
Provider version: 2.3.0
```

### Terraform Configuration Files
```hcl

terraform {
  required_providers {
    helm = {
      source = "hashicorp/helm"
      version = "2.3.0"
    }
  }
}

provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

resource "helm_release" "test" {
  name       = "test"
  repository = ""
  chart      = "helmchart"
  namespace  = "test"
  atomic = true
  lint = true
  create_namespace = true
}
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Expected Behavior
When using "create_namespace = true" in resource "helm_release", the namespace should be created on terraform apply. Similarly the namespace should be deleted on terraform destroy

### Actual Behavior
namespace is created on terraform apply, but namespace is not deleted on terraform destroy

**Comment by jrhouston** [comment]
Thanks for opening this @madhu-ramaya – we defer to helm's uninstall action on what deleting a helm release should do. In this case, `helm uninstall` does not delete a namespace that was created with the `--create-namespace` flag. There is some discussion on it in this closed issue on the helm repository: https://github.com/helm/helm/issues/1464

I would propose that if you want Terraform to manage and delete the namespace for your helm release that you use a `kubernetes_namespace` resource to create it and supply it to the `helm_release` resource.
