### ISSUE TITLE
Authentication Issue with cluster

### ISSUE THREAD

**Issue by sandrom** [hashicorp/terraform-provider-helm#789]
Terraform version: 1.0.9
Helm Provider version: 2.3.0
Kubernetes Provider version: 2.6.0
Running GCP, GKE regular release channel

Trying to push a helm chart via terraform
I provision a kubernetes_storage_class in the same terraform layer and it works nicely using the kubernetes provider
Sadly the helm provider does not seem to work and I get
*Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable*
I am a bit puzzled as the Kubernetes provider seems to work nicely but the helm provider doesn’t. Any way to fix that?

```
module "gke_auth" {
  source               = "../../../../modules/k8s-auth" # same as https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest/submodules/auth
  project              = var.project
  cluster_name         = local.cluster_name
  location             = local.cluster_location
  use_private_endpoint = false
}

provider "kubernetes" {
  cluster_ca_certificate = module.gke_auth.cluster_ca_certificate
  host                   = module.gke_auth.host
  token                  = module.gke_auth.token
}

provider "helm" {
  kubernetes {
    host                   = module.gke_auth.host
    token                  = module.gke_auth.token
    cluster_ca_certificate = module.gke_auth.cluster_ca_certificate
  }
}
```

**Comment by sandrom** [comment]
More info:

I run terraform in a separate layer for creating the cluster. This means the cluster already exists when this is called.

Furthermore I also get the same when I supply the context and config path in the provider block, but if I provide KUBE_CONFIG_PATH and KUBE_CTX environment variables before calling terraform it suddenly works fine. 

This looks more like a bug by now?

**Comment by kelly-brown** [comment]
I'm having this exact same problem.  Did you ever figure it out?

**Comment by mconigliaro** [comment]
Duplicate of #809?
