### ISSUE TITLE
"Error: cannot re-use a name that is still in use" on re-creation of Helm Chart (helm_release)

### ISSUE THREAD

**Issue by mkemmerz** [hashicorp/terraform-provider-helm#792]
```
Terraform version: 1.0.8
Helm Provider version: 2.3.0
Kubernetes version: 1.20.7
```

## Question
We are getting the following message: "Error: cannot re-use a name that is still in use".

This occurs if Terraform needs to destroy and re-create one of your Helm charts. I guess the Helm provider doesn't wait long enough so the Helm Chart still is not terminated but terraform. A re-run of the terraform apply solves the issue by creating the Helm chart again.

The helm_release documentation mentions a [replace ](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#replace) attribute in this case. As this is NOT adviced for production use we sadly can't use this.

Now to the question. Is there a safe way of waiting / retry the re-creation of the Helm Chart? Can we add some kind of delay to the Helm chart that will be re-created? Is there a safe way to use the `replace `attribute?

Using a [time_sleep ](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep#delay-create-usage) resource is not possible because we can't reference a resource to itself.
![image](https://user-images.githubusercontent.com/46575727/139062770-4a88366f-91be-4ab8-b5a5-121214ef9c11.png)

**Comment by jrhouston** [comment]
I had a dig into this – it looks as though this is something that might be fixed when we upgrade the helm dependency to 3.7, which introduces the [`--wait` option](https://github.com/helm/helm/commit/655bdcd2fd80557c87674c96117bc4e70c4eb0f6) to the uninstall action. In 3.6 there is no option to wait for the uninstall to finish, which I think is what is causing this problem. At present it will just fire off the delete calls and exit so it seems like sometimes it will hit the install action before the release has been fully deleted.

If that doesn't fix it then we will likely have to add "wait for delete" logic ourselves to the resource's delete operation which polls until the release is gone before considering the delete successful.

**Comment by mkemmerz** [comment]
This sounds like the option that would be needed here. I am really looking forward to this feature option.

We found a solution to this issue by using `terraform apply -parallelism=1` ; [-parallelism=1](https://www.terraform.io/docs/cli/commands/apply.html#parallelism-n) does not allow concurrent operations so it waits until the resource is destroyed, before creating it again.

**Comment by robert197** [comment]
@mkemmerz `-parallelism=1` option didn't solve the problem.

Any news on this issue I'm still having the same problem

**Comment by mkemmerz** [comment]
@robert197 
Sadly nothing new from my side.
The [2.4.0 version](https://github.com/hashicorp/terraform-provider-helm/releases/tag/v2.4.0) introduced the `wait` but I couldn't verify it yet.
