### ISSUE TITLE
Exec plugin auth seems broken in 2.4.0

### ISSUE THREAD

**Issue by lewispeckover** [hashicorp/terraform-provider-helm#797]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.0.10
Provider version: 2.4.0
Kubernetes version: 1.21
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
provider "helm" {
  kubernetes {
    host                   = "https://example.com"
    cluster_ca_certificate = "my-certificate"
    exec {
      api_version = "client.authentication.k8s.io/v1alpha1"
      args        = ["eks", "get-token", "--cluster-name", "my-cluster-id"]
      command     = "aws"
    }
  }
}

```

### Debug Output

https://gist.github.com/lewispeckover/f7587f48798af0a50e325d2db7326ce6

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

Exec plugin works as it did in 2.3.0.

### Actual Behavior

Error occurs during refresh:
> Kubernetes cluster unreachable: invalid configuration: interactiveMode must be specified for  to use exec authentication plugin

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Patricol** [comment]
Same issue; also while using
```
exec {
  api_version = "client.authentication.k8s.io/v1alpha1"
  command = "aws"
  args = [ "eks", "get-token", "--cluster-name", data.aws_eks_cluster.this.name]
}
```

**Comment by chasewm** [comment]
Having the same issue

**Comment by chasewm** [comment]
If anyone needs a workaround you can manually set the helm version like this:

```
terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "2.3.0"
    }
  }
}
```

**Comment by Spritekin** [comment]
I have the same problem... I thought it was a kubernetes provider problem so I opened a bug report, however it seems like it is a helm bug.

**Comment by jrhouston** [comment]
Looks like this validation was introduced when we [updated client-go](https://github.com/hashicorp/terraform-provider-helm/blame/73b5c4120e8ad2c50b178c502574cfe6d034d9fc/vendor/k8s.io/client-go/tools/clientcmd/validation.go#L311-L318). Although, the [godoc](https://github.com/hashicorp/terraform-provider-helm/blame/73b5c4120e8ad2c50b178c502574cfe6d034d9fc/vendor/k8s.io/client-go/tools/clientcmd/api/types.go#L255-L258) says the field is optional when `client.authentication.k8s.io/v1alpha1` is specified. 

PR incoming with a fix.

**Comment by n1vgabay** [comment]
I've got the same issues with **aws-ebs-csi-driver** and **aws-efs-csi-driver**.

**Comment by kumarpmd** [comment]
ran in to same issue while deploying helm chart.  Was able to get around the issue by going back to previous version, like @chasewm suggested.  Thank you.

```
helm_release.helm_install_chart: Creating...

Error: Kubernetes cluster unreachable: invalid configuration: interactiveMode must be specified for  to use exec authentication plugin
```

**Comment by jrhouston** [comment]
Apologies for the disruption folks. A new release with a hotfix for this issue should be available now.

**Comment by davidfluck-kong** [comment]
I normally try not to pile on in issue threads, but we ran into this earlier, and I want to say thank you for the prompt fix! We appreciate it.

**Comment by Spritekin** [comment]
@jrhouston 
No apologies needed, this is totally my fault for not pinning to a version. It also made me realise its time for an upgrade for the Kubernetes cluster and Terraform providers.
Thank you so much for your prompt fix, I will update to the new version in all my environments soon.
