### ISSUE TITLE
Add ability to hide sensitive values

### ISSUE THREAD

**Issue by rekahsoft** [hashicorp/terraform-provider-helm#80]
This is an enhancement request.

Add an additional property to `set` for `helm_release` resources that allow the value to be marked as 'sensitive' and not displayed in the state diff during a plan or apply.

For example:

```hcl
resource "helm_release" "my_database" {
    name      = "my_datasase"
    chart     = "stable/mariadb"

    set {
        name  = "mariadbUser"
        value = "foo"
    }

    set {
        name      = "mariadbPassword"
        value     = "THIS IS SUPER SECRET"
        sensitive = true
    }
}
```

### Terraform Version

```
terraform version
Terraform v0.11.7
+ provider.helm (unversioned)
```

Note: though `provider.helm` is said to be `unversioned`, it has version `v0.5.1`.

### Affected Resource(s)

Any `helm_release` resource is affected by this.

### Terraform Configuration Files
```hcl
resource "helm_release" "my_database" {
    name      = "my_datasase"
    chart     = "stable/mariadb"

    set {
        name  = "mariadbUser"
        value = "foo"
    }

    set {
        name = "mariadbPassword"
        value = "THIS IS SUPER SECRET"
    }
}
```

### Expected Behavior

Secret values should not be displayed. For example, when using the aws provider, some resources (eg aws_rds_instance) have values that are masked with `<sensitive>`.

### Actual Behavior

Secrets are displayed plain text:

```
  + helm_release.my_database
      id:                               <computed>
      chart:                            "stable/mariadb"
      disable_webhooks:                 "false"
      force_update:                     "false"
      metadata.#:                       <computed>
      name:                             "my_datasase"
      namespace:                        "default"
      recreate_pods:                    "false"
      reuse:                            "false"
      reuse_values:                     "false"
      set.#:                            "2"
      set.1144798963.name:              "mariadbUser"
      set.1144798963.value:             "foo"
      set.1144798963.name:              "mariadbPassword"
      set.1144798963.value:             "THIS IS SUPER SECRET"
      timeout:                          "300"
      verify:                           "false"
```

### Steps to Reproduce

1. Ensure terraform-provider-helm is installed
2. Ensure kubectl and helm are installed and configured
3. `terraform apply` | `terraform plan`

**Comment by rmb938** [comment]
I would like this to be added as well. Currently I don't have a way to use this provider without leaking secrets.
