### ISSUE TITLE
Helm function `deepCopy` returns errors when terraform apply while works fine when running `helm template` manually.

### ISSUE THREAD

**Issue by awx-fuyuanchu** [hashicorp/terraform-provider-helm#800]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v0.13.5
Provider version: 2.0.2
Kubernetes version: v1.19.14-gke.1900
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "some" {
      atomic                     = true
      chart                      = "opentelemetry-collector"
      name                       = "otel-collector-gateway"
      repository                 = "https://open-telemetry.github.io/opentelemetry-helm-charts"
      values                     = [
          <<~EOT
                fullnameOverride: "otel-collector-gateway"
                serviceAccount:
                  create: true
                clusterRole:
                  create: true
                  rules:
                    - apiGroups:
                        - ""
                      resources:
                        - services
                        - endpoints
                        - pods
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - extensions
                      resources:
                        - podsecuritypolicies
                      resourceNames:
                        - "gce.unprivileged-addon"
                      verbs:
                        - use
                # Configuration for agent OpenTelemetry Collector daemonset
                agentCollector:
                  enabled: false
                # Configuration for standalone OpenTelemetry Collector deployment
                standaloneCollector:
                  enabled: true
                  ports:
                    metrics:
                      enabled: true
                      containerPort: 8888
                      servicePort: 8888
                      protocol: TCP
                  replicaCount: 1
                  resources:
                    limits:
                      cpu: 1
                      memory: 2Gi
                serviceMonitor:
                  enabled: true
                  metricsEndpoints:
                    - port: metrics
                      interval: 15s
            EOT,
        ]
      verify                     = false
      version                    = "0.8.0"
      wait                       = true
      set {
          name  = "serviceMonitor.extraLabels.release"
          value = "kube-prometheus-stack"
        }
      set {
          name  = "standaloneCollector.nodeSelector"
          value = "default-node-pool"
        }
    }
```

### Debug Output

> module.otel-collector-gateway[0].helm_release.some: Creating...

> Error: template: opentelemetry-collector/templates/deployment.yaml:23:28: executing "opentelemetry-collector/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: opentelemetry-collector/templates/configmap.yaml:10:8: executing "opentelemetry-collector/templates/configmap.yaml" at <include "opentelemetry-collector.standaloneCollectorConfig" .>: error calling include: template: opentelemetry-collector/templates/_config.tpl:55:54: executing "opentelemetry-collector.standaloneCollectorConfig" at <mustMergeOverwrite (deepCopy .Values)>: error calling mustMergeOverwrite: cannot append two different types (string, map)

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
helm release supposed to be created after apply.

### Actual Behavior

terraform returned with errors while creating helm release

module.otel-collector-gateway[0].helm_release.some: Creating...

Error: template: opentelemetry-collector/templates/deployment.yaml:23:28: executing "opentelemetry-collector/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: opentelemetry-collector/templates/configmap.yaml:10:8: executing "opentelemetry-collector/templates/configmap.yaml" at <include "opentelemetry-collector.standaloneCollectorConfig" .>: error calling include: template: opentelemetry-collector/templates/_config.tpl:55:54: executing "opentelemetry-collector.standaloneCollectorConfig" at <mustMergeOverwrite (deepCopy .Values)>: error calling mustMergeOverwrite: cannot append two different types (string, map)

  on ../helm/main.tf line 5, in resource "helm_release" "some":
   5: resource "helm_release" "some" {

### Important Factoids

helm template works fine.

```
helm template otel  -f values-override.yaml ./opentelemetry-collector  --set "standaloneCollector.nodeSelector=default-node-pool"       --set "serviceMonitor.extraLabels.release=kube-prometheus-stack"
```

### References
The chart is here:
https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/templates/_config.tpl#L55

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Hi @FuyuanChu – I think there might be a couple of problems here. 

To try and reproduce here I had to reformat your example, as it wouldn't even validate on `terraform init`. So I formatted it like this:

```terraform
resource "helm_release" "some" {
  atomic                     = true
  chart                      = "opentelemetry-collector"
  name                       = "otel-collector-gateway"
  repository                 = "https://open-telemetry.github.io/opentelemetry-helm-charts"
  values                     = [<<-EOT
    fullnameOverride: "otel-collector-gateway"
    serviceAccount:
      create: true
    clusterRole:
      create: true
      rules:
        - apiGroups:
            - ""
          resources:
            - services
            - endpoints
            - pods
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - extensions
          resources:
            - podsecuritypolicies
          resourceNames:
            - "gce.unprivileged-addon"
          verbs:
            - use
    # Configuration for agent OpenTelemetry Collector daemonset
    agentCollector:
      enabled: false
    # Configuration for standalone OpenTelemetry Collector deployment
    standaloneCollector:
      enabled: true
      ports:
        metrics:
          enabled: true
          containerPort: 8888
          servicePort: 8888
          protocol: TCP
      replicaCount: 1
      resources:
        limits:
          cpu: 1
          memory: 2Gi
    serviceMonitor:
      enabled: true
      metricsEndpoints:
        - port: metrics
          interval: 15s
    EOT
  ]
  verify                     = false
  version                    = "0.8.0"
  wait                       = true
  
  set {
    name  = "serviceMonitor.extraLabels.release"
    value = "kube-prometheus-stack"
  }
  set {
    name  = "standaloneCollector.nodeSelector"
    value = "default-node-pool"
  }
}

```

After doing that I was able to run plan successfully, but apply failed with this error:

```
│ Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.nodeSelector): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got "string", expected "map"
│
│   with helm_release.some,
│   on main.tf line 7, in resource "helm_release" "some":
│    7: resource "helm_release" "some" {
│
```


This is because nodeSelector must be a map of labels and values to select on – not just a string. You will need to know which node label you are selecting on, and specify it in the set block like this:

```terraform
  set {
    name  = "standaloneCollector.nodeSelector.LABEL_NAME"
    value = "default-node-pool"
  }
```

**Comment by awx-fuyuanchu** [comment]
Cool, many thanks. It's very helpful.
