### ISSUE TITLE
Unable to set "list" value in set block

### ISSUE THREAD

**Issue by benjah1** [hashicorp/terraform-provider-helm#804]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.0.11
Provider version: 2.4.1
Kubernetes version: v1.19.10
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "akeyless" {
...
  set {
    name = "akeylessUserAuth.allowedAccessIDs"
    value = "[\"p-789 subClimekey1=subClimeVaasdasdf sdfdsfcxvl1\" ,\"p-666 subClimekey2=subClimeVal2\"]"
  }
}
```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
The full value to be set in the secret.

### Actual Behavior
The value is truncated. Only the following is passed into the secret,
```
[\"p-789 subClimekey1=subClimeVaasdasdf sdfdsfcxvl1\" 
```

### Important Factoids
Unable to pass the full value

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by benjah1** [comment]
in additional, this also affect the json in string format,
```
  set {
    name = "customerFragments"
    value = "{\"customer_fragments\": [{\"id\": \"cf-et8u.....b3iw7\",\"value\": \"qrm0YoYSHb0j...JKb/zZmU8..yj4Ja/h/pa..Fvu4Esw==\",\"description\": \"MyFirstCF\"}]}"
  }

# show error,
Error: failed parsing key "customerFragments" with value {"customer_fragments": [{"id": "cf-et8u.....b3iw7","value": "qrm0YoYSHb0j...JKb/zZmU8..yj4Ja/h/pa..Fvu4Esw==","description": "MyFirstCF"}]}, key "]}" has no value
```

**Comment by kclarkey** [comment]
Try escaping your commas (passing the literal `\,` to the underlying helm provider via `\\,`:

```terraform
resource "helm_release" "akeyless" {
...
  set {
    name = "akeylessUserAuth.allowedAccessIDs"
    value = "[\"p-789 subClimekey1=subClimeVaasdasdf sdfdsfcxvl1\"\\,\"p-666 subClimekey2=subClimeVal2\"]"
  }
  set {
    name = "customerFragments"
    value = "{\"customer_fragments\": [{\"id\": \"cf-et8u.....b3iw7\"\\,\"value\": \"qrm0YoYSHb0j...JKb/zZmU8..yj4Ja/h/pa..Fvu4Esw==\"\\,\"description\": \"MyFirstCF\"}]}"
  }
}
```

**Comment by esantoro** [comment]
Hi, this is to let you know that I'm facing the same problem with the provider version 2.5.1.

I did manage to get the provider to work by substituting the single command (`,`) with `\\,`.
