### ISSUE TITLE
Add support for timeouts block on helm_release and kubernetes_manifest resources

### ISSUE THREAD

**Issue by drdkadtr** [hashicorp/terraform-provider-helm#815]
### Description

Im experiencing timeout limits during apply command, and I find `timeout` string argument is confusing. 
Instead I suggest having a map type as described here: https://www.terraform.io/language/resources/syntax#operation-timeouts

Example of ci runs can be found here (without timeout setting): 
https://github.com/drdkadtr/learn-terraform-k8s-crd-openfaas/runs/4666572143?check_suite_focus=true

### Potential Terraform Configuration

```hcl
resource "helm_release" "openfaas" {
  repository = "https://openfaas.github.io/faas-netes"
  chart      = "openfaas"
  name       = "openfaas"
  namespace  = "openfaas"
  ...
  timeouts {
    create = "45m"
    update = "45m"
    delete = "45m"
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by zeusal** [comment]
Hi, It would be very useful to be able to use timeouts as in other resources.

**Comment by abi-jey** [comment]
Hi all, is there anyone working on this issue?

**Comment by williamohara** [comment]
I would like to set the timeout to be shorter in my case - when I am experimenting with different things that may cause an error - iIdon't like waiting five minutes for it to give me a failure.

**Comment by excalq** [comment]
Also useful would be a `default_timeouts` config in the provider block, so that third-party child modules' default timeouts can be set.
