### ISSUE TITLE
Apple Silicon (darwin_arm64) support

### ISSUE THREAD

**Issue by ana-cozma** [hashicorp/terraform-provider-helm#816]
### Description

I couldn't find an existing issue on this (please correct me if I'm wrong), so I thought I'd create one for adding support for the new Apple Silicon (M1).

After migrating to the new Mac, we ran into the following issue:

![image](https://user-images.githubusercontent.com/48124384/147951355-970b7c17-cb59-4f76-902f-3e83eb782d23.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by et304383** [comment]
Chiming in as affected too.  I'm shocked this is only coming up just now since Apple Silicon has been out over a year.

Edit: actually it could be the old version you're using.  Unless maybe the latest still isn't compiled for ARM?

**Comment by et304383** [comment]
The crux of the issue here is that the build is taking place inside Docker.  This means we can't even attempt to compile from source for ARM.

The build needs to be overhauled to not be Docker based if we're going to get ARM support.

**Comment by ana-cozma** [comment]
You are correct. Confirmed it works on: 2.4.1. Apologies for the oversight on the outdated version we were using!

**Comment by et304383** [comment]
@ana-cozma  if you have this issue again and CANNOT upgrade then I highly recommend the tool mentioned in my issue link:

https://github.com/kreuzwerker/m1-terraform-provider-helper

This tool has saved me SO much time with regards to addressing providers that aren't compiled for ARM until the latest versions and I'm not in a position to update to the latest version.
