### ISSUE TITLE
Support `proxy_url` in kubernetes block

### ISSUE THREAD

**Issue by nsmith5** [hashicorp/terraform-provider-helm#833]
### Description

Sometimes you need to access your kubernets cluster over a proxy. The kubernetes provider supports this with the [`proxy_url` argument](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#proxy_url) but no such argument is available for the helm provider.

### Potential Terraform Configuration

```diff
provider "helm" {
  kubernetes {
+   proxy_url = "socks5://localhost:6336"
  } 
}
```

### References

- A related PR here https://github.com/hashicorp/terraform-provider-helm/pull/654

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by nsmith5** [comment]
Happy to take a look at this and submit a PR ❤️

**Comment by savitha-atg** [comment]
I need this to deploy charts to a private GKE cluster. Any idea when it will be released?

**Comment by nsmith5** [comment]
I've released a patched provider here: https://registry.terraform.io/providers/nsmith5/helm/2.4.3. It's based on the PR above and support `proxy_url`. You can use that while you wait for the PR to be reviewed / released etc.

**Comment by savitha-atg** [comment]
Great! Thanks!

**Comment by poblahblahblah** [comment]
Would love this to be reviewed and merged if appropriate. We are currently using some hacky workarounds because this functionality is missing.

**Comment by iamasmith** [comment]
Definitely an upvote, needed for private GKE cluster deployments and seems obvious to bring feature compatibility with the K8S provider.
