### ISSUE TITLE
OCI: The specified item already exists in the keychain

### ISSUE THREAD

**Issue by harcher81** [hashicorp/terraform-provider-helm#845]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.1.7
Provider version: 3.5.0
Kubernetes version: 1.21
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
data "aws_ecr_authorization_token" "token" {}

locals {
  helm_base_registry_path = trimprefix(data.aws_ecr_authorization_token.token.proxy_endpoint, "https://")
}

resource "helm_release" "example1" {
  name    = "example1"
  chart   = "oci://${local.helm_base_registry_path}/example1"
  version = "1.0.0"

  repository_username = data.aws_ecr_authorization_token.token.user_name
  repository_password = data.aws_ecr_authorization_token.token.password
}

resource "helm_release" "example2" {
  name    = "example2"
  chart   = "oci://${local.helm_base_registry_path}/example2"
  version = "2.0.0"

  repository_username = data.aws_ecr_authorization_token.token.user_name
  repository_password = data.aws_ecr_authorization_token.token.password
}
```

### Debug Output
```
Error: could not login to OCI registry "XXXXXXXX.dkr.ecr.us-east-1.amazonaws.com": error storing credentials - err: exit status 1, out: `The specified item already exists in the keychain.`
```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

Deploying two helm charts without error.

### Actual Behavior

When they do the plan, there are error like on "Debug Output" section.

### Important Factoids

I'm on MacOS (12.3) Intel.  I think that crash only with multiple helm_release resources.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by harcher81** [comment]
I add : 
depends_on = [
  helm_release.example1
]
add I don't have issue anymore. That a good workaround.

**Comment by aiceball** [comment]
I have the same issue, but in my case I have same chart being deployed across multiple namespaces, like

```
resource "helm_release" "alertmanager_configs" {
  provider = helm

  for_each = local.alertmanager_configs_namespaces

  depends_on = [
    time_sleep.wait_before_alertmanager_configs,
  ]

  name         = "alertmanager-configs-${each.key}"
  namespace    = each.value
  repository = "oci://<registry>"
```

The workaround mentioned by @harcher81 above would not be too elegant in my scenario.
Is there a way for the resource to verify credentials against existing keychain before apply?
