### ISSUE TITLE
`repository_username` and `repository_password` should not be stored in Terraform state

### ISSUE THREAD

**Issue by kravvcu** [hashicorp/terraform-provider-helm#851]
### Terraform, Provider, Kubernetes and Helm Versions

The `repository_username` and `repository_password` field values should not be stored in Terraform state:

1. This can be a security risk and may lead to credentials leak. E.g. when working on a team and the password is pulled from an env var which is a personal access token, which also makes integration with CI seamless (e.g. $CI_JOB_TOKEN in case of GitLab).
2. It breaks applying plans output to a file, when the password, which is actually an access token, expires. Also in context of GitLab:
  a. `plan` is run in job A and outputs the plan (with the CI_JOB_TOKEN saved of `job A`).
  b. `apply` is a manual job run whenever deemed to be run - it fails on access to Helm registry because the CI_JOB_TOKEN saved in the plan already expired (because it was only valid for the runtime of `job A`).

``` 
Terraform version: 1.1.8
Provider version: 2.10
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 1.1"

  required_providers {
    google = {
      source  = "hashicorp/google"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
    }
    helm = {
      source  = "hashicorp/helm"
    }
  }
}

data "google_client_config" "default" {
}

provider "google" {
}

provider "kubernetes" {
  host                   = "FILLMEIN"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode("")
}

provider "helm" {
  kubernetes {
    host                   = "FILLMEIN"
    token                  = data.google_client_config.default.access_token
    cluster_ca_certificate = base64decode("")
  }
}

resource "kubernetes_namespace" "namespace" {
  metadata {
    name = "test"
  }
}

resource "helm_release" "coredns" {
  name      = "coredns"
  namespace = kubernetes_namespace.namespace.metadata.0.name

  repository = "https://coredns.github.io/helm"
  chart      = "coredns"

  # it doesn't matter that the repository is public, only added to prove the point
  repository_username = "whatever"
  repository_password = "watever-password"

  version = "1.16.0"
}
```

### Steps to Reproduce
1. `terraform apply`

4. `cat terraform.tfstate | grep repository_ `  

>          "repository_ca_file": null,
>             "repository_cert_file": null,
>             "repository_key_file": null,
>             "repository_password": "watever-password",
>             "repository_username": "whatever",

### Expected Behavior

The `repository_password` and `repository_username` are not present in Terraform state.

### Actual Behavior

The `repository_password` and `repository_username` are present in Terraform state.

### References

[This](https://github.com/hashicorp/terraform-provider-google/issues/11451) issue related to the Google provider is similar.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gmcoringa** [comment]
And if you set `repository_password` with ignore changes will lead to forbidden access
![ecr](https://user-images.githubusercontent.com/1846171/162957711-fe3dea86-d099-4705-b190-07e9c64989ef.png)

Tested with version `2.5.1`

**Comment by alexsomesan** [comment]
As things stand today, this is expected behaviour form Terraform, as explained here: https://www.terraform.io/language/state/sensitive-data

There is an ongoing conversation related to this issue: https://github.com/hashicorp/terraform/issues/30469
You might want to share details of your situation there to provide additional datapoints towards a decision.

**Comment by visit1985** [comment]
@alexsomesan, from a functionality perspective it is not possible to use OCI based repositories (with token expiry) as long as the helm provider does not use updated credentials for refreshing the resources from state.

**Comment by visit1985** [comment]
Shall we open a separate ticket for that topic then?
