### ISSUE TITLE
Feature Request: Add this provider to the Terraform public registry

### ISSUE THREAD

**Issue by TrevorVonSeggern** [hashicorp/terraform-provider-helm#86]
### Expected Behavior
"terraform init" should download this provider without having to manually install the binaries/install from source.

### Actual Behavior
"terraform init" => 'Provider "helm" not available for installation.'

**Comment by cosmopetrich** [comment]
I don't believe this is currently possible. The Terraform registry only supports modules, not providers or other plugins. There are plans to change that as noted in hashicorp/terraform#17154, but providers must be installed manually for now.

**Comment by TrevorVonSeggern** [comment]
Yep, I think you are right. You can close this if you want now, or leave open till terraform supports it.

**Comment by mildwonkey** [comment]
There is an open issue around hosting providers in the registry:  https://github.com/hashicorp/terraform/issues/15252

I'm involved with this task, so I will assign it to myself and post updates as I have more information. 

There is another option for you. Officially approved providers hosted on releases.hashicorp.com and  downloaded during `terraform init`. You could submit this provider to the [Terraform Provider Development Program](https://www.terraform.io/guides/terraform-provider-development-program.html).

**Comment by Jeeppler** [comment]
Yes, it would be awesome if this provider could be part of the official Terraform provider list: https://www.terraform.io/docs/providers/index.html

**Comment by meyskens** [comment]
https://github.com/terraform-providers/terraform-provider-helm

**Comment by meyskens** [comment]
We're official now!
