### ISSUE TITLE
Impossible to use TOKEN as password

### ISSUE THREAD

**Issue by monester** [hashicorp/terraform-provider-helm#861]
When you have configuration with short lived tokens as password to access docker registry on every `terraform plan` helm provider trying to update helm chart as password field is constantly changing.
Adding `lifecycle { ignore_changes = [repository_password]  }` don't work as well as token don't get updated and then get expired in few hours.

This problem is related to the issue #851 but storing short live token in state isn't a problem here.

### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.1.9
Provider version: 2.5.1
Kubernetes version: 1.22
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files

```hcl
data "aws_caller_identity" "current" {}
data "aws_ecr_authorization_token" "token" {}

resource "helm_release" "simple-page" {
  chart               = "simple-page"
  version             = "0.1.0"
  name                = "simple-page"
  repository          = "oci://${data.aws_caller_identity.current.account_id}.dkr.ecr.us-west-1.amazonaws.com"
  repository_username = data.aws_ecr_authorization_token.token.user_name
  repository_password = data.aws_ecr_authorization_token.token.password

  lifecycle {
    ignore_changes = [repository_password]
  }
}
```

### Debug Output

Not needed.

### Panic Output

No panic

### Steps to Reproduce

2 Scenarios:
With lifecycle:
1. `terraform apply`
2. wait for a day
3. `terraform apply` doesn't work because access denied.

Without lifecycle
1. `terraform apply`
2. `terraform apply` saying that there are changes in plan and trying to apply them.

### Expected Behavior
Changes applied only on changes in chart.

### Actual Behavior
Changes applied every time or getting access denied.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by davidalger** [comment]
Experienced identical issue using GAR (Google Artifact Registry) as well:

```hcl
data "google_client_config" "this" {}

resource "helm_release" "this" {
  name      = var.name
  chart     = "oci://us-docker.pkg.dev/my-project/helm/my-chart"
  version   = var.version
  namespace = kubernetes_namespace.this.id

  # Authenticate to GAR using OAuth token
  repository_username = "oauth2accesstoken"
  repository_password = data.google_client_config.this.access_token

  // ...
}
```

Results in a perma-diff due to the changing token value:

```hcl
Terraform will perform the following actions:
  # helm_release.this will be updated in-place
  ~ resource "helm_release" "this" {
        id                         = "my-service"
        name                       = "my-service"
      ~ repository_password        = (sensitive value)
        # (29 unchanged attributes hidden)
    }
```

The solution presented in #862 seems to be the correct approach here. Any chance this can be reviewed soon to hopefully make it into the next release @jrhouston?
