### ISSUE TITLE
make compile command leads to inability to run any other make commands

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-helm#866]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.1.9
Provider version: 2.5.1
Kubernetes version: 4.5.4
```

### Debug Output

```
mau@mau-JKDT676NCP terraform-provider-helm % make compile
==> Checking that code complies with gofmt requirements...
go: upgraded github.com/hashicorp/go-version v1.3.0 => v1.5.0
go: upgraded github.com/mitchellh/gox v0.4.0 => v1.0.1
/Users/mau/Documents/github.com/hashicorp/terraform-provider-helm/scripts/compile.sh: line 23: gox: command not found
make: *** [compile] Error 127
```
```
mau@mau-JKDT676NCP terraform-provider-helm % make     
==> Checking that code complies with gofmt requirements...
go build -v .
go: inconsistent vendoring in /Users/mau/Documents/github.com/hashicorp/terraform-provider-helm:
	github.com/hashicorp/go-version@v1.5.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/mitchellh/gox@v1.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/mitchellh/iochan@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/hashicorp/go-version@v1.3.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
make: *** [build] Error 1
```

### Steps to Reproduce

1. `make compile` in root directory
2. run any make command `make`, `make build` etc.

### Expected Behavior

runs compile.sh which includes running `gox` command if exists, else it'll download gox then run

### Actual Behavior

causes an error when running `make compile` which leads to the inability to run any make commands until go.mod & go.sum changes are discarded following the `make compile` run

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
@BBBmau the release process moved to [goreleaser](https://goreleaser.com/) for doing the compiling step so I think we can just delete the compile Makefile target now.
