### ISSUE TITLE
terraform plan is unrecoverable when tiller is not installed

### ISSUE THREAD

**Issue by stevvooe** [hashicorp/terraform-provider-helm#87]
When calculating a terraform plan, I get the following error message:

```
* module.cluster.module.addons.helm_release.datadog: helm_release.datadog: error creating tunnel: "could not find tiller"
```

It seems that when the cluster was recreated, the helm provider and its resources weren't marked as dirty and were never redeployed. Now, when calculating the plan, when it tries to see if the helm release exists, it fails saying that there is no tiller.

Because terraform never gets past this step, the only way to recover is to comment out the provider and release, taint the release, then reinstall everything.

Instead, the provider should treat a missing tiller as a missing release so the plan can proceed. Once tiller is reinstalled, then it can query the state of the release and proceed.

Version:

```
$ terrafrom -v
zsh: correct terrafrom to terraform [nyae]? y
Terraform v0.11.7
+ provider.google v1.15.0
+ provider.helm (unversioned)
+ provider.kubernetes v1.1.0
+ provider.local v1.1.0
+ provider.null v1.0.0
```

**Comment by lawrencegripper** [comment]
You can use `terraform state` commands to clean things up `terraform state rm module.cluster.module.addons.helm_release.datadog` will remove the orphaned resource and let you proceed. 

Not ideal but a workaround I found to a similar issue.

**Comment by woz5999** [comment]
This is extremely painful. Any issues with tiller can break an entire projects and require extensive manual intervention with advanced, potentially dangerous procedures to remedy.

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
