### ISSUE TITLE
Generic wait support for helm_release resource

### ISSUE THREAD

**Issue by hrishin** [hashicorp/terraform-provider-helm#870]
### Description

Sometimes `helm_release` resources are used to install the various deployments types. Especially in the case of the operator which installs something and reports its status in `.status` field of some custome resources.  Sometimes we have to execute a wait operation until resource deployments get complete. Now, `helm_release` don't allow `wait` for a certain condition like this, It would be nice if `helm_release` can provide generic wait support such as Kubernetes [alpha providers ](https://www.hashicorp.com/blog/wait-conditions-in-the-kubernetes-provider-for-hashicorp-terraform)support.

### Potential Terraform Configuration

```hcl
resource 'helm_release' 'foo' {
....
....

 wait_for = {
    resources = {
         group   = ""
         version = ""
         kind    = ""
    }
    fields = {
        "status.result = "sucsess",
        "status.phase" = "Running",
    }
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rpf3** [comment]
This would be great, especially for ingress resources that create load balancers.  I've been bitten specifically by AWS load balancers still being in a state of "Provisioning" even though the Helm release has completed.  When I then need to do something with the Helm-created load balancer, Terraform will fail.

**Comment by manobi** [comment]
That would solve the problem of waiting for pods created by custom resources.
