### ISSUE TITLE
app_version argument of helm_release is not supported

### ISSUE THREAD

**Issue by MostefaKamalLala** [hashicorp/terraform-provider-helm#871]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.2.2
Provider version: 2.4.1/2.5.1
Kubernetes version: 1.21.9
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

resource "helm_release" "nginx_ingress" {
  name       = "nginx-ingress-controller"

  repository         = "https://charts.bitnami.com/bitnami"
  chart                 = "nginx-ingress-controller"
  app_version      = var.image_tag

  set {
    name  = "service.type"
    value = "ClusterIP"
  }
}
```

### Debug Output

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Panic Output

```
Error: Unsupported argument
│
│   on modules\nginx\main.tf line 88, in resource "helm_release" "nginx-server":
│   88:   app_version      = var.image_tag
│
│ An argument named "app_version" is not expected here.
```
### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
Added the appVersion to the helm release

### Actual Behavior
Says that the argument is unsuported even though it is supposed to exist given
https://github.com/hashicorp/terraform-provider-helm/issues/531
https://github.com/hashicorp/terraform-provider-helm/pull/532

### References

- https://github.com/hashicorp/terraform-provider-helm/issues/531
- https://github.com/hashicorp/terraform-provider-helm/pull/532

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
@MostefaKamalLala thanks for opening an issue. The `app_version` attribute is only exposed as a computed field under the `metadata` block in the resource. `appVersion` is something that is only set in the `Chart.yaml` to communicate the version of the application contained within the chart. AFAIK it's not something you can configure or override at install time – that's what values are for. 

Looking at the chart for `nginx-ingress-controller` I can see there's an [`image.tag` value](https://artifacthub.io/packages/helm/bitnami/nginx-ingress-controller#nginx-ingress-controller-parameters) which I think is actually what you're looking for.

**Comment by MostefaKamalLala** [comment]
@jrhouston Thanks for the reply. I understand the fact as it is only exposed as a computed field.
And no I was not looking for the image.tag value.
As you know, when listing the helm releases you get the app_version column that is set in Chart.yaml which is annoying many developers because we would like to see the actual image.tag used in the helm release in app_version column. 

I though it was a possibility with this provider. This is another topic I dunno if Helm will eventully allow that, I found a couple workarounds but since I deploy using Terraform and a private Helm registry, none of them work for me.
