### ISSUE TITLE
allow specifying raw values.yaml

### ISSUE THREAD

**Issue by calind** [hashicorp/terraform-provider-helm#9]
The current approach works well for simple `values.yaml` overrides, but it gets pretty ugly when you need to pass complex yaml. By allowing to specify a custom `values.yaml` as string these complex cases can be templated.

Also I would suggest renaming the curent `value` option with `set` to be more inline with helm cli. `set` would get priority over `values`.

Here is an example for grafana deployment with ingress using the proposed changes:

```tf
data "template_file" "grafana_values" {
  template = <<EOF
server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: 'nginx'
      kubernetes.io/tls-acme: 'true'
    hosts:
      - grafana.example.com
    tls:
      - secretName: grafana-server-tls
        hosts:
          - grafana.example.com
EOF
}

resource "helm_chart" "grafana" {
  name        = "grafana"
  chart       = "stable/grafana"
  values      = "${data.template_file.grafana_values.rendered}"
  set {
    name    = "server.image"
    content = "grafana/grafana:4.4.3"
  }
}
```

I wil try comming up with a PR.

**Comment by mcuadros** [comment]
For me this goes against Terraform philosophy, but is true that the name/content pair, is a bit tedious, at the very beginning of the development I tried to implement this in a interface{} allowing write HCL more similar to the structure of the values. 

Let me thing about this.

**Comment by mcuadros** [comment]
Implemented at https://github.com/mcuadros/terraform-provider-helm/commit/5d5bad85f183ea7970bb633a0a92454214b66258
