### ISSUE TITLE
helm_release GET ---: EOF from elasticsearch

### ISSUE THREAD

**Issue by audunsolemdal** [hashicorp/terraform-provider-helm#900]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.1.0
Provider version: 2.4.1
Kubernetes version: 1.22.6
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "myrelease" {
  chart        = "https://helm.elastic.co/helm/elasticsearch/elasticsearch-7.17.3.tgz"
  name         = "elasticsearch"
  namespace    = data.kubernetes_namespace.this.metadata[0].name
  max_history  = 1
  atomic       = true
  reuse_values = true
  timeout      = 600

  values = [templatefile("${path.module}/templates/values.yaml.tpl", {})]
}

```

### Debug Output

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

Succeeded apply

### Actual Behavior

```
│Error: Get "https://helm.elastic.co/helm/elasticsearch/elasticsearch-7.17.3.tgz": EOF
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Unfortunately, we cannot reproduce this issue.
Seems to work fine with default values.
```
Plan: 1 to add, 0 to change, 0 to destroy.
helm_release.myrelease: Creating...
helm_release.myrelease: Still creating... [10s elapsed]
helm_release.myrelease: Still creating... [20s elapsed]
helm_release.myrelease: Still creating... [30s elapsed]
helm_release.myrelease: Still creating... [40s elapsed]
helm_release.myrelease: Creation complete after 47s [id=elasticsearch]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

We would need to have a look at the exact values you are passing to the chart in order to investigate further.

**Comment by audunsolemdal** [comment]
Values provided are irrelevant. 

However I am able to get this working from my local machine, but not on the jumpbox I am running the terraform apply command from. The chart downloads just fine on the jumpbox, and there are no records in the firewall. I've had this issue quite a while but still can't really figure out what the root cause is.
