### ISSUE TITLE
Helm Provider >2.4.1 with experiment manifest enabled always triggers helm_release, even without changes 

### ISSUE THREAD

**Issue by oscarjohansson94** [hashicorp/terraform-provider-helm#906]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version:  v1.2.2
Provider version: >v2.4.1
Kubernetes version: v1.22.6
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
terraform {
    required_providers {
        helm = {
            source = "hashicorp/helm"
            version = "=2.6.0"
        }
        azurerm = {
            source  = "hashicorp/azurerm"
            version = "=2.93.1"
        }
        kubernetes = {
            source = "hashicorp/kubernetes"
            version = "=2.10.0"
        }
    }
}

provider "helm" {
    kubernetes {
        host                   = REDACTED
        client_certificate     = REDACTED
        client_key             = REDACTED
        cluster_ca_certificate = REDACTED
    }

    experiments {
        manifest = true
    }
}

resource "helm_release" "deployment-staging" {
    name = var.name
    chart = var.chart
    version = var.chart_version
    values = [file(var.helm_values_path)]
    namespace = var.namespace
    repository_password = REDACTED
    repository_username = REDACTED
}

```

### Debug Output

This data is a bit sensitive. Terraform will output removing the helm_release and then adding the same release but with a increment in Helm Release Revision number.

### Steps to Reproduce

1. Use helm_release with OCI helm chart
2. Terraform apply

### Expected Behavior
No changes should be detected, this was the behavior on helm-provider version 2.4.1 (before OCI support)

### Actual Behavior
Helm_release wants to recreate all our release with an incremented Helm Release Revision number, even when there where no changes made. This causes all helm releases to be re-release every time we  apply.

### Important Factoids

We run multiple Terraform workspaces in Terraform Cloud, and have had many helm_releases in production during several years, this is the first time encountering this issue. The only change made to our setup, except upgrading from 2.4.1 to 2.6.0, was moving the charts to a Azure container registry and using the new OCI support.

We are running Kubernetes using Azure AKS.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Can you please share the diff that's being shown? Feel free to redact any sensitive values out of it.
A debug log would also help us a lot (you can obtain one by running Terraform with the `TF_LOG=debug` env variable set).

**Comment by ddup1** [comment]
We have similar issue. We use a data to get token from ECR so for each deployment helm provider want to modify our release because repository password has changed. But our chart are not modified, it's just the token to access ECR.

**Comment by megakid** [comment]
Using helm provider 2.6.0 we are also seeing this but only when `experiments { manifest = true }` is set.

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # helm_release.bleb-web-client will be updated in-place
  ~ resource "helm_release" "bleb-web-client" {
        id                         = "bleb-web-client"
      ~ manifest                   = jsonencode(
          ~ {
              ~ "deployment.apps/apps/v1/bleb-web-client" = {
                  ~ metadata   = {
                      ~ labels = {
                          ~ helm-revision                  = "7" -> "8"
                            # (5 unchanged elements hidden)
                        }
                        name   = "bleb-web-client"
                    }
                    # (3 unchanged elements hidden)
                }
              ~ "service/v1/bleb-web-client"              = {
                  ~ metadata   = {
                      ~ labels      = {
                          ~ helm-revision                  = "7" -> "8"
                            # (5 unchanged elements hidden)
                        }
                        name        = "bleb-web-client"
                        # (1 unchanged element hidden)
                    }
                    # (3 unchanged elements hidden)
                }
            }
        )
        name                       = "bleb-web-client"
        # (29 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
```

**Comment by oscarjohansson94** [comment]
I can confirm that we see the same behavior as @megakid, meaning that the issue only occurs when `experiments { manifest = true }`

**Comment by andrewhibbert** [comment]
This is not happening for me. It seems dependent on helm chart, might be worth providing what helm chart you are using and checking it looks okay. E.g. running `helm -n <namespace> get all <release>`, I don't think the generated manifests should have that label

**Comment by n-oden** [comment]
The specific case of using Google Artifact Repository as an OCI repo has the same problem that @ddup1 noted -- because the "password" changes each time terraform runs, the provider re-installs the `helm_release` resource each time it runs, creating a new helm history entry and basically polluting the helm history to the point of uselessness.

My initial thought was that this could be worked around by adding `repository_password` to `lifecycle.ignore_changes` but that creates a new problem: because the provider attempts to refresh the helm repository state during the plan stage, the token that is saved in state eventually expires and then plans fail because it receives an error attempting to talk to the repository.

(Our own context here is using Google Artifact Repository as a helm repo, but I think this is going to be a problem with any possible OCI repository.)

**Comment by jeremymcgee73** [comment]
I'm running into this as well. Same problem as @n-oden.

**Comment by ymatsiuk** [comment]
The same issue with `argo-cd` chart:
```
Terraform will perform the following actions:

  # module.<snip>.helm_release.argo-cd[0] will be updated in-place
  ~ resource "helm_release" "argo-cd" {
        id                         = "argo-cd"
      ~ manifest                   = jsonencode(
          ~ {
              ~ "kube-system/deployment.apps/apps/v1/argo-cd-redis-ha-haproxy"                                                    = {
                  ~ spec       = {
                      ~ template             = {
                          ~ metadata = {
                              ~ labels      = {
                                  ~ revision = "12" -> "13"
                                    # (2 unchanged elements hidden)
                                }
                                name        = "argo-cd-redis-ha-haproxy"
                                # (1 unchanged element hidden)
                            }
                          ~ spec     = {
                              ~ affinity           = {
                                  ~ podAntiAffinity = {
                                      ~ requiredDuringSchedulingIgnoredDuringExecution = [
                                          ~ {
                                              ~ labelSelector = {
                                                  ~ matchLabels = {
                                                      ~ revision = "12" -> "13"
                                                        # (2 unchanged elements hidden)
                                                    }
                                                }
                                                # (1 unchanged element hidden)
                                            },
                                        ]
                                    }
                                }
                                # (7 unchanged elements hidden)
                            }
                        }
                        # (4 unchanged elements hidden)
                    }
                    # (3 unchanged elements hidden)
                }
                # (61 unchanged elements hidden)
            }
        )
        name                       = "argo-cd"
        # (28 unchanged attributes hidden)
    }
```

Digging a bit deeper unveils that argo chart has [redis-ha](https://github.com/argoproj/argo-helm/blob/77d8a11dd88a229671e2143824b5f54fd2687811/charts/argo-cd/Chart.yaml#L19-L23) dependency.

Checking the latter unveils that this is the [feature](https://github.com/DandyDeveloper/charts/pull/89/files) of `redis-ha` and argo just [brings it in](https://github.com/argoproj/argo-helm/blob/77d8a11dd88a229671e2143824b5f54fd2687811/charts/argo-cd/values.yaml#L1215)

I hope this helps understand why you see the drift and also if you're the chart maintainer shows how easy it is to create a frustration for your "customers" 😉

**Comment by mozz-lx** [comment]
This still hapens with helm provider `v2.12.1`
