### ISSUE TITLE
Share resources in different Helm releases using Terraform

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-helm#907]
Deploying Kubernetes Deployment, Service and Ingress in EKS using Helm. Terraform is being used to deploy the Helm release via custom [Chart](https://github.com/git4suvendu/application-helm-charts/tree/gh-pages).

Deploying two Helm releases using Terraform:

Release 1 (game-app): consists of Deployment and Service manifests
Release 2 (game-app-ingress): consists of Ingress manifests. Ingress resource is pointing to Kubernetes Service created the first release.

**Problem:**  If I use Helm Install CLI command to deploy the Kubernetes manifests in two different releases then everything is working fine. No errors. But if I use Terraform to deploy two Helm releases then getting the below error:

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: Service "game-app-service" in namespace "ns-fargate-app" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "game-app-ingress": current value is "game-app"
│
│  with module.kubernetes_app_helm.helm_release.game_app_ingress,
│  on modules/kubernetes-app-helm/main.tf line 42, in resource "helm_release" "game_app_ingress":
│  42: resource "helm_release" "game_app_ingress" {`

Please refer to https://stackoverflow.com/questions/72842163/share-resources-in-different-helm-releases-using-terraform for more details.

 **Terraform version, Kubernetes provider version and Kubernetes version**
```
 `terraform {
  required_version = ">= 0.13.0"

  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "4.21.0"
    }
    local      = ">= 1.4"
    random     = ">= 2.1"
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.0"
    }
    helm = {
      source = "hashicorp/helm"
      version = "2.6.0"
    }
  }
}
`
```
 
## Question
```
What I am not able to understand is, why Terraform is not able to deploy the second Helm release and share Kubernetes service resource which has been created in another Helm release? Whereas Helm CLI is NOT giving any issues.
```

**Comment by gmoshiko** [comment]
I think this might help 

https://github.com/helm/helm/issues/8133#issuecomment-937979845
