### ISSUE TITLE
Concat arrays into single array causes the values input to become sensitive if a single array contains a secret

### ISSUE THREAD

**Issue by sakirma** [hashicorp/terraform-provider-helm#926]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: Terraform v1.2.6 on darwin_arm64
Provider version:  Installed hashicorp/helm v2.6.0 (signed by HashiCorp)
Kubernetes version: Client Version: v1.24.3 Kustomize Version: v4.5.4 Server Version: v1.21.7
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "loki" {
  name       = "loki"
  repository = "https://grafana.github.io/helm-charts"
  chart      = "loki-distributed"
  version    = "0.48.4"
  replace    = true

  namespace  = var.namespace
  depends_on = [kubernetes_namespace.monitoring_namespace]

  values = concat([
    var.cluster_values.in_cluster_only ? "" : file("${path.module}/loki_cloud.yaml"),

    var.cluster_values.in_cluster_only && var.cluster_values.in_cluster_only_values.use_loki_development_values ? file("${path.module}/loki_development.yaml") : "",

    var.loki_additional_values_path == "" ? "" : file(var.loki_additional_values_path),
    var.loki_storage_config
    ],
    var.loki_additional_values,
  var.loki_additional_values_sensitive)

  set {
    name  = "loki.storageConfig.gcs.bucket_name"
    value = !var.cluster_values.in_cluster_only && var.loki_storage_config == "" ? var.loki_storage_bucket_name : ""
  }

  set {
    name  = "loki.structuredConfig.ruler.storage.gcs.bucket_name"
    value = !var.cluster_values.in_cluster_only && var.loki_storage_config == "" ? var.loki_storage_bucket_name : ""
  }

}
```

Input values example
```hcl
  loki_additional_values = [file("${path.module}/values/loki.yaml")]

  loki_additional_values_sensitive = [<<-EOT
  key: "Value"
  key1: "Value1"
  EOT
  ,
  <<-EOT
    key3: "Value"
    key1: "Value1"
  EOT
  ]
```

### Debug Output

https://gist.github.com/sakirma/f9b57f99875618f9de4907f01ee3a315

### Steps to Reproduce

1. `have a helm resource that concats multiple arrays into one for the values field`
2. `terraform plan`

### Expected Behavior

I expect to see my nonsensitive values to be displayed next to sensitive values

### Actual Behavior

```hlc
resource "helm_release" "loki" {
        id                         = "loki"
        name                       = "loki"
      # Warning: this attribute value will be marked as sensitive and will not
      # display in UI output after applying this change.
      ~ values                     = (sensitive)
        # (27 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```

As you can see since I combine all my arrays with values (sensitive and nonsensitive) into a single array. I have to do this since values input is a single array.

And then it all becomes a sensitive

### Important Factoids

No, I run this on a k8s cluster which is running on Azure

### References

I looked it up and haven't found anything

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @sakirma,

Thank you for reporting this issue. This is a limitation of Terraform [Core] and there is nothing that we can do about it on the provider level. Please open a new issue on their issue tracker [here](https://github.com/hashicorp/terraform/issues) so they can track it and be aware.

Thank you.

**Comment by sakirma** [comment]
I know it is not relevant for this repository, but I am going to post the link to the conversation in Terraform [Core] here so that the next person with this problem can easily get there.

https://github.com/hashicorp/terraform/issues/31580#issuecomment-1209698793

So yeah this is intended.
I will immediately close this issue after posting this. 

----
edit: ah it doesn't open this issue after commenting this ✌🏻😄
