### ISSUE TITLE
Deploy OCI chart from AWS public ECR

### ISSUE THREAD

**Issue by idjemaoune** [hashicorp/terraform-provider-helm#943]
Error: ``could not download chart: failed to download "oci://public.ecr.aws/kubecost/cost-analyzer/kubecost``

## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.2.4
Helm Provider version: 2.6.0
Helm Provider version: 3.9.4
Kubernetes version: 1.23
```
## Terraform configuration
```hcl
resource "helm_release" "kubecost" {
...
  name             = "kubecost"
  repository       = "oci://public.ecr.aws/kubecost/cost-analyzer"
...
}
```

## Question
```
I'm experiencing an issue when trying to deploy kubecost from as public ECR, Is there any option to use OCI public registry?
```

**Comment by corey-hammerton** [comment]
I have the same error message when downloading a helm chart from a privately hosted Google Artifact Registry location using oauth2accesstoken login. Debug logs show nothing

**Comment by sirantd** [comment]
Have the same problem with `kubecost` and `karpenter` OCI registries.
I have the latest versions (but it changes nothing):
```
Terraform version: 1.3.3
Helm Provider version: 2.7.1
Helm Provider version: 3.10.1
Kubernetes version: 1.23
```

**Comment by ghost** [comment]
I ran into this myself. The repository is `kubecost` and the chart is `cost-analyzer`. Example:


```terraform
resource "kubernetes_namespace" "kubecost" {
  metadata {
    name = "kubecost"
  }
}

resource "helm_release" "kubecost" {
  name       = "kubecost"
  repository = "oci://public.ecr.aws/kubecost" 
  chart      = "cost-analyzer"
  version    = "1.97.0"
  namespace  = kubernetes_namespace.kubecost.metadata[0].name

  values = [
    "${file("values-eks-cost-monitoring.yaml")}"
  ]

}
```

**Comment by sirantd** [comment]
I was able to solve the problem by running
```
docker logout public.ecr.aws
```
as explained [here](https://docs.aws.amazon.com/AmazonECR/latest/public/public-troubleshooting.html)

**Comment by atamgp** [comment]
Try this?

```
provider "aws" {
  region = "us-east-1"
  alias  = "east1"
}

data "aws_ecrpublic_authorization_token" "token" {
  provider = aws.east1
}

resource "helm_release" "xyz" {
...

  name = "kubecost"
  repository          = "oci://public.ecr.aws/kubecost"
  chart   = "cost-analyzer"
  version = ...
  repository_username = data.aws_ecrpublic_authorization_token.token.user_name
  repository_password = data.aws_ecrpublic_authorization_token.token.password
```

**Comment by sergialonsaco** [comment]
> Try this?
> 
> ```
> provider "aws" {
>   region = "us-east-1"
>   alias  = "east1"
> }
> 
> data "aws_ecrpublic_authorization_token" "token" {
>   provider = aws.east1
> }
> 
> resource "helm_release" "xyz" {
> ...
> 
>   name = "kubecost"
>   repository          = "oci://public.ecr.aws/kubecost"
>   chart   = "cost-analyzer"
>   version = ...
>   repository_username = data.aws_ecrpublic_authorization_token.token.user_name
>   repository_password = data.aws_ecrpublic_authorization_token.token.password
> ```

any updates on this question? I ran into the same issue and above solution didn't solved the problem :(

**Comment by jessebye** [comment]
@sergialonsaco @atamgp We are also having this error with a similar configuration to the one Atam posted:

```
resource "helm_release" "aws_iam_controller" {
  name             = "iam-controller"
  namespace        = "aws-controllers-system"
  create_namespace = true

  chart               = "iam-controller"
  repository          = "oci://public.ecr.aws/aws-controllers-k8s"
  repository_username = data.aws_ecrpublic_authorization_token.token.user_name
  repository_password = data.aws_ecrpublic_authorization_token.token.password

  version = "v1.0.1"
...
```

The error: `Error: could not download chart: failed to download "oci://public.ecr.aws/aws-controllers-k8s/iam-controller" at version "v1.0.1"`
