### ISSUE TITLE
Special character with yamlencode with helm values

### ISSUE THREAD

**Issue by klemen-df** [hashicorp/terraform-provider-helm#948]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.1.9
Provider version: 2.5.1
Kubernetes version: aks v1.22.6
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
    set {
      name = "config"
      value = yamlencode({
        modules = {
          http_2xx = {
            prober  = "http"
            timeout = "5s"
            http = {
              valid_http_versions   = ["HTTP/2.0"]
              follow_redirects      = false
              preferred_ip_protocol = "ip4"
              method                = "HEAD"
              fail_if_not_ssl       = true
              enable_http2          = true
            }
          }
        }
      })
    }
```

### Debug Output
```
      + set {
          + name  = "config"
          + value = <<-EOT
                "modules":
                  "http_2xx":
                    "http":
                      "enable_http2": true
                      "fail_if_not_ssl": true
                      "follow_redirects": false
                      "method": "HEAD"
                      "preferred_ip_protocol": "ip4"
                      "valid_http_versions":
                      - "HTTP/2.0"
                    "prober": "http"
                    "timeout": "5s"
            EOT
        }
```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
```
"modules":
  "http_2xx":
    "http":
      "enable_http2": true
      "fail_if_not_ssl": true
      "follow_redirects": false
      "method": "HEAD"
      "preferred_ip_protocol": "ip4"
      "valid_http_versions":
      - "HTTP/2.0"
    "prober": "http"
    "timeout": "5s"
```

### Actual Behavior

```
|
  "modules":
    "http_2xx":
      "http":
        "enable_http2": true
        "fail_if_not_ssl": true
        "follow_redirects": false
        "method": "HEAD"
        "preferred_ip_protocol": "ip4"
        "valid_http_versions":
        - "HTTP/2.0"
      "prober": "http"
      "timeout": "5s"

```

**Comment by jrhouston** [comment]
Hi @KlemenDanfoss – I'm not sure if I understand your issue. Is the special character you are referring to the pipe `|` at the start of your second snippet? This character is used in YAML for multi-line strings. By using `yamlencode` you are creating a string value that contains YAML rather than specifying YAML directly, so that might be why you are seeing it appear with the `|` character once it's rendered.

**Comment by klemen-df** [comment]
Hi, yes, I'm talking about the pipe at the start of my second snippet.

So, basically, _yamlencode_ is not the right way to go to define a 'multiline variable'?

**Comment by dcoraboeuf** [comment]
Hi,

I have a similar issue.

I'm using Terraform Cloud and the Helm resource, setting a variable this way:

```
set {
   name = "application_yaml"
   value = var.application_yaml
}
```

where `var.application_yaml` happens to be a multiline string, like:

```
config:
   ingestion:
      processing:
         scale: 10
```

In the rendered values, I get:

```
application_yaml: |
  config:
   ingestion:
      processing:
         scale: 10
```

**Comment by jrhouston** [comment]
@KlemenDanfoss yeah, you might want to try using the `values` attribute instead, which accepts arbitrary YAML like this:

```terraform
values = [
  yamlencode({ 
    config = {
      modules = {
        http_2xx = {
          prober  = "http"
          timeout = "5s"
          http = {
            valid_http_versions   = ["HTTP/2.0"]
            follow_redirects      = false
            preferred_ip_protocol = "ip4"
            method                = "HEAD"
            fail_if_not_ssl       = true
            enable_http2          = true
          }
        }
      }
    }
  })
]
```

**Comment by klemen-df** [comment]
Hi,

thanks for the reply. I understand, I also found this.

If this doesn't 'work' then maybe we could add this to documentation (somehow) so other people don't get confused as well.

**Comment by nichoio** [comment]
I'm facing a related issue. I'm trying to parameterize [a value](https://github.com/awslabs/kubeflow-manifests/blob/8e2ffc5958da6fd6e17790236c484938c20e318b/charts/apps/jupyter-web-app/templates/ConfigMap/jupyter-web-app-config-tgcbb2gdkd-kubeflow-ConfigMap.yaml#L3) in a chart which uses Helm provider.

Excerpt from my code:
```terraform
  helm_config = {
    chart = ...
    values = [
      yamlencode({
        spawnerUiConfig = {
          spawnerFormDefaults = {
            image = {
              ...
            }
          }
        }
      })
    ]
  }
```
I'm trying to render the value like this:
```yaml
apiVersion: v1
kind: ConfigMap
data:
  spawner_ui_config.yaml: |
    {{ .Values.spawnerUiConfig }}
```

But this is what is applied:
```yaml
data:
  spawner_ui_config.yaml: |
    map[spawnerFormDefaults:map[image:map[
```

Desired output would be this:
```yaml
data:
  spawner_ui_config.yaml: |
    spawnerFormDefaults:
      image:
```

Any ideas how to get rendered this YAML correctly?

**Comment by yossigilad** [comment]
> I'm facing a related issue. I'm trying to parameterize [a value](https://github.com/awslabs/kubeflow-manifests/blob/8e2ffc5958da6fd6e17790236c484938c20e318b/charts/apps/jupyter-web-app/templates/ConfigMap/jupyter-web-app-config-tgcbb2gdkd-kubeflow-ConfigMap.yaml#L3) in a chart which uses Helm provider.
> 
> Excerpt from my code:
> 
> ```terraform
>   helm_config = {
>     chart = ...
>     values = [
>       yamlencode({
>         spawnerUiConfig = {
>           spawnerFormDefaults = {
>             image = {
>               ...
>             }
>           }
>         }
>       })
>     ]
>   }
> ```
> 
> I'm trying to render the value like this:
> 
> ```yaml
> apiVersion: v1
> kind: ConfigMap
> data:
>   spawner_ui_config.yaml: |
>     {{ .Values.spawnerUiConfig }}
> ```
> 
> But this is what is applied:
> 
> ```yaml
> data:
>   spawner_ui_config.yaml: |
>     map[spawnerFormDefaults:map[image:map[
> ```
> 
> Desired output would be this:
> 
> ```yaml
> data:
>   spawner_ui_config.yaml: |
>     spawnerFormDefaults:
>       image:
> ```
> 
> Any ideas how to get rendered this YAML correctly?

Hi, I'm facing  same issue, did you solve it?
