### ISSUE TITLE
terraform apply crashed with "x509: “kube-apiserver” certificate is not trusted" error

### ISSUE THREAD

**Issue by jveraduran** [hashicorp/terraform-provider-helm#955]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v1.2.4 on darwin_amd64
Provider version: 2.6.0
Kubernetes version: 1.23
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    linode = {
      source  = "linode/linode"
      version = "1.29.2"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.13.1"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "2.6.0"
    }
  }
}
provider "linode" {
  token = var.token
}

provider "kubernetes" {
  host                   = module.lke.api_endpoints[0]
  token                  = try(yamldecode(file("./cluster.yaml")).users[0].user.token, null)
  cluster_ca_certificate = try(base64decode(yamldecode(file("./cluster.yaml")).clusters[0].cluster.certificate-authority-data), null)
}

provider "helm" {
  kubernetes {
    host                   = module.lke.api_endpoints[0]
    token                  = try(yamldecode(file("./cluster.yaml")).users[0].user.token, null)
    cluster_ca_certificate = try(base64decode(yamldecode(file("./cluster.yaml")).clusters[0].cluster.certificate-authority-data), null)
  }
}

```

### Debug Output

```
Error: Kubernetes cluster unreachable: Get "https://XXXXXXX.REGION.linodelke.net:443/version": x509: “kube-apiserver” certificate is not trusted
```

NOTE: In addition to Terraform debugging, please set HELM_DEBUG=1 to enable debugging info from helm.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

A terraform apply to completed successfully, without errors.

### Actual Behavior

When I run `terraform apply` is showing this error, with the first apply. But on the second `terraform apply` works fine.

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  + create

Terraform will perform the following actions:

  # module.kubernetes_addons.module.external_dns[0].helm_release.external_dns will be created
  + resource "helm_release" "external_dns" {
      + atomic                     = false
      + chart                      = "external-dns"
      + cleanup_on_fail            = false
      + create_namespace           = true
      + dependency_update          = false
      + disable_crd_hooks          = false
      + disable_openapi_validation = false
      + disable_webhooks           = false
      + force_update               = true
      + id                         = (known after apply)
      + lint                       = false
      + manifest                   = (known after apply)
      + max_history                = 0
      + metadata                   = (known after apply)
      + name                       = "external-dns"
      + namespace                  = "external-dns"
      + pass_credentials           = false
      + recreate_pods              = false
      + render_subchart_notes      = true
      + replace                    = false
      + repository                 = "https://kubernetes-sigs.github.io/external-dns/"
      + reset_values               = false
      + reuse_values               = false
      + skip_crds                  = false
      + status                     = "deployed"
      + timeout                    = 300
      + verify                     = false
      + version                    = "1.11.0"
      + wait                       = true
      + wait_for_jobs              = false
    }

Plan: 1 to add, 0 to change, 0 to destroy.
module.kubernetes_addons.module.external_dns[0].helm_release.external_dns: Creating...
module.kubernetes_addons.module.external_dns[0].helm_release.external_dns: Still creating... [10s elapsed]
module.kubernetes_addons.module.external_dns[0].helm_release.external_dns: Still creating... [20s elapsed]
module.kubernetes_addons.module.external_dns[0].helm_release.external_dns: Still creating... [30s elapsed]
module.kubernetes_addons.module.external_dns[0].helm_release.external_dns: Still creating... [40s elapsed]
```

### Important Factoids

Running Linode LKE Cluster with [Terraform Provider](https://registry.terraform.io/providers/linode/linode/latest/docs)

### References

https://github.com/hashicorp/terraform-provider-helm/issues/951

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @jveraduran,

I will duplicate my answer from #951, because I believe it is the same issue.

If I understands you right, you spin up a new Kubernetes cluster and apply a helm chart to it within the same TF code. If that so, then the observed behaviour is expected. In short, the root cause here is how Terraform initializes providers. It does it all in one shot at the very beginning. In this case, first run of the code does not have a valid Kubernetes configuration for the Helm provider and it fails. Once you run it second time, the cluster is up and running and Terraform can fetch configuration for the provider and apply will be successful.

In this case, you either need to separate cluster management and resource provisioning, or use Terraform `-target` option to first spin up a cluster, and then apply resources.

This behaviour has mentioned in the Kubernetes provider's documentation [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources).

I hope that helps.

Thank you.
