### ISSUE TITLE
Helm chart requires CSR approval

### ISSUE THREAD

**Issue by peternavr** [hashicorp/terraform-provider-helm#96]
[CockroachDB](https://github.com/helm/charts/tree/master/stable/cockroachdb) requires CSR approval as it is deployed per node. Is this something that the helm provider would do? The concern is that the helm chart will timeout if you can't approve the CSR in time and thus, ends.

**Comment by mcuadros** [comment]
Closing this issue since is making reference to a version based on Helm 2, if this is still valid to the master branch please reopen it. Thanks.
