### ISSUE TITLE
Deploy helm charts one at a time using loop

### ISSUE THREAD

**Issue by lugtusonny** [hashicorp/terraform-provider-helm#961]
If you prefer, you can also ask your question in the Kubernetes community Slack channel [#terraform-providers](https://kubernetes.slack.com/messages/CJY6ATQH4). ([Sign up here](http://slack.k8s.io/))

## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: v1.2.8
Helm Provider version: v2.6.0
Kubernetes version: v1.24.2

```
## Terraform configuration
variable.tf
```
variable "appcore" {
  description = "Core Applications"
  type        = set(string)
  default     = [
    "core-app1",
    "core-app2",
    "core-app3",
    "core-app4",
  ]
}
```
main.tf
```
resource "helm_release" "core" {
    for_each = var.appcore
    name     = each.value
    chart            = "${var.CHART_REPOSITORY_NAME}/${each.value}"

    values = [
      "${file("${var.values_file}/${each.value}.yaml")}"
    ]
}
```
## Question
```
This works fine except that the applications are deployed in parallel. Any suggestions on how these applications can be deployed one at a time using a loop? or in order?
```

**Comment by BBBmau** [comment]
Hello! If you look at docs for parallelism [here](https://www.terraform.io/cli/commands/apply#parallelism-n) you can set the number of concurrent operations to 1
