### ISSUE TITLE
Debug slowness

### ISSUE THREAD

**Issue by DanielCastronovo** [hashicorp/terraform-provider-helm#977]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.3.2
Helm Provider version: 2.6
Kubernetes version: 1.22
```

## Question
```
A majority of my terraform plan is very slow when i use a helm provider.
Is-it possible to debug this latency ? and why ?

Thanks
```

**Comment by alexsomesan** [comment]
Logging output can be controlled with the TF_LOG or TF_PROVIDER_LOG environment variables. TF_LOG will give you output from both Terraform itself as well as the provider, while TF_PROVIDER_LOG will just show provider debug output.

Exporting TF_LOG=DEBUG will increase the log verbosity and emit HTTP request and response traces to stdout when running Terraform. This output is very useful when reporting a bug in the provider. There are several other log level values, like TRACE, ERROR, WARNIG.
