### ISSUE TITLE
ECR token refresh

### ISSUE THREAD

**Issue by DanielCastronovo** [hashicorp/terraform-provider-helm#978]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v1.3.2
Provider version: 2.6.0
Kubernetes version: EKS 1.21
```

### Affected Resource(s)

- helm_release

### Terraform Configuration Files
```
data "aws_ecr_authorization_token" "token" {}

resource "helm_release" "platform" {
  chart = "oci://${trimprefix(data.aws_ecr_authorization_token.token.proxy_endpoint, "https://")}/my-chart"
  repository_username = data.aws_ecr_authorization_token.token.user_name
  repository_password = data.aws_ecr_authorization_token.token.password
}
```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
Helm provider should be able to login to ecr.

### Actual Behavior
could not login to OCI registry "myaccount.dkr.ecr.us-east-1.amazonaws.com": login attempt to https://myaccount.dkr.ecr.us-east-1.amazonaws.com/v2/ failed with status: 403 Forbidden

It was working in a few hours after the new release, but now seems to not be working. Maybe its not refreshing the creds properly as ecr credentials require being constantly refreshed?

### References
[https://github.com/hashicorp/terraform-provider-helm/issues/844](https://github.com/hashicorp/terraform-provider-helm/issues/844)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jeremymcgee73** [comment]
This should get you going.

```
data "aws_ecr_authorization_token" "token" {}

resource "helm_release" "platform" {
  chart = "oci://${trimprefix(data.aws_ecr_authorization_token.token.proxy_endpoint, "https://")}/my-chart"
  repository_username = data.aws_ecr_authorization_token.token.user_name
  repository_password = data.aws_ecr_authorization_token.token.password
  lifecycle {
    ignore_changes = [repository_password]
  }
}
```

**Comment by jeremymcgee73** [comment]
Also, make sure your provider is  on version `2.5.1` or later.

**Comment by DanielCastronovo** [comment]
it's doesn't work because the token is not refreshed.

**Comment by jeremymcgee73** [comment]
I'm working through this as well. Try removing the lifecycle block, and using the latest version of the provider. That seems to be working for me.

**Comment by jeremymcgee73** [comment]
It does seem like when I'm using OCI, that helm_release thinks there is changes everytime TF is ran. I'll try to dig in and see why.

**Comment by ddup1** [comment]
@jeremymcgee73 helm_release think there is a change, because token has changed. 
I describe this behaviour in reply to this issue : https://github.com/hashicorp/terraform-provider-helm/issues/906

And i saw a PR that will fix our issue : https://github.com/hashicorp/terraform-provider-helm/pull/862

This PR will be merged in next release

**Comment by jeremymcgee73** [comment]
Awesome! Thanks, looking forward to it!

**Comment by jeremymcgee73** [comment]
This fixed the problem for me! Thanks!

**Comment by cunningr** [comment]
I seem to be still seeing this issue today, with the latest `2.8.0` provider;

We seem to be updating the helm chart because the `repository_password` token was updated.

```
  # module.cluster.helm_release.openstack_cluster will be updated in-place
  ~ resource "helm_release" "openstack_cluster" {
        id                         = "lab-sjc2-orange"
        name                       = "lab-sjc2-orange"
      ~ repository_password        = (sensitive value)
        # (29 unchanged attributes hidden)
    }

Plan: 1 to add, 2 to change, 1 to destroy.
```

If I use the suggested work around above to insert the lifecycle block;

```
  lifecycle {
    ignore_changes = [repository_password]
  }
```

Then I get a `403` once the token stored in TF state has expired as we seem to be using just reusing that one (?) instead of the new one.

```
Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/external from the dependency lock file
- Reusing previous version of hashicorp/kubernetes from the dependency lock file
- Reusing previous version of hashicorp/helm from the dependency lock file
- Reusing previous version of terraform-provider-openstack/openstack from the dependency lock file
- Installing hashicorp/aws v4.46.0...
- Installed hashicorp/aws v4.46.0 (signed by HashiCorp)
- Installing hashicorp/random v3.4.3...
- Installed hashicorp/random v3.4.3 (signed by HashiCorp)
- Installing hashicorp/external v2.2.3...
- Installed hashicorp/external v2.2.3 (signed by HashiCorp)
- Installing hashicorp/kubernetes v2.16.1...
- Installed hashicorp/kubernetes v2.16.1 (signed by HashiCorp)
- Installing hashicorp/helm v2.8.0...
- Installed hashicorp/helm v2.8.0 (signed by HashiCorp)
- Installing terraform-provider-openstack/openstack v1.42.0...
- Installed terraform-provider-openstack/openstack v1.42.0 (self-signed, key ID 4F80527A391BEFD2)
```

**Comment by cunningr** [comment]
I see https://github.com/hashicorp/terraform-provider-helm/issues/1017 we can set the auth in the provider instead.

However, we are using using helm_release in a non-root module so we cannot set a provider there.  We also have multiple aws providers using aliases for different resources, so we are not sure how we can consume it this way.

```
  data "aws_ecr_authorization_token" "token" {}. <<<<< how do we specify the AWS profile to use?
  provider "helm" {
    kubernetes {
      config_path    = "eks.kube"
      config_context = "default"
    }
    registry {
      url = "oci://ACCOUNTNUMBER.dkr.ecr.us-east-1.amazonaws.com"
      username = data.aws_ecr_authorization_token.token.user_name
      password = data.aws_ecr_authorization_token.token.password
    }
  }
```
