### ISSUE TITLE
Kubeconfig multiple paths breaks

### ISSUE THREAD

**Issue by trumpet2012** [hashicorp/terraform-provider-helm#98]
Doesn't honor multiple kubeconfig paths being set in KUBECONFIG environment variable.

### Terraform Version
v0.11.7

### Debug Output
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.helm: stat /Users/tholliday/.kube/config:/code/infrastructure/terraform-eks/kubeconfig_k8s: no such file or directory
```

### Expected Behavior
Helm provider should be able to handle multiple kubeconfigs being specified in the KUBECONFIG environment variable. This is a supported feature for kubectl. 

### Actual Behavior
It looks like it treats multiple `:` delimited kubeconfig paths as one config path.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create `helm_release`
1. Have multiple kubernetes configs in your KUBECONFIG environment
	e.g. `export KUBECONFIG=~/.kube/config:~/eks/.kube/config`
1. run `terraform plan`

### Important Factoids
We are setting up EKS using terraform and one of the outputs of the module is the kubernetes config file to connect to the cluster. For simplicity we tell add this separate kubeconfig to our KUBECONFIG paths so that kubectl will merge the config with our other cluster configurations.

**Comment by Lemmons** [comment]
I just ran into this today.  It was quite frustrating to debug. In my case the first config in the `KUBECONFIG` environment var was a file which doesn't exist, which caused the provider to attempt to install everything into a cluster at localhost.  I think the provider should, at least, raise and error if it is given a specific config context to use and it cannot find that context.  That would have made debugging this much easier.

My specific failure is when when doing a `terraform apply` looks like this:
```
* helm_release.my-release: error installing: Post http://localhost/apis/extensions/v1beta1/namespaces/my-namespace/deployments: dial tcp [::1]:80: connect: connection refused
```
