### ISSUE TITLE
Force helm chart upgrade to latest

### ISSUE THREAD

**Issue by barnabasbusa** [hashicorp/terraform-provider-helm#988]
### Description
I would like to be able to force upgrade of a helm chart with a new attribute. Lets say you have a couple dozen of helm charts that you are maintaining, and would like to drop the exact versioning for each helm chart that you are currently using. 
I propose a new attribute such that can be something like "latest" which would fetch the latest version of the helm chart that is available in a registry and would compare to currently running one, and upgrade the helm chart if a newer one is available. 

"latest" attribute would most likely conflict with "version" attribute. 

TLDR: Enable me to set the helm chart to latest without defining versions for it. 

### Potential Terraform Configuration

```
resource "helm_release" "example" {
  name       = "my-redis-release"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "redis"
  latest     =  true
}
```

### References

Helm release: https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release
Related stackoverflow question: https://stackoverflow.com/questions/73533300/how-to-update-the-helm-release-through-terraform 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielCastronovo** [comment]
Hello, nice request.

Be able to use a `> < or <= >= `selector for select the version could be nice too

**Comment by BBBmau** [comment]
Hello! Thank you for opening this issue, a solution would be to apply the `terraform taint` [command](https://developer.hashicorp.com/terraform/cli/commands/taint) on the specific resource that you want to redeploy, this will allow it to redeploy to the latest version.

**Comment by barnabasbusa** [comment]
As far as I understand, tf taint would replace the resources even if they don't need to be replaced (if the helm version wouldn't have a newer release, I wouldn't want to roll them just to get them back to the same version). 

Also if the helm release would be just replaced, then the history of the helm chart would be gone, as it would replace the helm chart not upgrade it to a newer version, thus the possibility to manually rollback is lost. Therefore, while it's an option to roll the cluster this way to the newest versions, it's not an ideal one in my opinion.

**Comment by alekitto** [comment]
Another way could be to add a new data source which exposes all the versions in a repository for the given chart (something like `helm search repo --versions`)

For example

```hcl
data "helm_versions" "redis_chart" {
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "redis"
  devel      = false # This could be optional
}

# This exposes an attribute "versions" which is an array of objects containing
# chart_version, app_version and description, ordered by chart_version desc

# Could be used like the following

resource "helm_release" "example" {
  name       = "my-redis-release"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "redis"
  version    =  data.helm_versions.redis_chart.versions[0].chart_version
}
```

**Comment by barnabasbusa** [comment]
If you run a loop around multiple helm charts that you would like to update, it would require a significantly longer terraform file. You would need to have a different helm_version for all helm charts, which seems really excessive for this.
I feel like having a "latest" flag would enable features like docker images. Where it just makes sense to run latest without needing to always update to the latest tag.
