### ISSUE TITLE
Helm Provider not overriding variable

### ISSUE THREAD

**Issue by MarkusBauerFS** [hashicorp/terraform-provider-helm#996]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: v1.2.8
Provider version: 2.7.0
Kubernetes version: 1.23.12
```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl
resource "helm_release" "vault-standalone" {
  name       = "vault"
  repository = "https://helm.releases.hashicorp.com"
  chart      = "vault"
  version = "0.22.1"
  namespace = var.k8s_namespace
  create_namespace = false
  values = [
    file("standalone-values.yaml")
  ]
  # Set the VAULT_TOKEN environment variable via Terraform to decouple it from config and
  # Remove it from the helm values file as it is sensitive in nature
  set {
    name = "server.extraEnvironmentVars.VAULT_SEAL_TYPE"
    value = var.vault_seal_type
  }

  set_sensitive {
    name  = "server.extraEnvironmentVars.VAULT_TOKEN"
    value = var.vault_seal_type == "transit" ? var.vault_unseal_token : null
  }
  set_sensitive {
    name  = "server.extraEnvironmentVars.VAULT_ADDR"
    value = var.vault_seal_type == "transit" ? var.vault_unseal_address : null
  }
  set {
    name  = "server.extraEnvironmentVars.VAULT_TRANSIT_SEAL_KEY_NAME"
    value = var.vault_seal_type == "transit" ? var.vault_unseal_key_name : null
  }
  set {
    name  = "server.extraEnvironmentVars.VAULT_TRANSIT_SEAL_MOUNT_PATH"
    value = var.vault_seal_type == "transit" ? var.vault_unseal_token : null
  }

}
```

### Steps to Reproduce
1. Set var.vault_seal_type to "transit" 
2. Apply - this should technically even work with Hashicorps default values for Vault

### Expected Behavior
The VAULT_ADDR environment variable should be set to a user provided value.

### Actual Behavior
The VAULT_ADDR falls back to its default value of "{{ include "vault.scheme" . }}://127.0.0.1:8200"
All other variables are not set by default and are properly rendered. 

[Link to template of affected resource](https://github.com/hashicorp/vault-helm/blob/main/templates/server-statefulset.yaml)

### Important Factoids
Running on-prem, I've verified that this is indeed a problem with the helm terraform provider as manually setting the variables, even setting them in the values file as per usual, all do work.

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @MarkusBauerFS,

Thanks for reporting this issue. I cannot reproduce it.

For simplicity I cut some sets from your original code and made `VAULT_ADDR` non-sensitive:

```hcl
variable "vault_seal_type" {
  default = "transit"
}

variable "vault_unseal_address" {
  default = "https://192.168.0.1"
}

resource "helm_release" "vault-standalone" {
  name       = "vault"
  repository = "https://helm.releases.hashicorp.com"
  chart      = "vault"
  version = "0.22.1"
  namespace = "default"
  create_namespace = false
  set {
    name  = "server.extraEnvironmentVars.VAULT_ADDR"
    value = var.vault_seal_type == "transit" ? var.vault_unseal_address : null
  }
}
```

I set up the env variable TF_LOG="DEBUG" and got the following output(cut all not related outputs):
```
$ export TF_LOG="DEBUG"
$ terraform apply -auto-approve
...
2022-11-21T16:27:07.213+0100 [INFO]  provider.terraform-provider-helm_v2.7.1_x5: 2022/11/21 16:27:07 ---[ values.yaml ]-----------------------------------
server:
  extraEnvironmentVars:
    VAULT_ADDR: https://192.168.0.1: timestamp=2022-11-21T16:27:07.213+0100
....
```

It seems to work with no issues.

Here is what I can see in the `StatefulSet`:
```yaml
- name: VAULT_ADDR
  value: http://127.0.0.1:8200
...
- name: VAULT_ADDR
  value: https://192.168.0.1
```

`VAULT_ADDR` appears 2 times, but that seems to be expected based on the [chart](https://github.com/hashicorp/vault-helm/blob/main/templates/server-statefulset.yaml#L90). It doesn't have a condition and adds `VAULT_ADDR` with the values you have defined.

**Comment by MarkusBauerFS** [comment]
Thank you! I'm assuming I must have overlooked it then when going through the Statefulset. Looks like the Helm Chart needs to be modified then to take this into account as it currently does not function as it should.
